import type { Question, DataTable } from '../../shared/types';
import { AMBEV, AMBEV_SOURCE, ambevBalanceTable, ambevIncomeTable } from '../../shared/ambev';

// Caso Ambev — DADOS REAIS (DFP consolidada 2025 × 2024, CVM). Valores em R$ mil.
// Todos os números das questões saem de AMBEV; os textos são montados a partir das constantes.

const B25 = AMBEV.bp[2025];
const B24 = AMBEV.bp[2024];
const D25 = AMBEV.dre[2025];
const D24 = AMBEV.dre[2024];

const CTX = 'DADOS REAIS — Ambev S.A., DFP consolidada 2025 × 2024 (valores em R$ mil)';
const NOTE = 'Valores em R$ mil. ' + AMBEV_SOURCE;
const NOTE_LO =
  'Valores em R$ mil. "Lucro Operacional" = linha "Resultado antes do resultado financeiro e dos tributos" da DFP (inclui equivalência patrimonial). ' +
  AMBEV_SOURCE;

/** Inteiro em pt-BR (ex.: 15.988.433). */
const fmt = (v: number) => v.toLocaleString('pt-BR');
/** Número com casas fixas em pt-BR (ex.: 18,01). */
const dec = (v: number, d = 2) => v.toLocaleString('pt-BR', { minimumFractionDigits: d, maximumFractionDigits: d });
/** Percentual com casas fixas (ex.: 18,01%). */
const pct = (v: number, d = 2) => `${dec(v, d)}%`;

type BpKey = keyof typeof B25;
type DreKey = keyof typeof D25;

function bpTable(caption: string, lines: [string, BpKey][], totalRows?: number[]): DataTable {
  return {
    caption,
    note: NOTE,
    headers: ['Conta', '31/12/2025', '31/12/2024'],
    rows: lines.map(([label, k]) => [label, fmt(B25[k]), fmt(B24[k])]),
    ...(totalRows ? { totalRows } : {}),
  };
}

function dreTable(caption: string, lines: [string, DreKey][], totalRows?: number[]): DataTable {
  return {
    caption,
    note: NOTE_LO,
    headers: ['Linha', '2025', '2024'],
    rows: lines.map(([label, k]) => [label, fmt(D25[k]), fmt(D24[k])]),
    ...(totalRows ? { totalRows } : {}),
  };
}

// Indicadores derivados (usados apenas para montar textos; gabaritos são recalculados pelo validador).
const av = (conta: number, base: number) => (conta / base) * 100;
const ah = (atual: number, anterior: number) => ((atual - anterior) / Math.abs(anterior)) * 100;

const ML24 = av(D24.lucroLiquido, D24.receitaLiquida);
const ML25 = av(D25.lucroLiquido, D25.receitaLiquida);
const MB24 = av(D24.lucroBruto, D24.receitaLiquida);
const MB25 = av(D25.lucroBruto, D25.receitaLiquida);
const MO24 = av(D24.lucroOperacional, D24.receitaLiquida);
const MO25 = av(D25.lucroOperacional, D25.receitaLiquida);
const GIRO24 = D24.receitaLiquida / B24.ativoTotal;
const GIRO25 = D25.receitaLiquida / B25.ativoTotal;
const ALAV24 = B24.ativoTotal / B24.patrimonioLiquido;
const ALAV25 = B25.ativoTotal / B25.patrimonioLiquido;
const ROE24 = av(D24.lucroLiquido, B24.patrimonioLiquido);
const ROE25 = av(D25.lucroLiquido, B25.patrimonioLiquido);
const LC24 = B24.ativoCirculante / B24.passivoCirculante;
const LC25 = B25.ativoCirculante / B25.passivoCirculante;
const DESPOP24 = D24.lucroBruto - D24.lucroOperacional;
const DESPOP25 = D25.lucroBruto - D25.lucroOperacional;
const PASSIVO25 = B25.passivoCirculante + B25.passivoNaoCirculante;
const PASSIVO24 = B24.passivoCirculante + B24.passivoNaoCirculante;

const SRC_AV = 'Aula 5 — Análise Vertical (A.V.) · Caso Ambev 2025 × 2024';
const SRC_AH = 'Aula 5 — Análise Horizontal (A.H.) · Caso Ambev 2025 × 2024';
const SRC_LC = 'Aula 5 — Liquidez Corrente · Caso Ambev 2025 × 2024';
const SRC_MG = 'Aula 5 — Margens Bruta, Operacional e Líquida · Caso Ambev 2025 × 2024';
const SRC_RF = 'Aula 4 — Resultado Financeiro · Caso Ambev 2025 × 2024';
const SRC_ROE = 'Aula 5 — ROE, Giro, Alavancagem e DuPont · Caso Ambev 2025 × 2024';
const SRC_EST = 'Aula 5 — Análise integrada e decisão · Caso Ambev 2025 × 2024';

const ATIVO_LINES: [string, BpKey][] = [
  ['Ativo Circulante', 'ativoCirculante'],
  ['  Caixa e equivalentes de caixa', 'caixa'],
  ['  Contas a receber', 'contasReceber'],
  ['  Estoques', 'estoques'],
  ['Ativo Não Circulante', 'ativoNaoCirculante'],
  ['  Realizável a Longo Prazo', 'rlp'],
  ['  Investimentos', 'investimentos'],
  ['  Imobilizado', 'imobilizado'],
  ['  Intangível', 'intangivel'],
  ['ATIVO TOTAL', 'ativoTotal'],
];

const LC_LINES: [string, BpKey][] = [
  ['ATIVO CIRCULANTE', 'ativoCirculante'],
  ['  Caixa e equivalentes de caixa', 'caixa'],
  ['  Aplicações financeiras', 'aplicacoesFinanceiras'],
  ['  Contas a receber', 'contasReceber'],
  ['  Estoques', 'estoques'],
  ['  Demais ativos circulantes (tributos, despesas antecipadas, outros)', 'outrosAC'],
  ['PASSIVO CIRCULANTE', 'passivoCirculante'],
  ['  Fornecedores', 'fornecedores'],
  ['  Obrigações fiscais', 'obrigacoesFiscais'],
  ['  Empréstimos e financiamentos', 'emprestimosCP'],
  ['  Outras obrigações', 'outrasObrigacoesCP'],
];

export const questions: Question[] = [
  // ---------------------------------------------------------------- A.V. do Ativo
  {
    id: 'amb-001',
    type: 'numeric',
    topic: 'av',
    subtopic: 'A.V. do Ativo',
    skill: 'amb-av-ativo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule a Análise Vertical (A.V.) do Intangível da Ambev em 31/12/2025, tomando o Ativo Total como base. Responda em %, com 2 casas decimais.',
    tables: [bpTable('Ambev — Ativo (recorte do BP consolidado)', ATIVO_LINES, [0, 4, 9])],
    correct: 36.24,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'analiseVertical', args: [B25.intangivel, B25.ativoTotal] },
    solution: {
      formula: 'A.V. = Conta / Ativo Total × 100',
      substitution: `A.V. Intangível 2025 = ${fmt(B25.intangivel)} / ${fmt(B25.ativoTotal)} × 100`,
      computation: `${dec(B25.intangivel / B25.ativoTotal, 4)} × 100 = ${pct(av(B25.intangivel, B25.ativoTotal))}`,
      result: pct(av(B25.intangivel, B25.ativoTotal)),
      unit: '% do Ativo Total',
      interpretation: `De cada R$ 100 de Ativo da Ambev, cerca de R$ ${dec(av(B25.intangivel, B25.ativoTotal))} são Intangível (marcas, ágio, softwares). É a maior conta do Ativo, à frente do Imobilizado (${pct(av(B25.imobilizado, B25.ativoTotal))}) e do Caixa (${pct(av(B25.caixa, B25.ativoTotal))}).`,
    },
    explanation:
      'A Análise Vertical responde "quanto essa conta representa dentro da estrutura?". No Balanço, a base é o Ativo Total (ou Passivo + PL). O Intangível ser a maior conta mostra que boa parte do valor da Ambev está em marcas e ágio de aquisições, e não em caixa ou fábricas.',
    reasoningSteps: [
      'Identifique que é A.V. (peso na estrutura de um mesmo ano), não A.H. (variação entre anos).',
      'Escolha a base correta: no BP, Ativo Total do mesmo ano (2025).',
      'Divida a conta pela base e multiplique por 100.',
      'Interprete: "a cada R$ 100 de Ativo, R$ X são desta conta".',
    ],
    commonMistake: 'Usar o Ativo Total de 2024 como base, ou dividir pelo Ativo Não Circulante em vez do Ativo Total.',
    rule: 'Na A.V. do Balanço, divida a conta pelo Ativo Total DO MESMO ANO — nunca misture anos na A.V.',
    formula: 'A.V. = Conta / Ativo Total × 100',
    hint: 'Use os dois valores da coluna 31/12/2025.',
    concept: 'A Análise Vertical mostra o peso de cada conta numa base de 100%. No BP, a base é o Ativo Total (ou Passivo + PL); na DRE, a Receita Líquida.',
    sourceReference: SRC_AV,
  },
  {
    id: 'amb-002',
    type: 'true-false',
    topic: 'av',
    subtopic: 'A.V. do Ativo — leitura',
    skill: 'amb-av-ativo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'easy',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: `Julgue: "Em 31/12/2025, Caixa e equivalentes de caixa (R$ ${fmt(B25.caixa)} mil) é a conta de maior peso no Ativo da Ambev pela Análise Vertical; logo, a estrutura da empresa é dominada por recursos líquidos."`,
    tables: [bpTable('Ambev — Ativo (recorte do BP consolidado)', ATIVO_LINES, [0, 4, 9])],
    correct: false,
    explanation: `Pela A.V. de 2025, as maiores contas do Ativo são Intangível (${pct(av(B25.intangivel, B25.ativoTotal))}), Imobilizado (${pct(av(B25.imobilizado, B25.ativoTotal))}) e só então Caixa (${pct(av(B25.caixa, B25.ativoTotal))}). Intangível + Imobilizado somam ${pct(av(B25.intangivel + B25.imobilizado, B25.ativoTotal))} do Ativo: a estrutura é dominada por ativos de longo prazo (marcas, ágio, fábricas), típica de empresa intensiva em capital. Além disso, o peso do Caixa caiu em relação a 2024 (${pct(av(B24.caixa, B24.ativoTotal))}).`,
    reasoningSteps: [
      'Calcule (ou estime) a A.V. das maiores contas do Ativo: conta / Ativo Total.',
      'Ordene da maior para a menor e compare com a afirmação.',
      'Some os grupos de longo prazo (Imobilizado + Intangível) e compare com o Caixa.',
      'Só então tire conclusões sobre o perfil da estrutura.',
    ],
    commonMistake: 'Olhar apenas o Ativo Circulante e concluir que o Caixa é a maior conta da empresa inteira.',
    rule: 'Para dizer qual conta "domina" a estrutura, compare as A.V. de TODAS as contas relevantes do Ativo Total, não só as do circulante.',
    formula: 'A.V. = Conta / Ativo Total × 100',
    hint: 'Compare Caixa com Imobilizado e Intangível, não apenas com as outras contas do circulante.',
    concept: 'A A.V. permite comparar contas de tamanhos diferentes na mesma base (100% do Ativo) e entender o perfil do negócio.',
    sourceReference: SRC_AV,
  },
  // ---------------------------------------------------------------- A.V. do Passivo / estrutura de capital
  {
    id: 'amb-003',
    type: 'numeric',
    topic: 'av',
    subtopic: 'A.V. do Passivo + PL',
    skill: 'amb-av-estrutura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule quanto o Patrimônio Líquido representa do total de Passivo + PL da Ambev em 31/12/2025 (Análise Vertical da estrutura de capital). Responda em %, com 2 casas decimais.',
    tables: [
      bpTable(
        'Ambev — Passivo e PL (recorte do BP consolidado)',
        [
          ['Passivo Circulante', 'passivoCirculante'],
          ['Passivo Não Circulante', 'passivoNaoCirculante'],
          ['Patrimônio Líquido', 'patrimonioLiquido'],
          ['ATIVO TOTAL (= Passivo + PL)', 'ativoTotal'],
        ],
        [3],
      ),
    ],
    correct: 61.19,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'analiseVertical', args: [B25.patrimonioLiquido, B25.ativoTotal] },
    solution: {
      formula: 'A.V. = PL / (Passivo + PL) × 100',
      substitution: `A.V. PL 2025 = ${fmt(B25.patrimonioLiquido)} / ${fmt(B25.ativoTotal)} × 100`,
      computation: `${dec(B25.patrimonioLiquido / B25.ativoTotal, 4)} × 100 = ${pct(av(B25.patrimonioLiquido, B25.ativoTotal))}`,
      result: pct(av(B25.patrimonioLiquido, B25.ativoTotal)),
      unit: '% do Passivo + PL',
      interpretation: `Cerca de ${pct(av(B25.patrimonioLiquido, B25.ativoTotal))} dos recursos que financiam o Ativo vêm dos sócios e ${pct(av(PASSIVO25, B25.ativoTotal))} vêm de terceiros. Em 2024 a proporção era praticamente a mesma (${pct(av(B24.patrimonioLiquido, B24.ativoTotal))} de PL), o que é coerente com a alavancagem estável de ${dec(ALAV24)} → ${dec(ALAV25)}.`,
    },
    explanation:
      'Do lado direito do Balanço, a A.V. mostra de onde vêm os recursos: terceiros (Passivo) ou sócios (PL). Como Ativo = Passivo + PL, o total do lado direito é igual ao Ativo Total. Um PL com peso alto indica estrutura financiada majoritariamente por capital próprio — o que se reflete numa alavancagem (Ativo/PL) baixa.',
    reasoningSteps: [
      'Lembre que Passivo + PL = Ativo Total; essa é a base da A.V. do lado direito.',
      'Divida o PL de 2025 pelo total de 2025 e multiplique por 100.',
      'Complemento: Passivo / (Passivo + PL) = 100% − peso do PL.',
      'Compare com 2024 para ver se a estrutura de capital mudou.',
    ],
    commonMistake: 'Dividir o PL pelo Passivo (terceiros) em vez de pelo total Passivo + PL, obtendo um número acima de 100%.',
    rule: 'A.V. do lado direito do BP sempre usa como base o total Passivo + PL (que é igual ao Ativo Total).',
    formula: 'A.V. = PL / (Passivo + PL) × 100',
    hint: 'O total de Passivo + PL é igual a um valor que já aparece na tabela.',
    concept: 'A estrutura de capital mostra quanto do Ativo é financiado por terceiros e quanto pelos sócios.',
    sourceReference: SRC_AV,
  },
  {
    id: 'amb-004',
    type: 'multiple-choice',
    topic: 'av',
    subtopic: 'A.V. do Passivo Circulante',
    skill: 'amb-av-estrutura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: 'Quanto a conta Fornecedores representa DENTRO do Passivo Circulante da Ambev em 31/12/2025, e qual a leitura correta? (Use 2 casas decimais.)',
    tables: [bpTable('Ambev — Passivo Circulante (recorte do BP consolidado)', LC_LINES.slice(6), [0])],
    options: [
      {
        id: 'A',
        text: `${pct(av(B25.fornecedores, B25.ativoTotal))} — Fornecedores são irrelevantes no curto prazo.`,
        whyWrong: 'Usou o Passivo + PL total como base. A pergunta pede o peso DENTRO do Passivo Circulante, então a base é o PC.',
      },
      {
        id: 'B',
        text: `${pct(ah(B25.fornecedores, B24.fornecedores))} — o peso de Fornecedores encolheu no PC.`,
        whyWrong: 'Calculou A.H. (variação de 2024 para 2025), não A.V. A A.V. mede peso na estrutura do mesmo ano.',
      },
      {
        id: 'C',
        text: `${pct(av(B25.fornecedores, B25.passivoCirculante))} — cerca de metade das obrigações de curto prazo é com fornecedores, ligada ao ciclo operacional, e não a empréstimos bancários.`,
      },
      {
        id: 'D',
        text: `${pct(av(B25.passivoCirculante, B25.fornecedores))} — o PC é o dobro dos fornecedores, logo a dívida é bancária.`,
        whyWrong: 'Inverteu a divisão (PC / Fornecedores). A conta vai no numerador e a base no denominador.',
      },
      {
        id: 'E',
        text: `${pct(av(B24.fornecedores, B24.passivoCirculante))} — fornecedores dominam o PC.`,
        whyWrong: 'Usou os valores de 2024, e não os de 31/12/2025 pedidos no enunciado.',
      },
    ],
    correct: 'C',
    calc: { fn: 'analiseVertical', args: [B25.fornecedores, B25.passivoCirculante] },
    solution: {
      formula: 'A.V. = Fornecedores / Passivo Circulante × 100',
      substitution: `${fmt(B25.fornecedores)} / ${fmt(B25.passivoCirculante)} × 100`,
      computation: `${dec(B25.fornecedores / B25.passivoCirculante, 4)} × 100 = ${pct(av(B25.fornecedores, B25.passivoCirculante))}`,
      result: pct(av(B25.fornecedores, B25.passivoCirculante)),
      unit: '% do Passivo Circulante',
      interpretation: `Fornecedores são quase metade do PC; empréstimos de curto prazo são só ${pct(av(B25.emprestimosCP, B25.passivoCirculante))}. Isso é importante para ler a Liquidez Corrente de ${dec(LC25)}: boa parte do PC é financiamento operacional que se renova com as compras.`,
    },
    explanation:
      'Quando a pergunta delimita a base ("dentro do Passivo Circulante"), a A.V. usa essa base. A composição do PC é essencial para não ler a Liquidez Corrente isoladamente: um PC dominado por fornecedores é diferente de um PC dominado por empréstimos bancários vencendo.',
    reasoningSteps: [
      'Identifique a base pedida: "dentro do PC" → base = Passivo Circulante.',
      'Use os valores de 2025.',
      'Conta / base × 100.',
      'Compare com as demais contas do PC (ex.: empréstimos) para interpretar a composição.',
    ],
    commonMistake: 'Usar automaticamente o Ativo Total ou o Passivo + PL como base, mesmo quando o enunciado pede o peso dentro de um subgrupo.',
    rule: 'Antes de dividir, leia qual é a base pedida: Ativo Total, Passivo + PL, um subgrupo (como o PC) ou a Receita Líquida.',
    formula: 'A.V. = Conta / Base × 100',
    hint: 'A base é o subtotal do grupo mencionado no enunciado.',
    concept: 'A composição do Passivo Circulante ajuda a avaliar o risco de curto prazo: obrigações operacionais (fornecedores) se renovam no ciclo; dívidas bancárias exigem caixa ou refinanciamento.',
    sourceReference: SRC_AV,
  },
  // ---------------------------------------------------------------- A.H.
  {
    id: 'amb-005',
    type: 'numeric',
    topic: 'ah',
    subtopic: 'A.H. da Receita',
    skill: 'amb-ah-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule a Análise Horizontal (A.H.) da Receita Líquida da Ambev de 2024 para 2025. Responda em %, com 2 casas decimais (use sinal negativo se houver queda).',
    tables: [dreTable('Ambev — Receita Líquida (DRE consolidada)', [['Receita Líquida', 'receitaLiquida']])],
    correct: -1.35,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'analiseHorizontal', args: [D25.receitaLiquida, D24.receitaLiquida] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: `(${fmt(D25.receitaLiquida)} − ${fmt(D24.receitaLiquida)}) / ${fmt(D24.receitaLiquida)} × 100`,
      computation: `${fmt(D25.receitaLiquida - D24.receitaLiquida)} / ${fmt(D24.receitaLiquida)} × 100 = ${pct(ah(D25.receitaLiquida, D24.receitaLiquida))}`,
      result: pct(ah(D25.receitaLiquida, D24.receitaLiquida)),
      unit: '% de variação',
      interpretation: `A Receita Líquida caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))} em 2025. Mesmo assim o Lucro Líquido cresceu ${pct(ah(D25.lucroLiquido, D24.lucroLiquido))} — sinal de que o lucro melhorou por eficiência (despesas) e tributos, não por expansão de vendas.`,
    },
    explanation:
      'A Análise Horizontal responde "quanto essa conta cresceu ou caiu?" e sempre usa o ano ANTERIOR como base. O sinal importa: valor negativo = queda. Uma queda pequena de receita não é, por si, ruim nem boa — precisa ser lida junto com o que aconteceu com custos, despesas e lucro.',
    reasoningSteps: [
      'Identifique atual (2025) e anterior (2024).',
      'Calcule a diferença: atual − anterior (o sinal mostra se cresceu ou caiu).',
      'Divida pela base ANTERIOR e multiplique por 100.',
      'Interprete junto com outras linhas da DRE.',
    ],
    commonMistake: 'Dividir pela receita de 2025 (ano atual) ou esquecer o sinal negativo da queda.',
    rule: 'Na A.H., a base é SEMPRE o período anterior, e o sinal do resultado indica crescimento (+) ou queda (−).',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'Qual dos dois anos é a base?',
    concept: 'A A.H. mostra a evolução de uma conta no tempo, em percentual sobre o período anterior.',
    sourceReference: SRC_AH,
  },
  {
    id: 'amb-006',
    type: 'numeric',
    topic: 'ah',
    subtopic: 'A.H. do Caixa',
    skill: 'amb-ah-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule a Análise Horizontal (A.H.) de Caixa e equivalentes de caixa da Ambev entre 31/12/2024 e 31/12/2025. Responda em %, com 2 casas decimais (com sinal).',
    tables: [ambevBalanceTable()],
    correct: -34.82,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'analiseHorizontal', args: [B25.caixa, B24.caixa] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: `(${fmt(B25.caixa)} − ${fmt(B24.caixa)}) / ${fmt(B24.caixa)} × 100`,
      computation: `${fmt(B25.caixa - B24.caixa)} / ${fmt(B24.caixa)} × 100 = ${pct(ah(B25.caixa, B24.caixa))}`,
      result: pct(ah(B25.caixa, B24.caixa)),
      unit: '% de variação',
      interpretation: `O caixa caiu cerca de um terço (R$ ${fmt(B24.caixa - B25.caixa)} mil), num ano em que a empresa teve Lucro Líquido de R$ ${fmt(D25.lucroLiquido)} mil. "Lucro não é caixa": o caixa gerado foi consumido por outros usos (por exemplo, distribuição aos acionistas, investimentos ou pagamento de obrigações), algo que só a DFC detalha. Essa queda explica a maior parte da redução da Liquidez Corrente (${dec(LC24)} → ${dec(LC25)}).`,
    },
    explanation:
      'A A.H. mostra a variação de uma conta em relação ao ano anterior. Aqui, a forte queda do caixa ocorre ao mesmo tempo em que a empresa lucrou — um exemplo real de que lucro (DRE, competência) e caixa (DFC) são coisas diferentes. O BP mostra apenas a "fotografia" do saldo final; o "filme do caixa" está na DFC.',
    reasoningSteps: [
      'Localize o caixa nas duas datas do BP.',
      'Atual − anterior: o resultado negativo indica queda.',
      'Divida pela base de 2024 e multiplique por 100.',
      'Relacione a queda com a liquidez e lembre que lucro não é caixa.',
    ],
    commonMistake: 'Usar 2025 como base (o que daria cerca de −53%) ou concluir que a empresa teve prejuízo porque o caixa caiu.',
    rule: 'Variação de caixa no BP não mede lucro: leia-a com a DRE (lucro) e a DFC (de onde veio e para onde foi o dinheiro).',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'A base é o saldo de 31/12/2024.',
    concept: 'BP é a fotografia; DRE é o filme do resultado; DFC é o filme do caixa. Uma queda de caixa com lucro positivo é perfeitamente possível.',
    sourceReference: SRC_AH,
  },
  {
    id: 'amb-007',
    type: 'multiple-choice',
    topic: 'ah',
    subtopic: 'A.H. do Lucro Líquido',
    skill: 'amb-ah-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Qual foi a Análise Horizontal (A.H.) do Lucro Líquido da Ambev de 2024 para 2025? (2 casas decimais.)',
    tables: [
      dreTable('Ambev — DRE consolidada (recorte)', [
        ['Receita Líquida', 'receitaLiquida'],
        ['Lucro Líquido', 'lucroLiquido'],
      ]),
    ],
    options: [
      {
        id: 'A',
        text: `+${pct(((D25.lucroLiquido - D24.lucroLiquido) / D25.lucroLiquido) * 100)}`,
        whyWrong: 'Dividiu a variação pelo lucro de 2025 (ano atual). Na A.H. a base é o ano anterior (2024).',
      },
      {
        id: 'B',
        text: `${pct(-ah(D25.lucroLiquido, D24.lucroLiquido))}`,
        whyWrong: 'Inverteu a ordem (anterior − atual) e trocou o sinal: o lucro CRESCEU de 2024 para 2025.',
      },
      {
        id: 'C',
        text: `${pct(ML25)}`,
        whyWrong: 'Esse número é a Margem Líquida de 2025 (LL / Receita), uma A.V. da DRE, e não a variação do lucro entre os anos.',
      },
      {
        id: 'D',
        text: `+${pct(ah(D25.lucroLiquido, D24.lucroLiquido))}`,
      },
      {
        id: 'E',
        text: `R$ ${fmt(D25.lucroLiquido - D24.lucroLiquido)} mil`,
        whyWrong: 'Essa é a variação absoluta em reais; a A.H. pede a variação RELATIVA, em % sobre o ano anterior.',
      },
    ],
    correct: 'D',
    calc: { fn: 'analiseHorizontal', args: [D25.lucroLiquido, D24.lucroLiquido] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: `(${fmt(D25.lucroLiquido)} − ${fmt(D24.lucroLiquido)}) / ${fmt(D24.lucroLiquido)} × 100`,
      computation: `${fmt(D25.lucroLiquido - D24.lucroLiquido)} / ${fmt(D24.lucroLiquido)} × 100 = ${pct(ah(D25.lucroLiquido, D24.lucroLiquido))}`,
      result: `+${pct(ah(D25.lucroLiquido, D24.lucroLiquido))}`,
      unit: '% de variação',
      interpretation: `O Lucro Líquido cresceu ${pct(ah(D25.lucroLiquido, D24.lucroLiquido))} enquanto a Receita caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}: a empresa passou a reter mais lucro por real vendido.`,
    },
    explanation:
      'A A.H. compara o mesmo item em dois períodos, com base no período anterior. Confundir A.H. com A.V. (margem) é um erro clássico: a margem mede peso dentro de um ano; a A.H. mede variação entre anos.',
    reasoningSteps: [
      'Separe A.H. (variação no tempo) de A.V. (peso na estrutura).',
      'Calcule atual − anterior.',
      'Divida pelo anterior e multiplique por 100.',
      'Confira o sinal: lucro subiu → A.H. positiva.',
    ],
    commonMistake: 'Usar o ano atual como base ou responder com a Margem Líquida.',
    rule: 'A.H. responde "quanto cresceu ou caiu"; A.V. responde "quanto pesa". Identifique a pergunta antes de escolher a fórmula.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'O lucro aumentou ou diminuiu? Isso define o sinal.',
    concept: 'A Análise Horizontal mede a evolução percentual de uma conta entre períodos.',
    sourceReference: SRC_AH,
  },
  {
    id: 'amb-008',
    type: 'true-false',
    topic: 'ah',
    subtopic: 'A.H. do Ativo — leitura',
    skill: 'amb-ah-leitura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: `Julgue: "O Ativo Total da Ambev caiu ${pct(-ah(B25.ativoTotal, B24.ativoTotal))} de 2024 para 2025, e a conta que mais contribuiu para essa queda, em reais, foi Caixa e equivalentes de caixa."`,
    tables: [bpTable('Ambev — Ativo (recorte do BP consolidado)', ATIVO_LINES, [0, 4, 9])],
    correct: true,
    explanation: `O Ativo Total caiu R$ ${fmt(B24.ativoTotal - B25.ativoTotal)} mil (A.H. ${pct(ah(B25.ativoTotal, B24.ativoTotal))}). Dessa queda, R$ ${fmt(B24.caixa - B25.caixa)} mil vieram do Caixa (A.H. ${pct(ah(B25.caixa, B24.caixa))}), seguido do Intangível (−R$ ${fmt(B24.intangivel - B25.intangivel)} mil; A.H. ${pct(ah(B25.intangivel, B24.intangivel))}) e do Imobilizado (−R$ ${fmt(B24.imobilizado - B25.imobilizado)} mil). Para saber qual conta "puxou" a variação do total, compare as variações em reais, não apenas os percentuais.`,
    reasoningSteps: [
      'Calcule a A.H. do total: (Atual − Anterior) / Anterior.',
      'Calcule a variação em reais das principais contas.',
      'Compare as contribuições em reais para a variação do total.',
      'Use a A.H. percentual de cada conta só para complementar a leitura.',
    ],
    commonMistake: 'Escolher a conta com maior A.H. percentual como a que mais "puxou" o total — uma conta pequena pode ter A.H. enorme e impacto pequeno em reais.',
    rule: 'Para explicar a variação de um total, compare as variações em reais das contas; a A.H. em % mostra intensidade, não contribuição.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'Calcule quanto cada grande conta variou em R$ mil.',
    concept: 'A A.H. de uma conta e sua contribuição para a variação do total são informações diferentes e complementares.',
    sourceReference: SRC_AH,
  },
  // ---------------------------------------------------------------- Liquidez
  {
    id: 'amb-009',
    type: 'multi-part',
    topic: 'liquidez',
    subtopic: 'Liquidez Corrente 2024 × 2025',
    skill: 'amb-lc-interpretacao',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: 'Com base no recorte do Balanço da Ambev, calcule a Liquidez Corrente dos dois anos e interprete a mudança.',
    tables: [bpTable('Ambev — Ativo e Passivo Circulantes (recorte do BP consolidado)', LC_LINES, [0, 6])],
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'a) Liquidez Corrente em 31/12/2024 (2 casas decimais).',
        correct: 1.1,
        unit: 'ratio',
        decimals: 2,
        points: 3,
        calc: { fn: 'liquidezCorrente', args: [B24.ativoCirculante, B24.passivoCirculante] },
        solution: {
          formula: 'LC = Ativo Circulante / Passivo Circulante',
          substitution: `LC 2024 = ${fmt(B24.ativoCirculante)} / ${fmt(B24.passivoCirculante)}`,
          computation: `= ${dec(LC24, 4)}`,
          result: dec(LC24),
          unit: 'vezes (índice)',
          interpretation: `Em 2024, para cada R$ 1,00 de PC havia R$ ${dec(LC24)} de AC: LC > 1, situação de folga.`,
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'b) Liquidez Corrente em 31/12/2025 (2 casas decimais).',
        correct: 0.96,
        unit: 'ratio',
        decimals: 2,
        points: 3,
        calc: { fn: 'liquidezCorrente', args: [B25.ativoCirculante, B25.passivoCirculante] },
        solution: {
          formula: 'LC = Ativo Circulante / Passivo Circulante',
          substitution: `LC 2025 = ${fmt(B25.ativoCirculante)} / ${fmt(B25.passivoCirculante)}`,
          computation: `= ${dec(LC25, 4)}`,
          result: dec(LC25),
          unit: 'vezes (índice)',
          interpretation: `Em 2025, para cada R$ 1,00 de PC há R$ ${dec(LC25)} de AC: LC < 1, sinal de atenção — o AC não cobre integralmente o PC.`,
        },
      },
      {
        id: 'c',
        kind: 'choice',
        prompt: 'c) Qual a leitura mais adequada da mudança?',
        points: 4,
        options: [
          {
            id: 'A',
            text: 'A empresa está insolvente em 2025, pois LC < 1 significa que não conseguirá pagar suas dívidas.',
            whyWrong: 'LC < 1 é sinal de ATENÇÃO, não de insolvência. É preciso olhar composição do AC e do PC, giro e natureza do negócio.',
          },
          {
            id: 'B',
            text: `A LC caiu principalmente porque o AC encolheu ${pct(-ah(B25.ativoCirculante, B24.ativoCirculante))}, puxado pela queda de ${pct(-ah(B25.caixa, B24.caixa))} do caixa, enquanto o PC caiu menos (${pct(-ah(B25.passivoCirculante, B24.passivoCirculante))}); como ~${dec(av(B25.fornecedores, B25.passivoCirculante), 0)}% do PC são fornecedores (operacionais), é sinal de atenção a acompanhar, e não de crise.`,
          },
          {
            id: 'C',
            text: 'A LC caiu porque o Passivo Circulante aumentou fortemente em 2025.',
            whyWrong: 'O PC DIMINUIU de 2024 para 2025; a queda da LC veio da redução maior do AC (sobretudo do caixa).',
          },
          {
            id: 'D',
            text: 'A mudança é irrelevante, pois a Ambev é uma empresa grande e lucrativa.',
            whyWrong: 'Tamanho e lucro não substituem a análise de liquidez: lucro não é caixa. A queda de 1,10 para 0,96 merece explicação.',
          },
        ],
        correct: 'B',
      },
    ],
    explanation:
      'A Liquidez Corrente compara o que se realiza no curto prazo (AC) com o que vence no curto prazo (PC). Pela regra da disciplina: LC > 1 folga, = 1 limite, < 1 atenção. Mas nunca se analisa a LC isoladamente: é preciso ver o que mudou no AC (caixa, recebíveis, estoques) e o que compõe o PC (fornecedores × empréstimos).',
    reasoningSteps: [
      'Calcule AC / PC para cada ano (não use Ativo Total nem Passivo Total).',
      'Classifique: > 1 folga, = 1 limite, < 1 atenção.',
      'Descubra o que mudou: compare a A.H. do AC e do PC e localize a conta que puxou a variação.',
      'Olhe a composição do PC antes de concluir sobre risco.',
    ],
    commonMistake: 'Concluir que LC < 1 significa falência, ou usar Passivo Total no denominador.',
    rule: 'Calcule LC = AC/PC e depois explique o número pela composição: qual conta do AC ou do PC mudou e qual a natureza dela.',
    formula: 'LC = Ativo Circulante / Passivo Circulante',
    hint: 'Compare quanto o AC e o PC variaram em %.',
    concept: 'Liquidez Corrente mede a cobertura das obrigações de curto prazo pelos recursos de curto prazo; sua leitura depende da composição dessas contas e da natureza do negócio.',
    sourceReference: SRC_LC,
  },
  {
    id: 'amb-010',
    type: 'multiple-choice',
    topic: 'liquidez',
    subtopic: 'Liquidez — leitura não isolada',
    skill: 'amb-lc-interpretacao',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: `A Liquidez Corrente da Ambev passou de ${dec(LC24)} (2024) para ${dec(LC25)} (2025). Um colega afirma: "A empresa precisa urgentemente tomar empréstimos de curto prazo para voltar a ter LC acima de 1". Qual análise é mais consistente com os dados?`,
    tables: [bpTable('Ambev — Ativo e Passivo Circulantes (recorte do BP consolidado)', LC_LINES, [0, 6])],
    options: [
      {
        id: 'A',
        text: 'O colega está certo: qualquer LC abaixo de 1 exige captar dívida de curto prazo imediatamente.',
        whyWrong: 'LC < 1 é sinal de atenção, não regra de ação automática. Além disso, captar dívida de CURTO prazo aumenta o PC junto com o AC e pouco melhora a LC.',
      },
      {
        id: 'B',
        text: 'A LC caiu porque os estoques explodiram, imobilizando o caixa.',
        whyWrong: `Os estoques CAÍRAM (de R$ ${fmt(B24.estoques)} mil para R$ ${fmt(B25.estoques)} mil). A conta que puxou a queda do AC foi o caixa.`,
      },
      {
        id: 'C',
        text: 'A LC deveria ser calculada com o Passivo Total, o que mostraria folga confortável.',
        whyWrong: 'LC é AC / PC por definição: compara curto prazo com curto prazo. Usar Passivo Total mistura prazos.',
      },
      {
        id: 'D',
        text: `A queda veio sobretudo do caixa (−R$ ${fmt(B24.caixa - B25.caixa)} mil); o PC é dominado por fornecedores (${pct(av(B25.fornecedores, B25.passivoCirculante))}) e os empréstimos de curto prazo são só R$ ${fmt(B25.emprestimosCP)} mil. É sinal de atenção a monitorar (caixa, giro, comparação com pares), não prova de que falta crédito.`,
      },
      {
        id: 'E',
        text: 'Como o lucro cresceu, a liquidez obrigatoriamente melhorou; o índice deve estar errado.',
        whyWrong: 'Lucro não é caixa. O lucro pode crescer enquanto o caixa cai (distribuições, investimentos, pagamentos).',
      },
    ],
    correct: 'D',
    explanation: `A análise da liquidez não termina no índice. Aqui, o AC caiu ${pct(-ah(B25.ativoCirculante, B24.ativoCirculante))}, principalmente pelo caixa (${pct(ah(B25.caixa, B24.caixa))}), enquanto o PC caiu ${pct(-ah(B25.passivoCirculante, B24.passivoCirculante))}. O PC é majoritariamente operacional (fornecedores), e a dívida bancária de curto prazo é pequena. Isso não elimina o risco — é um ponto de atenção —, mas muda a recomendação: monitorar a geração de caixa e comparar com pares, em vez de reagir mecanicamente ao número.`,
    reasoningSteps: [
      'Calcule ou confira a LC e classifique (folga, limite, atenção).',
      'Ache a conta do AC que mais caiu e a natureza do PC.',
      'Verifique se a ação proposta realmente melhora o índice (dívida de curto prazo aumenta o PC).',
      'Conclua de forma condicionada: atenção a monitorar, com comparação.',
    ],
    commonMistake: 'Tratar LC < 1 como sentença de crise e propor soluções que não atacam a causa.',
    rule: 'Diante de uma LC baixa, pergunte: qual conta mudou, qual é a natureza do PC e a ação proposta melhora mesmo o índice?',
    formula: 'LC = Ativo Circulante / Passivo Circulante',
    hint: 'Veja qual conta do AC mais diminuiu e quanto do PC é empréstimo.',
    concept: 'A leitura da Liquidez Corrente depende do caixa, dos recebíveis, dos estoques, da composição do PC e da natureza do negócio.',
    sourceReference: SRC_LC,
  },
  {
    id: 'amb-011',
    type: 'true-false',
    topic: 'liquidez',
    subtopic: 'Liquidez — pegadinha',
    skill: 'amb-lc-interpretacao',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'easy',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: `Julgue: "Como a Liquidez Corrente da Ambev em 2025 é ${dec(LC25)} (menor que 1), pode-se concluir que a empresa está insolvente e não conseguirá pagar suas obrigações."`,
    tables: [bpTable('Ambev — Circulantes (recorte do BP consolidado)', [['Ativo Circulante', 'ativoCirculante'], ['Passivo Circulante', 'passivoCirculante']])],
    correct: false,
    explanation: `Pela regra da disciplina, LC < 1 é sinal de ATENÇÃO, não de insolvência. Uma LC de ${dec(LC25)} significa que há R$ ${dec(LC25)} de AC para cada R$ 1,00 de PC. Para concluir algo, é preciso olhar a composição (o PC da Ambev é ${pct(av(B25.fornecedores, B25.passivoCirculante))} fornecedores), a geração de caixa, o giro e a natureza do negócio, e comparar com o ano anterior (${dec(LC24)}) e com pares.`,
    reasoningSteps: [
      'Classifique o índice: > 1 folga, = 1 limite, < 1 atenção.',
      'Lembre que o índice é uma fotografia de uma data.',
      'Verifique composição do AC e do PC e a capacidade de gerar caixa.',
      'Evite conclusões absolutas sem comparação.',
    ],
    commonMistake: 'Equiparar LC < 1 a falência.',
    rule: 'LC < 1 pede investigação (composição, giro, caixa, pares), nunca uma conclusão automática de insolvência.',
    formula: 'LC = Ativo Circulante / Passivo Circulante',
    hint: 'Qual é a regra de leitura da LC vista em aula?',
    concept: 'A LC é um indicador de folga de curto prazo; seu valor isolado não determina a capacidade de pagamento.',
    sourceReference: SRC_LC,
  },
  // ---------------------------------------------------------------- Margens
  {
    id: 'amb-012',
    type: 'numeric',
    topic: 'margens',
    subtopic: 'Margem Operacional',
    skill: 'amb-margens-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule a Margem Operacional da Ambev em 2025. Responda em %, com 2 casas decimais.',
    tables: [ambevIncomeTable()],
    correct: 26.54,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'margem', args: [D25.lucroOperacional, D25.receitaLiquida] },
    solution: {
      formula: 'MO = Lucro Operacional / Receita Líquida × 100',
      substitution: `MO 2025 = ${fmt(D25.lucroOperacional)} / ${fmt(D25.receitaLiquida)} × 100`,
      computation: `${dec(D25.lucroOperacional / D25.receitaLiquida, 4)} × 100 = ${pct(MO25)}`,
      result: pct(MO25),
      unit: '% da Receita Líquida',
      interpretation: `A cada R$ 100 de Receita Líquida, R$ ${dec(MO25)} viraram Lucro Operacional em 2025, contra R$ ${dec(MO24)} em 2024. A melhora veio da queda das despesas operacionais (de R$ ${fmt(DESPOP24)} mil para R$ ${fmt(DESPOP25)} mil).`,
    },
    explanation:
      'A Margem Operacional mostra quanto da receita sobra depois de custos e despesas operacionais, antes do resultado financeiro e dos tributos. Na DFP, a linha usada é "Resultado antes do resultado financeiro e dos tributos", que inclui a equivalência patrimonial — na disciplina tratamos essa linha como Lucro Operacional.',
    reasoningSteps: [
      'Localize o Lucro Operacional de 2025 (Lucro Bruto − Despesas Operacionais).',
      'Divida pela Receita Líquida do mesmo ano.',
      'Multiplique por 100.',
      'Leia como "a cada R$ 100 de receita…" e compare com 2024.',
    ],
    commonMistake: 'Usar o Lucro Bruto ou o LAIR no numerador, ou dividir pelo Ativo.',
    rule: 'Toda margem = lucro da linha desejada / Receita Líquida; escolha a linha de lucro pelo nome da margem.',
    formula: 'MO = Lucro Operacional / Receita Líquida × 100',
    hint: 'O Lucro Operacional vem antes do resultado financeiro na DRE.',
    concept: 'A Margem Operacional mede a eficiência da operação: quanto da receita sobra após custos e despesas operacionais.',
    sourceReference: SRC_MG,
  },
  {
    id: 'amb-013',
    type: 'multi-part',
    topic: 'margens',
    subtopic: 'Margem Bruta e Líquida',
    skill: 'amb-margens-leitura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: 'Calcule as margens indicadas da Ambev e interprete. Responda em %, com 2 casas decimais.',
    tables: [ambevIncomeTable()],
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'a) Margem Bruta de 2024.',
        correct: 51.24,
        unit: 'percent',
        decimals: 2,
        points: 2,
        calc: { fn: 'margem', args: [D24.lucroBruto, D24.receitaLiquida] },
        solution: {
          formula: 'MB = Lucro Bruto / Receita Líquida × 100',
          substitution: `${fmt(D24.lucroBruto)} / ${fmt(D24.receitaLiquida)} × 100`,
          computation: `= ${pct(MB24)}`,
          result: pct(MB24),
          unit: '% da Receita Líquida',
          interpretation: `A cada R$ 100 vendidos em 2024, R$ ${dec(MB24)} sobraram após o custo das vendas.`,
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'b) Margem Bruta de 2025.',
        correct: 51.42,
        unit: 'percent',
        decimals: 2,
        points: 2,
        calc: { fn: 'margem', args: [D25.lucroBruto, D25.receitaLiquida] },
        solution: {
          formula: 'MB = Lucro Bruto / Receita Líquida × 100',
          substitution: `${fmt(D25.lucroBruto)} / ${fmt(D25.receitaLiquida)} × 100`,
          computation: `= ${pct(MB25)}`,
          result: pct(MB25),
          unit: '% da Receita Líquida',
          interpretation: `A cada R$ 100 vendidos em 2025, R$ ${dec(MB25)} sobraram após o custo das vendas — praticamente estável em relação a 2024.`,
        },
      },
      {
        id: 'c',
        kind: 'numeric',
        prompt: 'c) Margem Líquida de 2025.',
        correct: 18.12,
        unit: 'percent',
        decimals: 2,
        points: 2,
        calc: { fn: 'margem', args: [D25.lucroLiquido, D25.receitaLiquida] },
        solution: {
          formula: 'ML = Lucro Líquido / Receita Líquida × 100',
          substitution: `${fmt(D25.lucroLiquido)} / ${fmt(D25.receitaLiquida)} × 100`,
          computation: `= ${pct(ML25)}`,
          result: pct(ML25),
          unit: '% da Receita Líquida',
          interpretation: `A cada R$ 100 de Receita Líquida, R$ ${dec(ML25)} viraram Lucro Líquido em 2025 (R$ ${dec(ML24)} em 2024).`,
        },
      },
      {
        id: 'd',
        kind: 'choice',
        prompt: 'd) Comparando 2024 e 2025, qual leitura é mais adequada?',
        points: 4,
        options: [
          {
            id: 'A',
            text: 'A Margem Líquida subiu porque a empresa reduziu fortemente o custo das vendas, o que aparece numa grande alta da Margem Bruta.',
            whyWrong: `A Margem Bruta praticamente não mudou (${pct(MB24)} → ${pct(MB25)}); a melhora não está no custo das vendas.`,
          },
          {
            id: 'B',
            text: `A Margem Bruta ficou estável (${pct(MB24)} → ${pct(MB25)}); a Margem Líquida subiu (${pct(ML24)} → ${pct(ML25)}) por eventos abaixo do Lucro Bruto: despesas operacionais menores e IR/CS menor, apesar de um resultado financeiro pior.`,
          },
          {
            id: 'C',
            text: 'A Margem Líquida subiu porque a receita cresceu.',
            whyWrong: `A Receita Líquida CAIU ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}. Margem é proporção; crescer receita não aumenta margem por si só.`,
          },
          {
            id: 'D',
            text: 'A Margem Líquida subiu porque o resultado financeiro melhorou.',
            whyWrong: `O resultado financeiro PIOROU (de R$ ${fmt(D24.resultadoFinanceiro)} mil para R$ ${fmt(D25.resultadoFinanceiro)} mil), pressionando a margem para baixo.`,
          },
        ],
        correct: 'B',
      },
    ],
    explanation:
      'As margens funcionam como uma "escada" da DRE: a Margem Bruta mostra o efeito do custo das vendas; a Operacional, o das despesas operacionais; a Líquida, o do resultado financeiro e dos tributos. Comparar os degraus entre dois anos mostra ONDE a rentabilidade mudou.',
    reasoningSteps: [
      'Calcule cada margem com a Receita Líquida do mesmo ano.',
      'Compare cada degrau (MB, MO, ML) entre 2024 e 2025.',
      'Localize o degrau em que a margem mudou e explique pelas linhas da DRE correspondentes.',
      'Expresse a leitura como "a cada R$ 100 de receita…".',
    ],
    commonMistake: 'Atribuir a melhora da Margem Líquida ao crescimento de receita ou ao custo das vendas sem conferir os degraus.',
    rule: 'Compare MB, MO e ML lado a lado: o degrau em que a margem muda mostra a linha da DRE responsável.',
    formula: 'MB = LB / RL; MO = LO / RL; ML = LL / RL',
    hint: 'Veja se a mudança aparece já na Margem Bruta ou só mais abaixo na DRE.',
    concept: 'Margem é a fração da Receita Líquida que vira cada nível de lucro.',
    sourceReference: SRC_MG,
  },
  {
    id: 'amb-014',
    type: 'multiple-choice',
    topic: 'margens',
    subtopic: 'Origem da melhora do lucro',
    skill: 'amb-origem-lucro',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: `Em 2025 a Receita Líquida da Ambev caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}, mas a Margem Operacional subiu de ${pct(MO24)} para ${pct(MO25)}. Qual explicação é consistente com a DRE?`,
    tables: [ambevIncomeTable()],
    options: [
      {
        id: 'A',
        text: `O custo das vendas caiu muito mais que a receita, elevando a Margem Bruta em vários pontos percentuais.`,
        whyWrong: `O custo das vendas caiu ${pct(-ah(-D25.custoVendas, -D24.custoVendas))}, pouco mais que a receita; a Margem Bruta só passou de ${pct(MB24)} para ${pct(MB25)}.`,
      },
      {
        id: 'B',
        text: 'A equivalência patrimonial foi a principal responsável pela alta da margem.',
        whyWrong: `A equivalência subiu para R$ ${fmt(D25.equivalenciaPatrimonial)} mil, valor muito pequeno diante de uma melhora de R$ ${fmt(D25.lucroOperacional - D24.lucroOperacional)} mil no Lucro Operacional.`,
      },
      {
        id: 'C',
        text: `As despesas operacionais caíram ${pct(-ah(DESPOP25, DESPOP24))} (de R$ ${fmt(DESPOP24)} mil para R$ ${fmt(DESPOP25)} mil), bem mais que a receita; com a Margem Bruta estável, isso elevou o Lucro Operacional e a MO.`,
      },
      {
        id: 'D',
        text: 'As receitas financeiras aumentaram e foram somadas ao Lucro Operacional.',
        whyWrong: 'Receitas financeiras ficam ABAIXO do Lucro Operacional (no Resultado Financeiro) e, além disso, diminuíram em 2025.',
      },
    ],
    correct: 'C',
    explanation: `Lucro Operacional = Lucro Bruto − Despesas Operacionais. O Lucro Bruto caiu ${pct(-ah(D25.lucroBruto, D24.lucroBruto))}, em linha com a receita (MB estável), mas as despesas operacionais (vendas, logística, administrativas e outras) caíram ${pct(-ah(DESPOP25, DESPOP24))}. Isso aumentou o Lucro Operacional em ${pct(ah(D25.lucroOperacional, D24.lucroOperacional))} e a MO em ${dec(MO25 - MO24)} p.p. A melhora, portanto, veio da eficiência em despesas, e não de vendas ou do financeiro.`,
    reasoningSteps: [
      'Compare a Margem Bruta dos dois anos para testar a hipótese "custo".',
      'Calcule Despesas Operacionais = Lucro Bruto − Lucro Operacional e sua A.H.',
      'Verifique em que posição da DRE cada item aparece (financeiro fica abaixo do LO).',
      'Pondere o tamanho de cada efeito em reais.',
    ],
    commonMistake: 'Atribuir a melhora operacional a itens financeiros, que ficam abaixo do Lucro Operacional.',
    rule: 'Para explicar uma margem, decomponha a DRE até o degrau correspondente e compare a A.H. de cada linha com a A.H. da receita.',
    formula: 'MO = (Lucro Bruto − Despesas Operacionais) / Receita Líquida × 100',
    hint: 'Calcule as despesas operacionais de cada ano pela diferença entre Lucro Bruto e Lucro Operacional.',
    concept: 'Se a Margem Bruta fica estável e a Margem Operacional sobe, a mudança está nas despesas operacionais.',
    sourceReference: SRC_MG,
  },
  // ---------------------------------------------------------------- Resultado financeiro
  {
    id: 'amb-015',
    type: 'numeric',
    topic: 'resultado-financeiro',
    subtopic: 'Despesas financeiras',
    skill: 'amb-rf-leitura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule a Análise Horizontal (A.H.) das Despesas Financeiras da Ambev de 2024 para 2025, usando os valores em módulo (sem o sinal negativo da DRE). Responda em %, com 2 casas decimais.',
    tables: [
      dreTable(
        'Ambev — Resultado Financeiro (recorte da DRE consolidada)',
        [
          ['Lucro Operacional', 'lucroOperacional'],
          ['  Receitas financeiras', 'receitasFinanceiras'],
          ['  Despesas financeiras', 'despesasFinanceiras'],
          ['(+/−) Resultado Financeiro', 'resultadoFinanceiro'],
          ['= Lucro antes do IR/CS', 'lair'],
        ],
        [0, 3, 4],
      ),
    ],
    correct: 31.13,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'analiseHorizontal', args: [-D25.despesasFinanceiras, -D24.despesasFinanceiras] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: `(${fmt(-D25.despesasFinanceiras)} − ${fmt(-D24.despesasFinanceiras)}) / ${fmt(-D24.despesasFinanceiras)} × 100`,
      computation: `${fmt(-D25.despesasFinanceiras + D24.despesasFinanceiras)} / ${fmt(-D24.despesasFinanceiras)} × 100 = ${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))}`,
      result: pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras)),
      unit: '% de variação',
      interpretation: `As despesas financeiras cresceram ${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))}, enquanto as receitas financeiras caíram. Com isso, o Resultado Financeiro piorou de R$ ${fmt(D24.resultadoFinanceiro)} mil para R$ ${fmt(D25.resultadoFinanceiro)} mil, consumindo parte do ganho operacional.`,
    },
    explanation:
      'Resultado Financeiro = Receitas financeiras − Despesas financeiras. Ao calcular a A.H. de uma despesa, trabalhar em módulo evita confusão de sinal: uma despesa que passa de 4,7 bi para 6,2 bi CRESCEU, e isso piora o resultado. A pergunta-chave da disciplina é: o lucro veio da operação ou foi ajudado/prejudicado pelo financeiro?',
    reasoningSteps: [
      'Tire o sinal das despesas (trabalhe em módulo) para medir o crescimento do gasto.',
      'Aplique a A.H. com base em 2024.',
      'Compare com as receitas financeiras para entender o Resultado Financeiro líquido.',
      'Avalie o efeito sobre o LAIR: o financeiro ajudou ou atrapalhou?',
    ],
    commonMistake: 'Calcular com os sinais negativos e concluir que a despesa "caiu 31%", ou achar que despesa financeira maior melhora o resultado.',
    rule: 'Ao analisar despesas, use o módulo para medir o tamanho do gasto e depois lembre o efeito: despesa maior reduz o lucro.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: `Use ${fmt(-D25.despesasFinanceiras)} e ${fmt(-D24.despesasFinanceiras)} sem o sinal negativo.`,
    concept: 'O Resultado Financeiro reflete o custo do financiamento e o rendimento das aplicações; fica entre o Lucro Operacional e o LAIR.',
    sourceReference: SRC_RF,
  },
  {
    id: 'amb-016',
    type: 'multiple-choice',
    topic: 'resultado-financeiro',
    subtopic: 'Operação × financeiro × tributos',
    skill: 'amb-rf-leitura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: `O Lucro Líquido da Ambev cresceu R$ ${fmt(D25.lucroLiquido - D24.lucroLiquido)} mil de 2024 para 2025. "O lucro veio da operação ou do financeiro?" Escolha a decomposição correta.`,
    tables: [
      dreTable(
        'Ambev — da operação ao Lucro Líquido (recorte da DRE consolidada)',
        [
          ['= Lucro Operacional', 'lucroOperacional'],
          ['(+/−) Resultado Financeiro', 'resultadoFinanceiro'],
          ['= Lucro antes do IR/CS', 'lair'],
          ['(−) IR/CS', 'irCs'],
          ['= Lucro Líquido', 'lucroLiquido'],
        ],
        [0, 2, 4],
      ),
    ],
    options: [
      {
        id: 'A',
        text: `Operação +R$ ${fmt(D25.lucroOperacional - D24.lucroOperacional)} mil; financeiro −R$ ${fmt(D24.resultadoFinanceiro - D25.resultadoFinanceiro)} mil (quase anulando o ganho operacional; LAIR ${pct(ah(D25.lair, D24.lair))}); IR/CS menor em R$ ${fmt(D25.irCs - D24.irCs)} mil explica o crescimento do LL.`,
      },
      {
        id: 'B',
        text: 'O lucro cresceu porque o resultado financeiro melhorou, compensando a queda da operação.',
        whyWrong: 'Inverteu os sinais: a operação MELHOROU e o financeiro PIOROU.',
      },
      {
        id: 'C',
        text: `O crescimento veio inteiramente da operação: o LAIR subiu na mesma proporção do Lucro Operacional (${pct(ah(D25.lucroOperacional, D24.lucroOperacional))}).`,
        whyWrong: `O LAIR praticamente não mudou (${pct(ah(D25.lair, D24.lair))}), porque o financeiro piorou quase o mesmo valor que a operação melhorou.`,
      },
      {
        id: 'D',
        text: 'O crescimento veio da receita líquida maior, que se transmitiu até o Lucro Líquido.',
        whyWrong: `A Receita Líquida caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))} em 2025.`,
      },
    ],
    correct: 'A',
    explanation: `Decompondo a variação do LL: o Lucro Operacional subiu R$ ${fmt(D25.lucroOperacional - D24.lucroOperacional)} mil; o Resultado Financeiro piorou R$ ${fmt(D24.resultadoFinanceiro - D25.resultadoFinanceiro)} mil; logo o LAIR variou R$ ${fmt(D25.lair - D24.lair)} mil (praticamente estável). O IR/CS foi R$ ${fmt(D25.irCs - D24.irCs)} mil menor (de R$ ${fmt(D24.irCs)} mil para R$ ${fmt(D25.irCs)} mil), e é isso que leva ao aumento de R$ ${fmt(D25.lucroLiquido - D24.lucroLiquido)} mil no LL. A operação melhorou, mas o financeiro consumiu esse ganho; a alta do LL dependeu de tributos menores — um efeito que precisa ser verificado quanto à recorrência.`,
    reasoningSteps: [
      'Calcule a variação em reais do Lucro Operacional.',
      'Calcule a variação do Resultado Financeiro (sinal: ficou mais negativo = piorou).',
      'Some as duas para chegar à variação do LAIR.',
      'Calcule a variação do IR/CS e confira: ΔLAIR + ΔIR/CS = ΔLL.',
    ],
    commonMistake: 'Olhar só o Lucro Líquido e atribuir toda a melhora à operação, sem decompor operação, financeiro e tributos.',
    rule: 'Para saber de onde veio o lucro, decomponha a variação do LL em: Δ Lucro Operacional + Δ Resultado Financeiro + Δ IR/CS.',
    formula: 'LL = Lucro Operacional ± Resultado Financeiro − IR/CS',
    hint: 'Faça a "ponte" entre o Lucro Operacional e o Lucro Líquido dos dois anos.',
    concept: 'A pergunta "o lucro veio da operação ou do financeiro?" é respondida separando os degraus da DRE abaixo do Lucro Operacional.',
    sourceReference: SRC_RF,
  },
  {
    id: 'amb-017',
    type: 'true-false',
    topic: 'resultado-financeiro',
    subtopic: 'LAIR estável',
    skill: 'amb-rf-leitura',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX,
    stem: `Julgue: "Embora o Lucro Operacional da Ambev tenha crescido ${pct(ah(D25.lucroOperacional, D24.lucroOperacional))} em 2025, o Lucro antes do IR/CS ficou praticamente estável (${pct(ah(D25.lair, D24.lair))}), porque o Resultado Financeiro piorou de R$ ${fmt(D24.resultadoFinanceiro)} mil para R$ ${fmt(D25.resultadoFinanceiro)} mil."`,
    tables: [ambevIncomeTable()],
    correct: true,
    explanation: `LAIR = Lucro Operacional ± Resultado Financeiro. O ganho operacional de R$ ${fmt(D25.lucroOperacional - D24.lucroOperacional)} mil foi praticamente anulado pela piora de R$ ${fmt(D24.resultadoFinanceiro - D25.resultadoFinanceiro)} mil do financeiro (despesas financeiras subiram ${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))}). Assim, a operação melhorou, mas o financeiro "devolveu" esse ganho antes dos tributos.`,
    reasoningSteps: [
      'Lembre a ordem da DRE: Lucro Operacional ± Resultado Financeiro = LAIR.',
      'Compare a variação em reais do LO com a do Resultado Financeiro.',
      'Confira a A.H. do LAIR.',
      'Conclua quem ajudou e quem atrapalhou o resultado.',
    ],
    commonMistake: 'Supor que, se o Lucro Operacional subiu, todos os lucros abaixo dele também sobem na mesma proporção.',
    rule: 'Entre o Lucro Operacional e o LAIR está o Resultado Financeiro: sempre confira se ele ajudou ou prejudicou.',
    formula: 'LAIR = Lucro Operacional ± Resultado Financeiro',
    hint: 'Compare a variação do Lucro Operacional com a do Resultado Financeiro, em reais.',
    concept: 'O resultado financeiro pode reforçar ou neutralizar a melhora da operação.',
    sourceReference: SRC_RF,
  },
  // ---------------------------------------------------------------- ROE, Giro, DuPont
  {
    id: 'amb-018',
    type: 'numeric',
    topic: 'roe',
    subtopic: 'ROE 2025',
    skill: 'amb-roe-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule o ROE da Ambev em 2025 (use o PL de 31/12/2025). Responda em %, com 2 casas decimais.',
    tables: [
      bpTable('Ambev — PL (BP consolidado)', [['Patrimônio Líquido', 'patrimonioLiquido']]),
      dreTable('Ambev — Lucro Líquido (DRE consolidada)', [['Lucro Líquido', 'lucroLiquido']]),
    ],
    correct: 18.01,
    unit: 'percent',
    decimals: 2,
    calc: { fn: 'roe', args: [D25.lucroLiquido, B25.patrimonioLiquido] },
    solution: {
      formula: 'ROE = Lucro Líquido / Patrimônio Líquido × 100',
      substitution: `ROE 2025 = ${fmt(D25.lucroLiquido)} / ${fmt(B25.patrimonioLiquido)} × 100`,
      computation: `${dec(D25.lucroLiquido / B25.patrimonioLiquido, 4)} × 100 = ${pct(ROE25)}`,
      result: pct(ROE25),
      unit: '% sobre o capital próprio',
      interpretation: `Para cada R$ 100 de capital próprio, a Ambev gerou R$ ${dec(ROE25)} de Lucro Líquido em 2025, contra R$ ${dec(ROE24)} em 2024. Se é "bom" depende da comparação com o custo de capital dos acionistas e com os pares do setor.`,
    },
    explanation:
      'O ROE mede o retorno sobre o capital dos sócios: Lucro Líquido dividido pelo Patrimônio Líquido. O número isolado não basta para julgar — compare com o ano anterior, com o custo de oportunidade do acionista e com empresas comparáveis.',
    reasoningSteps: [
      'Numerador: Lucro Líquido do ano (DRE).',
      'Denominador: Patrimônio Líquido (BP), não o Ativo.',
      'Divida e multiplique por 100.',
      'Interprete "para cada R$ 100 de capital próprio…" e compare.',
    ],
    commonMistake: 'Usar o Ativo Total no denominador (isso daria cerca de 11%) ou julgar o ROE sem comparação.',
    rule: 'ROE é sempre Lucro Líquido / Patrimônio Líquido — o "E" é de equity, o capital dos sócios.',
    formula: 'ROE = LL / PL × 100',
    hint: 'O denominador é o capital próprio.',
    concept: 'ROE (retorno sobre o Patrimônio Líquido) mostra quanto o capital dos sócios rendeu no período.',
    sourceReference: SRC_ROE,
  },
  {
    id: 'amb-019',
    type: 'numeric',
    topic: 'giro',
    subtopic: 'Giro do Ativo 2025',
    skill: 'amb-dupont-fatores',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Calcule o Giro do Ativo da Ambev em 2025 (use o Ativo Total de 31/12/2025). Responda em vezes, com 2 casas decimais.',
    tables: [
      bpTable('Ambev — Ativo e PL (BP consolidado)', [['Ativo Total', 'ativoTotal'], ['Patrimônio Líquido', 'patrimonioLiquido']]),
      dreTable('Ambev — DRE consolidada (recorte)', [['Receita Líquida', 'receitaLiquida'], ['Lucro Líquido', 'lucroLiquido']]),
    ],
    correct: 0.61,
    unit: 'times',
    decimals: 2,
    calc: { fn: 'giro', args: [D25.receitaLiquida, B25.ativoTotal] },
    solution: {
      formula: 'Giro = Receita Líquida / Ativo Total',
      substitution: `Giro 2025 = ${fmt(D25.receitaLiquida)} / ${fmt(B25.ativoTotal)}`,
      computation: `= ${dec(GIRO25, 4)}`,
      result: `${dec(GIRO25)}x`,
      unit: 'vezes',
      interpretation: `Cada R$ 1,00 de Ativo gerou R$ ${dec(GIRO25)} de receita em 2025, contra R$ ${dec(GIRO24)} em 2024. O giro subiu porque o Ativo caiu ${pct(-ah(B25.ativoTotal, B24.ativoTotal))} enquanto a receita caiu só ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}. Giro abaixo de 1 é natural num negócio intensivo em marcas, fábricas e distribuição.`,
    },
    explanation:
      'O Giro do Ativo mostra quantos reais de venda cada R$ 1 de Ativo gera. Ele pode subir por mais vendas ou por um Ativo menor — no caso da Ambev, foi o Ativo que encolheu. Giro baixo não é defeito em si: empresas intensivas em capital (fábricas, marcas) costumam ter giro menor que varejistas.',
    reasoningSteps: [
      'Numerador: Receita Líquida (DRE).',
      'Denominador: Ativo Total (BP), não o PL.',
      'Divida e expresse em "vezes".',
      'Compare com 2024 e identifique se mudou o numerador ou o denominador.',
    ],
    commonMistake: 'Dividir a receita pelo PL (o que mistura giro com alavancagem) ou achar que giro < 1 é sempre ruim.',
    rule: 'Giro = Receita / Ativo Total: ao interpretar uma mudança, verifique se veio da receita ou do tamanho do Ativo.',
    formula: 'Giro = Receita Líquida / Ativo Total',
    hint: 'Quantos reais de venda cada real de Ativo gerou?',
    concept: 'O Giro do Ativo mede a eficiência no uso dos ativos para gerar vendas e é um dos três fatores do DuPont.',
    sourceReference: SRC_ROE,
  },
  {
    id: 'amb-020',
    type: 'multiple-choice',
    topic: 'dupont',
    subtopic: 'ROE pelo DuPont',
    skill: 'amb-dupont-calculo',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX,
    stem: 'Usando a decomposição DuPont (Margem Líquida × Giro do Ativo × Alavancagem) com os dados de 2025, qual é o ROE da Ambev? (2 casas decimais.)',
    tables: [
      bpTable('Ambev — Ativo e PL (BP consolidado)', [['Ativo Total', 'ativoTotal'], ['Patrimônio Líquido', 'patrimonioLiquido']]),
      dreTable('Ambev — DRE consolidada (recorte)', [['Receita Líquida', 'receitaLiquida'], ['Lucro Líquido', 'lucroLiquido']]),
    ],
    options: [
      {
        id: 'A',
        text: pct(ML25 * GIRO25),
        whyWrong: 'Multiplicou apenas Margem × Giro e esqueceu a Alavancagem (Ativo/PL). Isso equivale a LL/Ativo, não ao ROE.',
      },
      {
        id: 'B',
        text: pct(ML25 * ALAV25),
        whyWrong: 'Multiplicou Margem × Alavancagem e esqueceu o Giro do Ativo.',
      },
      {
        id: 'C',
        text: pct(ML25),
        whyWrong: 'Essa é só a Margem Líquida (LL/Receita), o primeiro fator do DuPont, e não o ROE.',
      },
      {
        id: 'D',
        text: `${dec(ROE25 / 100, 4)}%`,
        whyWrong: 'Erro de escala: leu 0,18 como 0,18%. O ROE em fração é 0,18, ou seja, 18%.',
      },
      {
        id: 'E',
        text: pct(ROE25),
      },
    ],
    correct: 'E',
    calc: { fn: 'dupontDemonstracoes', args: [D25.lucroLiquido, D25.receitaLiquida, B25.ativoTotal, B25.patrimonioLiquido] },
    solution: {
      formula: 'ROE = (LL/Receita) × (Receita/Ativo) × (Ativo/PL)',
      substitution: `(${fmt(D25.lucroLiquido)}/${fmt(D25.receitaLiquida)}) × (${fmt(D25.receitaLiquida)}/${fmt(B25.ativoTotal)}) × (${fmt(B25.ativoTotal)}/${fmt(B25.patrimonioLiquido)})`,
      computation: `${pct(ML25)} × ${dec(GIRO25, 4)} × ${dec(ALAV25, 4)} = ${pct(ROE25)}`,
      result: pct(ROE25),
      unit: '% sobre o capital próprio',
      interpretation: `O DuPont reproduz o ROE direto (LL/PL = ${pct(ROE25)}), mas mostra de onde ele vem: margem de ${pct(ML25)}, giro de ${dec(GIRO25)}x e alavancagem de ${dec(ALAV25)}x.`,
    },
    explanation:
      'No DuPont, Receita e Ativo se cancelam na multiplicação, e o resultado é LL/PL — o próprio ROE. A vantagem é enxergar os três motores do retorno: rentabilidade das vendas (margem), eficiência dos ativos (giro) e uso de capital de terceiros (alavancagem).',
    reasoningSteps: [
      'Calcule a Margem Líquida (LL/Receita).',
      'Calcule o Giro (Receita/Ativo) e a Alavancagem (Ativo/PL).',
      'Multiplique os três fatores.',
      'Confira com LL/PL: os dois caminhos devem dar o mesmo resultado.',
    ],
    commonMistake: 'Esquecer um dos três fatores ou errar a escala do percentual.',
    rule: 'ROE = Margem × Giro × Alavancagem; se o produto não bater com LL/PL, algum fator está errado.',
    formula: 'ROE = ML × Giro × Alavancagem',
    hint: 'Os três fatores se encadeiam: o denominador de um é o numerador do próximo.',
    concept: 'A decomposição DuPont responde "de onde veio o ROE?".',
    sourceReference: SRC_ROE,
  },
  {
    id: 'amb-021',
    type: 'multi-part',
    topic: 'dupont',
    subtopic: 'DuPont 2024 × 2025',
    skill: 'amb-dupont-origem',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: `Monte o DuPont da Ambev para 2024 e compare com o de 2025, já calculado: ML ${pct(ML25)} × Giro ${dec(GIRO25)} × Alavancagem ${dec(ALAV25)} = ROE ${pct(ROE25)}. Use os valores de 31/12 de cada ano.`,
    tables: [
      bpTable('Ambev — Ativo e PL (BP consolidado)', [['Ativo Total', 'ativoTotal'], ['Patrimônio Líquido', 'patrimonioLiquido']]),
      dreTable('Ambev — DRE consolidada (recorte)', [['Receita Líquida', 'receitaLiquida'], ['Lucro Líquido', 'lucroLiquido']]),
    ],
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'a) Margem Líquida de 2024 (%, 2 casas).',
        correct: 16.6,
        unit: 'percent',
        decimals: 2,
        points: 2,
        calc: { fn: 'margem', args: [D24.lucroLiquido, D24.receitaLiquida] },
        solution: {
          formula: 'ML = LL / Receita Líquida × 100',
          substitution: `${fmt(D24.lucroLiquido)} / ${fmt(D24.receitaLiquida)} × 100`,
          computation: `= ${pct(ML24)}`,
          result: pct(ML24),
          unit: '% da Receita Líquida',
          interpretation: `A cada R$ 100 de receita, R$ ${dec(ML24)} viraram lucro em 2024 (R$ ${dec(ML25)} em 2025).`,
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'b) Giro do Ativo de 2024 (vezes, 2 casas).',
        correct: 0.55,
        unit: 'times',
        decimals: 2,
        points: 2,
        calc: { fn: 'giro', args: [D24.receitaLiquida, B24.ativoTotal] },
        solution: {
          formula: 'Giro = Receita Líquida / Ativo Total',
          substitution: `${fmt(D24.receitaLiquida)} / ${fmt(B24.ativoTotal)}`,
          computation: `= ${dec(GIRO24, 4)}`,
          result: `${dec(GIRO24)}x`,
          unit: 'vezes',
          interpretation: `Cada R$ 1 de Ativo gerou R$ ${dec(GIRO24)} de receita em 2024 (R$ ${dec(GIRO25)} em 2025).`,
        },
      },
      {
        id: 'c',
        kind: 'numeric',
        prompt: 'c) Alavancagem de 2024 (vezes, 2 casas).',
        correct: 1.63,
        unit: 'times',
        decimals: 2,
        points: 2,
        calc: { fn: 'alavancagem', args: [B24.ativoTotal, B24.patrimonioLiquido] },
        solution: {
          formula: 'Alavancagem = Ativo Total / PL',
          substitution: `${fmt(B24.ativoTotal)} / ${fmt(B24.patrimonioLiquido)}`,
          computation: `= ${dec(ALAV24, 4)}`,
          result: `${dec(ALAV24)}x`,
          unit: 'vezes',
          interpretation: `Cada R$ 1 dos sócios sustentava R$ ${dec(ALAV24)} de Ativo em 2024 — praticamente igual a 2025 (${dec(ALAV25)}).`,
        },
      },
      {
        id: 'd',
        kind: 'numeric',
        prompt: 'd) ROE de 2024 pelo DuPont (%, 2 casas).',
        correct: 14.91,
        unit: 'percent',
        decimals: 2,
        points: 2,
        calc: { fn: 'dupontDemonstracoes', args: [D24.lucroLiquido, D24.receitaLiquida, B24.ativoTotal, B24.patrimonioLiquido] },
        solution: {
          formula: 'ROE = ML × Giro × Alavancagem',
          substitution: `${pct(ML24)} × ${dec(GIRO24, 4)} × ${dec(ALAV24, 4)}`,
          computation: `= ${pct(ROE24)}`,
          result: pct(ROE24),
          unit: '% sobre o capital próprio',
          interpretation: `Confere com LL/PL de 2024 (${fmt(D24.lucroLiquido)} / ${fmt(B24.patrimonioLiquido)}).`,
        },
      },
      {
        id: 'e',
        kind: 'choice',
        prompt: `e) O ROE subiu de ${pct(ROE24)} para ${pct(ROE25)}. De onde veio a melhora?`,
        points: 2,
        options: [
          {
            id: 'A',
            text: 'Da alavancagem: a empresa passou a usar muito mais capital de terceiros.',
            whyWrong: `A alavancagem ficou praticamente estável (${dec(ALAV24)} → ${dec(ALAV25)}); ela não explica a alta do ROE.`,
          },
          {
            id: 'B',
            text: `Da margem (${pct(ML24)} → ${pct(ML25)}) e do giro (${dec(GIRO24)} → ${dec(GIRO25)}), com alavancagem estável — uma melhora de eficiência, não de risco financeiro.`,
          },
          {
            id: 'C',
            text: 'Só do crescimento da receita, que elevou todos os fatores.',
            whyWrong: 'A receita caiu; o giro subiu porque o Ativo encolheu mais que a receita, e a margem subiu por despesas e tributos menores.',
          },
          {
            id: 'D',
            text: 'Do aumento do Patrimônio Líquido.',
            whyWrong: 'O PL DIMINUIU; PL maior, com o mesmo lucro, reduziria o ROE.',
          },
        ],
        correct: 'B',
      },
    ],
    explanation:
      'Comparar o DuPont de dois anos mostra qual motor mudou. Na Ambev, margem e giro subiram e a alavancagem ficou estável: o ROE melhorou por rentabilidade das vendas e uso mais intenso dos ativos, e não por mais endividamento. Ainda assim, vale lembrar que parte da margem veio de IR/CS menor e que o giro subiu porque o Ativo encolheu (inclusive o caixa).',
    reasoningSteps: [
      'Calcule os três fatores de cada ano com os dados do próprio ano.',
      'Multiplique e confira com LL/PL.',
      'Compare fator a fator entre 2024 e 2025.',
      'Atribua a variação do ROE aos fatores que mudaram e investigue a causa de cada um.',
    ],
    commonMistake: 'Atribuir a alta do ROE à alavancagem sem conferir que ela ficou estável.',
    rule: 'Para explicar a variação do ROE, compare os três fatores do DuPont entre os anos e só atribua a melhora aos fatores que de fato mudaram.',
    formula: 'ROE = ML × Giro × Alavancagem',
    hint: 'Calcule e compare cada fator; qual deles praticamente não mudou?',
    concept: 'O DuPont separa o ROE em margem, giro e alavancagem, permitindo saber se o retorno veio de eficiência ou de risco financeiro.',
    sourceReference: SRC_ROE,
  },
  // ---------------------------------------------------------------- Essays (análise integrada)
  {
    id: 'amb-022',
    type: 'essay',
    topic: 'dupont',
    subtopic: 'De onde veio o ROE',
    skill: 'amb-dupont-origem',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: 'Escreva uma análise (8 a 12 linhas) respondendo: "O ROE da Ambev melhorou de 2024 para 2025? De onde veio essa variação?". Use a decomposição DuPont e CITE OS NÚMEROS dos dois anos (ROE, Margem Líquida, Giro e Alavancagem). Conclua sobre a qualidade da melhora, sem julgamentos absolutos.',
    tables: [ambevIncomeTable(), ambevBalanceTable()],
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: `Apresenta o ROE dos dois anos (${pct(ROE24)} → ${pct(ROE25)}).`,
          points: 2,
          keywords: [['roe', '14,9', '18'], ['roe', '14.9', '18'], ['roe', '15%', '18%']],
        },
        {
          id: 'c2',
          description: `Mostra a Margem Líquida subindo (${pct(ML24)} → ${pct(ML25)}) e a explica (despesas operacionais/IR-CS menores).`,
          points: 3,
          keywords: [['margem', '18,1'], ['margem', '18.1'], ['margem', '16,6'], ['margem', '16.6']],
        },
        {
          id: 'c3',
          description: `Mostra o Giro subindo (${dec(GIRO24)} → ${dec(GIRO25)}) porque o Ativo caiu mais que a receita.`,
          points: 2,
          keywords: [['giro', '0,61'], ['giro', '0.61'], ['giro', '0,55'], ['giro', '0.55']],
        },
        {
          id: 'c4',
          description: `Indica alavancagem estável (${dec(ALAV24)} → ${dec(ALAV25)}).`,
          points: 2,
          keywords: [['alavanc', '1,63'], ['alavanc', '1.63'], ['alavanc', 'estave'], ['alavanc', 'constante']],
        },
        {
          id: 'c5',
          description: 'Conclui que a melhora veio de eficiência (margem e giro), não de mais endividamento, condicionando o julgamento à comparação (ano anterior, custo de capital, pares).',
          points: 1,
          keywords: [['eficien'], ['nao veio', 'alavanc'], ['nao foi', 'alavanc'], ['custo de capital'], ['pares']],
        },
      ],
      seriousErrors: [
        {
          description: 'Afirma que a melhora do ROE veio de maior alavancagem/endividamento.',
          patterns: ['alavancagem aumentou', 'mais alavancada', 'aumento da alavancagem', 'aumentou o endividamento'],
          penalty: 2,
        },
        {
          description: 'Calcula ROE sobre o Ativo.',
          patterns: ['lucro liquido / ativo', 'll / ativo', 'll/ativo'],
          penalty: 2,
        },
      ],
      modelAnswer: `O ROE da Ambev subiu de ${pct(ROE24)} em 2024 para ${pct(ROE25)} em 2025. Pelo DuPont (ROE = Margem Líquida × Giro × Alavancagem), a melhora veio de dois fatores: a Margem Líquida passou de ${pct(ML24)} para ${pct(ML25)}, porque as despesas operacionais caíram ${pct(-ah(DESPOP25, DESPOP24))} e o IR/CS foi menor (R$ ${fmt(D24.irCs)} mil → R$ ${fmt(D25.irCs)} mil), mesmo com o resultado financeiro pior; e o Giro do Ativo subiu de ${dec(GIRO24)} para ${dec(GIRO25)}, pois o Ativo caiu ${pct(-ah(B25.ativoTotal, B24.ativoTotal))} enquanto a receita caiu só ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}. A Alavancagem ficou estável em ${dec(ALAV25)}, então a melhora não veio de mais endividamento, mas de eficiência. Ressalvas: parte da margem depende de tributos menores (verificar recorrência) e o giro subiu pela redução do Ativo, inclusive do caixa, e não por mais vendas. Para julgar se ${pct(ROE25)} é adequado, é preciso comparar com o custo de capital do acionista e com os pares do setor.`,
    },
    explanation:
      'Uma boa análise de ROE não para no número: decompõe pelo DuPont, compara fator a fator entre os anos, explica a causa de cada mudança com as linhas da DRE e do BP e conclui com ressalvas e comparação. "Sempre exigir números nas análises."',
    reasoningSteps: [
      'Calcule o ROE dos dois anos.',
      'Calcule Margem, Giro e Alavancagem de cada ano.',
      'Identifique quais fatores mudaram e explique a causa (DRE e BP).',
      'Conclua sobre a qualidade (eficiência × risco) e condicione o julgamento à comparação.',
    ],
    commonMistake: 'Descrever a alta do ROE sem números ou atribuí-la à alavancagem.',
    rule: 'Análise de rentabilidade = números dos dois anos + DuPont fator a fator + causa de cada variação + conclusão comparativa.',
    formula: 'ROE = ML × Giro × Alavancagem',
    hint: 'Monte uma pequena tabela mental com os três fatores de 2024 e 2025 antes de escrever.',
    concept: 'O DuPont mostra se o ROE vem de margem, de giro ou de alavancagem — e cada origem tem riscos e sustentabilidade diferentes.',
    sourceReference: SRC_ROE,
  },
  {
    id: 'amb-023',
    type: 'essay',
    topic: 'estrategia',
    subtopic: 'Riscos',
    skill: 'amb-riscos',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: 'Como analista, identifique e analise TRÊS pontos de atenção (riscos) nas demonstrações da Ambev de 2025 em comparação com 2024. Para cada um, CITE NÚMEROS (índice, valor ou A.H.) e explique por que merece acompanhamento, evitando conclusões absolutas.',
    tables: [ambevBalanceTable(), ambevIncomeTable()],
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: `Liquidez Corrente caiu para menos de 1 (${dec(LC24)} → ${dec(LC25)}), com leitura de "atenção".`,
          points: 3,
          keywords: [['0,96'], ['0.96']],
        },
        {
          id: 'c2',
          description: `Explica a composição: queda do caixa (${pct(ah(B25.caixa, B24.caixa))}) e/ou PC dominado por fornecedores (${pct(av(B25.fornecedores, B25.passivoCirculante))}).`,
          points: 2,
          keywords: [['caixa', '34'], ['caixa', '18.6'], ['caixa', '18,6'], ['fornecedor', '49'], ['fornecedor', '22.5'], ['fornecedor', '22,5']],
        },
        {
          id: 'c3',
          description: `Aponta a queda da Receita Líquida (${pct(ah(D25.receitaLiquida, D24.receitaLiquida))}).`,
          points: 2,
          keywords: [['receita', '1,35'], ['receita', '1.35'], ['receita', '1,3'], ['receita', '88']],
        },
        {
          id: 'c4',
          description: `Aponta a piora do Resultado Financeiro (R$ ${fmt(D24.resultadoFinanceiro)} mil → R$ ${fmt(D25.resultadoFinanceiro)} mil; despesas financeiras +${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))}).`,
          points: 2,
          keywords: [['financeir', '4.001'], ['financeir', '4,0'], ['financeir', '72'], ['financeir', '31'], ['financeir', '6,2'], ['financeir', '6.218']],
        },
        {
          id: 'c5',
          description: 'Condiciona o julgamento (não isolado; comparar com pares/setor; monitorar), sem afirmar insolvência.',
          points: 1,
          keywords: [['isolad'], ['pares'], ['setor'], ['monitor'], ['acompanh']],
        },
      ],
      seriousErrors: [
        {
          description: 'Afirma que LC < 1 significa falência/insolvência.',
          patterns: ['vai falir', 'esta falida', 'insolvente', 'falencia'],
          penalty: 2,
        },
        {
          description: 'Confunde lucro com caixa (ex.: diz que o caixa caiu porque houve prejuízo).',
          patterns: ['teve prejuizo', 'houve prejuizo'],
          penalty: 2,
        },
      ],
      modelAnswer: `1) Liquidez: a Liquidez Corrente caiu de ${dec(LC24)} para ${dec(LC25)}, abaixo de 1 (sinal de atenção). A queda veio principalmente do caixa, que recuou ${pct(-ah(B25.caixa, B24.caixa))} (R$ ${fmt(B24.caixa)} mil → R$ ${fmt(B25.caixa)} mil). Atenuante: ${pct(av(B25.fornecedores, B25.passivoCirculante))} do PC são fornecedores, obrigações operacionais que se renovam, e os empréstimos de curto prazo são só R$ ${fmt(B25.emprestimosCP)} mil. Não é insolvência, mas merece acompanhamento da geração de caixa. 2) Receita: a Receita Líquida caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))} (R$ ${fmt(D24.receitaLiquida)} mil → R$ ${fmt(D25.receitaLiquida)} mil); o lucro cresceu por corte de despesas e tributos menores, efeitos que têm limite se as vendas não voltarem a crescer. 3) Financeiro: o Resultado Financeiro piorou de R$ ${fmt(D24.resultadoFinanceiro)} mil para R$ ${fmt(D25.resultadoFinanceiro)} mil, com despesas financeiras +${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))}, e praticamente anulou o ganho operacional (LAIR ${pct(ah(D25.lair, D24.lair))}). Esses pontos devem ser comparados com pares do setor e acompanhados nos próximos períodos.`,
    },
    explanation:
      'Identificar riscos exige olhar BP e DRE juntos e sempre com números e comparação. Os três pontos mais visíveis na Ambev 2025 são: liquidez abaixo de 1 (com caixa em queda), receita em queda e resultado financeiro pior. Cada um deve ser lido com atenuantes e sem conclusões absolutas.',
    reasoningSteps: [
      'Calcule os indicadores-chave dos dois anos (LC, A.H. da receita, resultado financeiro).',
      'Procure o que piorou de um ano para o outro.',
      'Para cada risco, cite o número e a causa (composição).',
      'Pondere atenuantes e diga o que monitorar.',
    ],
    commonMistake: 'Listar riscos genéricos ("concorrência", "economia") sem números das demonstrações, ou declarar falência por LC < 1.',
    rule: 'Todo risco apontado numa análise deve vir com o número, a comparação entre anos e a causa contábil.',
    hint: 'Procure indicadores que pioraram de 2024 para 2025 no BP e na DRE.',
    concept: 'A análise de risco integra liquidez (BP), tendência de receita e resultado financeiro (DRE).',
    sourceReference: SRC_EST,
  },
  {
    id: 'amb-024',
    type: 'essay',
    topic: 'estrategia',
    subtopic: 'Ações para melhorar a rentabilidade',
    skill: 'amb-estrategia-acoes',
    caseTag: 'ambev',
    dataSource: 'real-ambev',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX,
    stem: 'Você é o gestor financeiro da Ambev. Proponha ações para melhorar o ROE em 2026, conectando cada ação a um fator do DuPont (margem, giro ou alavancagem) ou ao resultado financeiro, e justificando com NÚMEROS de 2025 × 2024. Aponte também ao menos um risco/trade-off das ações propostas.',
    tables: [ambevIncomeTable(), ambevBalanceTable()],
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: `Diagnóstico numérico do ponto de partida (ROE ${pct(ROE25)}; ML ${pct(ML25)}).`,
          points: 2,
          keywords: [['18,01'], ['18.01'], ['18,0'], ['18.0'], ['18,1'], ['18.1']],
        },
        {
          id: 'c2',
          description: `Ação sobre a margem: recuperar receita (caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}) via preço/mix/volume e/ou manter a disciplina de custos e despesas.`,
          points: 2,
          keywords: [['margem', 'receita'], ['margem', 'despesa'], ['margem', 'custo'], ['preco'], ['mix']],
        },
        {
          id: 'c3',
          description: `Ação sobre o giro: usar melhor o Ativo (giro ${dec(GIRO25)}; Ativo de R$ ${fmt(B25.ativoTotal)} mil), ex.: ativos ociosos, estoques, capacidade.`,
          points: 2,
          keywords: [['giro'], ['ativo', 'ocios'], ['ativo', 'produtiv'], ['estoque']],
        },
        {
          id: 'c4',
          description: `Ação sobre o resultado financeiro: reduzir despesas financeiras (R$ ${fmt(-D25.despesasFinanceiras)} mil; RF R$ ${fmt(D25.resultadoFinanceiro)} mil).`,
          points: 2,
          keywords: [['financeir', '4.001'], ['financeir', '4,0'], ['financeir', '6,2'], ['financeir', '6.218'], ['despesas financeiras', 'reduz']],
        },
        {
          id: 'c5',
          description: `Aponta risco/trade-off: mais alavancagem eleva o ROE mas aumenta o risco; liquidez já em ${dec(LC25)}; comparar com custo de capital.`,
          points: 2,
          keywords: [['alavanc', 'risco'], ['liquidez'], ['0,96'], ['0.96'], ['custo de capital']],
        },
      ],
      seriousErrors: [
        {
          description: 'Trata o aumento da alavancagem como melhora sem risco.',
          patterns: ['alavancagem sempre', 'sem nenhum risco', 'sem risco algum'],
          penalty: 2,
        },
        {
          description: 'Propõe "aumentar o PL" como forma de elevar o ROE (o efeito é o oposto, mantido o lucro).',
          patterns: ['aumentar o pl para aumentar o roe', 'aumentar o patrimonio liquido para aumentar o roe'],
          penalty: 2,
        },
      ],
      modelAnswer: `Ponto de partida: ROE de ${pct(ROE25)} (${pct(ROE24)} em 2024), com Margem Líquida de ${pct(ML25)}, Giro de ${dec(GIRO25)} e Alavancagem de ${dec(ALAV25)}. (1) Margem: a receita caiu ${pct(-ah(D25.receitaLiquida, D24.receitaLiquida))}; recuperar volume e mix/preço e manter a disciplina que reduziu as despesas operacionais em ${pct(-ah(DESPOP25, DESPOP24))} elevaria a margem sem depender de IR/CS menor. (2) Resultado financeiro: as despesas financeiras subiram ${pct(ah(-D25.despesasFinanceiras, -D24.despesasFinanceiras))} (R$ ${fmt(-D25.despesasFinanceiras)} mil) e o resultado financeiro ficou em R$ ${fmt(D25.resultadoFinanceiro)} mil; renegociar custos financeiros recuperaria parte do ganho operacional que hoje é consumido antes do LAIR. (3) Giro: com Ativo de R$ ${fmt(B25.ativoTotal)} mil e giro de ${dec(GIRO25)}, revisar ativos ociosos e estoques aumentaria a receita por real investido. Trade-off: elevar a alavancagem (hoje ${dec(ALAV25)}) aumentaria o ROE, mas também o risco, num momento em que a Liquidez Corrente já está em ${dec(LC25)}; qualquer ação deve ser comparada ao custo de capital e aos pares do setor.`,
    },
    explanation:
      'Recomendações de gestão devem nascer do diagnóstico numérico e se conectar aos motores do ROE (margem, giro, alavancagem) e ao resultado financeiro. Uma proposta madura também reconhece trade-offs: aumentar alavancagem eleva o ROE, mas eleva o risco, especialmente com liquidez já abaixo de 1.',
    reasoningSteps: [
      'Faça o diagnóstico: ROE e seus três fatores nos dois anos.',
      'Encontre os pontos fracos (receita em queda, financeiro pior, liquidez).',
      'Para cada ponto, proponha uma ação e diga qual fator do DuPont ela move.',
      'Pondere riscos e compare com custo de capital e pares.',
    ],
    commonMistake: 'Propor ações genéricas ("vender mais", "cortar custos") sem números nem ligação com o DuPont.',
    rule: 'Toda recomendação deve dizer qual indicador ela move, quanto ele vale hoje e qual risco ela traz.',
    formula: 'ROE = ML × Giro × Alavancagem',
    hint: 'Pergunte-se: qual fator do DuPont cada ação altera?',
    concept: 'Estratégia financeira é escolher entre alavancas de rentabilidade considerando risco e custo de capital.',
    sourceReference: SRC_EST,
  },
];
