import type { Question, DataTable } from '../../shared/types';

// ---------------------------------------------------------------------------
// Casos fictícios reutilizados (valores em R$ mil)
//  - Rede Jacarandá Supermercados S.A.: varejo, margem baixa, giro alto
//  - Metalúrgica Serra Azul S.A.: indústria, intensiva em imobilizado
//  - Horizonte Digital Consultoria Ltda.: serviços, muito caixa
// ---------------------------------------------------------------------------

const NOTE = 'Valores em R$ mil';
const REF_AV = 'Aula 5 — Análise Vertical (resumo da P1)';
const REF_AH = 'Aula 5 — Análise Horizontal (resumo da P1)';
const REF_MG = 'Aula 5 — Margens Bruta, Operacional e Líquida (resumo da P1)';
const REF_LC = 'Aula 5 — Liquidez Corrente (resumo da P1)';

const CTX_JAC = 'CASO FICTÍCIO PARA ESTUDO — Rede Jacarandá Supermercados S.A. (varejo alimentar: margem baixa, giro alto)';
const CTX_SERRA = 'CASO FICTÍCIO PARA ESTUDO — Metalúrgica Serra Azul S.A. (indústria de autopeças, intensiva em máquinas)';
const CTX_HOR = 'CASO FICTÍCIO PARA ESTUDO — Horizonte Digital Consultoria Ltda. (serviços de tecnologia, com muito caixa)';

const BAL_JAC = [
  { label: 'Jacarandá X1', ativo: 5000, passivo: 3500, pl: 1500 },
  { label: 'Jacarandá X2', ativo: 6000, passivo: 4400, pl: 1600 },
];
const BAL_SERRA = [
  { label: 'Serra Azul X1', ativo: 12000, passivo: 6000, pl: 6000 },
  { label: 'Serra Azul X2', ativo: 13000, passivo: 6700, pl: 6300 },
];
const BAL_HOR = [
  { label: 'Horizonte X1', ativo: 4000, passivo: 1400, pl: 2600 },
  { label: 'Horizonte X2', ativo: 5000, passivo: 1600, pl: 3400 },
];

const BP_JAC: DataTable = {
  caption: 'Rede Jacarandá — Balanço Patrimonial',
  note: NOTE,
  headers: ['Conta', 'X1', 'X2'],
  rows: [
    ['ATIVO CIRCULANTE', '2.800', '3.400'],
    ['Caixa e equivalentes', '400', '300'],
    ['Contas a receber de clientes', '600', '700'],
    ['Estoques de mercadorias', '1.800', '2.400'],
    ['ATIVO NÃO CIRCULANTE', '2.200', '2.600'],
    ['Imobilizado (lojas e centros de distribuição)', '2.200', '2.600'],
    ['ATIVO TOTAL', '5.000', '6.000'],
    ['PASSIVO CIRCULANTE', '2.800', '3.600'],
    ['Fornecedores', '2.000', '2.700'],
    ['Empréstimos de curto prazo', '500', '600'],
    ['Salários e encargos a pagar', '300', '300'],
    ['PASSIVO NÃO CIRCULANTE', '700', '800'],
    ['Financiamentos de longo prazo', '700', '800'],
    ['PATRIMÔNIO LÍQUIDO', '1.500', '1.600'],
    ['Capital Social', '1.000', '1.000'],
    ['Reservas de lucros', '500', '600'],
    ['PASSIVO + PL TOTAL', '5.000', '6.000'],
  ],
  totalRows: [0, 4, 6, 7, 11, 13, 16],
};

const DRE_JAC: DataTable = {
  caption: 'Rede Jacarandá — Demonstração do Resultado',
  note: NOTE,
  headers: ['Linha', 'X1', 'X2'],
  rows: [
    ['Receita Bruta', '11.500', '13.800'],
    ['(−) Deduções da receita', '(1.500)', '(1.800)'],
    ['Receita Líquida', '10.000', '12.000'],
    ['(−) Custo das Mercadorias Vendidas', '(7.800)', '(9.480)'],
    ['Lucro Bruto', '2.200', '2.520'],
    ['(−) Despesas Operacionais', '(1.700)', '(2.040)'],
    ['Lucro Operacional', '500', '480'],
    ['(±) Resultado Financeiro', '(80)', '(100)'],
    ['LAIR', '420', '380'],
    ['(−) IR/CS', '(120)', '(110)'],
    ['Lucro Líquido', '300', '270'],
  ],
  totalRows: [2, 4, 6, 8, 10],
};

const BP_SERRA: DataTable = {
  caption: 'Metalúrgica Serra Azul — Balanço Patrimonial',
  note: NOTE,
  headers: ['Conta', 'X1', 'X2'],
  rows: [
    ['ATIVO CIRCULANTE', '3.500', '3.800'],
    ['Caixa e equivalentes', '600', '450'],
    ['Contas a receber de clientes', '1.500', '1.700'],
    ['Estoques (matéria-prima e produtos)', '1.400', '1.650'],
    ['ATIVO NÃO CIRCULANTE', '8.500', '9.200'],
    ['Imobilizado (máquinas e fábrica)', '7.500', '8.200'],
    ['Intangível', '1.000', '1.000'],
    ['ATIVO TOTAL', '12.000', '13.000'],
    ['PASSIVO CIRCULANTE', '2.500', '3.000'],
    ['Fornecedores', '1.100', '1.300'],
    ['Empréstimos de curto prazo', '900', '1.200'],
    ['Salários e impostos a pagar', '500', '500'],
    ['PASSIVO NÃO CIRCULANTE', '3.500', '3.700'],
    ['Financiamentos de longo prazo', '3.500', '3.700'],
    ['PATRIMÔNIO LÍQUIDO', '6.000', '6.300'],
    ['Capital Social', '5.000', '5.000'],
    ['Reservas de lucros', '1.000', '1.300'],
    ['PASSIVO + PL TOTAL', '12.000', '13.000'],
  ],
  totalRows: [0, 4, 7, 8, 12, 14, 17],
};

const DRE_SERRA: DataTable = {
  caption: 'Metalúrgica Serra Azul — Demonstração do Resultado',
  note: NOTE,
  headers: ['Linha', 'X1', 'X2'],
  rows: [
    ['Receita Bruta', '9.600', '10.800'],
    ['(−) Deduções da receita', '(1.600)', '(1.800)'],
    ['Receita Líquida', '8.000', '9.000'],
    ['(−) Custo dos Produtos Vendidos', '(5.200)', '(6.120)'],
    ['Lucro Bruto', '2.800', '2.880'],
    ['(−) Despesas Operacionais', '(1.600)', '(1.620)'],
    ['Lucro Operacional', '1.200', '1.260'],
    ['(±) Resultado Financeiro', '(300)', '(360)'],
    ['LAIR', '900', '900'],
    ['(−) IR/CS', '(260)', '(270)'],
    ['Lucro Líquido', '640', '630'],
  ],
  totalRows: [2, 4, 6, 8, 10],
};

const BP_HOR: DataTable = {
  caption: 'Horizonte Digital — Balanço Patrimonial',
  note: NOTE,
  headers: ['Conta', 'X1', 'X2'],
  rows: [
    ['ATIVO CIRCULANTE', '3.400', '4.100'],
    ['Caixa e equivalentes', '2.400', '3.000'],
    ['Contas a receber de clientes', '900', '1.000'],
    ['Despesas antecipadas', '100', '100'],
    ['ATIVO NÃO CIRCULANTE', '600', '900'],
    ['Imobilizado (equipamentos)', '400', '500'],
    ['Intangível (softwares)', '200', '400'],
    ['ATIVO TOTAL', '4.000', '5.000'],
    ['PASSIVO CIRCULANTE', '1.200', '1.500'],
    ['Salários e encargos a pagar', '600', '700'],
    ['Impostos a recolher', '300', '350'],
    ['Adiantamentos de clientes', '300', '450'],
    ['PASSIVO NÃO CIRCULANTE', '200', '100'],
    ['Empréstimos de longo prazo', '200', '100'],
    ['PATRIMÔNIO LÍQUIDO', '2.600', '3.400'],
    ['Capital Social', '1.000', '1.000'],
    ['Reservas de lucros', '1.600', '2.400'],
    ['PASSIVO + PL TOTAL', '4.000', '5.000'],
  ],
  totalRows: [0, 4, 7, 8, 12, 14, 17],
};

const DRE_HOR: DataTable = {
  caption: 'Horizonte Digital — Demonstração do Resultado',
  note: NOTE,
  headers: ['Linha', 'X1', 'X2'],
  rows: [
    ['Receita Bruta', '6.900', '8.050'],
    ['(−) Deduções da receita', '(900)', '(1.050)'],
    ['Receita Líquida', '6.000', '7.000'],
    ['(−) Custo dos Serviços Prestados', '(3.300)', '(3.710)'],
    ['Lucro Bruto', '2.700', '3.290'],
    ['(−) Despesas Operacionais', '(1.500)', '(1.750)'],
    ['Lucro Operacional', '1.200', '1.540'],
    ['(±) Resultado Financeiro', '100', '160'],
    ['LAIR', '1.300', '1.700'],
    ['(−) IR/CS', '(400)', '(510)'],
    ['Lucro Líquido', '900', '1.190'],
  ],
  totalRows: [2, 4, 6, 8, 10],
};

export const questions: Question[] = [
  // =========================================================================
  // ANÁLISE VERTICAL (8)
  // =========================================================================
  {
    id: 'an-001',
    type: 'numeric',
    topic: 'av',
    subtopic: 'A.V. do Ativo',
    skill: 'av-calculo-ativo',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX_JAC,
    stem: 'Com base no Balanço Patrimonial da Rede Jacarandá, calcule a Análise Vertical (A.V.) dos Estoques de mercadorias em X2. Responda em %, com 1 casa decimal.',
    table: BP_JAC,
    balanceCheck: BAL_JAC,
    correct: 40.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'analiseVertical', args: [2400, 6000] },
    solution: {
      formula: 'A.V. (Ativo) = Conta / Ativo Total × 100',
      substitution: 'A.V. Estoques X2 = 2.400 / 6.000 × 100',
      computation: '2.400 / 6.000 = 0,40 → 0,40 × 100 = 40,0',
      result: '40,0%',
      unit: '% do Ativo Total',
      interpretation: 'De cada R$ 100 aplicados no Ativo da Jacarandá em X2, R$ 40 estão em estoques de mercadorias — algo típico de um varejo, que precisa de prateleira cheia para vender.',
    },
    explanation:
      'A Análise Vertical responde "quanto essa conta representa dentro da estrutura?". Para contas do Ativo, a base é sempre o Ativo Total do mesmo período. Os Estoques representam 40% de tudo o que a empresa aplicou em X2.',
    reasoningSteps: [
      'Identifique se a conta é do Ativo, do Passivo + PL ou da DRE — isso define a base.',
      'Estoques são Ativo, então a base é o Ativo Total de X2 (6.000).',
      'Divida a conta pela base e multiplique por 100.',
      'Leia o resultado como "peso" da conta na estrutura do Ativo.',
    ],
    commonMistake: 'Usar o Ativo Circulante (3.400) como base, obtendo 70,6%, ou misturar o Ativo Total de X1 com a conta de X2.',
    rule: 'Na A.V., a base é sempre o total da estrutura do mesmo período: Ativo Total para contas do Ativo, Passivo + PL para o lado direito e Receita Líquida na DRE.',
    formula: 'A.V. = Conta / Ativo Total × 100',
    hint: 'Qual é o total do lado do Ativo em X2?',
    concept: 'A Análise Vertical mede o peso de cada conta dentro de um total do mesmo período, permitindo enxergar a estrutura patrimonial ou de resultado.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-002',
    type: 'multiple-choice',
    topic: 'av',
    subtopic: 'A.V. do Passivo + PL',
    skill: 'av-base-correta',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_SERRA,
    stem: 'Qual é a A.V. dos Financiamentos de longo prazo da Metalúrgica Serra Azul em X2? Considere 2 casas decimais.',
    table: BP_SERRA,
    balanceCheck: BAL_SERRA,
    options: [
      { id: 'A', text: '58,73%', whyWrong: 'Dividiu pelo Patrimônio Líquido (3.700 / 6.300). Na A.V. do lado direito, a base é o total Passivo + PL, não apenas o PL.' },
      { id: 'B', text: '5,71%', whyWrong: 'Calculou a A.H. ((3.700 − 3.500) / 3.500): isso mede quanto a conta cresceu, não quanto ela pesa na estrutura.' },
      { id: 'C', text: '28,46%' },
      { id: 'D', text: '55,22%', whyWrong: 'Dividiu pelo Passivo Total (PC + PNC = 6.700), esquecendo o PL. A base da A.V. do lado direito é Passivo + PL Total (13.000).' },
      { id: 'E', text: '0,28%', whyWrong: 'Erro de escala: 3.700 / 13.000 = 0,2846, que equivale a 28,46%, e não a 0,28%.' },
    ],
    correct: 'C',
    calc: { fn: 'analiseVertical', args: [3700, 13000] },
    solution: {
      formula: 'A.V. (Passivo + PL) = Conta / (Passivo + PL Total) × 100',
      substitution: 'A.V. Financiamentos LP X2 = 3.700 / 13.000 × 100',
      computation: '3.700 / 13.000 = 0,2846 → × 100 = 28,46',
      result: '28,46%',
      unit: '% do Passivo + PL Total',
      interpretation: 'De cada R$ 100 de fontes de recursos da Serra Azul em X2, cerca de R$ 28,46 vieram de financiamentos de longo prazo.',
    },
    explanation:
      'O lado direito do balanço mostra as fontes de recursos: capital de terceiros (Passivo) e capital próprio (PL). A A.V. de uma conta desse lado usa o total Passivo + PL como base, que é igual ao Ativo Total (13.000). Assim, os financiamentos de longo prazo financiam 28,46% da estrutura.',
    reasoningSteps: [
      'Localize a conta: Financiamentos LP estão no Passivo Não Circulante.',
      'Base do lado direito = Passivo + PL Total = 13.000.',
      'Calcule 3.700 / 13.000 × 100.',
      'Confira a escala: um quociente de 0,28 corresponde a 28%.',
    ],
    commonMistake: 'Usar o Passivo Total ou o PL como base, ou confundir A.V. com A.H.',
    rule: 'Do lado direito do balanço, a base da A.V. é o Passivo + PL Total — que, pela equação patrimonial, é igual ao Ativo Total.',
    formula: 'A.V. = Conta / (Passivo + PL Total) × 100',
    hint: 'Qual é o total do lado direito do balanço em X2?',
    concept: 'Pela equação Ativo = Passivo + PL, o total das fontes é igual ao total das aplicações; a A.V. do lado direito mostra quanto cada fonte financia da estrutura.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-003',
    type: 'numeric',
    topic: 'av',
    subtopic: 'A.V. da DRE',
    skill: 'av-calculo-dre',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_HOR,
    stem: 'Calcule a A.V. das Despesas Operacionais da Horizonte Digital em X2. Responda em %, com 1 casa decimal.',
    table: DRE_HOR,
    correct: 25.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'analiseVertical', args: [1750, 7000] },
    solution: {
      formula: 'A.V. (DRE) = Linha / Receita Líquida × 100',
      substitution: 'A.V. Despesas Operacionais X2 = 1.750 / 7.000 × 100',
      computation: '1.750 / 7.000 = 0,25 → × 100 = 25,0',
      result: '25,0%',
      unit: '% da Receita Líquida',
      interpretation: 'A cada R$ 100 de Receita Líquida em X2, R$ 25 foram consumidos por despesas operacionais (administrativas, comerciais etc.).',
    },
    explanation:
      'Na DRE, a base da Análise Vertical é a Receita Líquida, porque é a receita que efetivamente pertence à empresa depois das deduções. As despesas operacionais consumiram 25% dela. Usar a Receita Bruta (8.050) inflaria a base e subestimaria o peso da despesa.',
    reasoningSteps: [
      'Reconheça que a linha está na DRE: a base é a Receita Líquida.',
      'Use o valor do mesmo período: RL de X2 = 7.000.',
      'Divida 1.750 por 7.000 e multiplique por 100.',
      'Interprete: "a cada R$ 100 de RL, quanto essa linha consome?".',
    ],
    commonMistake: 'Usar a Receita Bruta (8.050) como base, obtendo 21,7%.',
    rule: 'Na DRE, toda A.V. (e toda margem) usa a Receita Líquida como base.',
    formula: 'A.V. = Linha da DRE / Receita Líquida × 100',
    hint: 'Qual receita, bruta ou líquida, é a base de comparação das linhas da DRE?',
    concept: 'A A.V. da DRE mostra quanto de cada R$ 100 de Receita Líquida foi consumido por custos e despesas ou sobrou como lucro.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-004',
    type: 'true-false',
    topic: 'av',
    subtopic: 'Base da A.V.',
    skill: 'av-base-correta',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Na Análise Vertical da DRE, cada linha deve ser dividida pela Receita Bruta, pois ela representa o total vendido pela empresa."',
    correct: false,
    explanation:
      'A base da A.V. da DRE é a Receita Líquida. A Receita Bruta inclui valores que não pertencem à empresa (impostos sobre vendas, devoluções, abatimentos), por isso não é a referência para medir o peso dos custos, despesas e lucros.',
    reasoningSteps: [
      'Lembre as três bases da A.V.: Ativo Total, Passivo + PL Total e Receita Líquida.',
      'Na DRE, a referência é a receita que de fato fica com a empresa.',
      'Receita Bruta − Deduções = Receita Líquida; a base é a líquida.',
    ],
    commonMistake: 'Achar que a "maior receita" é a base correta só porque representa o total faturado.',
    rule: 'Na DRE, A.V. e margens usam sempre a Receita Líquida como denominador.',
    hint: 'Os impostos sobre vendas pertencem à empresa?',
    concept: 'Receita Líquida = Receita Bruta − Deduções; é a base de toda a análise da DRE na disciplina.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-005',
    type: 'multi-part',
    topic: 'av',
    subtopic: 'A.V. × A.H.',
    skill: 'av-vs-ah-combinar',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'interpretation',
    context: CTX_HOR,
    stem: 'Analise as Contas a receber de clientes da Horizonte Digital nos dois anos.',
    table: BP_HOR,
    balanceCheck: BAL_HOR,
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'A.V. das Contas a receber em X1 (%, 1 casa decimal).',
        correct: 22.5,
        unit: 'percent',
        decimals: 1,
        points: 2,
        calc: { fn: 'analiseVertical', args: [900, 4000] },
        solution: {
          formula: 'A.V. = Conta / Ativo Total × 100',
          substitution: '900 / 4.000 × 100',
          computation: '900 / 4.000 = 0,225 → 22,5',
          result: '22,5%',
          unit: '% do Ativo Total',
          interpretation: 'Em X1, R$ 22,50 de cada R$ 100 do Ativo eram valores a receber de clientes.',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'A.V. das Contas a receber em X2 (%, 1 casa decimal).',
        correct: 20.0,
        unit: 'percent',
        decimals: 1,
        points: 2,
        calc: { fn: 'analiseVertical', args: [1000, 5000] },
        solution: {
          formula: 'A.V. = Conta / Ativo Total × 100',
          substitution: '1.000 / 5.000 × 100',
          computation: '1.000 / 5.000 = 0,20 → 20,0',
          result: '20,0%',
          unit: '% do Ativo Total',
          interpretation: 'Em X2, R$ 20 de cada R$ 100 do Ativo eram valores a receber de clientes.',
        },
      },
      {
        id: 'c',
        kind: 'numeric',
        prompt: 'A.H. das Contas a receber de X1 para X2 (%, 2 casas decimais).',
        correct: 11.11,
        unit: 'percent',
        decimals: 2,
        points: 3,
        calc: { fn: 'analiseHorizontal', args: [1000, 900] },
        solution: {
          formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
          substitution: '(1.000 − 900) / 900 × 100',
          computation: '100 / 900 = 0,1111 → 11,11',
          result: '+11,11%',
          unit: '% de variação',
          interpretation: 'O saldo a receber cresceu 11,11% em valor de X1 para X2.',
        },
      },
      {
        id: 'd',
        kind: 'choice',
        prompt: 'Como explicar que a conta cresceu em valor, mas perdeu peso na estrutura?',
        points: 3,
        correct: 'B',
        options: [
          { id: 'A', text: 'Há um erro: se a conta cresceu, a A.V. obrigatoriamente teria de subir.', whyWrong: 'A A.V. depende também da base. Se a base cresce mais que a conta, o peso cai mesmo com crescimento em valor.' },
          { id: 'B', text: 'O Ativo Total cresceu 25%, mais do que as Contas a receber (11,11%); por isso o peso relativo da conta caiu.' },
          { id: 'C', text: 'A A.V. caiu porque os clientes passaram a pagar menos do que deviam.', whyWrong: 'Nada nos dados indica inadimplência; o saldo a receber aumentou. A queda da A.V. é efeito da base que cresceu mais.' },
          { id: 'D', text: 'A queda da A.V. de 22,5% para 20% mostra que a conta diminuiu 2,5%.', whyWrong: 'Confunde A.V. com A.H.: a A.V. caiu 2,5 pontos percentuais de participação, enquanto o valor da conta aumentou 11,11%.' },
        ],
      },
    ],
    explanation:
      'A.V. e A.H. respondem perguntas diferentes. A A.H. mostra que o saldo a receber cresceu 11,11%; a A.V. mostra que sua participação no Ativo caiu de 22,5% para 20%, porque o Ativo Total cresceu 25% (de 4.000 para 5.000), puxado sobretudo pelo caixa. Uma conta pode crescer em valor e, ao mesmo tempo, perder peso na estrutura.',
    reasoningSteps: [
      'Calcule a A.V. de cada ano usando o Ativo Total do próprio ano.',
      'Calcule a A.H. usando o valor anterior como base.',
      'Compare o crescimento da conta com o crescimento da base (Ativo Total).',
      'Conclua: se a base cresce mais que a conta, a A.V. cai.',
    ],
    commonMistake: 'Concluir que a conta "diminuiu" porque a A.V. caiu.',
    rule: 'A.V. mede peso na estrutura; A.H. mede crescimento no tempo — sempre combine as duas antes de concluir.',
    formula: 'A.V. = Conta / Base × 100; A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'Quanto cresceu o Ativo Total no mesmo período?',
    concept: 'A participação de uma conta é uma razão: ela muda quando a conta muda, mas também quando a base muda.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-006',
    type: 'multiple-choice',
    topic: 'av',
    subtopic: 'Leitura da A.V. da DRE',
    skill: 'av-interpretacao',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX_JAC,
    stem: 'Calcule a A.V. do Custo das Mercadorias Vendidas (CMV) da Rede Jacarandá em X2 e escolha a leitura correta.',
    table: DRE_JAC,
    options: [
      { id: 'A', text: '21,5% — o CMV cresceu cerca de um quinto de X1 para X2.', whyWrong: 'Esse é o resultado da A.H. ((9.480 − 7.800) / 7.800), que mede crescimento, e não a A.V., que mede peso na Receita Líquida.' },
      { id: 'B', text: '79,0% — a cada R$ 100 de Receita Líquida, R$ 79 foram consumidos pelo custo das mercadorias vendidas.' },
      { id: 'C', text: '68,7% — a cada R$ 100 vendidos, R$ 68,70 foram gastos com mercadorias.', whyWrong: 'Usou a Receita Bruta (13.800) como base. A A.V. da DRE é calculada sobre a Receita Líquida (12.000).' },
      { id: 'D', text: '21,0% — a cada R$ 100 de Receita Líquida, sobram R$ 21 de CMV.', whyWrong: 'Esse é o complemento (100% − 79%), que corresponde à Margem Bruta, e não ao peso do CMV.' },
      { id: 'E', text: '158,0% — o CMV supera o tamanho da empresa.', whyWrong: 'Dividiu pelo Ativo Total (6.000). Linhas da DRE são comparadas com a Receita Líquida, não com o Ativo.' },
    ],
    correct: 'B',
    calc: { fn: 'analiseVertical', args: [9480, 12000] },
    solution: {
      formula: 'A.V. (DRE) = Linha / Receita Líquida × 100',
      substitution: '9.480 / 12.000 × 100',
      computation: '9.480 / 12.000 = 0,79 → 79,0',
      result: '79,0%',
      unit: '% da Receita Líquida',
      interpretation: 'O custo das mercadorias consome R$ 79 de cada R$ 100 de Receita Líquida; sobram R$ 21 (Margem Bruta) para cobrir as demais despesas.',
    },
    explanation:
      'A A.V. da DRE mostra quanto de cada R$ 100 de Receita Líquida foi consumido por cada linha. Um CMV de 79% é coerente com um supermercado, que revende mercadorias com pouco acréscimo de preço e compensa a margem baixa com grande volume.',
    reasoningSteps: [
      'Identifique a linha (CMV de X2 = 9.480) e a base (Receita Líquida de X2 = 12.000).',
      'Calcule 9.480 / 12.000 × 100 = 79%.',
      'Traduza: "a cada R$ 100 de RL, R$ 79 vão para o custo".',
      'Descarte leituras que falam em crescimento: isso é A.H.',
    ],
    commonMistake: 'Ler a A.V. como se fosse crescimento (A.H.) ou usar a Receita Bruta como base.',
    rule: 'A.V. responde "quanto essa conta representa dentro da estrutura?"; se a frase fala em "cresceu" ou "caiu", é A.H.',
    formula: 'A.V. = Linha / Receita Líquida × 100',
    hint: 'A pergunta é sobre peso na receita, não sobre variação no tempo.',
    concept: 'Na DRE, a A.V. de custos e despesas é o "consumo" da receita; a A.V. dos lucros corresponde às margens.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-007',
    type: 'short-answer',
    topic: 'av',
    subtopic: 'A.V. e natureza do negócio',
    skill: 'av-interpretacao',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: 'CASO FICTÍCIO PARA ESTUDO — comparação entre Rede Jacarandá (varejo), Metalúrgica Serra Azul (indústria) e Horizonte Digital (serviços).',
    stem: 'A tabela mostra a maior conta do Ativo de cada empresa em X2, pela Análise Vertical. Explique o que essas A.V. revelam sobre a natureza de cada negócio e por que a A.V. permite comparar empresas de tamanhos diferentes. Aponte também um cuidado ao fazer essa comparação.',
    table: {
      caption: 'Maior conta do Ativo em X2 (A.V. sobre o Ativo Total)',
      note: 'Valores em R$ mil',
      headers: ['Empresa', 'Conta', 'Valor', 'Ativo Total', 'A.V.'],
      rows: [
        ['Rede Jacarandá (varejo)', 'Estoques de mercadorias', '2.400', '6.000', '40,0%'],
        ['Metalúrgica Serra Azul (indústria)', 'Imobilizado', '8.200', '13.000', '63,1%'],
        ['Horizonte Digital (serviços)', 'Caixa e equivalentes', '3.000', '5.000', '60,0%'],
      ],
    },
    balanceCheck: [BAL_JAC[1], BAL_SERRA[1], BAL_HOR[1]],
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Relaciona o peso dos estoques ao modelo de varejo (vender mercadorias, prateleira cheia).',
          points: 3,
          keywords: [['estoque', 'varej'], ['estoque', 'mercador'], ['estoque', 'revend']],
        },
        {
          id: 'c2',
          description: 'Relaciona o imobilizado elevado à indústria intensiva em máquinas/fábrica e o caixa elevado à empresa de serviços com poucos ativos físicos.',
          points: 3,
          keywords: [['imobilizado', 'industr'], ['imobilizado', 'maquin'], ['imobilizado', 'fabric']],
        },
        {
          id: 'c3',
          description: 'Explica que a A.V. transforma valores absolutos em participação percentual, tornando comparáveis empresas de portes diferentes.',
          points: 2,
          keywords: [['porte'], ['tamanho'], ['percent', 'compar'], ['proporc']],
        },
        {
          id: 'c4',
          description: 'Aponta um cuidado: comparar com empresas do mesmo setor/natureza, ou combinar com A.H. e períodos anteriores, sem julgar "bom" ou "ruim" isoladamente.',
          points: 2,
          keywords: [['setor'], ['mesmo ramo'], ['natureza'], ['isolad'], ['periodo anterior']],
        },
      ],
      seriousErrors: [
        { description: 'Trata a A.V. como medida de crescimento.', patterns: ['cresceu 40', 'cresceu 60', 'cresceu 63'] },
        { description: 'Julga uma estrutura como "melhor" sem considerar a natureza do negócio.', patterns: ['estrutura melhor', 'empresa melhor', 'mais saudavel que as outras'] },
      ].map((e) => ({ ...e, penalty: 2 })),
      modelAnswer:
        'A A.V. mostra onde cada empresa aplica seus recursos. No varejo (Jacarandá), 40% do Ativo está em estoques, porque o negócio é revender mercadorias e precisa de prateleira cheia. Na indústria (Serra Azul), 63% está no imobilizado: máquinas e fábrica são a base da produção. Na consultoria (Horizonte), 60% está em caixa, pois o serviço depende de pessoas e não de ativos físicos. Como a A.V. expressa cada conta em percentual do total, ela elimina o efeito do porte e permite comparar empresas de tamanhos diferentes. Cuidado: estruturas diferentes refletem a natureza do negócio, então a comparação faz mais sentido com empresas do mesmo setor e com o histórico da própria empresa, combinando A.V. com A.H.',
    },
    explanation:
      'A Análise Vertical revela a "cara" da estrutura patrimonial. Estoques altos, imobilizado alto ou caixa alto não são bons nem ruins em si: refletem o modelo de negócio. Por ser percentual, a A.V. neutraliza o porte, mas a leitura correta exige comparar com pares do setor e com o próprio histórico.',
    reasoningSteps: [
      'Pergunte: "quanto essa conta representa dentro da estrutura?".',
      'Associe a conta dominante à atividade da empresa (revenda, produção, serviço).',
      'Lembre que percentuais permitem comparar portes diferentes.',
      'Evite julgamentos absolutos: compare com o setor e com o período anterior.',
    ],
    commonMistake: 'Concluir que a empresa com mais caixa é "melhor" sem considerar que cada negócio exige uma estrutura diferente.',
    rule: 'Leia a A.V. à luz da natureza do negócio e compare-a com empresas do mesmo setor ou com o histórico da própria empresa.',
    hint: 'O que uma indústria, um supermercado e uma consultoria precisam ter para funcionar?',
    concept: 'A A.V. expressa cada conta como percentual do total, revelando a composição da estrutura e permitindo comparações entre empresas de portes diferentes.',
    sourceReference: REF_AV,
  },
  {
    id: 'an-008',
    type: 'true-false',
    topic: 'av',
    subtopic: 'A.V. × A.H.',
    skill: 'av-vs-ah-combinar',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Se a A.V. de uma conta do Ativo caiu de um ano para o outro, então o valor dessa conta necessariamente diminuiu."',
    correct: false,
    explanation:
      'A A.V. é uma razão entre a conta e o total. Se o Ativo Total cresce mais rápido que a conta, a participação cai mesmo que a conta tenha aumentado em valor. Para saber se a conta cresceu ou caiu, é preciso olhar a A.H.',
    reasoningSteps: [
      'Lembre que A.V. = Conta / Base: duas coisas podem mudar.',
      'Teste um exemplo: conta 900 → 1.000 e Ativo 4.000 → 5.000; A.V. 22,5% → 20%.',
      'A conta subiu 11%, mas o peso caiu.',
      'Conclua que queda de A.V. não implica queda em valor.',
    ],
    commonMistake: 'Confundir perda de participação (A.V.) com redução de valor (A.H.).',
    rule: 'A.V. de uma conta pode cair mesmo que ela cresça em valor; use a A.H. para medir a variação do valor.',
    hint: 'O que acontece com uma fração quando o denominador cresce mais que o numerador?',
    concept: 'A A.V. mede participação; a A.H. mede variação no tempo. São perguntas diferentes.',
    sourceReference: REF_AV,
  },

  // =========================================================================
  // ANÁLISE HORIZONTAL (8)
  // =========================================================================
  {
    id: 'an-009',
    type: 'numeric',
    topic: 'ah',
    subtopic: 'Cálculo da A.H.',
    skill: 'ah-calculo',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX_JAC,
    stem: 'Calcule a Análise Horizontal (A.H.) da Receita Líquida da Rede Jacarandá de X1 para X2. Responda em %, com 1 casa decimal.',
    table: DRE_JAC,
    correct: 20.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'analiseHorizontal', args: [12000, 10000] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: '(12.000 − 10.000) / 10.000 × 100',
      computation: '2.000 / 10.000 = 0,20 → × 100 = 20,0',
      result: '+20,0%',
      unit: '% de variação em relação a X1',
      interpretation: 'A Receita Líquida da Jacarandá cresceu 20% de X1 para X2.',
    },
    explanation:
      'A Análise Horizontal responde "quanto essa conta cresceu ou caiu?". A variação absoluta (2.000) é dividida pelo valor do período anterior, que é o ponto de partida da comparação.',
    reasoningSteps: [
      'Identifique o período atual (X2) e o anterior (X1).',
      'Calcule a variação absoluta: atual − anterior.',
      'Divida pela base anterior e multiplique por 100.',
      'Mantenha o sinal: positivo é crescimento, negativo é queda.',
    ],
    commonMistake: 'Dividir pelo valor atual (2.000 / 12.000 = 16,7%).',
    rule: 'Na A.H., a base é sempre o período anterior.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'De onde a receita partiu?',
    concept: 'A A.H. mede a evolução de uma conta ao longo do tempo, em percentual sobre o valor de partida.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-010',
    type: 'numeric',
    topic: 'ah',
    subtopic: 'Sinal da A.H.',
    skill: 'ah-sinal',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_JAC,
    stem: 'Calcule a A.H. do Caixa e equivalentes da Rede Jacarandá de X1 para X2. Responda em %, com 1 casa decimal, e use o sinal negativo se houver queda.',
    table: BP_JAC,
    balanceCheck: BAL_JAC,
    correct: -25.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'analiseHorizontal', args: [300, 400] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: '(300 − 400) / 400 × 100',
      computation: '−100 / 400 = −0,25 → × 100 = −25,0',
      result: '−25,0%',
      unit: '% de variação em relação a X1',
      interpretation: 'O caixa da Jacarandá caiu 25% de X1 para X2, enquanto os estoques subiram — parte do dinheiro foi aplicada em mercadorias.',
    },
    explanation:
      'Quando o valor atual é menor que o anterior, a variação é negativa e deve ser apresentada com sinal de menos. Dizer "25%" sem sinal sugere crescimento e inverte a leitura do analista.',
    reasoningSteps: [
      'Atual = 300; anterior = 400.',
      'Variação: 300 − 400 = −100.',
      'Divida pela base anterior: −100 / 400 = −0,25.',
      'Multiplique por 100 e preserve o sinal: −25%.',
    ],
    commonMistake: 'Escrever +25% (esquecer o sinal) ou dividir pelo atual (−100 / 300 = −33,3%).',
    rule: 'Quedas aparecem com sinal negativo na A.H.; sempre faça (atual − anterior), nunca o contrário.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'O caixa aumentou ou diminuiu?',
    concept: 'O sinal da A.H. indica a direção do movimento: positivo = cresceu; negativo = caiu.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-011',
    type: 'multiple-choice',
    topic: 'ah',
    subtopic: 'Sinal e base da A.H.',
    skill: 'ah-sinal',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_SERRA,
    stem: 'Qual é a A.H. do Lucro Líquido da Metalúrgica Serra Azul de X1 para X2? Considere 2 casas decimais.',
    table: DRE_SERRA,
    options: [
      { id: 'A', text: '+1,56%', whyWrong: 'Inverteu o sinal: o lucro caiu de 640 para 630, então a variação é negativa.' },
      { id: 'B', text: '−1,59%', whyWrong: 'Dividiu pelo valor atual (−10 / 630). A base da A.H. é sempre o período anterior (640).' },
      { id: 'C', text: '−1 ponto percentual', whyWrong: 'Essa é a variação da margem líquida (8% → 7%), em pontos percentuais. A pergunta pede a variação do valor do lucro, que é a A.H.' },
      { id: 'D', text: '−1,56%' },
      { id: 'E', text: 'R$ −10 mil, ou seja, −10%', whyWrong: 'Confundiu a variação absoluta (R$ 10 mil) com a variação percentual. É preciso dividir a diferença pela base anterior.' },
    ],
    correct: 'D',
    calc: { fn: 'analiseHorizontal', args: [630, 640] },
    solution: {
      formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
      substitution: '(630 − 640) / 640 × 100',
      computation: '−10 / 640 = −0,015625 → × 100 = −1,5625',
      result: '−1,56%',
      unit: '% de variação em relação a X1',
      interpretation: 'O Lucro Líquido caiu 1,56% de X1 para X2, mesmo com a Receita Líquida crescendo 12,5%.',
    },
    explanation:
      'A A.H. compara o valor atual com o anterior e preserva o sinal. Aqui o lucro caiu R$ 10 mil sobre uma base de R$ 640 mil, uma queda de 1,56%. Note o contraste: a empresa vendeu mais, mas lucrou menos — um sinal para investigar as margens.',
    reasoningSteps: [
      'Atual (X2) = 630; anterior (X1) = 640.',
      'Variação absoluta = −10.',
      'Base = anterior = 640 → −10 / 640 = −1,5625%.',
      'Diferencie variação percentual (A.H.) de variação em pontos percentuais (de margens).',
    ],
    commonMistake: 'Dividir pelo atual ou esquecer o sinal negativo.',
    rule: 'A.H. = (atual − anterior) / anterior: o sinal vem da subtração e a base é sempre o passado.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
    hint: 'O lucro de X2 é maior ou menor que o de X1?',
    concept: 'A A.H. mede a evolução percentual de um valor; variações de percentuais (como margens) são expressas em pontos percentuais.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-012',
    type: 'true-false',
    topic: 'ah',
    subtopic: 'Sinal da A.H.',
    skill: 'ah-sinal',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Na Análise Horizontal, se uma conta passou de R$ 400 mil para R$ 300 mil, a variação deve ser apresentada como −25%, pois a base de comparação é o valor anterior."',
    correct: true,
    explanation:
      'A A.H. é (300 − 400) / 400 × 100 = −25%. A base é o valor anterior (400), e o sinal negativo indica queda. Se a base fosse o atual (300), o resultado seria −33,3%, o que distorce a leitura.',
    reasoningSteps: [
      'Faça atual − anterior: 300 − 400 = −100.',
      'Divida pelo anterior: −100 / 400 = −0,25.',
      'Converta para %: −25%.',
    ],
    commonMistake: 'Achar que a variação deve ser sempre positiva ou dividir pelo valor atual.',
    rule: 'Na A.H., sempre divida pela base anterior e mantenha o sinal da variação.',
    hint: 'Refaça a conta usando 400 como base.',
    concept: 'A A.H. mede quanto uma conta cresceu ou caiu em relação ao período anterior.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-013',
    type: 'multiple-choice',
    topic: 'ah',
    subtopic: 'Relevância: combinar A.V. e A.H.',
    skill: 'ah-relevancia-av',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX_HOR,
    stem: 'Na Horizonte Digital, o Intangível (softwares) teve A.H. de +100% de X1 para X2, e o Caixa teve A.H. de +25%. Um colega afirma que "a principal mudança do Ativo foi o Intangível". Qual avaliação é a mais adequada?',
    table: BP_HOR,
    balanceCheck: BAL_HOR,
    options: [
      { id: 'A', text: 'O colega está certo: a maior A.H. sempre indica a mudança mais relevante.', whyWrong: 'A A.H. ignora o tamanho da conta. Uma variação percentual alta sobre uma base pequena pode ter pouco impacto na estrutura.' },
      { id: 'B', text: 'O colega está certo, pois o Intangível dobrou e passou a ser a maior conta do Ativo.', whyWrong: 'O Intangível dobrou, mas continua pequeno: 400 de 5.000, ou 8% do Ativo. A maior conta é o Caixa (60%).' },
      { id: 'C', text: 'É preciso combinar A.H. com A.V.: o Intangível dobrou, mas pesa apenas 8% do Ativo e variou R$ 200 mil; o Caixa, com A.H. menor, pesa 60% e variou R$ 600 mil, sendo a mudança mais relevante para a estrutura.' },
      { id: 'D', text: 'A comparação é impossível, pois A.H. e A.V. não podem ser usadas juntas.', whyWrong: 'Ao contrário: A.V. e A.H. são complementares. Uma mostra o peso, a outra a evolução; juntas indicam a relevância da variação.' },
      { id: 'E', text: 'O Caixa é mais relevante porque sua A.H. de 25% é maior que a A.V. de 8% do Intangível.', whyWrong: 'Compara grandezas diferentes (A.H. de uma conta com A.V. de outra). A relevância vem de olhar peso e variação de cada conta.' },
    ],
    correct: 'C',
    explanation:
      'A A.H. mostra o ritmo de variação, mas não o tamanho. Uma conta pequena pode dobrar (A.H. de 100%) sem alterar muito a estrutura. Combinar A.V. (peso) e A.H. (evolução) — e olhar a variação absoluta — mostra que o Caixa, que já representa 60% do Ativo e cresceu R$ 600 mil, é a mudança mais relevante.',
    reasoningSteps: [
      'Calcule a A.V. das duas contas em X2: Caixa 3.000 / 5.000 = 60%; Intangível 400 / 5.000 = 8%.',
      'Compare as variações absolutas: Caixa +600; Intangível +200.',
      'Pondere: alta A.H. em conta pequena tem pouco impacto.',
      'Conclua usando A.V. e A.H. em conjunto.',
    ],
    commonMistake: 'Considerar relevante apenas a conta com maior A.H., ignorando seu peso na estrutura.',
    rule: 'Antes de destacar uma A.H. alta, verifique a A.V. da conta: variação grande em conta pequena raramente muda a estrutura.',
    hint: 'Quanto cada conta pesa no Ativo de X2?',
    concept: 'A relevância de uma variação depende da combinação entre o crescimento (A.H.) e o peso da conta (A.V.).',
    sourceReference: REF_AH,
  },
  {
    id: 'an-014',
    type: 'multi-part',
    topic: 'ah',
    subtopic: 'A.H. de receita e custo',
    skill: 'ah-interpretacao',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX_SERRA,
    stem: 'A diretoria da Serra Azul comemora o crescimento das vendas. Use a A.H. para avaliar o que aconteceu entre X1 e X2.',
    table: DRE_SERRA,
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'A.H. da Receita Líquida (%, 1 casa decimal).',
        correct: 12.5,
        unit: 'percent',
        decimals: 1,
        points: 3,
        calc: { fn: 'analiseHorizontal', args: [9000, 8000] },
        solution: {
          formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
          substitution: '(9.000 − 8.000) / 8.000 × 100',
          computation: '1.000 / 8.000 = 0,125 → 12,5',
          result: '+12,5%',
          unit: '% de variação',
          interpretation: 'A Receita Líquida cresceu 12,5%.',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'A.H. do Custo dos Produtos Vendidos (%, 2 casas decimais).',
        correct: 17.69,
        unit: 'percent',
        decimals: 2,
        points: 3,
        calc: { fn: 'analiseHorizontal', args: [6120, 5200] },
        solution: {
          formula: 'A.H. = (Atual − Anterior) / Anterior × 100',
          substitution: '(6.120 − 5.200) / 5.200 × 100',
          computation: '920 / 5.200 = 0,1769 → 17,69',
          result: '+17,69%',
          unit: '% de variação',
          interpretation: 'O custo dos produtos vendidos cresceu 17,69%, acima da receita.',
        },
      },
      {
        id: 'c',
        kind: 'choice',
        prompt: 'Qual a consequência mais direta dessa combinação?',
        points: 4,
        correct: 'A',
        options: [
          { id: 'A', text: 'Como o custo cresceu mais que a receita, a Margem Bruta caiu (de 35% para 32%): a empresa vendeu mais, mas ficou com uma fatia menor de cada real vendido depois do custo do produto.' },
          { id: 'B', text: 'Como a receita cresceu, o Lucro Bruto necessariamente cresceu na mesma proporção (12,5%).', whyWrong: 'O Lucro Bruto só cresce na mesma proporção se o custo também crescer 12,5%. Ele cresceu apenas 2,86% (2.800 → 2.880).' },
          { id: 'C', text: 'O custo cresceu 17,69% e a receita 12,5%, portanto a margem bruta caiu 5,19%.', whyWrong: 'Subtrair A.H.s não fornece a variação da margem. A margem bruta caiu 3 pontos percentuais (35% → 32%), calculada com LB / RL de cada ano.' },
          { id: 'D', text: 'A alta do custo não importa, pois o crescimento da receita sempre compensa.', whyWrong: 'Quando o custo cresce mais que a receita, cada real vendido deixa menos lucro bruto; crescer vendendo com margem menor pode não compensar.' },
        ],
      },
    ],
    explanation:
      'A A.H. isolada de uma linha conta só parte da história. Comparar o crescimento da receita (12,5%) com o do custo (17,69%) revela pressão sobre a margem: o Lucro Bruto cresceu só 2,86% e a Margem Bruta caiu de 35% para 32%. Crescer vendas não é o mesmo que crescer lucro.',
    reasoningSteps: [
      'Calcule a A.H. da receita e do custo com base em X1.',
      'Compare os ritmos: o custo cresceu mais rápido.',
      'Traduza em margem: LB/RL caiu de 2.800/8.000 = 35% para 2.880/9.000 = 32%.',
      'Evite subtrair A.H.s para obter margens.',
    ],
    commonMistake: 'Comemorar o crescimento da receita sem comparar com o crescimento do custo.',
    rule: 'Compare a A.H. da receita com a A.H. dos custos e despesas: se o custo cresce mais rápido, a margem encolhe.',
    formula: 'A.H. = (Atual − Anterior) / Anterior × 100; MB = LB / RL',
    hint: 'O que cresceu mais rápido: a receita ou o custo?',
    concept: 'A A.H. de linhas da DRE, lida em conjunto, mostra se o crescimento é acompanhado de ganho ou perda de margem.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-015',
    type: 'true-false',
    topic: 'ah',
    subtopic: 'Relevância: combinar A.V. e A.H.',
    skill: 'ah-relevancia-av',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Em uma empresa com Ativo Total de R$ 50 milhões, a conta Adiantamentos a fornecedores passou de R$ 10 mil para R$ 30 mil (A.H. de +200%). Como é a maior A.H. do balanço, essa é necessariamente a variação mais relevante para a análise."',
    correct: false,
    explanation:
      'A A.H. de +200% é alta, mas a conta representa uma fração ínfima do Ativo (R$ 30 mil em R$ 50 milhões, cerca de 0,06%). Uma variação percentual grande em conta pequena tem pouco impacto na estrutura. Por isso a A.H. deve ser lida junto com a A.V.',
    reasoningSteps: [
      'Calcule a A.V. da conta: 30 / 50.000 ≈ 0,06% do Ativo.',
      'Compare a variação absoluta (R$ 20 mil) com o tamanho da empresa.',
      'Conclua que a relevância depende de peso e variação, não só da A.H.',
    ],
    commonMistake: 'Escolher a conta com maior A.H. como a mais importante sem olhar o seu peso.',
    rule: 'A.H. alta em conta pequena raramente é relevante: combine sempre A.V. e A.H.',
    hint: 'Quanto essa conta representa dentro do Ativo?',
    concept: 'A A.H. mede ritmo de variação; a A.V. mede peso. Relevância exige os dois.',
    sourceReference: REF_AH,
  },
  {
    id: 'an-016',
    type: 'short-answer',
    topic: 'ah',
    subtopic: 'A.V. × A.H.',
    skill: 'av-ah-diferenca',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Explique a diferença entre Análise Vertical e Análise Horizontal: qual pergunta cada uma responde, qual é a base de cálculo de cada uma e por que é útil usá-las em conjunto.',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'A.V. mede o peso/participação da conta na estrutura (quanto representa), com base no total do mesmo período (Ativo Total, Passivo + PL ou Receita Líquida).',
          points: 3,
          keywords: [['vertical', 'represent'], ['vertical', 'particip'], ['vertical', 'peso'], ['vertical', 'estrutura']],
        },
        {
          id: 'c2',
          description: 'A.H. mede quanto a conta cresceu ou caiu ao longo do tempo, com base no período anterior.',
          points: 3,
          keywords: [['horizontal', 'cresc'], ['horizontal', 'variac'], ['horizontal', 'evolu'], ['horizontal', 'anterior']],
        },
        {
          id: 'c3',
          description: 'Menciona as bases corretas (Ativo Total / Receita Líquida para A.V.; valor anterior para A.H.).',
          points: 2,
          keywords: [['ativo total', 'anterior'], ['receita liquida', 'anterior'], ['passivo', 'anterior']],
        },
        {
          id: 'c4',
          description: 'Justifica o uso conjunto: uma variação alta em conta pequena pode ser pouco relevante, e uma conta pode crescer e perder peso.',
          points: 2,
          keywords: [['conjunt'], ['combin'], ['juntas'], ['complement']],
        },
      ],
      seriousErrors: [
        { description: 'Inverte os conceitos (A.V. como crescimento no tempo).', patterns: ['vertical mede o crescimento', 'vertical compara periodos', 'horizontal mede a participacao'], penalty: 3 },
        { description: 'Indica o valor atual como base da A.H.', patterns: ['dividido pelo atual', 'base e o valor atual', 'base e o atual'], penalty: 2 },
      ],
      modelAnswer:
        'A Análise Vertical responde "quanto essa conta representa dentro da estrutura?": divide a conta pelo total do mesmo período (Ativo Total, Passivo + PL Total ou Receita Líquida na DRE). A Análise Horizontal responde "quanto essa conta cresceu ou caiu?": (atual − anterior) / anterior × 100, sempre com o período anterior como base e mantendo o sinal. Usadas em conjunto, mostram se uma variação é relevante: uma conta pequena pode ter A.H. enorme sem mudar a estrutura, e uma conta pode crescer em valor e ainda assim perder participação (A.V.) se o total cresceu mais.',
    },
    explanation:
      'A.V. e A.H. são complementares: a primeira é um corte "no mesmo ano" (estrutura), a segunda uma comparação "entre anos" (evolução). A leitura conjunta evita superestimar variações em contas pequenas e esclarece mudanças de participação.',
    reasoningSteps: [
      'Associe cada técnica à sua pergunta-chave.',
      'Lembre as bases: total do mesmo período (A.V.) e período anterior (A.H.).',
      'Dê um exemplo em que só uma delas levaria a conclusão errada.',
    ],
    commonMistake: 'Trocar as perguntas: usar a A.V. para falar de crescimento ou a A.H. para falar de peso.',
    rule: 'A.V. = "quanto representa?" (mesmo período); A.H. = "quanto cresceu ou caiu?" (base anterior).',
    hint: 'Uma olha a estrutura de um ano; a outra compara anos.',
    concept: 'A.V. analisa a composição de uma demonstração; A.H. analisa sua evolução no tempo.',
    sourceReference: REF_AH,
  },

  // =========================================================================
  // MARGENS (10)
  // =========================================================================
  {
    id: 'an-017',
    type: 'numeric',
    topic: 'margens',
    subtopic: 'Margem Líquida',
    skill: 'margem-liquida-calculo',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX_HOR,
    stem: 'Calcule a Margem Líquida da Horizonte Digital em X2. Responda em %, com 1 casa decimal.',
    table: DRE_HOR,
    correct: 17.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'margem', args: [1190, 7000] },
    solution: {
      formula: 'ML = Lucro Líquido / Receita Líquida × 100',
      substitution: 'ML X2 = 1.190 / 7.000 × 100',
      computation: '1.190 / 7.000 = 0,17 → × 100 = 17,0',
      result: '17,0%',
      unit: '% da Receita Líquida',
      interpretation: 'A cada R$ 100 de Receita Líquida, R$ 17 viraram Lucro Líquido em X2 (contra R$ 15 em X1).',
    },
    explanation:
      'A Margem Líquida responde "quanto sobra ao final?": de toda a Receita Líquida, quanto restou depois de custos, despesas operacionais, resultado financeiro e impostos sobre o lucro. Na Horizonte, 17% da receita virou lucro líquido.',
    reasoningSteps: [
      'Localize o Lucro Líquido de X2 (1.190) — a última linha da DRE.',
      'Use a Receita Líquida de X2 (7.000) como denominador.',
      'Divida e multiplique por 100.',
      'Interprete: "a cada R$ 100 de RL, R$ X viram Lucro Líquido".',
    ],
    commonMistake: 'Dividir pela Receita Bruta (8.050), obtendo 14,8%.',
    rule: 'Toda margem é um lucro dividido pela Receita Líquida do mesmo período.',
    formula: 'ML = LL / RL × 100',
    hint: 'Qual é a última linha da DRE?',
    concept: 'Margem Líquida mostra quanto de cada real de Receita Líquida se transforma em Lucro Líquido.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-018',
    type: 'multi-part',
    topic: 'margens',
    subtopic: 'Margem Líquida — cálculo e interpretação',
    skill: 'margem-liquida-interpretacao',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'interpretation',
    stem: 'Uma empresa apresentou Receita Líquida = 1.000 e Lucro Líquido = 120 (em R$ mil).',
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'a) Calcule a Margem Líquida (%, 1 casa decimal).',
        correct: 12.0,
        unit: 'percent',
        decimals: 1,
        points: 5,
        calc: { fn: 'margem', args: [120, 1000] },
        solution: {
          formula: 'ML = Lucro Líquido / Receita Líquida × 100',
          substitution: 'ML = 120 / 1.000 × 100',
          computation: '120 / 1.000 = 0,12 → × 100 = 12,0',
          result: '12,0%',
          unit: '% da Receita Líquida',
          interpretation: 'A cada R$ 100 de Receita Líquida, R$ 12 viram Lucro Líquido.',
        },
      },
      {
        id: 'b',
        kind: 'text',
        prompt: 'b) Interprete o resultado em uma frase.',
        points: 5,
        rubric: {
          criteria: [
            {
              id: 'b1',
              description: 'Usa a leitura "a cada R$ 100 de Receita Líquida, R$ 12 viram Lucro Líquido" (ou equivalente por real).',
              points: 3,
              keywords: [['100', '12'], ['cada real', '0,12'], ['cada r$ 1', '0,12'], ['cada r$1', '0,12']],
            },
            {
              id: 'b2',
              description: 'Deixa claro que a base é a receita (líquida) e o resultado é o lucro líquido que sobra ao final.',
              points: 2,
              keywords: [['receita', 'lucro'], ['vend', 'lucro'], ['receita', 'sobra']],
            },
          ],
          seriousErrors: [
            { description: 'Lê a margem como 0,12% (erro de escala).', patterns: ['0,12%', '0.12%'], penalty: 2 },
            { description: 'Relaciona a margem ao Ativo ou ao PL.', patterns: ['de ativo', 'do ativo', 'do patrimonio'], penalty: 2 },
          ],
          modelAnswer: 'A Margem Líquida de 12% significa que, a cada R$ 100 de Receita Líquida, R$ 12 sobram ao final como Lucro Líquido, depois de custos, despesas, resultado financeiro e impostos.',
        },
      },
    ],
    explanation:
      'Margem Líquida = 120 / 1.000 = 12%. A leitura padrão da disciplina é: "a cada R$ 100 de Receita Líquida, R$ 12 viram Lucro Líquido". Essa frase deixa explícitos o numerador (lucro) e a base (receita).',
    reasoningSteps: [
      'Divida o lucro líquido pela receita líquida.',
      'Converta para %: × 100.',
      'Traduza para "a cada R$ 100 de RL, R$ X de LL".',
    ],
    commonMistake: 'Escrever 0,12% (escala) ou 88% (complemento, que é o quanto foi consumido por custos e despesas).',
    rule: 'Interprete qualquer margem como "a cada R$ 100 de Receita Líquida, R$ X viram aquele lucro".',
    formula: 'ML = LL / RL × 100',
    hint: 'Comece pela fração 120 / 1.000.',
    concept: 'A margem mede a eficiência em transformar receita em lucro.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-019',
    type: 'multiple-choice',
    topic: 'margens',
    subtopic: 'Margem Bruta',
    skill: 'margem-bruta-calculo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_SERRA,
    stem: 'Qual é a Margem Bruta da Metalúrgica Serra Azul em X2?',
    tables: [DRE_SERRA, BP_SERRA],
    balanceCheck: BAL_SERRA,
    options: [
      { id: 'A', text: '26,7%', whyWrong: 'Usou a Receita Bruta (10.800) como denominador. As margens são calculadas sobre a Receita Líquida (9.000).' },
      { id: 'B', text: '22,2%', whyWrong: 'Dividiu o Lucro Bruto pelo Ativo Total (13.000). Margem compara lucro com receita, não com o Ativo.' },
      { id: 'C', text: '68,0%', whyWrong: 'Esse é o complemento: 6.120 / 9.000 = 68% é o peso do custo na receita, não o que sobra depois dele.' },
      { id: 'D', text: '32,0%' },
      { id: 'E', text: '0,32%', whyWrong: 'Erro de escala: 2.880 / 9.000 = 0,32, que corresponde a 32%, e não a 0,32%.' },
    ],
    correct: 'D',
    calc: { fn: 'margem', args: [2880, 9000] },
    solution: {
      formula: 'MB = Lucro Bruto / Receita Líquida × 100',
      substitution: 'MB X2 = 2.880 / 9.000 × 100',
      computation: '2.880 / 9.000 = 0,32 → × 100 = 32,0',
      result: '32,0%',
      unit: '% da Receita Líquida',
      interpretation: 'Depois do custo diretamente ligado ao produto, sobram R$ 32 de cada R$ 100 de Receita Líquida (em X1 sobravam R$ 35).',
    },
    explanation:
      'A Margem Bruta responde "depois do custo diretamente ligado ao produto, quanto sobra?". Na Serra Azul, de cada R$ 100 de Receita Líquida, R$ 68 vão para o custo dos produtos e R$ 32 sobram para cobrir despesas operacionais, juros, impostos e gerar lucro.',
    reasoningSteps: [
      'Localize o Lucro Bruto de X2 (2.880).',
      'Use a Receita Líquida de X2 (9.000) — não a bruta, nem o Ativo.',
      'Calcule 2.880 / 9.000 × 100 = 32%.',
      'Confira a escala e se você não calculou o complemento.',
    ],
    commonMistake: 'Usar Receita Bruta, dividir pelo Ativo ou responder o complemento (68%).',
    rule: 'Margem = lucro da linha desejada / Receita Líquida; ela nunca usa o Ativo nem a Receita Bruta.',
    formula: 'MB = LB / RL × 100',
    hint: 'O denominador é sempre a mesma linha da DRE para todas as margens.',
    concept: 'Margem Bruta mede quanto da Receita Líquida sobra depois do custo das vendas.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-020',
    type: 'multiple-choice',
    topic: 'margens',
    subtopic: 'Escala e leitura de margens',
    skill: 'margem-escala',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Uma planilha calculou Lucro Líquido / Receita Líquida e apresentou o resultado 0,18 (sem formatação percentual). Qual é a leitura correta?',
    options: [
      { id: 'A', text: 'A Margem Líquida é de 0,18%: a cada R$ 100 de Receita Líquida, sobram R$ 0,18 de lucro.', whyWrong: 'Erro de escala: 0,18 é uma fração. Multiplicada por 100, corresponde a 18%, e não a 0,18%.' },
      { id: 'B', text: 'A Margem Líquida é de 82%, pois 0,18 representa o que foi consumido por custos e despesas.', whyWrong: 'Confunde a margem com o seu complemento. O quociente LL/RL é o que sobra; 82% seria o que foi consumido.' },
      { id: 'C', text: 'A cada R$ 100 de Ativo, a empresa gera R$ 18 de lucro.', whyWrong: 'A margem usa a Receita Líquida como base, e não o Ativo. Lucro sobre Ativo não é a margem líquida.' },
      { id: 'D', text: 'A cada R$ 18 de Receita Líquida, a empresa gera R$ 100 de Lucro Líquido.', whyWrong: 'Inverteu numerador e denominador: o lucro é uma parte da receita, e não o contrário.' },
      { id: 'E', text: 'A Margem Líquida é de 18%: a cada R$ 100 de Receita Líquida, R$ 18 viram Lucro Líquido.' },
    ],
    correct: 'E',
    explanation:
      'O quociente 0,18 é uma fração; em percentual, 0,18 × 100 = 18%. A leitura padrão é "a cada R$ 100 de Receita Líquida, R$ 18 viram Lucro Líquido". Cuidado com a escala (0,18 ≠ 0,18%), com o complemento (82%) e com a base (receita, não Ativo).',
    reasoningSteps: [
      'Reconheça que 0,18 é fração: multiplique por 100 para obter %.',
      'Identifique numerador (lucro líquido) e denominador (receita líquida).',
      'Monte a frase "a cada R$ 100 de RL, R$ 18 de LL".',
      'Descarte leituras com base errada ou invertida.',
    ],
    commonMistake: 'Ler 0,18 como 0,18% — um erro de 100 vezes.',
    rule: 'Quociente 0,XX corresponde a XX%; confira sempre a escala antes de interpretar.',
    formula: 'ML = LL / RL × 100',
    hint: 'Quanto é 0,18 × 100?',
    concept: 'Margens expressas como fração (0,18) e como percentual (18%) são a mesma informação.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-021',
    type: 'numeric',
    topic: 'margens',
    subtopic: 'Margem Operacional',
    skill: 'margem-operacional-calculo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_SERRA,
    stem: 'Calcule a Margem Operacional da Metalúrgica Serra Azul em X2. Responda em %, com 1 casa decimal.',
    table: DRE_SERRA,
    correct: 14.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'margem', args: [1260, 9000] },
    solution: {
      formula: 'MO = Lucro Operacional / Receita Líquida × 100',
      substitution: 'MO X2 = 1.260 / 9.000 × 100',
      computation: '1.260 / 9.000 = 0,14 → × 100 = 14,0',
      result: '14,0%',
      unit: '% da Receita Líquida',
      interpretation: 'Depois do custo do produto e das despesas operacionais, sobram R$ 14 de cada R$ 100 de Receita Líquida: a operação "para em pé", mas com folga menor que em X1 (15%).',
    },
    explanation:
      'A Margem Operacional responde "a operação completa para em pé depois das despesas operacionais?". O Lucro Operacional é o Lucro Bruto menos as Despesas Operacionais, antes do resultado financeiro e dos impostos sobre o lucro.',
    reasoningSteps: [
      'Localize o Lucro Operacional de X2 (1.260 = 2.880 − 1.620).',
      'Divida pela Receita Líquida de X2 (9.000).',
      'Multiplique por 100.',
      'Compare com X1 (1.200 / 8.000 = 15%) para ler a tendência.',
    ],
    commonMistake: 'Usar o LAIR (900), que já inclui o resultado financeiro, obtendo 10%.',
    rule: 'Lucro Operacional = Lucro Bruto − Despesas Operacionais; o resultado financeiro fica abaixo dele.',
    formula: 'MO = LO / RL × 100',
    hint: 'O resultado financeiro faz parte da operação?',
    concept: 'A Margem Operacional mostra se a atividade principal, já com despesas administrativas e comerciais, gera lucro.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-022',
    type: 'multi-part',
    topic: 'margens',
    subtopic: 'Cascata de margens',
    skill: 'margens-cascata',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX_JAC,
    stem: 'A Rede Jacarandá cresceu a receita em 20% de X1 para X2, mas o Lucro Líquido caiu. Use as margens para localizar onde o resultado se perdeu.',
    table: DRE_JAC,
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'Margem Bruta em X1 (%, 1 casa decimal).',
        correct: 22.0,
        unit: 'percent',
        decimals: 1,
        points: 2,
        calc: { fn: 'margem', args: [2200, 10000] },
        solution: {
          formula: 'MB = LB / RL × 100',
          substitution: '2.200 / 10.000 × 100',
          computation: '0,22 × 100 = 22,0',
          result: '22,0%',
          unit: '% da RL',
          interpretation: 'Em X1, sobravam R$ 22 de cada R$ 100 de RL depois do CMV.',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'Margem Bruta em X2 (%, 1 casa decimal).',
        correct: 21.0,
        unit: 'percent',
        decimals: 1,
        points: 2,
        calc: { fn: 'margem', args: [2520, 12000] },
        solution: {
          formula: 'MB = LB / RL × 100',
          substitution: '2.520 / 12.000 × 100',
          computation: '0,21 × 100 = 21,0',
          result: '21,0%',
          unit: '% da RL',
          interpretation: 'Em X2, sobram R$ 21 de cada R$ 100 de RL depois do CMV: queda de 1 p.p.',
        },
      },
      {
        id: 'c',
        kind: 'numeric',
        prompt: 'Margem Líquida em X2 (%, 2 casas decimais).',
        correct: 2.25,
        unit: 'percent',
        decimals: 2,
        points: 3,
        calc: { fn: 'margem', args: [270, 12000] },
        solution: {
          formula: 'ML = LL / RL × 100',
          substitution: '270 / 12.000 × 100',
          computation: '0,0225 × 100 = 2,25',
          result: '2,25%',
          unit: '% da RL',
          interpretation: 'A cada R$ 100 de RL, R$ 2,25 viraram Lucro Líquido em X2 (contra R$ 3,00 em X1).',
        },
      },
      {
        id: 'd',
        kind: 'choice',
        prompt: 'Sabendo que a Margem Operacional foi de 5% (X1) para 4% (X2), qual diagnóstico é o mais adequado?',
        points: 3,
        correct: 'C',
        options: [
          { id: 'A', text: 'A queda veio só do resultado financeiro, pois as margens bruta e operacional ficaram estáveis.', whyWrong: 'As margens bruta (22% → 21%) e operacional (5% → 4%) caíram; o problema começa antes do resultado financeiro.' },
          { id: 'B', text: 'Como a Margem Líquida é baixa (2,25%), a empresa é inviável.', whyWrong: 'Margem baixa é típica de varejo de alto giro; a viabilidade depende do volume, do giro e da comparação com pares, não da margem isolada.' },
          { id: 'C', text: 'A empresa perdeu 1 p.p. já na Margem Bruta (custo das mercadorias subiu mais que a receita) e manteve essa perda na operacional; com o resultado financeiro um pouco pior, a ML caiu de 3% para 2,25%.' },
          { id: 'D', text: 'O crescimento de 20% da receita garante que a margem líquida também subiu 20%.', whyWrong: 'Crescimento de receita não implica crescimento de margem; aqui o lucro caiu 10% enquanto a receita subiu 20%.' },
        ],
      },
    ],
    explanation:
      'A leitura em cascata (MB → MO → ML) mostra em que degrau da DRE o resultado se perdeu. Na Jacarandá, o CMV cresceu mais que a receita (MB caiu 1 p.p.), as despesas operacionais mantiveram o mesmo peso (17% da RL nos dois anos), e o resultado financeiro piorou um pouco. O crescimento de 20% das vendas não se converteu em lucro.',
    reasoningSteps: [
      'Calcule MB, MO e ML nos dois anos sobre a Receita Líquida.',
      'Compare cada margem em pontos percentuais.',
      'Localize o primeiro degrau onde a margem cai.',
      'Explique a causa (custo, despesa, financeiro, impostos).',
    ],
    commonMistake: 'Olhar só a última linha e atribuir toda a queda ao resultado financeiro ou aos impostos.',
    rule: 'Para descobrir onde o lucro se perdeu, desça a DRE margem a margem (MB → MO → ML) e veja em que degrau a queda começa.',
    formula: 'MB = LB / RL; MO = LO / RL; ML = LL / RL',
    hint: 'A Margem Bruta mudou de X1 para X2?',
    concept: 'Margens em cascata decompõem a DRE: cada degrau mostra o que sobra após um grupo de custos ou despesas.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-023',
    type: 'true-false',
    topic: 'margens',
    subtopic: 'Margem Bruta — conceito',
    skill: 'margem-bruta-conceito',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "A Margem Bruta responde quanto sobra depois do custo diretamente ligado ao produto; por isso, despesas administrativas e comerciais não afetam a Margem Bruta, mas afetam a Margem Operacional."',
    correct: true,
    explanation:
      'O Lucro Bruto é a Receita Líquida menos o custo das vendas — gastos que "grudam" diretamente no produto ou serviço. Despesas administrativas e comerciais são despesas operacionais e entram depois, reduzindo o Lucro Operacional e, portanto, a Margem Operacional.',
    reasoningSteps: [
      'Lembre a estrutura: RL − Custo = LB; LB − Despesas Operacionais = LO.',
      'Classifique o gasto: ele gruda diretamente no produto? Se não, é despesa.',
      'Despesas administrativas e comerciais entram abaixo do Lucro Bruto.',
    ],
    commonMistake: 'Achar que qualquer gasto da empresa reduz a Margem Bruta.',
    rule: 'Custo (gruda no produto) afeta a Margem Bruta; despesa operacional só afeta a partir da Margem Operacional.',
    hint: 'Em que linha da DRE ficam as despesas administrativas?',
    concept: 'Cada margem corresponde a um degrau da DRE e só é afetada pelos itens acima desse degrau.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-024',
    type: 'multiple-choice',
    topic: 'margens',
    subtopic: 'Comparação de margens entre setores',
    skill: 'margem-comparacao-setor',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: 'CASO FICTÍCIO PARA ESTUDO — Rede Jacarandá Supermercados (varejo) × Horizonte Digital Consultoria (serviços).',
    stem: 'Em X2, a Rede Jacarandá teve Margem Líquida de 2,25% e Receita Líquida de R$ 12.000 mil; a Horizonte Digital teve Margem Líquida de 17% e Receita Líquida de R$ 7.000 mil. Qual conclusão é a mais adequada?',
    options: [
      { id: 'A', text: 'A Jacarandá é uma empresa pior, pois sua margem é quase oito vezes menor.', whyWrong: 'Margem não deve ser julgada isoladamente nem entre setores muito diferentes; varejo opera com margem baixa e compensa com volume e giro.' },
      { id: 'B', text: 'A Horizonte vende mais, já que tem a maior margem.', whyWrong: 'Margem não mede volume de vendas: a Jacarandá tem receita maior (12.000 contra 7.000).' },
      { id: 'C', text: 'As margens não podem ser comparadas porque estão em anos diferentes.', whyWrong: 'Os dados são do mesmo ano (X2). O problema não é o período, e sim a natureza diferente dos negócios.' },
      { id: 'D', text: 'A diferença reflete, em boa parte, a natureza dos negócios: varejo costuma trabalhar com margem baixa e alto giro; a avaliação de cada margem deve ser feita contra pares do setor e o histórico da própria empresa.' },
      { id: 'E', text: 'A Jacarandá deveria aumentar os preços até atingir 17% de margem, igualando-se à Horizonte.', whyWrong: 'Tomar como meta a margem de outro setor ignora concorrência e modelo de negócio; um supermercado que eleva preços pode perder volume.' },
    ],
    correct: 'D',
    explanation:
      'Margens refletem o modelo de negócio. Supermercados revendem com pouco acréscimo e ganham no volume (giro alto); consultorias vendem conhecimento com custo direto proporcionalmente menor. O julgamento correto compara a margem com empresas do mesmo setor e com o período anterior — por exemplo, a queda da Jacarandá de 3% para 2,25% merece atenção, independentemente da margem da Horizonte.',
    reasoningSteps: [
      'Identifique os setores das empresas comparadas.',
      'Lembre que margem baixa pode ser compensada por giro alto.',
      'Busque a referência certa: pares do setor e histórico.',
      'Evite julgamentos absolutos ("pior", "melhor").',
    ],
    commonMistake: 'Concluir que margem menor significa empresa pior, sem considerar o setor.',
    rule: 'Julgue uma margem comparando-a com pares do setor e com o histórico da empresa, nunca com setores de modelo diferente.',
    hint: 'Um supermercado e uma consultoria ganham dinheiro do mesmo jeito?',
    concept: 'Margens variam muito entre setores; a comparação útil é com empresas semelhantes e ao longo do tempo.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-025',
    type: 'essay',
    topic: 'margens',
    subtopic: 'Cascata de margens — discursiva',
    skill: 'margens-cascata',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: CTX_SERRA,
    stem: 'A Serra Azul aumentou a Receita Líquida em 12,5% de X1 para X2, mas o Lucro Líquido caiu de 640 para 630. Calcule (ou use) as margens bruta, operacional e líquida dos dois anos e explique, de forma fundamentada, em que pontos da DRE a rentabilidade das vendas se deteriorou e o que a diretoria deveria investigar.',
    table: DRE_SERRA,
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Apresenta as margens corretas: MB 35% → 32%; MO 15% → 14%; ML 8% → 7%.',
          points: 3,
          keywords: [['35', '32'], ['15', '14', '8', '7']],
        },
        {
          id: 'c2',
          description: 'Identifica a principal perda na Margem Bruta: o custo dos produtos cresceu mais que a receita.',
          points: 3,
          keywords: [['bruta', 'custo'], ['cpv', 'cresc'], ['custo', 'mais que a receita'], ['custo', 'cresceu mais']],
        },
        {
          id: 'c3',
          description: 'Reconhece que as despesas operacionais ganharam eficiência (de 20% para 18% da RL) e amorteceram a queda, e/ou que o resultado financeiro piorou (−300 → −360).',
          points: 2,
          keywords: [['despesas operacionais', 'dilu'], ['despesas operacionais', 'menor peso'], ['despesa', '18'], ['financeiro', 'pior'], ['juros', 'aument']],
        },
        {
          id: 'c4',
          description: 'Sugere investigação pertinente: preço de matéria-prima, política de preços/descontos, mix de produtos, eficiência fabril, endividamento — sem julgamento absoluto.',
          points: 2,
          keywords: [['materia-prima'], ['materia prima'], ['preco'], ['mix'], ['eficiencia'], ['endivid']],
        },
      ],
      seriousErrors: [
        { description: 'Calcula margens sobre o Ativo ou a Receita Bruta.', patterns: ['sobre o ativo', 'receita bruta como base', 'dividido pelo ativo'], penalty: 2 },
        { description: 'Afirma que receita maior garante lucro maior.', patterns: ['receita maior garante', 'sempre aumenta o lucro'], penalty: 2 },
      ],
      modelAnswer:
        'Margens: MB = 2.800/8.000 = 35% em X1 e 2.880/9.000 = 32% em X2; MO = 1.200/8.000 = 15% e 1.260/9.000 = 14%; ML = 640/8.000 = 8% e 630/9.000 = 7%. A principal deterioração está na Margem Bruta: o custo dos produtos cresceu 17,7%, acima da receita (12,5%), e a fatia que sobra depois do custo diretamente ligado ao produto caiu 3 p.p. As despesas operacionais, ao contrário, ficaram quase estáveis em valor e caíram de 20% para 18% da RL, o que amorteceu a queda (MO caiu só 1 p.p.). Abaixo da operação, o resultado financeiro piorou (de −300 para −360), refletindo mais juros, e o IR/CS levou o LL a 630. A diretoria deveria investigar o preço de matéria-prima, descontos concedidos, mix de produtos e eficiência fabril, além do custo do endividamento, comparando com o histórico e com concorrentes.',
    },
    explanation:
      'Ler as margens em cascata mostra onde a rentabilidade das vendas foi perdida: aqui, principalmente no custo do produto (MB −3 p.p.), parcialmente compensado por despesas operacionais mais diluídas. Vender mais com margem menor pode manter o lucro estável ou até reduzi-lo.',
    reasoningSteps: [
      'Calcule MB, MO e ML dos dois anos sobre a Receita Líquida.',
      'Compare em pontos percentuais e localize a maior queda.',
      'Use A.H. de custo e despesas para explicar a causa.',
      'Proponha o que investigar, sem julgamentos absolutos.',
    ],
    commonMistake: 'Concluir que "o problema foi o imposto" ou "o financeiro" sem olhar a Margem Bruta.',
    rule: 'Margem caiu? Desça a DRE degrau a degrau e encontre onde começa a perda antes de propor ações.',
    formula: 'MB = LB / RL; MO = LO / RL; ML = LL / RL',
    hint: 'Compare a A.H. da receita com a A.H. do custo dos produtos.',
    concept: 'Margens em sequência permitem localizar a origem de uma queda de lucratividade.',
    sourceReference: REF_MG,
  },
  {
    id: 'an-026',
    type: 'true-false',
    topic: 'margens',
    subtopic: 'Pontos percentuais × variação percentual',
    skill: 'margem-pp-vs-percent',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Se a Margem Líquida de uma empresa passou de 15% para 17%, é correto dizer que ela cresceu 2%."',
    correct: false,
    explanation:
      'A diferença entre dois percentuais é medida em pontos percentuais: a margem aumentou 2 p.p. Em termos relativos (A.H. da margem), o aumento foi de (17 − 15) / 15 ≈ 13,3%. Dizer "cresceu 2%" mistura as duas medidas.',
    reasoningSteps: [
      'Note que os dois valores já são percentuais.',
      'Diferença simples entre percentuais = pontos percentuais (17 − 15 = 2 p.p.).',
      'Variação relativa = (17 − 15) / 15 = 13,3%.',
      'Escolha a expressão que corresponde ao que se quer comunicar.',
    ],
    commonMistake: 'Chamar a diferença entre dois percentuais de "variação de X%".',
    rule: 'Diferença entre dois percentuais se expressa em pontos percentuais (p.p.); "%" fica para variação relativa.',
    hint: 'Qual a diferença entre "p.p." e "%"?',
    concept: 'Pontos percentuais medem diferença absoluta entre taxas; a variação percentual mede a mudança relativa.',
    sourceReference: REF_MG,
  },

  // =========================================================================
  // LIQUIDEZ CORRENTE (9)
  // =========================================================================
  {
    id: 'an-027',
    type: 'numeric',
    topic: 'liquidez',
    subtopic: 'Cálculo da LC',
    skill: 'lc-calculo',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX_SERRA,
    stem: 'Calcule a Liquidez Corrente da Metalúrgica Serra Azul em X2. Arredonde para 2 casas decimais.',
    table: BP_SERRA,
    balanceCheck: BAL_SERRA,
    correct: 1.27,
    unit: 'ratio',
    decimals: 2,
    calc: { fn: 'liquidezCorrente', args: [3800, 3000] },
    solution: {
      formula: 'LC = Ativo Circulante / Passivo Circulante',
      substitution: 'LC X2 = 3.800 / 3.000',
      computation: '3.800 / 3.000 = 1,2667',
      result: '1,27',
      unit: 'vezes (R$ de AC por R$ 1 de PC)',
      interpretation: 'Existem aproximadamente R$ 1,27 de Ativos Circulantes para cada R$ 1 de obrigação de curto prazo — folga, pela regra didática, mas menor que em X1 (1,40).',
    },
    explanation:
      'A Liquidez Corrente compara os recursos que viram caixa em até 12 meses (AC) com as obrigações que vencem em até 12 meses (PC). Na Serra Azul, o índice caiu de 1,40 para 1,27, porque o PC (empréstimos de curto prazo) cresceu mais que o AC e o caixa diminuiu.',
    reasoningSteps: [
      'Localize o Ativo Circulante (3.800) e o Passivo Circulante (3.000) de X2.',
      'Divida AC por PC.',
      'Aplique a regra didática: > 1 folga; = 1 limite; < 1 atenção.',
      'Complemente olhando a composição do AC e do PC.',
    ],
    commonMistake: 'Dividir pelo Passivo Total (PC + PNC = 6.700), obtendo 0,57.',
    rule: 'Liquidez Corrente usa só o circulante dos dois lados: AC / PC.',
    formula: 'LC = AC / PC',
    hint: 'Quais grupos do balanço vencem ou se realizam em até 12 meses?',
    concept: 'A LC mede quantos reais de recursos de curto prazo a empresa tem para cada real de obrigação de curto prazo.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-028',
    type: 'multiple-choice',
    topic: 'liquidez',
    subtopic: 'Cálculo da LC',
    skill: 'lc-calculo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    context: CTX_JAC,
    stem: 'Qual é a Liquidez Corrente da Rede Jacarandá em X2? Arredonde para 2 casas decimais.',
    table: BP_JAC,
    balanceCheck: BAL_JAC,
    options: [
      { id: 'A', text: '0,94' },
      { id: 'B', text: '0,77', whyWrong: 'Dividiu o AC pelo Passivo Total (3.400 / 4.400). A LC compara apenas obrigações de curto prazo (PC).' },
      { id: 'C', text: '1,06', whyWrong: 'Inverteu a fórmula (PC / AC = 3.600 / 3.400). A LC é AC dividido por PC.' },
      { id: 'D', text: '1,36', whyWrong: 'Dividiu Ativo Total por Passivo Total (6.000 / 4.400); isso mistura longo prazo e não é a LC.' },
      { id: 'E', text: '0,57', whyWrong: 'Dividiu o AC pelo Ativo Total (3.400 / 6.000) — isso é uma A.V., não um índice de liquidez.' },
    ],
    correct: 'A',
    calc: { fn: 'liquidezCorrente', args: [3400, 3600] },
    solution: {
      formula: 'LC = Ativo Circulante / Passivo Circulante',
      substitution: 'LC X2 = 3.400 / 3.600',
      computation: '3.400 / 3.600 = 0,9444',
      result: '0,94',
      unit: 'vezes',
      interpretation: 'Existem aproximadamente R$ 0,94 de Ativos Circulantes para cada R$ 1 de obrigação de curto prazo — sinal de atenção pela regra didática, que precisa ser lido junto com a natureza do varejo (giro alto de estoques, fornecedores como fonte de financiamento).',
    },
    explanation:
      'A LC = AC / PC = 3.400 / 3.600 = 0,94. Pela regra didática, abaixo de 1 indica atenção. Mas, no varejo, é comum o PC ser alto por causa dos fornecedores (que financiam os estoques) e os estoques girarem rápido; por isso o índice deve ser lido junto com a composição do AC e do PC.',
    reasoningSteps: [
      'Localize AC (3.400) e PC (3.600) de X2.',
      'Calcule AC / PC = 0,94.',
      'Descarte bases erradas (Passivo Total, Ativo Total) e a fórmula invertida.',
      'Interprete à luz do negócio.',
    ],
    commonMistake: 'Usar o Passivo Total no denominador.',
    rule: 'Na LC, numerador e denominador são ambos de curto prazo: AC no numerador, PC no denominador.',
    formula: 'LC = AC / PC',
    hint: 'Qual é o total do Passivo Circulante em X2?',
    concept: 'A LC compara o que vira dinheiro em até 12 meses com o que precisa ser pago em até 12 meses.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-029',
    type: 'true-false',
    topic: 'liquidez',
    subtopic: 'LC não isolada',
    skill: 'lc-nao-isolada',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Uma empresa com Liquidez Corrente menor que 1 está insolvente, ou seja, caminha necessariamente para a falência."',
    correct: false,
    explanation:
      'LC < 1 é um sinal de atenção, não uma sentença de falência. A capacidade de pagamento depende também do caixa, do prazo dos recebíveis, da velocidade de giro dos estoques, da natureza do negócio e da composição do PC. Varejistas com giro alto, por exemplo, podem operar com LC abaixo de 1 de forma sustentável.',
    reasoningSteps: [
      'Lembre a regra didática: < 1 = atenção, não falência.',
      'Pergunte o que compõe o AC (caixa? estoques?) e o PC (fornecedores? empréstimos?).',
      'Considere a natureza do negócio e a velocidade de giro.',
    ],
    commonMistake: 'Tratar LC < 1 como prova de insolvência.',
    rule: 'Nunca conclua sobre solvência só pela LC: olhe caixa, recebíveis, estoques, natureza do negócio, giro e composição do PC.',
    hint: 'A regra didática fala em "atenção" ou em "falência"?',
    concept: 'A LC é um termômetro de folga de curto prazo; sua leitura depende do contexto do negócio.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-030',
    type: 'true-false',
    topic: 'liquidez',
    subtopic: 'Fórmula da LC',
    skill: 'lc-calculo',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "No cálculo da Liquidez Corrente, usa-se o Passivo Circulante, e não o Passivo Total, porque o índice compara recursos que se realizam em até 12 meses com obrigações que vencem em até 12 meses."',
    correct: true,
    explanation:
      'A LC confronta grandezas de mesmo horizonte: o Ativo Circulante (realizável em até 12 meses) e o Passivo Circulante (exigível em até 12 meses). Incluir o Passivo Não Circulante misturaria dívidas de longo prazo e reduziria artificialmente o índice.',
    reasoningSteps: [
      'Recorde as definições de circulante: até 12 meses.',
      'Verifique que numerador e denominador têm o mesmo horizonte.',
      'Conclua que o Passivo Total não serve para LC.',
    ],
    commonMistake: 'Usar o Passivo Total por achar que "todas as dívidas importam".',
    rule: 'Um índice de liquidez de curto prazo compara apenas grandezas de curto prazo.',
    hint: 'Qual é o horizonte de tempo do Ativo Circulante?',
    concept: 'Liquidez = velocidade de conversão em caixa; exigibilidade = prazo de pagamento. A LC cruza os dois no curto prazo.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-031',
    type: 'multi-part',
    topic: 'liquidez',
    subtopic: 'LC — cálculo, evolução e leitura',
    skill: 'lc-interpretacao',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    context: CTX_HOR,
    stem: 'Analise a Liquidez Corrente da Horizonte Digital.',
    table: BP_HOR,
    balanceCheck: BAL_HOR,
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'LC em X1 (2 casas decimais).',
        correct: 2.83,
        unit: 'ratio',
        decimals: 2,
        points: 2,
        calc: { fn: 'liquidezCorrente', args: [3400, 1200] },
        solution: {
          formula: 'LC = AC / PC',
          substitution: '3.400 / 1.200',
          computation: '3.400 / 1.200 = 2,8333',
          result: '2,83',
          unit: 'vezes',
          interpretation: 'Em X1, havia cerca de R$ 2,83 de AC para cada R$ 1 de PC.',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'LC em X2 (2 casas decimais).',
        correct: 2.73,
        unit: 'ratio',
        decimals: 2,
        points: 2,
        calc: { fn: 'liquidezCorrente', args: [4100, 1500] },
        solution: {
          formula: 'LC = AC / PC',
          substitution: '4.100 / 1.500',
          computation: '4.100 / 1.500 = 2,7333',
          result: '2,73',
          unit: 'vezes',
          interpretation: 'Em X2, há cerca de R$ 2,73 de AC para cada R$ 1 de PC.',
        },
      },
      {
        id: 'c',
        kind: 'choice',
        prompt: 'Qual é a leitura mais adequada do índice de X2?',
        points: 3,
        correct: 'D',
        options: [
          { id: 'A', text: 'A empresa tem R$ 2,73 de caixa para cada R$ 1 de dívida total.', whyWrong: 'A LC usa todo o Ativo Circulante (não só o caixa) e apenas o Passivo Circulante (não a dívida total).' },
          { id: 'B', text: 'A liquidez piorou de forma preocupante, pois o índice caiu.', whyWrong: 'A queda (2,83 → 2,73) é pequena e o índice segue muito acima de 1, com AC composto majoritariamente por caixa.' },
          { id: 'C', text: 'O índice indica 273% de chance de pagar as dívidas.', whyWrong: 'A LC não é uma probabilidade; é uma relação entre AC e PC (R$ de AC por R$ 1 de PC).' },
          { id: 'D', text: 'Existem aproximadamente R$ 2,73 de Ativos Circulantes para cada R$ 1 de obrigação de curto prazo, com AC formado principalmente por caixa — folga ampla.' },
        ],
      },
      {
        id: 'd',
        kind: 'text',
        prompt: 'Uma LC tão alta é sempre positiva? Comente em 2 ou 3 frases.',
        points: 3,
        rubric: {
          criteria: [
            {
              id: 'd1',
              description: 'Reconhece que LC alta indica folga para pagar o curto prazo.',
              points: 1,
              keywords: [['folga'], ['seguranc'], ['capacidade de pag'], ['pagar', 'curto prazo']],
            },
            {
              id: 'd2',
              description: 'Aponta que excesso de caixa/recursos parados pode significar dinheiro pouco aproveitado (oportunidade de investir, distribuir ou crescer), dependendo da estratégia.',
              points: 2,
              keywords: [['parad'], ['ocios'], ['oportunidade'], ['investir'], ['rentab'], ['distribu']],
            },
          ],
          seriousErrors: [{ description: 'Afirma que LC alta é sempre ótima.', patterns: ['sempre otim', 'sempre bom', 'sempre positiv'], penalty: 1 }],
          modelAnswer: 'Uma LC alta indica folga para honrar as obrigações de curto prazo. Mas não é automaticamente positiva: caixa em excesso pode estar parado, rendendo menos do que renderia se investido na operação, em crescimento ou distribuído aos sócios. A leitura depende da estratégia e da comparação com pares.',
        },
      },
    ],
    explanation:
      'A Horizonte tem LC muito acima de 1, e seu AC é dominado por caixa (3.000 de 4.100), o que dá qualidade ao índice. Ainda assim, nenhum índice é "quanto maior, melhor": excesso de liquidez pode indicar recursos ociosos. A leitura padrão é "existem aproximadamente R$ X de AC para cada R$ 1 de obrigação de curto prazo".',
    reasoningSteps: [
      'Calcule AC / PC em cada ano.',
      'Compare a evolução e o nível em relação a 1.',
      'Verifique a composição do AC (caixa × estoques × recebíveis).',
      'Pondere se a folga é útil ou se há recursos parados.',
    ],
    commonMistake: 'Ler a LC como probabilidade ou como caixa sobre dívida total.',
    rule: 'Leia a LC como "R$ X de AC para cada R$ 1 de PC" e qualifique-a pela composição do AC e pela estratégia da empresa.',
    formula: 'LC = AC / PC',
    hint: 'Quanto do AC de X2 é caixa?',
    concept: 'LC alta mostra folga de curto prazo, mas pode também indicar recursos pouco aproveitados.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-032',
    type: 'multiple-choice',
    topic: 'liquidez',
    subtopic: 'Composição do AC',
    skill: 'lc-composicao',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    context: 'CASO FICTÍCIO PARA ESTUDO — Moda Ametista Ltda. (loja de moda) × Distribuidora Aroeira Ltda. (distribuição de alimentos)',
    stem: 'As duas empresas têm a mesma Liquidez Corrente (1,80). Na Moda Ametista, a gerência informa que boa parte dos estoques é de coleções antigas, com venda lenta. Qual conclusão é a mais adequada?',
    table: {
      caption: 'Composição do circulante (31/12/X2)',
      note: NOTE,
      headers: ['Conta', 'Moda Ametista', 'Distribuidora Aroeira'],
      rows: [
        ['Caixa e equivalentes', '100', '900'],
        ['Contas a receber de clientes', '200', '700'],
        ['Estoques', '1.500', '200'],
        ['ATIVO CIRCULANTE', '1.800', '1.800'],
        ['PASSIVO CIRCULANTE', '1.000', '1.000'],
        ['Liquidez Corrente', '1,80', '1,80'],
      ],
      totalRows: [3, 4, 5],
    },
    options: [
      { id: 'A', text: 'As duas têm a mesma capacidade de pagamento, pois a LC é igual.', whyWrong: 'O índice é igual, mas a qualidade do AC não: a Ametista depende de vender estoques de giro lento para pagar o PC.' },
      { id: 'B', text: 'A Ametista está em melhor situação, pois tem mais estoques para vender.', whyWrong: 'Estoque encalhado demora a virar caixa e pode exigir descontos; mais estoque não significa mais liquidez.' },
      { id: 'C', text: 'Apesar da LC igual, a Aroeira tem liquidez de melhor qualidade: seu AC é formado sobretudo por caixa e recebíveis, enquanto a LC da Ametista é inflada por estoque de venda lenta, que pode demorar a virar dinheiro.' },
      { id: 'D', text: 'Ambas estão em situação de atenção, pois a LC está abaixo de 2.', whyWrong: 'A regra didática usa 1 como referência: acima de 1 indica folga. Não existe o corte "abaixo de 2 = atenção".' },
      { id: 'E', text: 'A Ametista deveria ser analisada com o Passivo Total para ter um índice mais preciso.', whyWrong: 'Trocar o PC pelo Passivo Total não resolve o problema e mistura prazos; a questão é a composição do AC.' },
    ],
    correct: 'C',
    explanation:
      'Dois índices iguais podem esconder realidades diferentes. A LC soma todo o AC como se tudo virasse caixa no mesmo ritmo, mas estoque encalhado é o item menos líquido. Por isso a LC deve ser lida junto com a composição do AC (caixa, recebíveis, estoques) e com o giro dos estoques.',
    reasoningSteps: [
      'Confirme que a LC é a mesma (1.800 / 1.000).',
      'Abra a composição do AC de cada empresa.',
      'Pergunte: quanto do AC vira caixa rapidamente?',
      'Considere informações qualitativas (estoque de giro lento).',
    ],
    commonMistake: 'Concluir que LC igual significa capacidade de pagamento igual.',
    rule: 'Antes de confiar numa LC, verifique do que é feito o AC: caixa e recebíveis valem mais para pagar o curto prazo do que estoques de giro lento.',
    formula: 'LC = AC / PC',
    hint: 'Qual das duas consegue transformar seu AC em dinheiro mais rápido?',
    concept: 'A LC trata todo o AC de forma igual; a análise da composição corrige essa limitação.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-033',
    type: 'essay',
    topic: 'liquidez',
    subtopic: 'LC < 1 — discussão',
    skill: 'lc-nao-isolada',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    stem: 'Uma empresa com Liquidez Corrente de 0,85 está em situação ruim? Discuta, explicando o que o índice mostra, que informações adicionais você buscaria e em que situações esse nível pode ser sustentável ou preocupante.',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Interpreta o índice: há cerca de R$ 0,85 de AC para cada R$ 1 de PC; pela regra didática, abaixo de 1 indica atenção.',
          points: 2,
          keywords: [['0,85', 'cada'], ['85 centavos'], ['atencao'], ['menor que 1'], ['abaixo de 1']],
        },
        {
          id: 'c2',
          description: 'Afirma que não se deve analisar a LC isoladamente nem concluir falência/insolvência só por ela.',
          points: 2,
          keywords: [['isolad'], ['nao significa', 'falen'], ['nao necessariamente'], ['depende']],
        },
        {
          id: 'c3',
          description: 'Lista fatores a investigar: caixa, recebíveis, estoques, giro, composição do PC (fornecedores × empréstimos).',
          points: 3,
          keywords: [['caixa', 'estoque'], ['receb', 'estoque'], ['giro'], ['composicao', 'passivo'], ['fornecedor']],
        },
        {
          id: 'c4',
          description: 'Dá exemplo de quando é sustentável (ex.: varejo com giro alto, vendas à vista, prazo de fornecedores) e de quando preocupa (ex.: PC com empréstimos vencendo, estoque encalhado, queda de caixa, tendência de piora).',
          points: 3,
          keywords: [['varej'], ['a vista'], ['supermerc'], ['empresti', 'venc'], ['encalh'], ['tendencia'], ['piora']],
        },
      ],
      seriousErrors: [
        { description: 'Conclui que LC < 1 significa falência ou insolvência certa.', patterns: ['esta falida', 'vai falir', 'esta insolvente', 'certamente insolvente', 'quebrou'], penalty: 3 },
        { description: 'Calcula ou descreve a LC com Passivo Total.', patterns: ['passivo total'], penalty: 2 },
      ],
      modelAnswer:
        'Não necessariamente. LC = 0,85 significa que existem aproximadamente R$ 0,85 de Ativos Circulantes para cada R$ 1 de obrigação de curto prazo; pela regra didática (> 1 folga, = 1 limite, < 1 atenção), é um sinal de atenção, não de falência. O índice não deve ser analisado isoladamente: é preciso ver quanto do AC é caixa e recebíveis de curto prazo, se os estoques giram rápido ou estão encalhados, e do que é feito o PC (fornecedores que se renovam com o giro ou empréstimos bancários vencendo). Em um supermercado que vende à vista, gira estoques rapidamente e paga fornecedores a prazo, uma LC abaixo de 1 pode ser estrutural e sustentável. Preocupa quando o PC está concentrado em empréstimos vencendo, o caixa vem caindo, os estoques estão parados ou o índice mostra tendência de piora em relação a anos anteriores e a pares do setor.',
    },
    explanation:
      'A regra didática (> 1 folga, = 1 limite, < 1 atenção) é um ponto de partida. A conclusão depende do caixa, dos recebíveis, dos estoques, da natureza do negócio, do giro e da composição do PC, além da comparação com o histórico e com pares.',
    reasoningSteps: [
      'Traduza o índice: R$ 0,85 de AC por R$ 1 de PC.',
      'Aplique a regra didática (atenção), sem decretar falência.',
      'Liste as informações que qualificam o índice.',
      'Mostre cenários em que o mesmo número tem leituras diferentes.',
    ],
    commonMistake: 'Afirmar que LC < 1 significa empresa insolvente ou falida.',
    rule: 'LC < 1 pede investigação, não veredito: olhe caixa, recebíveis, estoques, natureza do negócio, giro e composição do PC.',
    formula: 'LC = AC / PC',
    hint: 'Pense em um supermercado que vende à vista e paga fornecedores a prazo.',
    concept: 'A LC indica folga ou aperto de curto prazo; sua leitura depende do modelo de negócio e da qualidade do circulante.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-034',
    type: 'multiple-choice',
    topic: 'liquidez',
    subtopic: 'Leitura da LC',
    skill: 'lc-interpretacao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Uma empresa apresenta Liquidez Corrente de 0,96. Qual é a interpretação correta do índice?',
    options: [
      { id: 'A', text: 'A empresa tem 96% de probabilidade de pagar suas dívidas de curto prazo.', whyWrong: 'A LC não é uma probabilidade, e sim a relação entre o Ativo Circulante e o Passivo Circulante.' },
      { id: 'B', text: 'A empresa está insolvente e deve pedir recuperação judicial.', whyWrong: 'LC < 1 é sinal de atenção, não de insolvência; a conclusão depende de caixa, estoques, recebíveis, giro e composição do PC.' },
      { id: 'C', text: 'Existem R$ 0,96 de caixa para cada R$ 1 de dívida total da empresa.', whyWrong: 'A LC usa todo o Ativo Circulante (não só o caixa) e apenas o Passivo Circulante (não a dívida total).' },
      { id: 'D', text: 'Existem aproximadamente R$ 0,96 de Ativos Circulantes para cada R$ 1 de obrigação de curto prazo.' },
      { id: 'E', text: 'Para cada R$ 1 de Ativo Circulante, a empresa deve R$ 0,96 no curto prazo.', whyWrong: 'Inverteu a relação: 0,96 é AC por real de PC, e não PC por real de AC.' },
    ],
    correct: 'D',
    explanation:
      'LC = AC / PC = 0,96 significa que, para cada R$ 1 de obrigação de curto prazo, há cerca de R$ 0,96 de recursos que devem virar caixa em até 12 meses. Pela regra didática, isso pede atenção — mas a leitura final depende do contexto do negócio.',
    reasoningSteps: [
      'Lembre a fórmula: AC no numerador, PC no denominador.',
      'Traduza a razão como "R$ de AC para cada R$ 1 de PC".',
      'Aplique a regra didática: < 1 = atenção.',
      'Evite leituras de probabilidade, insolvência ou dívida total.',
    ],
    commonMistake: 'Inverter a relação ou ler o índice como percentual de chance.',
    rule: 'Leia LC = X como "existem aproximadamente R$ X de AC para cada R$ 1 de PC".',
    formula: 'LC = AC / PC',
    hint: 'O que está no numerador e o que está no denominador?',
    concept: 'A LC é uma razão de cobertura: quanto de recursos de curto prazo existe para cada real de obrigação de curto prazo.',
    sourceReference: REF_LC,
  },
  {
    id: 'an-035',
    type: 'numeric',
    topic: 'liquidez',
    subtopic: 'Regra didática da LC',
    skill: 'lc-regra-didatica',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    context: CTX_JAC,
    stem: 'Calcule a Liquidez Corrente da Rede Jacarandá em X1 e classifique-a pela regra didática (folga, limite ou atenção). Arredonde para 2 casas decimais.',
    table: BP_JAC,
    balanceCheck: BAL_JAC,
    correct: 1.0,
    unit: 'ratio',
    decimals: 2,
    calc: { fn: 'liquidezCorrente', args: [2800, 2800] },
    solution: {
      formula: 'LC = Ativo Circulante / Passivo Circulante',
      substitution: 'LC X1 = 2.800 / 2.800',
      computation: '2.800 / 2.800 = 1,00',
      result: '1,00',
      unit: 'vezes',
      interpretation: 'Existe R$ 1,00 de Ativo Circulante para cada R$ 1 de obrigação de curto prazo: situação limite pela regra didática (sem folga). Em X2, o índice caiu para 0,94 (atenção).',
    },
    explanation:
      'Com AC igual ao PC, a LC é exatamente 1: situação limite, sem folga. A regra didática (> 1 folga, = 1 limite, < 1 atenção) é o primeiro filtro; no varejo, a leitura precisa considerar o giro dos estoques e o papel dos fornecedores no PC.',
    reasoningSteps: [
      'Localize AC (2.800) e PC (2.800) de X1.',
      'Divida: 2.800 / 2.800 = 1,00.',
      'Classifique: = 1 → limite.',
      'Contextualize com a natureza do negócio e com a evolução para X2.',
    ],
    commonMistake: 'Usar o Passivo Total (3.500), obtendo 0,80 e classificando como atenção.',
    rule: 'Regra didática da LC: > 1 folga; = 1 limite; < 1 atenção — e sempre complementada pela análise do contexto.',
    formula: 'LC = AC / PC',
    hint: 'Compare os totais do AC e do PC de X1.',
    concept: 'LC = 1 significa que os recursos de curto prazo cobrem exatamente as obrigações de curto prazo.',
    sourceReference: REF_LC,
  },
];
