import type { Question } from '../../shared/types';

// Questões CONCEITUAIS da Aula 5: BP e DRE lidos em conjunto, perguntas que cada
// demonstração responde, roteiro de análise em 3 partes (formato da prova), Liquidez
// Corrente (e suas variações), DuPont com a "barraca de praia" (margem, giro,
// alavancagem) e a lista de ROEs. Sem números de empresa real ou fictícia.

const SRC = {
  ponte: 'Aula 5 — "O Balanço e a DRE lidos em conjunto": a ponte entre as duas é o ROE (slides)',
  perguntas: 'Aula 5 — "Perguntas que cada demonstração responde" (slides)',
  roteiro: 'Aula 5 — "O roteiro de análise em 3 partes — o formato da prova" (slides)',
  liquidez: 'Aula 5 — "Liquidez Corrente: nunca leia o número sozinho" (slides)',
  barraca: 'Aula 5 — "DuPont: a barraca de praia — três jeitos de encher o mesmo bolso" (slides)',
  margem: 'Aula 5 — "DuPont, fator 1: Margem Líquida" (slides)',
  giro: 'Aula 5 — "DuPont, fator 2: Giro do Ativo" (slides)',
  alav: 'Aula 5 — "DuPont, fator 3: Alavancagem — faca de dois gumes" (slides)',
  roes: 'Aula 5 — ROE como ponte entre BP e DRE; lista de ROEs por empresa ("Por que bancos e bens de consumo rendem mais que varejo e aéreas?") (slides)',
};

const F = {
  roe: 'ROE = Lucro Líquido (DRE) / Patrimônio Líquido (BP) × 100',
  lc: 'LC = Ativo Circulante / Passivo Circulante',
  margem: 'Margem = Lucro / Receita × 100',
  giro: 'Giro do Ativo = Receita / Ativo Total',
  alav: 'Alavancagem = Ativo Total / Patrimônio Líquido',
  dupont: 'ROE = Margem Líquida × Giro do Ativo × Alavancagem',
};

export const questions: Question[] = [
  // =====================================================================
  // 1. A ponte entre BP e DRE
  // =====================================================================
  {
    id: 'a5-001',
    type: 'multiple-choice',
    topic: 'roe',
    skill: 'roe-ponte-bp-dre',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Na Aula 5, o professor afirma que "nenhuma demonstração responde sozinha" e que existe uma ponte entre o Balanço (a foto) e a DRE (o filme). Qual alternativa descreve corretamente essa ponte e a pergunta que ela responde?',
    options: [
      {
        id: 'A',
        text: 'A ponte é a Liquidez Corrente, que pega o Ativo Circulante do Balanço e o compara com a Receita da DRE para responder "a empresa consegue pagar as contas?".',
        whyWrong: 'A Liquidez Corrente usa só o Balanço (AC ÷ PC); nenhuma linha da DRE entra no índice.',
      },
      {
        id: 'B',
        text: 'A ponte é a Margem Líquida, que divide o Lucro Líquido pelo Ativo Total e responde "quanto cada R$ 1 de ativo rendeu?".',
        whyWrong: 'A Margem Líquida é LL ÷ Receita, duas linhas da DRE; não cruza com o Balanço. Lucro ÷ Ativo seria "margem × giro", não a margem.',
      },
      {
        id: 'C',
        text: 'A ponte é o ROE: Lucro Líquido (DRE) ÷ Patrimônio Líquido (Balanço), respondendo à pergunta do dono: "para cada R$ 1 que deixei na empresa, quanto voltou neste ano?".',
      },
      {
        id: 'D',
        text: 'A ponte é a Análise Horizontal, que compara o Lucro Líquido de um ano com o do ano anterior para responder "melhorou ou piorou?".',
        whyWrong: 'A A.H. compara a mesma linha em dois períodos (DRE com DRE ou BP com BP); não liga o lucro ao capital dos sócios.',
      },
      {
        id: 'E',
        text: 'A ponte é o Giro do Ativo, que divide o Patrimônio Líquido pela Receita e responde "quantas vezes o capital dos sócios girou?".',
        whyWrong: 'O Giro é Receita ÷ Ativo Total (e não PL ÷ Receita). Ele cruza DRE com BP, mas responde sobre eficiência do ativo, não sobre o retorno do dono.',
      },
    ],
    correct: 'C',
    explanation:
      'O Balanço mostra onde a empresa investiu e quem financia; a DRE mostra quanto a operação rendeu entre uma foto e outra. Lucro alto sobre um PL gigante pode ser retorno ruim, e margem bonita com dívida curta e caixa vazio pode ser risco — por isso nenhuma responde sozinha. A ponte é o ROE: pega o Lucro Líquido (fim do filme da DRE) e divide pelo Patrimônio Líquido (foto do Balanço), respondendo à pergunta do dono: "para cada R$ 1 que deixei na empresa, quanto voltou neste ano?".',
    reasoningSteps: [
      'Identifique de qual demonstração vem cada parte do indicador: numerador e denominador.',
      'A "ponte" precisa de uma linha da DRE e uma do BP ao mesmo tempo.',
      'Lucro Líquido (DRE) ÷ Patrimônio Líquido (BP) = ROE: o retorno sobre o capital que o sócio deixou na empresa.',
      'Confira se a pergunta respondida é a do dono ("quanto voltou para cada R$ 1 meu?").',
    ],
    commonMistake: 'Achar que qualquer indicador que cruza BP e DRE é "a ponte" (o Giro também cruza, mas responde sobre o ativo, não sobre o dono) ou colocar o Ativo Total no lugar do PL.',
    rule: 'Quando a pergunta é "quanto voltou para o sócio?", o denominador é o Patrimônio Líquido — nunca o Ativo nem a Receita.',
    formula: F.roe,
    hint: 'Pense em quem fez a pergunta: o dono quer saber o retorno sobre o capital DELE.',
    concept: 'O ROE liga o resultado do período (DRE) ao capital próprio investido (BP). É a medida do retorno do sócio e, por isso, a ponte entre as duas demonstrações.',
    sourceReference: SRC.ponte,
  },

  // =====================================================================
  // 2. Perguntas que cada demonstração responde
  // =====================================================================
  {
    id: 'a5-002',
    type: 'classification',
    topic: 'fundamentos',
    skill: 'demonstracao-pergunta',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Classifique cada pergunta conforme a demonstração que a responde: o Balanço Patrimonial (a foto) ou a DRE (o filme do resultado).',
    items: [
      { id: 'i1', label: 'Onde a empresa investe? Quais são as maiores contas do ativo?' },
      { id: 'i2', label: 'O produto é rentável?' },
      { id: 'i3', label: 'Quem financia: capital próprio ou de terceiros, em que proporção?' },
      { id: 'i4', label: 'A operação para em pé depois das despesas?' },
      { id: 'i5', label: 'A dívida é cara (bancos) ou "de graça" (fornecedores)?' },
      { id: 'i6', label: 'Sobra alguma coisa para o sócio no fim do período?' },
      { id: 'i7', label: 'Os prazos do que vence casam com os prazos do que se realiza?' },
      { id: 'i8', label: 'De onde vem o lucro: da operação ou do financeiro?' },
    ],
    categories: [
      { id: 'bp', label: 'Balanço Patrimonial (a foto)' },
      { id: 'dre', label: 'DRE (o filme do resultado)' },
    ],
    correct: { i1: 'bp', i2: 'dre', i3: 'bp', i4: 'dre', i5: 'bp', i6: 'dre', i7: 'bp', i8: 'dre' },
    explanation:
      'O Balanço responde sobre investimento e financiamento: onde o dinheiro está aplicado (ativo), quem o financia (passivo e PL), se a dívida é cara ou de graça e se os prazos casam (liquidez). A DRE responde sobre o resultado: se o produto é rentável (margem bruta), se a operação para em pé (margem operacional), se sobra para o sócio (margem líquida), se melhorou ou piorou (A.H.) e de onde vem o lucro (operação ou resultado financeiro).',
    reasoningSteps: [
      'Pergunte: a resposta está em um ESTOQUE (saldo numa data) ou em um FLUXO (o que aconteceu no período)?',
      'Investimento, financiamento, dívida e prazos são saldos → Balanço.',
      'Rentabilidade do produto, da operação e do sócio, e a origem do lucro são fluxos → DRE.',
    ],
    commonMistake: 'Mandar "a dívida é cara?" para a DRE por causa dos juros: a pergunta é sobre QUEM financia (bancos × fornecedores), que se lê na composição do Passivo.',
    rule: 'Saldo numa data responde-se com o Balanço; resultado de um período responde-se com a DRE.',
    hint: 'Foto (saldos) ou filme (fluxos)?',
    concept: 'Cada demonstração tem suas perguntas-chave: o Balanço fala de investimento e financiamento; a DRE, de rentabilidade e origem do resultado.',
    sourceReference: SRC.perguntas,
  },
  {
    id: 'a5-003',
    type: 'classification',
    topic: 'estrategia',
    skill: 'pergunta-ferramenta',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Para cada pergunta do analista, indique a ferramenta (ou a linha) que a responde, conforme a Aula 5.',
    items: [
      { id: 'i1', label: 'Quais são as maiores contas do ativo? Onde a empresa investe?' },
      { id: 'i2', label: 'Quem financia a empresa e em que proporção: sócios, bancos ou fornecedores?' },
      { id: 'i3', label: 'Os prazos casam? Há descasamento entre o que vence e o que se realiza no curto prazo?' },
      { id: 'i4', label: 'A empresa melhorou ou piorou de um ano para o outro, e em qual linha?' },
      { id: 'i5', label: 'O lucro vem da operação ou de juros e aplicações?' },
      { id: 'i6', label: 'Quanto cada grupo do Passivo + PL representa do total?' },
    ],
    categories: [
      { id: 'av-ativo', label: 'A.V. do Ativo' },
      { id: 'av-passivo', label: 'A.V. do Passivo + PL' },
      { id: 'lc', label: 'Liquidez Corrente' },
      { id: 'ah', label: 'A.H. (variação entre períodos)' },
      { id: 'rf', label: 'Resultado Financeiro na DRE' },
    ],
    correct: { i1: 'av-ativo', i2: 'av-passivo', i3: 'lc', i4: 'ah', i5: 'rf', i6: 'av-passivo' },
    explanation:
      'Cada pergunta tem uma ferramenta: "onde investe?" é a A.V. do Ativo (cada conta ÷ Ativo Total); "quem financia?" é a A.V. do Passivo + PL (cada fonte ÷ total); "os prazos casam?" é a Liquidez Corrente (AC ÷ PC); "melhorou ou piorou?" é a A.H. (variação de cada linha entre dois períodos); "de onde vem o lucro?" se lê na linha de Resultado Financeiro da DRE, comparando Lucro Operacional e Lucro Líquido. Como diz o professor: "ferramentas de sempre — nada novo, tudo junto".',
    reasoningSteps: [
      'Pergunta de COMPOSIÇÃO ("quanto representa") → A.V.; decida se a base é o Ativo ou o Passivo + PL.',
      'Pergunta de EVOLUÇÃO ("melhorou ou piorou") → A.H.',
      'Pergunta de PRAZO no curto prazo → Liquidez Corrente.',
      'Pergunta de ORIGEM do lucro → separe a operação do financeiro na DRE.',
    ],
    commonMistake: 'Responder "quem financia?" com a A.V. do Ativo (lado errado do Balanço) ou "melhorou ou piorou?" com a A.V., que só mostra a estrutura de um ano.',
    rule: 'Composição = A.V. (÷ base); evolução = A.H. (variação); prazos = LC; origem do lucro = Resultado Financeiro.',
    hint: 'Financiamento está no lado direito do Balanço.',
    concept: 'A análise usa poucas ferramentas: A.V. para estrutura, A.H. para evolução, LC para prazos e a cascata da DRE para a origem do lucro.',
    sourceReference: SRC.perguntas,
  },

  // =====================================================================
  // 3. Roteiro em 3 partes (formato da prova)
  // =====================================================================
  {
    id: 'a5-004',
    type: 'classification',
    topic: 'estrategia',
    skill: 'roteiro-3-partes',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'O roteiro de análise em 3 partes é o formato da prova. Classifique cada tópico na parte do roteiro em que ele é tratado.',
    items: [
      { id: 'i1', label: 'A.V. e A.H. do Ativo: onde a empresa investe e o que mudou' },
      { id: 'i2', label: 'Margens bruta, operacional e líquida' },
      { id: 'i3', label: 'Custo × diferenciação: como a empresa compete' },
      { id: 'i4', label: 'Estrutura de capital e maior financiador' },
      { id: 'i5', label: 'ROE e a satisfação do acionista' },
      { id: 'i6', label: 'Riscos do negócio e ações concretas ligadas às linhas das DFs' },
      { id: 'i7', label: 'Prazos e Liquidez Corrente' },
      { id: 'i8', label: 'A.V. e A.H. da DRE: a receita cresceu? O lucro acompanhou?' },
    ],
    categories: [
      { id: 'p1', label: 'Parte 1 — Decisões de investimento e financiamento (Balanço)' },
      { id: 'p2', label: 'Parte 2 — Resultados (DRE)' },
      { id: 'p3', label: 'Parte 3 — Estratégia' },
    ],
    correct: { i1: 'p1', i2: 'p2', i3: 'p3', i4: 'p1', i5: 'p2', i6: 'p3', i7: 'p1', i8: 'p2' },
    explanation:
      'A Parte 1 lê o Balanço: A.V. e A.H. do ativo e do passivo, estrutura de capital, maior financiador, prazos e liquidez. A Parte 2 lê a DRE: A.V. e A.H., margens bruta, operacional e líquida, ROE e a satisfação do acionista. A Parte 3 fecha com estratégia: custo × diferenciação, riscos do negócio e ações concretas ligadas às linhas das demonstrações. A prova é com consulta ao anexo das DFs e "resposta sem número vale no máximo metade".',
    reasoningSteps: [
      'Pergunte de onde vêm os dados do tópico: Balanço → Parte 1; DRE → Parte 2.',
      'O ROE usa LL ÷ PL, mas entra na Parte 2, junto das margens, porque fecha a leitura do resultado para o acionista.',
      'Tudo o que é posicionamento, risco e plano de ação vai para a Parte 3.',
    ],
    commonMistake: 'Colocar o ROE na Parte 1 porque usa o PL do Balanço: no roteiro ele encerra a Parte 2 (resultados e satisfação do acionista).',
    rule: 'Parte 1 = Balanço (investimento, financiamento, prazos); Parte 2 = DRE (margens e ROE); Parte 3 = estratégia e ações com número.',
    hint: 'Balanço, DRE, e só depois o "e agora, o que fazer?".',
    concept: 'O roteiro em 3 partes organiza a análise: primeiro o Balanço, depois a DRE, por fim a estratégia — sempre com números.',
    sourceReference: SRC.roteiro,
  },

  // =====================================================================
  // 4. Liquidez: nunca leia o número sozinho
  // =====================================================================
  {
    id: 'a5-005',
    type: 'true-false',
    topic: 'liquidez',
    skill: 'lc-composicao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Quando a empresa declara dividendos a pagar no fim do ano, o Passivo Circulante aumenta e a Liquidez Corrente cai; mas essa obrigação não é uma dívida nova com terceiros, e sim lucro que vai sair para os sócios — por isso o analista deve olhar a composição do PC antes de concluir que a liquidez piorou."',
    correct: true,
    explanation:
      'Verdadeiro. O dividendo declarado é uma obrigação exigível no curto prazo e, portanto, entra no Passivo Circulante, reduzindo a LC. Mas ele não resulta de um empréstimo nem de compra a prazo: é parte do lucro que deixa de ficar no PL. Como diz o professor, "um dividendo declarado incha o PC sem ser dívida nova" — e por isso nunca se lê o número sozinho; é preciso olhar o que compõe o numerador e o denominador.',
    reasoningSteps: [
      'Localize a conta: dividendos a pagar é obrigação de curto prazo → PC.',
      'Veja o efeito mecânico: PC maior → LC menor.',
      'Pergunte a origem: veio de dívida nova com terceiros ou de lucro destinado aos sócios?',
      'Condicione a conclusão à composição do PC, não só ao número.',
    ],
    commonMistake: 'Tratar toda queda da LC como "endividamento de curto prazo", sem ver que parte do PC pode ser dividendo declarado.',
    rule: 'Antes de concluir sobre a Liquidez Corrente, abra o Passivo Circulante e pergunte de onde veio cada obrigação.',
    formula: F.lc,
    hint: 'De onde veio o aumento do PC?',
    concept: 'A Liquidez Corrente compara AC e PC, mas sua leitura depende da qualidade dos itens: caixa e recebíveis valem mais que estoque, e um dividendo declarado incha o PC sem ser dívida nova.',
    sourceReference: SRC.liquidez,
  },
  {
    id: 'a5-006',
    type: 'multiple-choice',
    topic: 'liquidez',
    skill: 'lc-composicao',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    stem: 'Uma rede de supermercados vende à vista e recebe no ato, mas paga seus fornecedores em 45 dias; seu estoque gira em poucos dias. A Liquidez Corrente dela é 0,85. Uma fábrica de máquinas, que vende a prazo longo e mantém estoques por meses, tem LC de 1,30. Qual análise está de acordo com a leitura ensinada na Aula 5?',
    options: [
      {
        id: 'A',
        text: 'O supermercado está em situação pior, porque LC abaixo de 1 significa que ele não consegue pagar as contas de curto prazo.',
        whyWrong: 'Aplica a regra de bolso sem olhar a composição e o giro: quem recebe à vista e paga depois gera caixa antes de a obrigação vencer.',
      },
      {
        id: 'B',
        text: 'As duas estão bem, pois o que importa é a média dos índices, que fica acima de 1.',
        whyWrong: 'Não existe "média" entre empresas diferentes; cada índice é lido com a composição e o ritmo do próprio negócio.',
      },
      {
        id: 'C',
        text: 'A fábrica está necessariamente mais segura, porque 1,30 é maior que 0,85 e o índice resume toda a informação necessária.',
        whyWrong: 'O número não resume tudo: um AC cheio de estoque lento e recebíveis longos vale menos do que um AC de caixa que entra todo dia.',
      },
      {
        id: 'D',
        text: 'O índice menor que 1 do supermercado convive bem com o giro rápido: ele transforma estoque em caixa antes de os fornecedores vencerem. Já o 1,30 da fábrica merece a pergunta "o que compõe esse AC?", pois estoques e recebíveis lentos valem menos que caixa.',
      },
      {
        id: 'E',
        text: 'Nenhuma conclusão é possível sem calcular o ROE das duas empresas.',
        whyWrong: 'O ROE mede retorno do sócio, não prazo; a leitura de liquidez se faz com a composição do AC/PC e o giro do negócio.',
      },
    ],
    correct: 'D',
    explanation:
      'A regra de bolso (acima de 1 folga, igual a 1 limite, abaixo de 1 atenção) é o ponto de partida, nunca o ponto de chegada. "Giro rápido convive bem com índice < 1": o supermercado vende e recebe antes de pagar o fornecedor, então o PC é coberto pelo caixa que entra todo dia. Na fábrica, o AC é feito de estoque demorado e recebíveis longos; "caixa e recebíveis valem mais que estoque" — e um estoque de meses vale ainda menos. A pergunta certa é "o que compõe o numerador e o denominador?".',
    reasoningSteps: [
      'Calcule ou leia a LC e aplique a regra de bolso como primeiro sinal.',
      'Abra o AC: quanto é caixa, quanto é recebível, quanto é estoque — e em quanto tempo cada um vira dinheiro?',
      'Abra o PC: quando as obrigações vencem? Há dívida bancária ou só fornecedores?',
      'Compare o ritmo de entrada de caixa com o ritmo de vencimento: é isso que decide se LC < 1 é problema.',
    ],
    commonMistake: 'Ler a LC como um veredito ("abaixo de 1 = empresa ruim") sem olhar o giro e a composição do circulante.',
    rule: 'Depois da regra de bolso, sempre pergunte: o AC vira caixa antes de o PC vencer?',
    formula: F.lc,
    hint: 'Quem recebe hoje e paga daqui a 45 dias precisa de quanto caixa parado?',
    concept: 'A Liquidez Corrente é um número que precisa de contexto: composição do AC e do PC, velocidade do giro e o que mudou de um ano para o outro.',
    sourceReference: SRC.liquidez,
  },
  {
    id: 'a5-007',
    type: 'true-false',
    topic: 'liquidez',
    skill: 'lc-variacoes',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "A liquidez imediata, citada em aula como variação da Liquidez Corrente, é mais abrangente que ela: além do disponível, inclui no numerador os estoques e os recebíveis de longo prazo."',
    correct: false,
    explanation:
      'Falso. As variações citadas na Aula 5 vão na direção oposta: elas RESTRINGEM o numerador. A liquidez seca exclui os estoques (o item que demora mais a virar caixa); a liquidez imediata vai além e considera só o disponível (caixa e equivalentes). Ambas são "a mesma ideia" da LC, cada vez mais conservadora — nenhuma delas amplia o numerador.',
    reasoningSteps: [
      'Lembre a ordem de liquidez do AC: caixa, depois recebíveis, depois estoques.',
      'Cada variação corta o item menos líquido: seca tira o estoque; imediata fica só com o caixa.',
      'Itens de longo prazo nunca entram em índice de curto prazo.',
    ],
    commonMistake: 'Confundir "imediata" com "mais completa": o nome indica o que já é dinheiro, não o que está mais longe de virar dinheiro.',
    rule: 'Da LC para a seca e para a imediata, o numerador só encolhe: tira-se primeiro o estoque, depois tudo que não é caixa.',
    formula: 'LC = AC / PC; Seca = (AC − Estoques) / PC; Imediata = Disponível / PC',
    hint: 'O que é "imediato" para pagar uma conta?',
    concept: 'Liquidez seca e imediata são variações mais conservadoras da Liquidez Corrente: retiram do numerador os itens que demoram mais a virar caixa.',
    sourceReference: SRC.liquidez,
  },

  // =====================================================================
  // 5. A barraca de praia: margem, giro e alavancagem
  // =====================================================================
  {
    id: 'a5-008',
    type: 'numeric',
    topic: 'dupont',
    skill: 'dupont-barraca-margem',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    stem: 'Na barraca de praia da Aula 5, a caipirinha custa R$ 8 para ser feita e é vendida por R$ 25. Qual é a margem da caipirinha, isto é, quanto do preço de venda sobra como lucro? Responda em %, com 1 casa decimal.',
    correct: 68.0,
    unit: 'percent',
    decimals: 1,
    calc: { fn: 'margem', args: [17, 25] },
    solution: {
      formula: F.margem,
      substitution: 'Margem = (25 − 8) / 25 × 100 = 17 / 25 × 100',
      computation: '17 ÷ 25 = 0,68 → 68,0',
      result: '68,0%',
      unit: '%',
      interpretation: 'De cada R$ 100 vendidos em caipirinha, R$ 68 sobram como lucro. É o primeiro jeito de encher o bolso: ganhar muito em cada venda.',
    },
    explanation:
      'A margem compara o lucro de cada venda com o PREÇO de venda, não com o custo. Lucro por caipirinha = 25 − 8 = R$ 17; margem = 17 ÷ 25 = 68%. É a mesma lógica da Margem Líquida (LL ÷ Receita): "de cada R$ 100 vendidos, quantos viram lucro".',
    reasoningSteps: [
      'Calcule o lucro unitário: preço − custo.',
      'Divida pelo preço (a receita), nunca pelo custo.',
      'Multiplique por 100 e arredonde como pedido.',
    ],
    commonMistake: 'Dividir o lucro pelo custo (17 ÷ 8 = 212,5%), confundindo margem com markup, ou responder "R$ 17" quando a pergunta pede percentual.',
    rule: 'Margem é sempre lucro ÷ receita (preço); o custo só entra para achar o lucro.',
    formula: F.margem,
    hint: 'O denominador é o que o cliente pagou.',
    concept: 'Margem é a parcela do preço que vira lucro. Na DuPont, a Margem Líquida (LL ÷ Receita) é o primeiro fator do ROE.',
    sourceReference: SRC.barraca,
  },
  {
    id: 'a5-009',
    type: 'multiple-choice',
    topic: 'dupont',
    skill: 'dupont-barraca-margem',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Na barraca de praia, a caipirinha custa R$ 8 e é vendida por R$ 25 (margem de 68%); a água custa R$ 2 e é vendida por R$ 5. Qual alternativa compara corretamente as margens dos dois produtos?',
    calc: { fn: 'margem', args: [3, 5] },
    options: [
      {
        id: 'A',
        text: 'A água é mais rentável, porque seu custo de R$ 2 é muito menor que os R$ 8 da caipirinha.',
        whyWrong: 'Compara custos absolutos; a margem relaciona o lucro ao preço de venda de cada produto.',
      },
      {
        id: 'B',
        text: 'A água tem margem de 60% ((5 − 2) ÷ 5), abaixo dos 68% da caipirinha: a caipirinha ganha mais em cada real vendido — é o caminho da margem.',
      },
      {
        id: 'C',
        text: 'Os dois produtos têm a mesma margem, já que cada um é vendido com lucro — R$ 3 na água e R$ 17 na caipirinha.',
        whyWrong: 'Ter lucro não significa ter a mesma margem; R$ 3 sobre R$ 5 e R$ 17 sobre R$ 25 são proporções diferentes.',
      },
      {
        id: 'D',
        text: 'A água tem margem de 150% ((5 − 2) ÷ 2), bem maior que a da caipirinha.',
        whyWrong: 'Dividiu o lucro pelo custo, e não pelo preço de venda; isso é markup, não margem.',
      },
      {
        id: 'E',
        text: 'A margem da caipirinha é de 17%, porque o lucro por unidade é R$ 17.',
        whyWrong: 'Confunde o lucro em reais (R$ 17) com a margem em percentual (17 ÷ 25 = 68%).',
      },
    ],
    correct: 'B',
    solution: {
      formula: F.margem,
      substitution: 'Margem da água = (5 − 2) / 5 × 100',
      computation: '3 ÷ 5 = 0,60 → 60,0',
      result: '60,0% (água) contra 68,0% (caipirinha)',
      unit: '%',
      interpretation: 'A caipirinha deixa R$ 68 de cada R$ 100 vendidos; a água, R$ 60. A caipirinha enche o bolso mais rápido por venda.',
    },
    explanation:
      'A margem de cada produto é lucro unitário ÷ preço: água (5 − 2) ÷ 5 = 60%; caipirinha (25 − 8) ÷ 25 = 68%. A caipirinha tem margem maior: ganha mais em cada real vendido. Esse é o primeiro "jeito de encher o bolso" da barraca — vender produtos de margem alta —, equivalente ao fator Margem Líquida da DuPont.',
    reasoningSteps: [
      'Calcule o lucro unitário de cada produto (preço − custo).',
      'Divida cada lucro pelo PREÇO do próprio produto.',
      'Compare os percentuais, não os reais.',
    ],
    commonMistake: 'Comparar custos ou lucros em reais, ou dividir o lucro pelo custo (markup) em vez de pelo preço.',
    rule: 'Para comparar a rentabilidade de produtos, compare margens (lucro ÷ preço), não valores absolutos.',
    formula: F.margem,
    hint: 'Coloque os dois produtos na mesma base: "a cada R$ 100 vendidos…".',
    concept: 'Margem mede quanto de cada real vendido vira lucro; produtos diferentes se comparam pela margem, não pelo lucro em reais.',
    sourceReference: SRC.barraca,
  },
  {
    id: 'a5-010',
    type: 'numeric',
    topic: 'giro',
    skill: 'dupont-barraca-giro',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    stem: 'Dois vendedores têm o mesmo isopor de R$ 100 (o ativo). O primeiro fica sentado e vende 1 caixa por dia; o segundo anda a praia inteira e vende 5 caixas por dia com o MESMO isopor. Suponha que cada caixa vendida gere R$ 100 de receita. Qual é o Giro do Ativo diário do segundo vendedor? Responda em vezes, com 1 casa decimal.',
    correct: 5.0,
    unit: 'times',
    decimals: 1,
    calc: { fn: 'giro', args: [500, 100] },
    solution: {
      formula: F.giro,
      substitution: 'Giro = (5 caixas × R$ 100) / R$ 100 = 500 / 100',
      computation: '500 ÷ 100 = 5,0',
      result: '5,0x',
      unit: 'vezes',
      interpretation: 'Cada R$ 1 investido no isopor gera R$ 5 de venda por dia; o primeiro vendedor, com o mesmo isopor, gera só R$ 1 (giro de 1,0x). A receita é 5 vezes maior com o mesmo ativo.',
    },
    explanation:
      'Giro do Ativo = Receita ÷ Ativo. O segundo vendedor fatura 5 × R$ 100 = R$ 500 com um ativo de R$ 100: giro de 5,0x. O primeiro fatura R$ 100 com os mesmos R$ 100: giro de 1,0x. O ativo é idêntico; o que muda é quantas vezes ele "roda" — o segundo jeito de encher o bolso.',
    reasoningSteps: [
      'Calcule a receita: quantidade vendida × receita por caixa.',
      'Divida pelo valor do ativo (o isopor).',
      'Compare com o outro vendedor: mesmo denominador, numerador 5 vezes maior.',
    ],
    commonMistake: 'Dividir o ativo pela receita (100 ÷ 500 = 0,2) ou achar que o giro muda porque o isopor mudou — o ativo é o mesmo.',
    rule: 'Giro = Receita ÷ Ativo: com o mesmo ativo, vender mais é girar mais.',
    formula: F.giro,
    hint: 'O isopor é o mesmo; o que muda é quanto ele vende.',
    concept: 'O Giro do Ativo mostra quantos reais de venda cada R$ 1 de ativo gera. Vender mais com a mesma estrutura aumenta o giro.',
    sourceReference: SRC.barraca,
  },
  {
    id: 'a5-011',
    type: 'multi-part',
    topic: 'alavancagem',
    skill: 'dupont-barraca-alavancagem',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    stem: 'Com R$ 1.000 próprios, a barraca de praia rende R$ 300 no verão (30%). O dono pega R$ 2.000 emprestados a 10% ao verão e monta uma barraca 3 vezes maior, que rende proporcionalmente. Responda em R$ (sem casas decimais) e em %, com 1 casa decimal.',
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'Quanto a barraca 3 vezes maior rende no verão, antes dos juros?',
        correct: 900,
        unit: 'currency',
        decimals: 0,
        points: 1,
        calc: { fn: 'multiplica', args: [300, 3] },
        solution: {
          formula: 'Resultado da operação = resultado original × 3',
          substitution: '300 × 3',
          computation: '300 × 3 = 900',
          result: 'R$ 900',
          unit: 'R$',
          interpretation: 'Com R$ 3.000 de ativo (1.000 próprios + 2.000 de terceiros), a operação rende R$ 900 — os mesmos 30% sobre o ativo.',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'Quanto o dono paga de juros no verão?',
        correct: 200,
        unit: 'currency',
        decimals: 0,
        points: 1,
        calc: { fn: 'multiplica', args: [2000, 0.1] },
        solution: {
          formula: 'Juros = empréstimo × taxa',
          substitution: '2.000 × 10%',
          computation: '2.000 × 0,10 = 200',
          result: 'R$ 200',
          unit: 'R$',
          interpretation: 'O custo do dinheiro de terceiros é fixo: R$ 200, chova ou faça sol.',
        },
      },
      {
        id: 'c',
        kind: 'numeric',
        prompt: 'Quanto sobra para o dono depois dos juros?',
        correct: 700,
        unit: 'currency',
        decimals: 0,
        points: 2,
        calc: { fn: 'subtrai', args: [900, 200] },
        solution: {
          formula: 'Sobra para o dono = resultado da operação − juros',
          substitution: '900 − 200',
          computation: '900 − 200 = 700',
          result: 'R$ 700',
          unit: 'R$',
          interpretation: 'Dos R$ 900 gerados, R$ 200 remuneram o banco; R$ 700 ficam com o dono.',
        },
      },
      {
        id: 'd',
        kind: 'numeric',
        prompt: 'Qual é o retorno do dono sobre os MESMOS R$ 1.000 próprios? Responda em %, com 1 casa decimal.',
        correct: 70.0,
        unit: 'percent',
        decimals: 1,
        points: 3,
        calc: { fn: 'roe', args: [700, 1000] },
        solution: {
          formula: F.roe,
          substitution: 'Retorno = 700 / 1.000 × 100',
          computation: '700 ÷ 1.000 = 0,70 → 70,0',
          result: '70,0%',
          unit: '%',
          interpretation: 'Sem dívida, o dono ganhava 30% (300 sobre 1.000). Com a alavancagem, ganha 70% sobre o mesmo capital próprio, porque a operação rende 30% e o dinheiro emprestado custa só 10%.',
        },
      },
      {
        id: 'e',
        kind: 'choice',
        prompt: 'Agora suponha que chova o verão inteiro e a operação dê prejuízo, em vez de lucro. O que acontece com o dono alavancado em comparação com o dono que usou só os R$ 1.000 próprios?',
        points: 3,
        options: [
          {
            id: 'A',
            text: 'O prejuízo é o mesmo nos dois casos, porque o capital próprio é igual (R$ 1.000).',
            whyWrong: 'O prejuízo nasce na operação, que é 3 vezes maior; o capital próprio igual é justamente o que faz a perda pesar mais sobre cada real do dono.',
          },
          {
            id: 'B',
            text: 'O dono alavancado perde menos, porque o banco assume parte do prejuízo.',
            whyWrong: 'O banco recebe os R$ 200 de juros chova ou faça sol; ele não divide o prejuízo da operação.',
          },
          {
            id: 'C',
            text: 'O mesmo multiplicador que triplicou o lucro triplica o prejuízo da operação — e os juros de R$ 200 continuam devidos, piorando ainda mais a perda sobre os R$ 1.000 próprios.',
          },
          {
            id: 'D',
            text: 'A alavancagem não afeta o resultado em cenário de chuva, pois só funciona quando há lucro.',
            whyWrong: 'A alavancagem é uma "faca de dois gumes": amplia o resultado para os dois lados, lucro ou prejuízo.',
          },
        ],
        correct: 'C',
      },
    ],
    explanation:
      'A barraca 3 vezes maior rende 3 × 300 = R$ 900. O empréstimo custa 2.000 × 10% = R$ 200. Sobram 900 − 200 = R$ 700 para o dono, que investiu os mesmos R$ 1.000: retorno de 70%, contra 30% sem dívida. A alavancagem amplia o ROE porque a operação rende 30% e o dinheiro de terceiros custa 10%. Mas, "se chover o verão inteiro, o mesmo multiplicador triplica o prejuízo" — e os juros continuam devidos.',
    reasoningSteps: [
      'Calcule o resultado da operação ampliada (3 vezes o original).',
      'Calcule o custo fixo da dívida (principal × taxa).',
      'Subtraia os juros: o que sobra é do dono.',
      'Divida a sobra pelo capital PRÓPRIO, que não mudou — é isso que o ROE mede.',
      'Repita o raciocínio com prejuízo: o multiplicador é o mesmo, mas o sinal se inverte.',
    ],
    commonMistake: 'Dividir os R$ 700 pelo ativo total de R$ 3.000 (23,3%) em vez de pelos R$ 1.000 próprios, ou esquecer que os juros são devidos mesmo com prejuízo.',
    rule: 'Alavancagem amplia o retorno do sócio quando a operação rende MAIS do que custa a dívida — e amplia a perda quando rende menos; os juros são fixos nos dois cenários.',
    formula: F.alav,
    hint: 'Os R$ 1.000 do dono não mudaram; mudou o tamanho da barraca e apareceu um custo fixo.',
    concept: 'Alavancagem é usar dinheiro de terceiros para operar um ativo maior do que o capital próprio permitiria. Multiplica o resultado sobre o PL nos dois sentidos.',
    sourceReference: SRC.barraca,
  },

  // =====================================================================
  // 6. Os três fatores da DuPont
  // =====================================================================
  {
    id: 'a5-012',
    type: 'true-false',
    topic: 'dupont',
    skill: 'dupont-terceiro-fator',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Julgue: "Margem Líquida × Giro do Ativo resulta em Lucro Líquido ÷ Ativo Total, ou seja, o retorno sobre o ATIVO. Para chegar ao ROE, falta o terceiro fator da DuPont, a Alavancagem (Ativo ÷ PL), que responde: de quem é esse ativo?"',
    correct: true,
    explanation:
      'Verdadeiro. (LL ÷ Receita) × (Receita ÷ Ativo) cancela a Receita e deixa LL ÷ Ativo: quanto o ativo rendeu, independentemente de quem o financiou. O sócio, porém, quer saber o retorno sobre o capital DELE. Multiplicando por Ativo ÷ PL, o Ativo se cancela e sobra LL ÷ PL = ROE. Por isso o professor diz: "margem × giro = retorno sobre o ativo; falta o terceiro fator: de quem é esse ativo?".',
    reasoningSteps: [
      'Escreva os três fatores como frações e cancele o que se repete.',
      'Margem × Giro cancela a Receita → LL ÷ Ativo (retorno do ativo).',
      '× Alavancagem cancela o Ativo → LL ÷ PL (retorno do sócio).',
      'A alavancagem é o que separa "o ativo rendeu" de "o sócio ganhou".',
    ],
    commonMistake: 'Achar que margem × giro já é o ROE, esquecendo que o ativo pode ser financiado em parte por terceiros.',
    rule: 'Margem × giro mede o ativo; só a alavancagem traduz esse retorno para o capital dos sócios.',
    formula: F.dupont,
    hint: 'Cancele as frações: o que sobra no denominador depois de margem × giro?',
    concept: 'A DuPont separa o ROE em eficiência de vendas (margem), uso do ativo (giro) e estrutura de financiamento (alavancagem). Os dois primeiros medem o ativo; o terceiro diz de quem ele é.',
    sourceReference: SRC.giro,
  },
  {
    id: 'a5-013',
    type: 'true-false',
    topic: 'alavancagem',
    skill: 'alavancagem-leitura',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Bancos operam com alavancagem (Ativo ÷ PL) próxima de 10 vezes, e justamente por isso são, como lembrou o professor, as empresas menos reguladas da economia: o mercado confia no capital de terceiros que elas administram."',
    correct: false,
    explanation:
      'Falso. A primeira parte está certa — bancos têm alavancagem da ordem de 10×, porque a maior parte do seu ativo é financiada pelos depósitos dos clientes, e não pelo capital dos acionistas. A conclusão está invertida: exatamente por sustentarem R$ 10 de ativo com R$ 1 próprio, uma perda pequena no ativo consome uma fatia grande do PL, e por isso os bancos são as empresas MAIS reguladas. Alavancagem igual a 1,0 significaria 100% capital próprio; quanto mais alta, maior o risco e maior a vigilância.',
    reasoningSteps: [
      'Alavancagem = Ativo ÷ PL: 10× significa R$ 10 de ativo para cada R$ 1 dos sócios.',
      'Pergunte: uma perda de 5% do ativo consome quanto do PL? Com 10×, consome 50%.',
      'Risco maior para terceiros (depositantes) → regulação maior, não menor.',
    ],
    commonMistake: 'Associar alavancagem alta a "confiança do mercado" em vez de a risco ampliado — a faca de dois gumes corta também para baixo.',
    rule: 'Quanto maior a alavancagem, mais uma oscilação do ativo se amplifica sobre o PL; alavancagem 1,0 = 100% capital próprio.',
    formula: F.alav,
    hint: 'O que acontece com R$ 1 de PL quando um ativo de R$ 10 perde 10% do valor?',
    concept: 'Alavancagem mede quantos reais de ativo cada R$ 1 dos sócios sustenta. Igual a 1,0 = sem terceiros; bancos, perto de 10×, são os mais regulados.',
    sourceReference: SRC.alav,
  },
  {
    id: 'a5-014',
    type: 'multiple-choice',
    topic: 'alavancagem',
    skill: 'alavancagem-uso',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    stem: 'Uma empresa estuda tomar um empréstimo para ampliar a operação. Quatro propostas estão na mesa. Pela regra da Aula 5 sobre como usar bem a alavancagem, qual proposta é a mais adequada?',
    options: [
      {
        id: 'A',
        text: 'Financiar a nova fábrica (ativo que leva 8 anos para se pagar) com capital de giro bancário renovado a cada 90 dias, porque a taxa curta é a mais baixa disponível.',
        whyWrong: 'A dívida é barata, mas não está casada com o prazo do ativo: o empréstimo vence muito antes de a fábrica gerar o caixa para pagá-lo.',
      },
      {
        id: 'B',
        text: 'Tomar dívida a 14% ao ano para ampliar uma linha de produtos que rende 9% ao ano sobre o ativo, porque "alavancagem sempre aumenta o ROE".',
        whyWrong: 'A operação rende menos do que custa o dinheiro: aqui a alavancagem REDUZ o ROE. "Nunca alavancar uma operação que não remunera o custo do capital."',
      },
      {
        id: 'C',
        text: 'Tomar o máximo de dívida possível, já que os bancos operam a 10× e são bem-sucedidos.',
        whyWrong: 'Bancos são um caso à parte (e os mais regulados); copiar a alavancagem deles ignora o custo da dívida e o risco de prejuízo ampliado.',
      },
      {
        id: 'D',
        text: 'Não tomar dívida nenhuma, pois alavancagem igual a 1,0 é sempre a estrutura mais rentável para o sócio.',
        whyWrong: 'Alavancagem 1,0 é a mais segura, não a mais rentável: quando a operação rende mais que a dívida, recusar terceiros deixa retorno na mesa.',
      },
      {
        id: 'E',
        text: 'Financiar a nova fábrica com dívida de longo prazo a 8% ao ano, casada com o prazo do ativo, numa operação que rende 15% ao ano sobre o ativo.',
      },
    ],
    correct: 'E',
    explanation:
      'A Aula 5 dá duas condições para usar bem a alavancagem: dívida BARATA (custa menos do que a operação rende) e CASADA com o prazo do ativo (o ativo gera o caixa antes de a dívida vencer). A proposta E atende às duas: 15% de retorno contra 8% de custo, e vencimento alinhado à vida da fábrica. As demais quebram pelo menos uma: descasamento de prazo (A), operação que não remunera o custo do capital (B), endividamento sem critério (C) ou recusa de um ganho disponível (D).',
    reasoningSteps: [
      'Compare o retorno da operação com o custo da dívida: só vale alavancar se a operação render mais.',
      'Compare o prazo da dívida com o prazo em que o ativo gera caixa: devem casar.',
      'Lembre que a mesma alavancagem amplia o prejuízo; não existe "quanto mais, melhor".',
      'Elimine as propostas que falham em uma das duas condições.',
    ],
    commonMistake: 'Olhar só a taxa de juros (escolher a mais baixa) e esquecer o prazo, ou achar que qualquer dívida aumenta o ROE.',
    rule: 'Alavanque apenas quando a operação rende mais que o custo da dívida E o prazo da dívida casa com o prazo do ativo.',
    formula: F.alav,
    hint: 'Duas perguntas: a dívida é barata em relação ao que a operação rende? Ela vence antes ou depois de o ativo pagar por si?',
    concept: 'Alavancagem bem usada é dívida barata e casada com o prazo do ativo; alavancar uma operação que não remunera o custo do capital só amplia o prejuízo.',
    sourceReference: SRC.alav,
  },
  {
    id: 'a5-015',
    type: 'multiple-choice',
    topic: 'giro',
    skill: 'giro-melhorar',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    stem: 'Uma indústria pesada tem Giro do Ativo baixo, típico do setor, e a diretoria quer melhorá-lo. Qual conjunto de ações atua diretamente sobre o giro, conforme a Aula 5?',
    options: [
      {
        id: 'A',
        text: 'Vender mais com a mesma estrutura, enxugar estoques e recebíveis e desmobilizar o ativo ocioso.',
      },
      {
        id: 'B',
        text: 'Aumentar o preço de venda e cortar despesas administrativas, para que cada real vendido deixe mais lucro.',
        whyWrong: 'Preço e despesas atuam na MARGEM (lucro ÷ receita), não no giro (receita ÷ ativo). Giro baixo se compensa com margem maior, mas isso não é "melhorar o giro".',
      },
      {
        id: 'C',
        text: 'Trocar capital próprio por empréstimos, para que o ativo seja sustentado com menos PL.',
        whyWrong: 'Isso altera a Alavancagem (Ativo ÷ PL). O giro usa o Ativo Total, que não muda quando apenas se troca a fonte de financiamento.',
      },
      {
        id: 'D',
        text: 'Comprar uma segunda fábrica igual à atual, dobrando o ativo e a capacidade, mesmo sem demanda para a produção extra.',
        whyWrong: 'Dobrar o ativo sem vender mais derruba o giro: o denominador cresce e o numerador fica parado.',
      },
      {
        id: 'E',
        text: 'Como o giro é determinado pelo setor (varejo gira mais que a cervejaria), nada pode ser feito; só resta aceitar o índice.',
        whyWrong: 'O setor explica o nível típico do giro, mas dentro dele há espaço: estoques, recebíveis e ativo ocioso são decisões da gestão.',
      },
    ],
    correct: 'A',
    explanation:
      'Giro = Receita ÷ Ativo Total. Para subir, ou a receita cresce com a mesma estrutura, ou o ativo encolhe sem perder venda: enxugar estoques e recebíveis e desmobilizar ativo ocioso reduzem o denominador. Indústria pesada, energia e concessões têm giro naturalmente baixo (ativos enormes, venda lenta) e por isso precisam de margem maior para compensar — mas isso é outro fator da DuPont. Preço e despesas mexem na margem; dívida mexe na alavancagem.',
    reasoningSteps: [
      'Escreva a fórmula: Receita ÷ Ativo.',
      'Separe as ações que aumentam o numerador (vender mais com a mesma estrutura) das que reduzem o denominador (estoques, recebíveis, ativo ocioso).',
      'Descarte ações que mexem em margem (preço, despesas) ou alavancagem (fonte de financiamento).',
    ],
    commonMistake: 'Confundir "melhorar o giro" com "melhorar a margem" ou achar que trocar PL por dívida muda o giro.',
    rule: 'Para mexer no giro, mexa na receita ou no tamanho do ativo; para mexer na margem, mexa em preço, custos e despesas; para mexer na alavancagem, mexa na fonte do financiamento.',
    formula: F.giro,
    hint: 'Qual é o numerador e qual é o denominador do giro? Cada ação mexe em qual deles?',
    concept: 'O Giro do Ativo melhora vendendo mais com a mesma estrutura ou reduzindo o ativo sem perder venda. Setores de ativo pesado giram pouco e compensam com margem.',
    sourceReference: SRC.giro,
  },

  // =====================================================================
  // 7. Lista de ROEs do slide
  // =====================================================================
  {
    id: 'a5-016',
    type: 'short-answer',
    topic: 'roe',
    skill: 'roe-setores-sinal',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    stem: 'A lista de ROEs do slide traz, entre outros: Itaú 24%, Bradesco 15%, Ambev 18%, Natura −11%, Casas Bahia −15% e Azul −22%. (a) Use a decomposição DuPont para explicar por que bancos e empresas de bens de consumo tendem a render mais que varejo e companhias aéreas. (b) Explique o que significa um ROE negativo como o da Azul (−22%), traduzindo o número para "cada R$ 100 do sócio".',
    rubric: {
      requireNumbers: true,
      criteria: [
        {
          id: 'c1',
          description: 'Explica os bancos pela alavancagem: ativo sustentado majoritariamente por terceiros (depósitos), alavancagem da ordem de 10×.',
          points: 2,
          keywords: [['banco', 'alavanc'], ['banco', 'terceiro'], ['banco', 'deposit'], ['banco', '10']],
        },
        {
          id: 'c2',
          description: 'Explica bens de consumo pela margem: marca, preço e mix elevam a Margem Líquida (ex.: Ambev).',
          points: 2,
          keywords: [['consumo', 'margem'], ['ambev', 'margem'], ['marca', 'margem'], ['preco', 'margem']],
        },
        {
          id: 'c3',
          description: 'Contrapõe varejo (margem fina, mesmo com giro alto) e aéreas (ativo pesado, giro baixo e dívida cara) como setores de ROE menor.',
          points: 2,
          keywords: [['varejo', 'margem'], ['aere', 'ativo'], ['aere', 'divid'], ['aere', 'alavanc'], ['aere', 'giro'], ['margem fina']],
        },
        {
          id: 'c4',
          description: 'Define ROE negativo como prejuízo: Lucro Líquido negativo dividido pelo PL.',
          points: 2,
          keywords: [['prejuizo'], ['lucro', 'negativ'], ['resultado negativ']],
        },
        {
          id: 'c5',
          description: 'Traduz −22%: a cada R$ 100 que o sócio deixou na empresa, R$ 22 foram perdidos (o PL diminuiu).',
          points: 2,
          keywords: [['22', 'perd'], ['22', 'cada'], ['100', '22'], ['22', 'consum'], ['22', 'dimin']],
        },
      ],
      seriousErrors: [
        {
          description: 'Afirma que ROE negativo significa que o Patrimônio Líquido é negativo.',
          patterns: ['pl negativo', 'patrimonio liquido negativo', 'patrimonio negativo'],
          penalty: 2,
        },
        {
          description: 'Trata o ROE alto dos bancos como prova de que eles têm a maior margem.',
          patterns: ['bancos tem a maior margem', 'banco tem margem maior', 'bancos rendem mais pela margem'],
          penalty: 2,
        },
      ],
      modelAnswer:
        '(a) Pela DuPont, ROE = Margem Líquida × Giro × Alavancagem. Bancos rendem mais pela alavancagem: a maior parte do ativo é financiada por depósitos de terceiros (alavancagem da ordem de 10×), então um retorno modesto sobre o ativo vira um ROE alto, como os 24% do Itaú — e é por isso que são as empresas mais reguladas. Bens de consumo, como a Ambev (18%), rendem pela margem: marca, preço e mix fazem cada real vendido deixar mais lucro. Varejo gira muito, mas com margem fina, e a margem baixa limita o ROE; companhias aéreas têm ativo pesado (giro baixo), dívida cara e custos sensíveis a combustível e câmbio, o que leva a margens negativas. (b) ROE negativo significa prejuízo: o Lucro Líquido foi negativo e, dividido pelo PL, dá um retorno negativo. Azul −22% quer dizer que, para cada R$ 100 que o sócio deixou na empresa, R$ 22 foram perdidos no ano — o PL encolheu em vez de ser remunerado. O mesmo vale para Casas Bahia (−15%) e Natura (−11%).',
    },
    explanation:
      'A DuPont explica a lista: bancos chegam a ROEs altos com margem e giro modestos porque a alavancagem é enorme (ativo financiado por depósitos); bens de consumo chegam lá pela margem (marca, preço, mix). Varejo gira muito, mas com margem fina; aéreas têm ativo pesado, giro baixo e dívida cara. Um ROE negativo é simplesmente prejuízo dividido pelo PL: Azul −22% significa que cada R$ 100 do sócio perdeu R$ 22 no ano. Como sempre, o número só ganha sentido comparado com o setor, com o ano anterior e com o custo de capital.',
    reasoningSteps: [
      'Lembre a fórmula: ROE = LL ÷ PL, e a decomposição em margem × giro × alavancagem.',
      'Para cada setor, pergunte qual fator puxa o ROE: alavancagem (bancos), margem (consumo), giro alto com margem fina (varejo), ativo pesado e dívida (aéreas).',
      'Para o ROE negativo, volte ao numerador: LL negativo = prejuízo.',
      'Traduza o percentual para a pergunta do dono: "a cada R$ 100 meus, quanto voltou (ou se perdeu)?".',
    ],
    commonMistake: 'Explicar o ROE alto dos bancos pela margem, ou ler ROE negativo como "PL negativo" em vez de prejuízo no período.',
    rule: 'Para explicar por que um ROE é alto, baixo ou negativo, decomponha em margem, giro e alavancagem e volte ao sinal do Lucro Líquido.',
    formula: F.dupont,
    hint: 'Quem financia o ativo de um banco? E o que acontece com o PL quando o lucro é negativo?',
    concept: 'ROEs diferentes entre setores se explicam pelos três fatores da DuPont; ROE negativo é prejuízo: o capital do sócio diminuiu no período.',
    sourceReference: SRC.roes,
  },
];
