import type { Question } from '../../shared/types';

// Banco de questões — Aulas 1 e 2: Contabilidade e Decisão, Balanço Patrimonial,
// classificação em Ativo / Passivo / PL, Circulante × Não Circulante e Patrimônio Líquido.

const AULA1 = 'Aula 1 — Contexto da contabilidade: usuários, finalidades (planejamento, controle, decisão) e visão geral das DFs (slides)';
const AULA2_BP = 'Aula 2 — Balanço Patrimonial: estrutura e formação; Ativo = Passivo + PL; Caso Alfenas S.A. (slides)';
const AULA2_CLASS = 'Aulas 1 e 2 — Bens, direitos e obrigações; Ativo, Passivo e PL (estática patrimonial) (slides)';
const AULA2_CIRC = 'Aula 2 — Grupos do BP: ordenação por liquidez (Ativo) e por exigibilidade (Passivo) (slides)';
const AULA2_GRUPOS = 'Aulas 2 e 4 — Grupos do Ativo: AC, Realizável a LP, Investimentos, Imobilizado e Intangível (slides)';
const AULA4_CRIT = 'Aula 4 — Forma e conteúdo do BP: critérios de classificação (Circulante até 1 ano; RLP / Exigível a LP após 1 ano) (slides)';
const AULA2_PL = 'Aula 2 — Patrimônio Líquido: capital social, reservas e lucros acumulados — a riqueza dos sócios (slides)';
const AULA4_PL = 'Aula 4 — Variações do PL: capital investido e resultado (receitas × despesas) (slides)';
const MIL = 'Valores em R$ mil';

export const questions: Question[] = [
  // =========================================================================
  // FUNDAMENTOS (7)
  // =========================================================================
  {
    id: 'bp-001',
    topic: 'fundamentos',
    subtopic: 'BP × DRE × DFC',
    skill: 'fund-demonstracoes',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem: 'Na disciplina, cada demonstração contábil é associada a uma imagem. Qual associação está correta?',
    options: [
      {
        id: 'A',
        text: 'BP = filme do resultado; DRE = fotografia; DFC = filme do caixa.',
        whyWrong: 'Inverteu BP e DRE. O BP mostra a posição em uma data (fotografia); é a DRE que acumula receitas e despesas de um período.',
      },
      {
        id: 'B',
        text: 'BP = fotografia; DRE = filme do caixa; DFC = filme do resultado.',
        whyWrong: 'Trocou DRE e DFC. A DRE segue a competência (resultado); a DFC mostra entradas e saídas de dinheiro (caixa).',
      },
      {
        id: 'C',
        text: 'BP = fotografia; DRE = filme do resultado; DFC = filme do caixa.',
      },
      {
        id: 'D',
        text: 'BP, DRE e DFC são todas fotografias, pois são publicadas na data de encerramento do exercício.',
        whyWrong: 'Confundiu a data de publicação com o que a demonstração mede. DRE e DFC mostram fluxos de um período inteiro, não a posição em um instante.',
      },
      {
        id: 'E',
        text: 'BP = filme do caixa; DRE = filme do resultado; DFC = fotografia.',
        whyWrong: 'O BP não acompanha movimentação de dinheiro ao longo do tempo; ele retrata saldos em uma data. A DFC é que é o "filme do caixa".',
      },
    ],
    correct: 'C',
    explanation:
      'O Balanço Patrimonial mostra a posição patrimonial (bens, direitos, obrigações e PL) em uma data específica — por isso é uma fotografia. A DRE mostra como o resultado foi formado ao longo do período (filme do resultado), e a DFC mostra como o caixa entrou e saiu nesse período (filme do caixa).',
    reasoningSteps: [
      'Pergunte: a demonstração mostra saldos em uma data ou movimentos ao longo de um período?',
      'Saldos em uma data = fotografia (BP).',
      'Movimento de receitas e despesas = filme do resultado (DRE).',
      'Movimento de entradas e saídas de dinheiro = filme do caixa (DFC).',
    ],
    commonMistake: 'Confundir DRE com DFC, achando que a DRE mostra o dinheiro que entrou e saiu.',
    rule: 'Estoque em uma data é fotografia (BP); fluxo ao longo do período é filme — de resultado (DRE) ou de caixa (DFC).',
    hint: 'Pense em "instante" versus "período".',
    concept: 'BP é uma demonstração de posição (saldo em uma data). DRE e DFC são demonstrações de fluxo: uma do resultado por competência, a outra do caixa.',
    sourceReference: AULA1,
  },
  {
    id: 'bp-002',
    topic: 'fundamentos',
    subtopic: 'BP × DRE × DFC',
    skill: 'fund-demonstracoes',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Julgue: "A DRE é a demonstração que mostra quanto dinheiro entrou e saiu do caixa da empresa durante o período."',
    correct: false,
    explanation:
      'Quem mostra entradas e saídas de dinheiro é a DFC, o "filme do caixa". A DRE é o "filme do resultado": confronta receitas e despesas pelo regime de competência, independentemente de terem sido recebidas ou pagas no período.',
    reasoningSteps: [
      'Identifique o que a afirmação descreve: movimentação de dinheiro.',
      'Movimentação de dinheiro é o objeto da DFC.',
      'A DRE trata de receitas e despesas (resultado), não de caixa.',
    ],
    commonMistake: 'Achar que "receita" significa "dinheiro recebido" e, por isso, que a DRE é um relatório de caixa.',
    rule: 'Se a pergunta é sobre dinheiro entrando e saindo, a resposta é DFC; se é sobre lucro ou prejuízo, é DRE.',
    hint: 'Qual das demonstrações é chamada de "filme do caixa"?',
    concept: 'DRE = filme do resultado (competência). DFC = filme do caixa. "Lucro não é caixa."',
    sourceReference: AULA1,
  },
  {
    id: 'bp-003',
    topic: 'fundamentos',
    subtopic: 'Usuários da informação contábil',
    skill: 'fund-usuarios',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Classifique cada usuário da informação contábil como interno ou externo à empresa.',
    items: [
      { id: 'i1', label: 'Diretor financeiro que decide se a empresa deve tomar um empréstimo' },
      { id: 'i2', label: 'Banco que analisa a concessão de crédito à empresa' },
      { id: 'i3', label: 'Gerente de produção que acompanha o custo da fábrica' },
      { id: 'i4', label: 'Investidor que avalia comprar ações da companhia' },
      { id: 'i5', label: 'Fornecedor que decide se vende a prazo para a empresa' },
      { id: 'i6', label: 'Receita Federal (fisco)' },
      { id: 'i7', label: 'Conselho de administração ao aprovar o orçamento anual' },
    ],
    categories: [
      { id: 'interno', label: 'Usuário interno' },
      { id: 'externo', label: 'Usuário externo' },
    ],
    correct: { i1: 'interno', i2: 'externo', i3: 'interno', i4: 'externo', i5: 'externo', i6: 'externo', i7: 'interno' },
    explanation:
      'Usuários internos são os que tomam decisões de dentro da empresa (gestores, diretores, conselho) e usam a contabilidade para planejar e controlar. Usuários externos estão fora da gestão (bancos, investidores, fornecedores, governo) e usam as demonstrações para decidir se emprestam, investem, vendem a prazo ou tributam.',
    reasoningSteps: [
      'Pergunte: essa pessoa ou entidade decide em nome da empresa?',
      'Se decide a gestão (planejar, controlar, decidir internamente), é usuário interno.',
      'Se apenas se relaciona com a empresa (empresta, investe, fornece, tributa), é usuário externo.',
    ],
    commonMistake: 'Classificar o conselho de administração como externo por não participar do dia a dia, ou o investidor como interno por "ter interesse" na empresa.',
    rule: 'O critério é a posição em relação à gestão: quem decide dentro da empresa é interno; quem avalia a empresa de fora é externo.',
    hint: 'Pense em quem tem acesso aos relatórios gerenciais e quem depende das demonstrações publicadas.',
    concept: 'A contabilidade informa usuários internos (planejamento, controle e decisão) e externos (crédito, investimento, fornecimento, tributação).',
    sourceReference: AULA1,
  },
  {
    id: 'bp-004',
    topic: 'fundamentos',
    subtopic: 'Finalidade da Contabilidade',
    skill: 'fund-finalidade',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem:
      'Ao final de cada mês, a gerente de uma rede de lojas compara as despesas efetivamente realizadas com as que estavam previstas no orçamento e investiga as diferenças. Qual finalidade da Contabilidade está sendo usada principalmente nessa atividade?',
    options: [
      {
        id: 'A',
        text: 'Planejamento',
        whyWrong: 'Planejamento é a elaboração do orçamento (antes). Aqui o orçamento já existe e está sendo comparado com o realizado.',
      },
      {
        id: 'B',
        text: 'Registro do patrimônio',
        whyWrong: 'Registrar o patrimônio é a base de tudo, mas a atividade descrita vai além do registro: confronta previsto × realizado.',
      },
      {
        id: 'C',
        text: 'Informação a usuários externos',
        whyWrong: 'A gerente é usuária interna e o relatório é gerencial; não se trata de informar bancos, investidores ou governo.',
      },
      {
        id: 'D',
        text: 'Controle',
      },
      {
        id: 'E',
        text: 'Decisão de investimento',
        whyWrong: 'Nenhuma alternativa de investimento está sendo escolhida; a atividade é verificar se o que foi executado seguiu o planejado.',
      },
    ],
    correct: 'D',
    explanation:
      'Controle, nos slides, é "o processo pelo qual a alta administração se certifica de que a organização está agindo em conformidade com seus planos e políticas" — exatamente comparar o realizado com o orçado e investigar desvios. O planejamento vem antes ("decidir que curso de ação deverá ser tomado para o futuro") e a decisão é "o conjunto de ações que leva à obtenção dos objetivos definidos pelo planejamento". As três finalidades se conectam, mas a comparação com o orçamento é a marca do controle.',
    reasoningSteps: [
      'Localize a atividade no tempo: antes (planejar), durante/depois (controlar) ou na escolha entre alternativas (decidir).',
      'Comparar realizado com previsto acontece depois do plano.',
      'Comparação com orçamento e investigação de desvios = controle.',
    ],
    commonMistake: 'Escolher "planejamento" só porque a palavra "orçamento" aparece no enunciado.',
    rule: 'Planejar é definir o que deve acontecer; controlar é medir o que aconteceu contra o planejado; decidir é escolher entre alternativas com base nessa informação.',
    hint: 'O orçamento já foi feito. O que a gerente está fazendo com ele?',
    concept: 'Finalidades da Contabilidade (Aula 1): Planejamento = decidir o curso de ação para o futuro; Controle = certificar-se de que a organização age conforme planos e políticas (comunicação, motivação e verificação); Decisão = ações que levam aos objetivos do planejamento — "o coração desta disciplina".',
    sourceReference: AULA1,
  },
  {
    id: 'bp-005',
    topic: 'fundamentos',
    subtopic: 'BP × DRE × DFC',
    skill: 'fund-demonstracoes',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'short-answer',
    stem: 'Explique, em poucas linhas, por que o Balanço Patrimonial é chamado de "fotografia" enquanto a DRE é chamada de "filme do resultado".',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Afirma que o BP mostra a posição patrimonial em uma data/momento específico.',
          points: 4,
          keywords: [['momento'], ['instante'], ['data'], ['posicao']],
        },
        {
          id: 'c2',
          description: 'Afirma que a DRE mostra o resultado acumulado ao longo de um período.',
          points: 4,
          keywords: [['periodo'], ['ao longo'], ['acumul'], ['durante']],
        },
        {
          id: 'c3',
          description: 'Relaciona a diferença a saldo (estoque) × fluxo/movimento.',
          points: 2,
          keywords: [['saldo'], ['fluxo'], ['movimento'], ['receitas', 'despesas']],
        },
      ],
      seriousErrors: [
        {
          description: 'Afirma que o BP mostra o lucro do período ou que a DRE mostra o caixa.',
          patterns: ['bp mostra o lucro', 'balanco mostra o lucro', 'dre mostra o caixa', 'dre mostra o dinheiro'],
          penalty: 3,
        },
      ],
      modelAnswer:
        'O BP é uma fotografia porque retrata a posição patrimonial — bens, direitos, obrigações e PL — em uma data específica, como 31/12: são saldos naquele instante. A DRE é um filme porque mostra o fluxo de receitas e despesas acumuladas ao longo de um período, explicando como o resultado (lucro ou prejuízo) foi formado. Da mesma forma, a DFC é o filme do caixa.',
    },
    explanation:
      'A diferença está no tempo: o BP mede saldos em uma data (posição), enquanto a DRE mede movimentos ao longo de um período (fluxo). Por isso o BP de 31/12 não diz como a empresa chegou até ali — essa história é contada pela DRE (resultado) e pela DFC (caixa).',
    reasoningSteps: [
      'Defina o que o BP mostra e em que momento.',
      'Defina o que a DRE mostra e em que intervalo de tempo.',
      'Conclua com a ideia de saldo (fotografia) × fluxo (filme).',
    ],
    commonMistake: 'Dizer que o BP é fotografia "porque é publicado uma vez por ano" — a DRE também é, e nem por isso é fotografia.',
    rule: 'Ao explicar uma demonstração, diga sempre o que ela mede e em que dimensão de tempo (data ou período).',
    hint: 'Uma fotografia congela um instante; um filme mostra uma sequência.',
    concept: 'BP = posição em uma data (fotografia). DRE = formação do resultado em um período (filme do resultado). DFC = movimento do caixa no período (filme do caixa).',
    sourceReference: AULA1,
  },
  {
    id: 'bp-006',
    topic: 'fundamentos',
    subtopic: 'Escolha da demonstração',
    skill: 'fund-escolha-demonstracao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem:
      'Um analista de crédito quer entender, para o último ano, de onde veio e para onde foi o dinheiro de uma empresa: quanto a operação gerou de caixa, quanto foi gasto em investimentos e quanto foi captado com bancos. Qual demonstração responde diretamente a essa pergunta?',
    options: [
      {
        id: 'A',
        text: 'Balanço Patrimonial, pois mostra o saldo de Caixa.',
        whyWrong: 'O BP mostra o saldo de Caixa em uma data (fotografia), mas não explica as entradas e saídas que levaram a esse saldo.',
      },
      {
        id: 'B',
        text: 'DFC — Demonstração dos Fluxos de Caixa.',
      },
      {
        id: 'C',
        text: 'DRE, pois mostra as receitas da empresa.',
        whyWrong: 'A DRE segue a competência: uma receita pode ter sido registrada sem que o dinheiro tenha entrado. Ela é o filme do resultado, não do caixa.',
      },
      {
        id: 'D',
        text: 'Balancete de verificação.',
        whyWrong: 'O balancete lista saldos das contas para conferir débitos e créditos; não organiza os fluxos de caixa por origem e destino.',
      },
    ],
    correct: 'B',
    explanation:
      'A pergunta é sobre movimento de dinheiro ao longo do ano, separado por origem (operação, financiamento) e destino (investimentos). Isso é o "filme do caixa": a DFC. O BP só mostra o saldo final de Caixa, e a DRE mostra o resultado por competência, que pode ser bem diferente do caixa.',
    reasoningSteps: [
      'Identifique o objeto da pergunta: dinheiro (caixa), não lucro.',
      'Identifique a dimensão de tempo: ao longo do ano (fluxo), não em uma data.',
      'Fluxo de caixa ao longo do período = DFC.',
    ],
    commonMistake: 'Escolher a DRE porque ela tem "receitas", esquecendo que receita por competência não é dinheiro recebido.',
    rule: 'Objeto + tempo definem a demonstração: caixa no período = DFC; resultado no período = DRE; posição em uma data = BP.',
    hint: 'O analista quer o caminho do dinheiro, não o saldo final nem o lucro.',
    concept: 'A DFC mostra entradas e saídas de caixa no período; complementa o BP (saldo) e a DRE (resultado).',
    sourceReference: AULA1,
  },
  {
    id: 'bp-007',
    topic: 'fundamentos',
    subtopic: 'Escolha da demonstração',
    skill: 'fund-escolha-demonstracao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem:
      'Julgue: "Uma empresa pode apresentar lucro na DRE do ano e, no mesmo ano, mostrar redução do saldo de caixa na DFC — por exemplo, se vendeu muito a prazo e ainda não recebeu."',
    correct: true,
    explanation:
      'A DRE reconhece a venda quando ela acontece (competência), mesmo que o cliente pague só no ano seguinte. A DFC só registra o dinheiro quando ele efetivamente entra. Por isso lucro e variação de caixa podem caminhar em direções opostas: "Lucro não é caixa".',
    reasoningSteps: [
      'Lembre que a DRE é filme do resultado (competência) e a DFC é filme do caixa.',
      'Venda a prazo gera receita na DRE, mas não entrada de caixa no mesmo momento.',
      'Logo, lucro e caixa podem divergir no mesmo período.',
    ],
    commonMistake: 'Supor que lucro no período implica, necessariamente, aumento de caixa.',
    rule: 'Antes de concluir algo sobre caixa a partir do lucro, verifique se receitas foram recebidas e despesas foram pagas — lucro não é caixa.',
    hint: 'Em que momento a venda a prazo aparece na DRE? E na DFC?',
    concept: 'DRE (competência) e DFC (caixa) medem coisas diferentes; uma empresa lucrativa pode ficar sem caixa.',
    sourceReference: AULA1,
  },

  // =========================================================================
  // BALANÇO PATRIMONIAL — equação patrimonial (7)
  // =========================================================================
  {
    id: 'bp-008',
    topic: 'bp',
    subtopic: 'Definições',
    skill: 'bp-definicoes',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem: 'Qual alternativa define corretamente os três grandes grupos do Balanço Patrimonial?',
    options: [
      {
        id: 'A',
        text: 'Ativo = dinheiro em caixa; Passivo = despesas; PL = lucro do ano.',
        whyWrong: 'Reduz o Ativo ao caixa, confunde Passivo (obrigação) com despesa (DRE) e PL com lucro. O lucro é apenas uma das fontes de variação do PL.',
      },
      {
        id: 'B',
        text: 'Ativo = bens e direitos; Passivo = obrigações com os sócios; PL = obrigações com terceiros.',
        whyWrong: 'Inverteu Passivo e PL. Passivo são obrigações com terceiros; o PL é a parte que pertence aos proprietários.',
      },
      {
        id: 'C',
        text: 'Ativo = bens, direitos e obrigações; Passivo = dívidas bancárias; PL = capital social.',
        whyWrong: 'Obrigações não são Ativo, Passivo não é só dívida bancária (inclui fornecedores, salários, impostos) e PL não é só capital social (inclui reservas, ajustes de avaliação patrimonial e lucros/prejuízos acumulados).',
      },
      {
        id: 'D',
        text: 'Ativo = bens e direitos; Passivo = obrigações com terceiros; PL = riqueza residual dos proprietários.',
      },
    ],
    correct: 'D',
    explanation:
      'Ativo reúne os bens e direitos controlados pela empresa (aplicações de recursos). Passivo são as obrigações com terceiros (fornecedores, bancos, empregados, governo). O PL é o que sobra para os proprietários depois de descontar o Passivo do Ativo: a riqueza residual. Daí a equação Ativo = Passivo + PL.',
    reasoningSteps: [
      'Ativo: o que a empresa tem (bens) e tem a receber (direitos).',
      'Passivo: o que a empresa deve a terceiros.',
      'PL: o que sobra para os sócios — Ativo menos Passivo.',
    ],
    commonMistake: 'Tratar PL como "lucro" ou como "dinheiro dos sócios guardado no caixa".',
    rule: 'Ativo = aplicações (bens e direitos); Passivo + PL = origens (terceiros e proprietários).',
    hint: 'Lembre da equação patrimonial e de quem é "dono" de cada lado.',
    concept: 'Ativo = bens e direitos; Passivo = obrigações com terceiros; PL = riqueza residual dos proprietários.',
    formula: 'Ativo = Passivo + PL',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-009',
    topic: 'bp',
    subtopic: 'Equação patrimonial',
    skill: 'bp-equacao-termo-faltante',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'calculation',
    type: 'numeric',
    context: 'CASO FICTÍCIO PARA ESTUDO — Comercial Ipê Ltda. (comércio de materiais de construção)',
    stem:
      'Em 31/12, a Comercial Ipê tinha Ativo Total de R$ 850 mil e Passivo (obrigações com terceiros) de R$ 520 mil. Qual é o Patrimônio Líquido? Responda em R$ mil, sem casas decimais.',
    correct: 330,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'subtrai', args: [850, 520] },
    solution: {
      formula: 'PL = Ativo − Passivo',
      substitution: 'PL = 850 − 520',
      computation: '850 − 520 = 330',
      result: 'R$ 330 mil',
      unit: 'R$ mil',
      interpretation: 'Dos R$ 850 mil aplicados no Ativo, R$ 520 mil foram financiados por terceiros e R$ 330 mil pertencem aos proprietários.',
    },
    balanceCheck: [{ label: 'Comercial Ipê 31/12', ativo: 850, passivo: 520, pl: 330 }],
    explanation:
      'Da equação Ativo = Passivo + PL, isolamos o PL: PL = Ativo − Passivo. O PL é a parte do Ativo que sobra para os sócios depois de descontadas as obrigações com terceiros.',
    reasoningSteps: [
      'Escreva a equação patrimonial: Ativo = Passivo + PL.',
      'Identifique o termo que falta (PL).',
      'Isole-o: PL = Ativo − Passivo.',
      'Substitua e confira: 520 + 330 = 850.',
    ],
    commonMistake: 'Somar Ativo e Passivo (1.370), como se o PL fosse "tudo o que a empresa movimenta".',
    rule: 'Em qualquer caso de termo faltante, escreva Ativo = Passivo + PL e isole o que falta; depois confira se a igualdade fecha.',
    formula: 'Ativo = Passivo + PL',
    hint: 'O PL é a riqueza residual: o que sobra depois de pagar terceiros.',
    concept: 'A equação patrimonial sempre fecha: todo Ativo foi financiado por terceiros (Passivo) ou pelos proprietários (PL).',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-010',
    topic: 'bp',
    subtopic: 'Equação patrimonial',
    skill: 'bp-equacao-termo-faltante',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    type: 'numeric',
    context: 'CASO FICTÍCIO PARA ESTUDO — Distribuidora Rio Claro Ltda. (distribuição de alimentos)',
    stem:
      'Com base nas contas abaixo, calcule o total do Passivo (obrigações com terceiros) da Distribuidora Rio Claro em 31/12. Responda em R$ mil, sem casas decimais.',
    table: {
      caption: 'Distribuidora Rio Claro — saldos em 31/12',
      note: MIL,
      headers: ['Conta', 'Saldo'],
      rows: [
        ['Caixa', 120],
        ['Estoques', 260],
        ['Duplicatas a Receber', 180],
        ['Imóvel', 640],
        ['Capital Social', 500],
        ['Reservas de Lucros', 150],
      ],
    },
    correct: 550,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'subtrai', args: [1200, 500, 150] },
    solution: {
      formula: 'Passivo = Ativo − PL',
      substitution: 'Ativo = 120 + 260 + 180 + 640 = 1.200; PL = 500 + 150 = 650; Passivo = 1.200 − 500 − 150',
      computation: '1.200 − 650 = 550',
      result: 'R$ 550 mil',
      unit: 'R$ mil',
      interpretation: 'R$ 550 mil do Ativo foram financiados por terceiros (fornecedores, bancos etc.) e R$ 650 mil pelos proprietários.',
    },
    balanceCheck: [{ label: 'Distribuidora Rio Claro 31/12', ativo: 1200, passivo: 550, pl: 650 }],
    explanation:
      'Primeiro separe as contas por grupo: Caixa, Estoques, Duplicatas a Receber e Imóvel são Ativo (bens e direitos) e somam R$ 1.200 mil. Capital Social e Reservas de Lucros são PL e somam R$ 650 mil. Pela equação patrimonial, Passivo = Ativo − PL = R$ 550 mil.',
    reasoningSteps: [
      'Classifique cada conta em Ativo, Passivo ou PL.',
      'Some o Ativo (1.200) e o PL (650).',
      'Isole o termo faltante: Passivo = Ativo − PL.',
      'Confira: 550 + 650 = 1.200.',
    ],
    commonMistake: 'Somar o Capital Social ao Ativo (tratando-o como recurso da empresa) e chegar a um Ativo de R$ 1.700 mil.',
    rule: 'Antes de aplicar a equação, classifique cada conta; erro de classificação vira erro de cálculo.',
    formula: 'Ativo = Passivo + PL',
    hint: 'Capital Social e Reservas não são bens nem direitos.',
    concept: 'O Passivo é o termo que equilibra a equação quando se conhece o Ativo e o PL.',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-011',
    topic: 'bp',
    subtopic: 'Efeito de fatos na equação',
    skill: 'bp-efeito-fatos',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multi-part',
    context: 'CASO FICTÍCIO PARA ESTUDO — Gráfica Vale Verde Ltda. (serviços gráficos)',
    stem:
      'Em 01/03, a Gráfica Vale Verde tinha Ativo de R$ 1.000 mil, Passivo de R$ 400 mil e PL de R$ 600 mil. Em março ocorreram apenas dois fatos: (1) compra de uma máquina impressora de R$ 200 mil a prazo, com o fornecedor; (2) aporte de R$ 300 mil em dinheiro feito pelos sócios para aumento do Capital Social. Responda às partes abaixo.',
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'a) Qual o Ativo Total após os dois fatos? Responda em R$ mil, sem casas decimais.',
        correct: 1500,
        unit: 'currency',
        decimals: 0,
        points: 4,
        calc: { fn: 'soma', args: [1000, 200, 300] },
        solution: {
          formula: 'Ativo final = Ativo inicial + Máquina + Caixa recebido do aporte',
          substitution: 'Ativo final = 1.000 + 200 + 300',
          computation: '1.000 + 200 + 300 = 1.500',
          result: 'R$ 1.500 mil',
          unit: 'R$ mil',
          interpretation: 'Os dois fatos aumentaram o Ativo: um com um bem (Imobilizado), outro com dinheiro (Caixa).',
        },
      },
      {
        id: 'b',
        kind: 'numeric',
        prompt: 'b) Qual o PL após os dois fatos? Responda em R$ mil, sem casas decimais.',
        correct: 900,
        unit: 'currency',
        decimals: 0,
        points: 3,
        calc: { fn: 'soma', args: [600, 300] },
        solution: {
          formula: 'PL final = PL inicial + Aporte dos sócios',
          substitution: 'PL final = 600 + 300',
          computation: '600 + 300 = 900',
          result: 'R$ 900 mil',
          unit: 'R$ mil',
          interpretation: 'Só o aporte alterou o PL; a compra a prazo foi financiada por terceiros (Passivo). Conferência: Passivo 600 + PL 900 = Ativo 1.500.',
        },
      },
      {
        id: 'c',
        kind: 'choice',
        prompt: 'c) Sobre a compra da máquina a prazo, qual afirmação é correta?',
        options: [
          {
            id: 'A',
            text: 'Aumentou o Ativo e o PL, pois a empresa ficou mais rica.',
            whyWrong: 'A empresa ganhou um bem, mas assumiu uma dívida de igual valor; a riqueza dos sócios não mudou.',
          },
          {
            id: 'B',
            text: 'Aumentou o Ativo (Imobilizado) e o Passivo (Fornecedores), sem alterar o PL.',
          },
          {
            id: 'C',
            text: 'Reduziu o PL, pois a compra é uma despesa.',
            whyWrong: 'Máquina para uso na operação é Ativo Imobilizado, não despesa. Ela não passa pela DRE no momento da compra.',
          },
          {
            id: 'D',
            text: 'Não alterou nada, pois não houve saída de dinheiro.',
            whyWrong: 'A contabilidade registra o fato, não só o dinheiro: entrou um bem e surgiu uma obrigação.',
          },
        ],
        correct: 'B',
        points: 3,
      },
    ],
    balanceCheck: [
      { label: 'Vale Verde 01/03', ativo: 1000, passivo: 400, pl: 600 },
      { label: 'Vale Verde 31/03', ativo: 1500, passivo: 600, pl: 900 },
    ],
    explanation:
      'A compra a prazo aumenta o Ativo (máquina) e o Passivo (fornecedor) no mesmo valor: o PL não muda, porque a empresa não ficou mais rica — trocou uma dívida por um bem. O aporte dos sócios aumenta o Ativo (Caixa) e o PL (Capital Social). Ao final, Ativo 1.500 = Passivo 600 + PL 900: a equação continua fechando após cada fato.',
    reasoningSteps: [
      'Para cada fato, pergunte: o que entrou ou saiu do Ativo?',
      'Em seguida: quem financiou — terceiros (Passivo) ou sócios/resultado (PL)?',
      'Aplique os efeitos no saldo inicial, fato a fato.',
      'Confira se Ativo = Passivo + PL depois de cada fato.',
    ],
    commonMistake: 'Achar que comprar um bem aumenta o PL ("a empresa ficou mais rica") ou que compra de máquina é despesa.',
    rule: 'Todo fato mantém a equação em equilíbrio: se o Ativo muda, a contrapartida está em outro Ativo, no Passivo ou no PL — e o PL só muda com aportes/retiradas dos sócios ou com resultado.',
    formula: 'Ativo = Passivo + PL',
    hint: 'Separe os dois fatos e veja a origem dos recursos de cada um.',
    concept: 'Fatos permutativos trocam valores entre contas sem alterar o PL; aportes e resultado são as fontes que alteram o PL.',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-012',
    topic: 'bp',
    subtopic: 'Efeito de fatos na equação',
    skill: 'bp-efeito-fatos',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    stem: 'Uma empresa paga, em dinheiro, R$ 80 mil que devia a um fornecedor. Qual o efeito desse fato na equação patrimonial?',
    options: [
      {
        id: 'A',
        text: 'Ativo diminui R$ 80 mil e PL diminui R$ 80 mil.',
        whyWrong: 'Tratou o pagamento como uma nova despesa. A despesa (ou o estoque) já foi reconhecida quando a compra ocorreu; agora só se quita a dívida.',
      },
      {
        id: 'B',
        text: 'Ativo diminui R$ 80 mil e Passivo diminui R$ 80 mil; PL não se altera.',
      },
      {
        id: 'C',
        text: 'Ativo não se altera, pois o dinheiro apenas "trocou de mãos".',
        whyWrong: 'Saiu dinheiro do Caixa da empresa, então o Ativo diminuiu.',
      },
      {
        id: 'D',
        text: 'Passivo diminui R$ 80 mil e PL aumenta R$ 80 mil.',
        whyWrong: 'Ignorou a saída de Caixa. Quitar uma dívida com dinheiro próprio não cria riqueza para os sócios.',
      },
      {
        id: 'E',
        text: 'Ativo diminui R$ 80 mil e nada mais muda, por isso a equação deixa de fechar até o fim do mês.',
        whyWrong: 'A equação patrimonial fecha depois de cada fato; não existe "desequilíbrio temporário".',
      },
    ],
    correct: 'B',
    explanation:
      'O Caixa (Ativo) cai R$ 80 mil e a obrigação com o fornecedor (Passivo) desaparece no mesmo valor. A riqueza dos sócios não muda: a dívida já existia desde a compra, e o efeito da compra (estoque ou despesa) já foi registrado naquele momento. Pagar fornecedor não é uma nova despesa.',
    reasoningSteps: [
      'O que saiu ou entrou no Ativo? Saiu Caixa.',
      'Qual a contrapartida? A dívida com o fornecedor foi extinta (Passivo).',
      'O PL só muda com aportes/retiradas ou resultado — nenhum dos dois ocorreu.',
    ],
    commonMistake: 'Tratar o pagamento ao fornecedor como uma nova despesa, reduzindo o PL.',
    rule: 'Pagamento de obrigação já registrada reduz Ativo e Passivo ao mesmo tempo; não é despesa nova.',
    formula: 'Ativo = Passivo + PL',
    hint: 'A compra que gerou essa dívida já foi registrada antes.',
    concept: 'Quitar dívidas diminui os dois lados da equação na mesma medida, mantendo o PL.',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-013',
    topic: 'bp',
    subtopic: 'Efeito de fatos na equação',
    skill: 'bp-efeito-fatos',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem: 'Julgue: "A compra de mercadorias para revenda, paga à vista, não altera o total do Ativo nem o PL."',
    correct: true,
    explanation:
      'Sai dinheiro do Caixa e entra o mesmo valor em Estoques: os dois são Ativo, então o total não muda. Não há obrigação nova (Passivo) nem alteração da riqueza dos sócios (PL). É uma troca dentro do próprio Ativo.',
    reasoningSteps: [
      'Identifique as contas afetadas: Caixa e Estoques.',
      'Ambas são Ativo; uma sobe e a outra desce no mesmo valor.',
      'Sem Passivo novo nem aporte/resultado, o PL não se altera.',
    ],
    commonMistake: 'Achar que toda compra reduz o patrimônio, ou que comprar estoque é despesa imediata.',
    rule: 'Se as duas contas afetadas estão no mesmo grupo e variam em sentidos opostos, o total do grupo não muda.',
    hint: 'A empresa trocou um ativo por outro.',
    concept: 'Fatos permutativos trocam valores entre contas sem alterar o PL.',
    sourceReference: AULA2_BP,
  },
  {
    id: 'bp-014',
    topic: 'bp',
    subtopic: 'Efeito de fatos na equação',
    skill: 'bp-equacao-termo-faltante',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: 'CASO FICTÍCIO PARA ESTUDO — Laticínios Serra Azul S.A. (indústria de alimentos)',
    stem:
      'No início do ano, a Laticínios Serra Azul tinha Ativo de R$ 2.400 mil e Passivo de R$ 1.500 mil. Durante o ano: (1) obteve lucro líquido de R$ 180 mil, integralmente retido; (2) os sócios aportaram R$ 120 mil em dinheiro; (3) tomou um empréstimo bancário de R$ 300 mil, depositado no Caixa. Qual o PL no final do ano?',
    options: [
      {
        id: 'A',
        text: 'R$ 1.500 mil',
        whyWrong: 'Somou o empréstimo ao PL. Empréstimo é obrigação com terceiros (Passivo), não riqueza dos sócios.',
      },
      {
        id: 'B',
        text: 'R$ 900 mil',
        whyWrong: 'Calculou só o PL inicial (2.400 − 1.500) e ignorou o lucro e o aporte, as duas fontes que alteram o PL.',
      },
      {
        id: 'C',
        text: 'R$ 1.020 mil',
        whyWrong: 'Esqueceu o lucro retido (900 + 120); o resultado é uma das duas fontes de alteração do PL.',
      },
      {
        id: 'D',
        text: 'R$ 1.080 mil',
        whyWrong: 'Esqueceu o aporte dos sócios (900 + 180), que também aumenta o PL (Capital Social).',
      },
      {
        id: 'E',
        text: 'R$ 1.200 mil',
      },
    ],
    correct: 'E',
    calc: { fn: 'soma', args: [900, 180, 120] },
    solution: {
      formula: 'PL final = (Ativo inicial − Passivo inicial) + Lucro retido + Aportes',
      substitution: 'PL final = (2.400 − 1.500) + 180 + 120',
      computation: '900 + 180 + 120 = 1.200',
      result: 'R$ 1.200 mil',
      unit: 'R$ mil',
      interpretation: 'O empréstimo aumentou Ativo e Passivo, mas não o PL. Ativo final = 2.400 + 180 + 120 + 300 = 3.000; Passivo final = 1.800; 1.800 + 1.200 = 3.000.',
    },
    balanceCheck: [
      { label: 'Serra Azul início do ano', ativo: 2400, passivo: 1500, pl: 900 },
      { label: 'Serra Azul fim do ano', ativo: 3000, passivo: 1800, pl: 1200 },
    ],
    explanation:
      'O PL inicial é a riqueza residual: 2.400 − 1.500 = 900. Ele só se altera por duas fontes: aportes dos sócios (+120) e resultado (+180 de lucro retido). O empréstimo aumenta Caixa e Passivo, sem tocar no PL. Assim, PL final = 1.200, e a equação fecha: Ativo 3.000 = Passivo 1.800 + PL 1.200.',
    reasoningSteps: [
      'Ache o PL inicial pela equação: PL = Ativo − Passivo.',
      'Para cada fato, pergunte se ele é aporte/retirada dos sócios ou resultado — só esses alteram o PL.',
      'Some ao PL inicial apenas os efeitos que alteram o PL.',
      'Confira montando Ativo e Passivo finais.',
    ],
    commonMistake: 'Incluir o empréstimo no PL porque "entrou dinheiro" na empresa.',
    rule: 'Entrada de dinheiro não significa aumento de PL: pergunte de quem veio o recurso — terceiros (Passivo) ou sócios/resultado (PL).',
    formula: 'Ativo = Passivo + PL',
    hint: 'Comece descobrindo o PL inicial. Depois, quais dos três fatos são aporte ou resultado?',
    concept: 'O PL varia apenas com aportes (ou retiradas) dos sócios e com o resultado do período.',
    sourceReference: AULA2_BP,
  },

  // =========================================================================
  // CLASSIFICAÇÃO — Ativo / Passivo / PL (9)
  // =========================================================================
  {
    id: 'bp-015',
    topic: 'classificacao',
    subtopic: 'Ativo, Passivo ou PL',
    skill: 'class-ativo-passivo-pl',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Classifique cada conta no grupo do Balanço Patrimonial a que pertence.',
    items: [
      { id: 'i1', label: 'Caixa' },
      { id: 'i2', label: 'Veículo' },
      { id: 'i3', label: 'Marca adquirida' },
      { id: 'i4', label: 'Duplicatas a Receber' },
      { id: 'i5', label: 'Fornecedores' },
      { id: 'i6', label: 'Salários a Pagar' },
      { id: 'i7', label: 'Capital Social' },
    ],
    categories: [
      { id: 'ativo', label: 'Ativo' },
      { id: 'passivo', label: 'Passivo' },
      { id: 'pl', label: 'Patrimônio Líquido' },
    ],
    correct: { i1: 'ativo', i2: 'ativo', i3: 'ativo', i4: 'ativo', i5: 'passivo', i6: 'passivo', i7: 'pl' },
    explanation:
      'Caixa, Veículo e Marca são bens (a Marca é um bem intangível); Duplicatas a Receber é um direito — todos Ativo. Fornecedores e Salários a Pagar são obrigações com terceiros — Passivo. Capital Social é o recurso investido pelos sócios — PL.',
    reasoningSteps: [
      'A empresa tem ou tem a receber? Ativo.',
      'A empresa deve a terceiros? Passivo.',
      'Representa o investimento ou a riqueza dos proprietários? PL.',
    ],
    commonMistake: 'Colocar Capital Social no Ativo ou a Marca como despesa.',
    rule: 'Contas "a Receber" são Ativo; contas "a Pagar"/"a Recolher" são Passivo; Capital, Reservas e Lucros/Prejuízos são PL.',
    hint: 'Pergunte se a conta representa algo que a empresa tem, deve ou que pertence aos sócios.',
    concept: 'Ativo = bens e direitos; Passivo = obrigações com terceiros; PL = riqueza residual dos proprietários.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-016',
    topic: 'classificacao',
    subtopic: 'Ativo, Passivo ou PL',
    skill: 'class-ativo-passivo-pl',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Classifique cada conta no grupo do Balanço Patrimonial a que pertence.',
    items: [
      { id: 'i1', label: 'Estoque de mercadorias' },
      { id: 'i2', label: 'Imóvel usado como sede' },
      { id: 'i3', label: 'Empréstimo bancário' },
      { id: 'i4', label: 'Impostos a Recolher' },
      { id: 'i5', label: 'Aplicações financeiras' },
      { id: 'i6', label: 'Reservas de Lucros' },
      { id: 'i7', label: 'Financiamento de longo prazo' },
      { id: 'i8', label: 'Prejuízos Acumulados' },
    ],
    categories: [
      { id: 'ativo', label: 'Ativo' },
      { id: 'passivo', label: 'Passivo' },
      { id: 'pl', label: 'Patrimônio Líquido' },
    ],
    correct: { i1: 'ativo', i2: 'ativo', i3: 'passivo', i4: 'passivo', i5: 'ativo', i6: 'pl', i7: 'passivo', i8: 'pl' },
    explanation:
      'Estoque e Imóvel são bens; Aplicações financeiras são direitos (a receber de uma instituição financeira) — Ativo. Empréstimo, Financiamento e Impostos a Recolher são obrigações com terceiros — Passivo. Reservas de Lucros e Prejuízos Acumulados são componentes do PL; o prejuízo reduz o PL, mas continua sendo PL (com saldo redutor).',
    reasoningSteps: [
      'Identifique se a conta é bem, direito, obrigação ou recurso dos sócios.',
      'Bens e direitos → Ativo; obrigações com terceiros → Passivo.',
      'Capital, Reservas e Lucros/Prejuízos Acumulados → PL.',
    ],
    commonMistake: 'Classificar Prejuízos Acumulados como Passivo ("é algo negativo") ou Aplicações financeiras como PL.',
    rule: 'Não classifique pela "sensação" (bom/ruim): pergunte se é bem/direito, obrigação com terceiros ou recurso dos proprietários.',
    hint: 'Prejuízo é "negativo", mas é dívida com alguém?',
    concept: 'O PL é composto por Capital Social, Reservas (de capital e de lucros), Ajustes de Avaliação Patrimonial e Lucros/Prejuízos Acumulados; prejuízos reduzem o PL.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-017',
    topic: 'classificacao',
    subtopic: 'Capital Social',
    skill: 'class-capital-social',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Julgue: "Capital Social é uma conta do Ativo, pois representa os recursos que os sócios colocaram na empresa."',
    correct: false,
    explanation:
      'Capital Social é PL: indica a origem dos recursos (os sócios), não onde eles estão aplicados. Quando os sócios integralizam capital em dinheiro, o dinheiro vai para o Caixa (Ativo) e o Capital Social registra, no PL, que essa parte pertence aos proprietários.',
    reasoningSteps: [
      'Pergunte: a conta mostra onde o recurso está aplicado ou de onde ele veio?',
      'Onde está aplicado → Ativo (ex.: Caixa). De onde veio → Passivo ou PL.',
      'Capital Social mostra que o recurso veio dos sócios → PL.',
    ],
    commonMistake: 'Classificar Capital Social como Ativo por associá-lo ao dinheiro recebido dos sócios.',
    rule: 'Ativo mostra aplicações (onde está o recurso); Passivo e PL mostram origens (de quem veio).',
    hint: 'O dinheiro do aporte está no Caixa. Então o que o Capital Social está registrando?',
    concept: 'Capital Social é o valor investido pelos sócios, registrado no PL como origem de recursos.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-018',
    topic: 'classificacao',
    subtopic: 'Compra de ativo × despesa',
    skill: 'class-compra-ativo',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem: 'Uma empresa compra um prédio por R$ 2 milhões, à vista, para instalar sua sede administrativa. Como esse fato deve ser registrado no momento da compra?',
    options: [
      {
        id: 'A',
        text: 'Como despesa administrativa de R$ 2 milhões na DRE do período.',
        whyWrong: 'O prédio continuará gerando benefícios por muitos anos; é um bem da empresa (Ativo Imobilizado), não um gasto consumido no período.',
      },
      {
        id: 'B',
        text: 'Como redução do PL, pois saiu dinheiro da empresa.',
        whyWrong: 'Saída de dinheiro não reduz o PL quando a empresa recebe em troca um bem de mesmo valor.',
      },
      {
        id: 'C',
        text: 'Como Ativo Imobilizado de R$ 2 milhões, com redução de R$ 2 milhões no Caixa.',
      },
      {
        id: 'D',
        text: 'Como Passivo, pois imóveis exigem gastos futuros com manutenção e impostos.',
        whyWrong: 'Gastos futuros ainda não incorridos não são obrigação hoje; o prédio é um bem, não uma dívida.',
      },
    ],
    correct: 'C',
    explanation:
      'O prédio é um bem de uso, que servirá à empresa por vários anos: vai para o Ativo Não Circulante — Imobilizado. A compra à vista apenas troca Caixa por Imobilizado; o total do Ativo e o PL não mudam. O consumo do prédio ao longo do tempo (depreciação) é que vira despesa aos poucos.',
    reasoningSteps: [
      'Pergunte: o gasto gera benefício só no período ou por vários anos?',
      'Benefício por vários anos e bem de uso → Ativo Imobilizado.',
      'Identifique a contrapartida: saída de Caixa (à vista).',
    ],
    commonMistake: 'Tratar a compra do prédio como despesa por causa do valor alto pago.',
    rule: 'Gasto que gera bem ou direito utilizável no futuro é Ativo; vira despesa só à medida que é consumido.',
    hint: 'A empresa ainda terá o prédio no dia seguinte à compra?',
    concept: 'Imobilizado = bens tangíveis de uso na operação, por prazo longo (prédios, máquinas, veículos).',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-019',
    topic: 'classificacao',
    subtopic: 'Compra de ativo × despesa',
    skill: 'class-compra-ativo',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem: 'Julgue: "Uma marca comprada de outra empresa, que será explorada por muitos anos, deve ser registrada no Ativo Não Circulante (Intangível), e não como despesa do período."',
    correct: true,
    explanation:
      'A marca é um bem incorpóreo que gera benefícios futuros por vários anos; por isso é Ativo — no grupo Intangível do Ativo Não Circulante. Lançá-la como despesa reduziria indevidamente o resultado do período e esconderia um ativo relevante do Balanço.',
    reasoningSteps: [
      'Pergunte se o gasto gera benefício futuro por mais de um período.',
      'Se sim, é Ativo; verifique se é tangível (Imobilizado) ou incorpóreo (Intangível).',
      'Marca é incorpórea → Intangível.',
    ],
    commonMistake: 'Tratar a marca como despesa porque "não é algo físico".',
    rule: 'Não ter forma física não impede algo de ser Ativo: marcas, patentes e softwares adquiridos são Intangível.',
    hint: 'O fato de não ser possível tocar a marca muda o benefício futuro que ela gera?',
    concept: 'Intangível = bens incorpóreos (marcas, patentes, softwares e ágio) que geram benefícios por longo prazo.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-020',
    topic: 'classificacao',
    subtopic: 'Bens, direitos e obrigações',
    skill: 'class-bens-direitos-obrigacoes',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Classifique cada item como bem, direito ou obrigação da empresa.',
    items: [
      { id: 'i1', label: 'Veículo de entregas' },
      { id: 'i2', label: 'Estoque de mercadorias' },
      { id: 'i3', label: 'Duplicatas a Receber de clientes' },
      { id: 'i4', label: 'Aplicações financeiras em banco' },
      { id: 'i5', label: 'Fornecedores' },
      { id: 'i6', label: 'Salários a Pagar' },
      { id: 'i7', label: 'Imóvel próprio' },
      { id: 'i8', label: 'Impostos a Recolher' },
    ],
    categories: [
      { id: 'bem', label: 'Bem' },
      { id: 'direito', label: 'Direito' },
      { id: 'obrigacao', label: 'Obrigação' },
    ],
    correct: { i1: 'bem', i2: 'bem', i3: 'direito', i4: 'direito', i5: 'obrigacao', i6: 'obrigacao', i7: 'bem', i8: 'obrigacao' },
    explanation:
      'Bens são itens que satisfazem uma necessidade e têm avaliação econômica, tangíveis (veículo, estoque, imóvel) ou intangíveis (marcas, patentes). Direitos, nas palavras dos slides, são valores sobre os quais "exercemos o domínio, mas estão na posse de terceiros" (duplicatas de clientes, aplicações a resgatar no banco). Obrigações são "bens que se encontram sob nossa posse, mas cujo domínio é exercido por terceiros" (fornecedores, empregados, governo). Bens e direitos formam o Ativo; obrigações formam o Passivo.',
    reasoningSteps: [
      'A empresa possui o item fisicamente ou como propriedade? Bem.',
      'A empresa tem algo a receber de alguém? Direito.',
      'A empresa tem algo a pagar a alguém? Obrigação.',
    ],
    commonMistake: 'Classificar Aplicações financeiras como bem por "ser dinheiro", ou Duplicatas a Receber como obrigação por ter a palavra "duplicata".',
    rule: 'Leia o sufixo: "a Receber" indica direito; "a Pagar"/"a Recolher" indica obrigação.',
    hint: 'Uma aplicação é algo que a empresa tem fisicamente ou algo que o banco lhe deve devolver?',
    concept: 'Bens e direitos compõem o Ativo; obrigações com terceiros compõem o Passivo. Direito = domínio nosso, posse de terceiros; obrigação = posse nossa, domínio de terceiros.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-021',
    topic: 'classificacao',
    subtopic: 'Bens, direitos e obrigações',
    skill: 'class-bens-direitos-obrigacoes',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem: 'Qual das contas abaixo representa um DIREITO da empresa?',
    options: [
      {
        id: 'A',
        text: 'Duplicatas a Pagar',
        whyWrong: '"A Pagar" indica que a empresa deve: é obrigação (Passivo), não direito.',
      },
      {
        id: 'B',
        text: 'Veículo',
        whyWrong: 'Veículo é Ativo, mas é um bem (a empresa o possui), não um direito a receber de alguém.',
      },
      {
        id: 'C',
        text: 'Capital Social',
        whyWrong: 'Capital Social é PL: registra a origem dos recursos aportados pelos sócios, não algo a receber.',
      },
      {
        id: 'D',
        text: 'Salários a Pagar',
        whyWrong: 'É obrigação com empregados (Passivo).',
      },
      {
        id: 'E',
        text: 'Duplicatas a Receber',
      },
    ],
    correct: 'E',
    explanation:
      'Direito é um valor que a empresa tem a receber de terceiros. Duplicatas a Receber representam vendas a prazo que os clientes ainda vão pagar — um direito, classificado no Ativo. Veículo também é Ativo, mas é um bem.',
    reasoningSteps: [
      'Separe Ativo de Passivo/PL: direito sempre é Ativo.',
      'Dentro do Ativo, separe bens (a empresa possui) de direitos (a empresa tem a receber).',
      'Procure a conta "a Receber".',
    ],
    commonMistake: 'Confundir Duplicatas a Receber com Duplicatas a Pagar pela palavra "duplicata".',
    rule: 'Para distinguir bem de direito, pergunte se o valor depende de alguém pagar à empresa — se sim, é direito.',
    hint: 'Direito = alguém deve à empresa.',
    concept: 'Direitos são créditos da empresa contra terceiros (clientes, bancos, outros devedores): a empresa exerce o domínio, mas o valor está na posse de outrem.',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-022',
    topic: 'classificacao',
    subtopic: 'Capital Social',
    skill: 'class-capital-social',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem: 'Os sócios de uma empresa recém-criada integralizam R$ 500 mil de capital em dinheiro, depositado na conta da empresa. Como esse fato aparece no Balanço Patrimonial?',
    options: [
      {
        id: 'A',
        text: 'Caixa (Ativo) + R$ 500 mil e Capital Social (Ativo) + R$ 500 mil.',
        whyWrong: 'Capital Social no Ativo duplica o recurso: o Ativo ficaria com R$ 1.000 mil sem nenhuma origem correspondente, e a equação não fecharia.',
      },
      {
        id: 'B',
        text: 'Caixa (Ativo) + R$ 500 mil e Obrigações com sócios (Passivo) + R$ 500 mil.',
        whyWrong: 'Capital integralizado não é dívida com prazo de pagamento; é investimento dos proprietários, registrado no PL.',
      },
      {
        id: 'C',
        text: 'Receita de R$ 500 mil na DRE, aumentando o lucro do período.',
        whyWrong: 'Aporte de sócios não é receita: não vem da venda de bens ou serviços. Ele altera o PL diretamente, sem passar pela DRE.',
      },
      {
        id: 'D',
        text: 'Caixa (Ativo) + R$ 500 mil e Capital Social (PL) + R$ 500 mil.',
      },
      {
        id: 'E',
        text: 'Apenas Capital Social (PL) + R$ 500 mil, pois o dinheiro pertence aos sócios.',
        whyWrong: 'O dinheiro passou a pertencer à empresa e está no Caixa (Ativo). Registrar só o PL deixaria a equação desequilibrada.',
      },
    ],
    correct: 'D',
    explanation:
      'Todo fato tem dois lados: onde o recurso está aplicado (Caixa, no Ativo) e de onde ele veio (sócios, Capital Social no PL). A equação fica Ativo 500 = Passivo 0 + PL 500. O aporte é uma das duas fontes de alteração do PL e não passa pela DRE.',
    reasoningSteps: [
      'Onde o recurso ficou? No Caixa → Ativo.',
      'De onde veio? Dos sócios, como investimento → PL (Capital Social).',
      'Confira a equação: 500 = 0 + 500.',
    ],
    commonMistake: 'Lançar o Capital Social no Ativo ou tratar o aporte como receita.',
    rule: 'Em todo fato, registre a aplicação (Ativo) e a origem (Passivo ou PL); se as duas pontas caem no mesmo lado sem se anular, algo está errado.',
    formula: 'Ativo = Passivo + PL',
    hint: 'Separe "onde está o dinheiro" de "quem forneceu o dinheiro".',
    concept: 'Aportes dos sócios aumentam o Ativo (o recurso recebido) e o PL (Capital Social).',
    sourceReference: AULA2_CLASS,
  },
  {
    id: 'bp-023',
    topic: 'classificacao',
    subtopic: 'Saldo devedor × dívida',
    skill: 'class-saldo-devedor',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem: 'Julgue: "Se a conta Caixa apresenta saldo devedor de R$ 40 mil, isso significa que a empresa deve R$ 40 mil ao banco."',
    correct: false,
    explanation:
      '"Saldo devedor" é linguagem técnica: indica que a soma dos débitos da conta supera a dos créditos. Contas de Ativo, como Caixa, têm saldo normalmente devedor — significa que a empresa TEM R$ 40 mil em caixa. Dívida com banco seria uma conta de Passivo (Empréstimos), de saldo credor.',
    reasoningSteps: [
      'Identifique a natureza da conta: Caixa é Ativo.',
      'Contas de Ativo têm saldo normal devedor.',
      'Saldo devedor em conta de Ativo = valor que a empresa possui, não que deve.',
    ],
    commonMistake: 'Ler "saldo devedor" como "a empresa está devendo", confundindo o termo contábil com a linguagem do dia a dia (ou do extrato bancário).',
    rule: 'Débito e crédito são lados da conta, não "bom" ou "ruim": interprete o saldo sempre a partir da natureza da conta.',
    hint: 'Qual é a natureza da conta Caixa?',
    concept: 'Contas de Ativo têm saldo devedor; contas de Passivo e PL têm saldo credor. O termo não indica dívida.',
    sourceReference: AULA2_CLASS,
  },

  // =========================================================================
  // CIRCULANTE × NÃO CIRCULANTE (8)
  // =========================================================================
  {
    id: 'bp-024',
    topic: 'circulante',
    subtopic: 'Grupos do Ativo',
    skill: 'circ-grupos-ativo',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Classifique cada conta no grupo do Ativo a que pertence (considere a data do balanço como referência).',
    items: [
      { id: 'i1', label: 'Caixa e equivalentes de caixa' },
      { id: 'i2', label: 'Duplicatas a Receber com vencimento em 90 dias' },
      { id: 'i3', label: 'Estoque de mercadorias para revenda' },
      { id: 'i4', label: 'Empréstimo concedido a uma coligada, a receber em 3 anos' },
      { id: 'i5', label: 'Participação permanente de 30% no capital de outra empresa' },
      { id: 'i6', label: 'Máquinas da fábrica' },
      { id: 'i7', label: 'Marca adquirida' },
      { id: 'i8', label: 'Software adquirido para gestão' },
    ],
    categories: [
      { id: 'ac', label: 'Ativo Circulante' },
      { id: 'rlp', label: 'ANC — Realizável a Longo Prazo' },
      { id: 'inv', label: 'ANC — Investimentos' },
      { id: 'imob', label: 'ANC — Imobilizado' },
      { id: 'intang', label: 'ANC — Intangível' },
    ],
    correct: { i1: 'ac', i2: 'ac', i3: 'ac', i4: 'rlp', i5: 'inv', i6: 'imob', i7: 'intang', i8: 'intang' },
    explanation:
      'O Ativo Circulante reúne o que se realiza em até 12 meses (caixa e equivalentes, contas a receber, estoques). O Não Circulante se divide em: Realizável a Longo Prazo (créditos e títulos após 12 meses), Investimentos (participações em outras empresas e imóveis não usados na operação), Imobilizado (terrenos, edifícios, máquinas e veículos usados na atividade) e Intangível (marcas, patentes, softwares e ágio). Investimentos, Imobilizado e Intangível "não se destinam à venda".',
    reasoningSteps: [
      'Primeiro decida: vira caixa em até 12 meses? Se sim, Ativo Circulante.',
      'Se não, é direito a receber no longo prazo? RLP.',
      'É participação em outra empresa ou imóvel fora da operação? Investimentos.',
      'É bem físico de uso? Imobilizado. É incorpóreo (marca, patente, software, ágio)? Intangível.',
    ],
    commonMistake: 'Colocar o empréstimo a receber em 3 anos no Ativo Circulante só porque é "dinheiro a receber".',
    rule: 'Classifique em duas etapas: prazo (até 12 meses → Circulante) e, se Não Circulante, natureza (direito LP, participação/imóvel fora da operação, bem tangível ou incorpóreo).',
    hint: 'Comece pelo prazo; depois pela natureza do item.',
    concept: 'ANC = Realizável a Longo Prazo, Investimentos (participações e imóveis não operacionais), Imobilizado (bens de uso) e Intangível (marcas, patentes, softwares, ágio).',
    sourceReference: AULA2_GRUPOS,
  },
  {
    id: 'bp-025',
    topic: 'circulante',
    subtopic: 'Passivo Circulante × Não Circulante',
    skill: 'circ-pc-pnc',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'classification',
    stem: 'Na data do balanço, classifique cada obrigação como Passivo Circulante ou Passivo Não Circulante.',
    items: [
      { id: 'i1', label: 'Fornecedores com vencimento em 60 dias' },
      { id: 'i2', label: 'Salários a Pagar do mês' },
      { id: 'i3', label: 'Impostos a Recolher no mês seguinte' },
      { id: 'i4', label: 'Empréstimo bancário que vence em 8 meses' },
      { id: 'i5', label: 'Parcelas de um financiamento que vencem daqui a 2 a 4 anos' },
      { id: 'i6', label: 'Parcela do mesmo financiamento que vence em 10 meses' },
      { id: 'i7', label: 'Debêntures emitidas com vencimento em 3 anos' },
    ],
    categories: [
      { id: 'pc', label: 'Passivo Circulante' },
      { id: 'pnc', label: 'Passivo Não Circulante' },
    ],
    correct: { i1: 'pc', i2: 'pc', i3: 'pc', i4: 'pc', i5: 'pnc', i6: 'pc', i7: 'pnc' },
    explanation:
      'O critério é o prazo de exigibilidade a partir da data do balanço: obrigações que vencem em até 12 meses são Passivo Circulante; as que vencem depois, Passivo Não Circulante (chamado nos slides de "Exigível a Longo Prazo"). Um mesmo financiamento pode ser dividido: a parcela que vence em 10 meses vai para o PC, e as parcelas de 2 a 4 anos ficam no PNC.',
    reasoningSteps: [
      'Para cada obrigação, conte o prazo até o vencimento a partir da data do balanço.',
      'Até 12 meses → Passivo Circulante.',
      'Mais de 12 meses → Passivo Não Circulante.',
      'Se uma dívida tem parcelas em prazos diferentes, separe-as.',
    ],
    commonMistake: 'Classificar o financiamento inteiro pelo prazo do contrato ("é de longo prazo"), ignorando a parcela que vence nos próximos 12 meses.',
    rule: 'Classifique pelo vencimento de cada parcela na data do balanço, não pelo nome ou pelo prazo total do contrato.',
    hint: 'O que importa é quando cada valor precisa ser pago.',
    concept: 'PC = obrigações exigíveis em até 12 meses; PNC (Exigível a Longo Prazo) = exigíveis após 12 meses.',
    sourceReference: AULA4_CRIT,
  },
  {
    id: 'bp-026',
    topic: 'circulante',
    subtopic: 'Critério de 12 meses',
    skill: 'circ-12-meses',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem: 'Qual é o critério geral para separar o Ativo Circulante do Ativo Não Circulante?',
    options: [
      {
        id: 'A',
        text: 'Itens que se realizam (viram caixa ou são consumidos) em até 12 meses após a data do balanço são Circulante.',
      },
      {
        id: 'B',
        text: 'Itens de valor baixo são Circulante; itens de valor alto são Não Circulante.',
        whyWrong: 'O valor não define o grupo. Um estoque de R$ 10 milhões continua sendo Circulante.',
      },
      {
        id: 'C',
        text: 'Itens físicos são Circulante; itens não físicos são Não Circulante.',
        whyWrong: 'Caixa e Duplicatas a Receber não são "físicos" no sentido de bens de uso e são Circulante; máquinas são físicas e são Não Circulante.',
      },
      {
        id: 'D',
        text: 'Itens comprados no ano corrente são Circulante; os comprados em anos anteriores são Não Circulante.',
        whyWrong: 'A data de aquisição não importa: uma máquina comprada ontem é Imobilizado (Não Circulante).',
      },
    ],
    correct: 'A',
    explanation:
      'A fronteira entre Circulante e Não Circulante é temporal: até 12 meses da data do balanço. No Ativo, isso significa o prazo para virar caixa ou ser consumido na operação; no Passivo, o prazo para a obrigação ser paga.',
    reasoningSteps: [
      'Lembre que a classificação olha para o futuro a partir da data do balanço.',
      'Pergunte em quanto tempo o item vira caixa (Ativo) ou precisa ser pago (Passivo).',
      'Até 12 meses → Circulante.',
    ],
    commonMistake: 'Associar Circulante a "barato" ou a "comprado recentemente".',
    rule: 'Circulante × Não Circulante é uma questão de prazo (12 meses a partir do balanço), não de valor, natureza física ou data de compra.',
    hint: 'O critério é de tempo.',
    concept: 'Ativo e Passivo Circulantes: realização/exigibilidade em até 12 meses (nos slides: "tudo que se transformará em dinheiro, ou será pago, até 1 ano").',
    sourceReference: AULA4_CRIT,
  },
  {
    id: 'bp-027',
    topic: 'circulante',
    subtopic: 'Financiamento de longo prazo com parcela no próximo ano',
    skill: 'circ-emprestimo-lp-parcela',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: 'CASO FICTÍCIO PARA ESTUDO — Transportadora Cerrado Ltda. (logística rodoviária)',
    stem:
      'Em 31/12/2025, a Transportadora Cerrado contratou um empréstimo de R$ 600 mil, a ser pago em 5 parcelas anuais iguais de R$ 120 mil; a primeira vence em 31/12/2026. Desconsidere juros. Como o empréstimo deve aparecer no Balanço de 31/12/2025?',
    options: [
      {
        id: 'A',
        text: 'Passivo Não Circulante de R$ 600 mil, pois o contrato é de 5 anos.',
        whyWrong: 'Classificou pelo prazo total do contrato, ignorando que R$ 120 mil vencem nos próximos 12 meses.',
      },
      {
        id: 'B',
        text: 'Passivo Circulante de R$ 600 mil, pois o pagamento começa no próximo ano.',
        whyWrong: 'Apenas a primeira parcela vence em até 12 meses; as outras quatro vencem depois disso.',
      },
      {
        id: 'C',
        text: 'Passivo Circulante de R$ 480 mil e Não Circulante de R$ 120 mil.',
        whyWrong: 'Inverteu os grupos: o que vence nos próximos 12 meses (uma parcela) é que vai para o Circulante.',
      },
      {
        id: 'D',
        text: 'Passivo Circulante de R$ 120 mil e Passivo Não Circulante de R$ 480 mil.',
      },
      {
        id: 'E',
        text: 'Passivo Circulante de R$ 120 mil e Não Circulante de R$ 600 mil.',
        whyWrong: 'Contou a primeira parcela duas vezes. O total das duas partes tem de ser igual à dívida de R$ 600 mil.',
      },
    ],
    correct: 'D',
    calc: { fn: 'subtrai', args: [600, 120] },
    solution: {
      formula: 'PNC = Dívida total − Parcelas que vencem em até 12 meses',
      substitution: 'PNC = 600 − 120',
      computation: '600 − 120 = 480',
      result: 'PC = R$ 120 mil; PNC = R$ 480 mil',
      unit: 'R$ mil',
      interpretation: 'O usuário do balanço precisa ver quanto da dívida pressiona o caixa dos próximos 12 meses (R$ 120 mil).',
    },
    explanation:
      'A classificação é feita parcela a parcela, pelo vencimento contado a partir da data do balanço. A parcela de 31/12/2026 vence em até 12 meses → Passivo Circulante (R$ 120 mil). As quatro parcelas seguintes vencem depois → Passivo Não Circulante (R$ 480 mil). A cada novo balanço, a próxima parcela é transferida do PNC para o PC.',
    reasoningSteps: [
      'Liste as parcelas e seus vencimentos.',
      'Marque quais vencem em até 12 meses da data do balanço.',
      'Some essas parcelas no PC e o restante no PNC.',
      'Confira se PC + PNC = valor total da dívida.',
    ],
    commonMistake: 'Deixar todo o financiamento no PNC porque "é um empréstimo de longo prazo".',
    rule: 'Dívida de longo prazo com parcelas no próximo ano é dividida: a parte que vence em até 12 meses vai para o PC; o restante fica no PNC.',
    hint: 'Quantas parcelas vencem nos próximos 12 meses?',
    concept: 'A exigibilidade é avaliada por parcela, e não pelo prazo total do contrato.',
    sourceReference: AULA4_CRIT,
  },
  {
    id: 'bp-028',
    topic: 'circulante',
    subtopic: 'Critério de 12 meses',
    skill: 'circ-12-meses',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem: 'Julgue: "Duplicatas a Receber de uma venda cujo cliente pagará em 18 meses devem ser classificadas no Ativo Circulante, porque toda conta de clientes é Circulante."',
    correct: false,
    explanation:
      'O que define o grupo é o prazo de realização, não o nome da conta. Um recebível que só vira caixa daqui a 18 meses ultrapassa o limite de 12 meses: vai para o Ativo Não Circulante, no Realizável a Longo Prazo. Quando faltarem 12 meses ou menos, ele é transferido para o Circulante.',
    reasoningSteps: [
      'Identifique o prazo de realização: 18 meses.',
      'Compare com o limite de 12 meses.',
      'Acima de 12 meses → Ativo Não Circulante (Realizável a Longo Prazo).',
    ],
    commonMistake: 'Classificar pelo nome da conta ("clientes é sempre circulante") em vez de pelo prazo.',
    rule: 'Sempre olhe o prazo de cada item na data do balanço; o nome da conta não decide o grupo.',
    hint: 'Em quanto tempo esse direito vira caixa?',
    concept: 'Realizável a Longo Prazo = direitos que se convertem em caixa após 12 meses.',
    sourceReference: AULA4_CRIT,
  },
  {
    id: 'bp-029',
    topic: 'circulante',
    subtopic: 'Liquidez × Exigibilidade',
    skill: 'circ-liquidez-exigibilidade',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'short-answer',
    stem: 'Explique a diferença entre LIQUIDEZ e EXIGIBILIDADE e diga como cada conceito organiza um lado do Balanço Patrimonial.',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Define liquidez como a velocidade/facilidade de conversão de um ativo em caixa.',
          points: 4,
          keywords: [
            ['liquidez', 'caixa'],
            ['liquidez', 'convert'],
            ['liquidez', 'transform'],
            ['liquidez', 'dinheiro'],
          ],
        },
        {
          id: 'c2',
          description: 'Define exigibilidade como o prazo em que a obrigação precisa ser paga.',
          points: 4,
          keywords: [
            ['exigibilidade', 'prazo'],
            ['exigibilidade', 'pag'],
            ['exigibilidade', 'venc'],
            ['exigibilidade', 'quita'],
          ],
        },
        {
          id: 'c3',
          description: 'Relaciona: Ativo ordenado por liquidez; Passivo ordenado por exigibilidade.',
          points: 2,
          keywords: [
            ['ativo', 'passivo', 'ordem'],
            ['ativo', 'passivo', 'ordena'],
            ['ativo', 'passivo', 'primeiro'],
            ['ativo', 'passivo', 'organiza'],
          ],
        },
      ],
      seriousErrors: [
        {
          description: 'Inverte os conceitos (liquidez como prazo de pagamento ou exigibilidade como conversão em caixa).',
          patterns: ['liquidez e o prazo de pagamento', 'liquidez e o prazo para pagar', 'exigibilidade e a velocidade', 'exigibilidade e a conversao'],
          penalty: 4,
        },
      ],
      modelAnswer:
        'Liquidez é a velocidade (ou facilidade) com que um ativo se converte em caixa: Caixa é o mais líquido, depois recebíveis, estoques e, por fim, imobilizado e intangível. Exigibilidade é o prazo em que uma obrigação precisa ser paga: quanto mais cedo vence, mais exigível. O Ativo é apresentado em ordem decrescente de liquidez e o Passivo em ordem decrescente de exigibilidade — por isso Circulante vem antes de Não Circulante nos dois lados.',
    },
    explanation:
      'Os dois conceitos tratam de tempo, mas de lados diferentes: liquidez olha para os ativos ("do que vira dinheiro mais rápido para o mais lento") e exigibilidade para as obrigações ("do que vence primeiro para o que vence depois"). Essa lógica explica a ordem das contas no BP e a divisão entre Circulante e Não Circulante.',
    reasoningSteps: [
      'Associe liquidez ao Ativo e à conversão em caixa.',
      'Associe exigibilidade ao Passivo e ao prazo de pagamento.',
      'Mostre a consequência: ordem de apresentação nos dois lados do BP.',
    ],
    commonMistake: 'Usar "liquidez" para falar de dívidas, ou dizer que o Passivo é ordenado por valor.',
    rule: 'Liquidez = quando o ativo vira caixa; exigibilidade = quando a obrigação precisa ser paga. O Ativo segue a primeira, o Passivo a segunda.',
    hint: 'Um conceito pertence ao lado do Ativo; o outro, ao lado do Passivo.',
    concept: 'Liquidez = velocidade de conversão em caixa (ordem do Ativo). Exigibilidade = prazo de pagamento (ordem do Passivo).',
    sourceReference: AULA2_CIRC,
  },
  {
    id: 'bp-030',
    topic: 'circulante',
    subtopic: 'Liquidez × Exigibilidade',
    skill: 'circ-liquidez-exigibilidade',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'ordering',
    stem: 'Ordene os grupos do Ativo como aparecem no Balanço Patrimonial, do MAIS líquido para o MENOS líquido.',
    items: [
      { id: 'o1', label: 'Caixa e equivalentes de caixa' },
      { id: 'o2', label: 'Duplicatas a Receber (curto prazo)' },
      { id: 'o3', label: 'Estoques' },
      { id: 'o4', label: 'Realizável a Longo Prazo' },
      { id: 'o5', label: 'Imobilizado' },
    ],
    explanation:
      'O Ativo é ordenado por liquidez decrescente: "do que vira dinheiro mais rápido para o mais lento". Caixa já é dinheiro. Duplicatas a Receber viram caixa quando o cliente paga. Estoques precisam primeiro ser vendidos e, depois, recebidos. O Realizável a Longo Prazo só vira caixa após 12 meses, e o Imobilizado não se destina à venda — é usado na operação (grau de liquidez: rápida no circulante, lenta no RLP, inexistente nos bens de uso).',
    reasoningSteps: [
      'Pergunte, para cada item, quantos passos faltam para virar caixa.',
      'Caixa: zero passos; Duplicatas: receber; Estoques: vender e receber.',
      'Itens do Não Circulante vêm depois: primeiro o RLP (direitos), depois os bens de uso.',
    ],
    commonMistake: 'Colocar Estoques antes de Duplicatas a Receber, esquecendo que o estoque ainda precisa ser vendido.',
    rule: 'Conte quantas etapas separam o item do dinheiro: menos etapas = mais líquido = aparece primeiro no Ativo.',
    hint: 'O estoque precisa ser vendido antes de virar recebível.',
    concept: 'Liquidez = velocidade de conversão em caixa; define a ordem de apresentação do Ativo.',
    sourceReference: AULA2_CIRC,
  },
  {
    id: 'bp-031',
    topic: 'circulante',
    subtopic: 'Liquidez × Exigibilidade',
    skill: 'circ-liquidez-exigibilidade',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Julgue: "No Passivo, as obrigações são apresentadas em ordem de exigibilidade: as que vencem primeiro aparecem primeiro."',
    correct: true,
    explanation:
      'O Passivo segue a exigibilidade, isto é, o prazo de pagamento: "do que vence primeiro para o que vence depois". Por isso o Passivo Circulante (vence em até 12 meses) vem antes do Passivo Não Circulante (Exigível a Longo Prazo), e o PL fica por último — "não vai ser pago, não é obrigação exigível". O Ativo, por sua vez, segue a liquidez.',
    reasoningSteps: [
      'Associe o Passivo ao conceito de exigibilidade.',
      'Exigibilidade = prazo de pagamento.',
      'Mais exigível (vence antes) aparece primeiro.',
    ],
    commonMistake: 'Achar que o Passivo é ordenado por liquidez ou por valor.',
    rule: 'Ativo: ordem de liquidez. Passivo: ordem de exigibilidade.',
    hint: 'Qual conceito organiza o lado das obrigações?',
    concept: 'Exigibilidade = prazo em que a obrigação deve ser paga.',
    sourceReference: AULA2_CIRC,
  },

  // =========================================================================
  // PATRIMÔNIO LÍQUIDO (6)
  // =========================================================================
  {
    id: 'bp-032',
    topic: 'pl',
    subtopic: 'Componentes do PL',
    skill: 'pl-componentes',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem: 'Qual das contas abaixo NÃO faz parte do Patrimônio Líquido?',
    options: [
      {
        id: 'A',
        text: 'Capital Social',
        whyWrong: 'Capital Social é o principal componente do PL: o valor investido pelos sócios.',
      },
      {
        id: 'B',
        text: 'Reservas de Lucros',
        whyWrong: 'Reservas são lucros retidos com destinação específica e ficam no PL.',
      },
      {
        id: 'C',
        text: 'Duplicatas a Receber',
      },
      {
        id: 'D',
        text: 'Prejuízos Acumulados',
        whyWrong: 'Prejuízos Acumulados ficam no PL, reduzindo-o. Não são obrigação com terceiros.',
      },
    ],
    correct: 'C',
    explanation:
      'O PL é formado por Capital Social, Reservas (de capital e de lucros), Ajustes de Avaliação Patrimonial e Lucros ou Prejuízos Acumulados — "a riqueza dos sócios". Duplicatas a Receber são um direito da empresa contra clientes — portanto, Ativo.',
    reasoningSteps: [
      'Lembre os componentes do PL: Capital Social, Reservas, Ajustes de Avaliação Patrimonial, Lucros/Prejuízos Acumulados.',
      'Verifique se alguma alternativa é bem, direito ou obrigação.',
      'Direito a receber → Ativo, não PL.',
    ],
    commonMistake: 'Excluir Prejuízos Acumulados do PL por achar que "prejuízo é dívida".',
    rule: 'PL contém apenas o que pertence aos proprietários: capital aportado e resultados acumulados/reservados (positivos ou negativos).',
    hint: 'Uma das contas representa algo que clientes devem à empresa.',
    concept: 'PL = Capital Social + Reservas (de capital e de lucros) ± Ajustes de Avaliação Patrimonial ± Lucros/Prejuízos Acumulados.',
    sourceReference: AULA2_PL,
  },
  {
    id: 'bp-033',
    topic: 'pl',
    subtopic: 'PL não é caixa',
    skill: 'pl-nao-e-caixa',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Julgue: "Se o Patrimônio Líquido de uma empresa é de R$ 900 mil, então ela tem R$ 900 mil disponíveis em caixa."',
    correct: false,
    explanation:
      'O PL é a riqueza residual dos proprietários — a diferença entre Ativo e Passivo —, não um saldo de dinheiro. Os recursos dos sócios estão aplicados em todo o Ativo: estoques, máquinas, imóveis, recebíveis e também caixa. O dinheiro disponível está na conta Caixa, no Ativo.',
    reasoningSteps: [
      'Lembre que o PL fica do lado das origens de recursos.',
      'O dinheiro em si é uma aplicação e aparece no Ativo (Caixa).',
      'Logo, o valor do PL não informa quanto há em caixa.',
    ],
    commonMistake: 'Pensar que o PL é "o dinheiro da empresa" ou "o caixa dos sócios".',
    rule: 'Para saber quanto dinheiro a empresa tem, olhe a conta Caixa no Ativo; o PL só diz quanto do Ativo pertence aos sócios.',
    hint: 'De que lado do BP fica o Caixa? E o PL?',
    concept: 'PL = Ativo − Passivo: indica a parte do Ativo financiada pelos sócios, não um valor em dinheiro.',
    sourceReference: AULA2_PL,
  },
  {
    id: 'bp-034',
    topic: 'pl',
    subtopic: 'Fontes de alteração do PL',
    skill: 'pl-fontes-alteracao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem: 'Qual dos fatos abaixo altera o Patrimônio Líquido da empresa?',
    options: [
      {
        id: 'A',
        text: 'Tomada de empréstimo bancário de R$ 200 mil, creditado na conta da empresa.',
        whyWrong: 'Aumenta Caixa (Ativo) e Empréstimos (Passivo); o recurso é de terceiros, não dos sócios.',
      },
      {
        id: 'B',
        text: 'Compra de estoque a prazo de R$ 50 mil.',
        whyWrong: 'Aumenta Estoques (Ativo) e Fornecedores (Passivo); não há aporte nem resultado.',
      },
      {
        id: 'C',
        text: 'Recebimento de R$ 30 mil de um cliente referente a venda feita no mês anterior.',
        whyWrong: 'Troca Duplicatas a Receber por Caixa, dentro do Ativo. A receita já foi reconhecida quando a venda aconteceu.',
      },
      {
        id: 'D',
        text: 'Pagamento de R$ 40 mil a um fornecedor.',
        whyWrong: 'Reduz Caixa (Ativo) e Fornecedores (Passivo); quitar dívida não é despesa nova.',
      },
      {
        id: 'E',
        text: 'Aumento de capital de R$ 100 mil, integralizado pelos sócios em dinheiro.',
      },
    ],
    correct: 'E',
    explanation:
      'O PL só se altera por duas fontes: aportes (ou retiradas) dos sócios e resultado do período (lucro aumenta, prejuízo reduz). O aumento de capital é um aporte. As demais operações trocam valores entre contas de Ativo e Passivo, sem mudar a riqueza dos proprietários.',
    reasoningSteps: [
      'Para cada fato, pergunte: é aporte/retirada dos sócios ou resultado (receita/despesa)?',
      'Se não for nenhum dos dois, o PL não se altera.',
      'Aumento de capital pelos sócios = aporte → altera o PL.',
    ],
    commonMistake: 'Achar que qualquer entrada de dinheiro (como um empréstimo) aumenta o PL.',
    rule: 'Antes de mexer no PL, verifique se o fato é aporte/retirada dos sócios ou resultado; caso contrário, o PL fica igual.',
    hint: 'O PL tem apenas duas fontes de alteração.',
    concept: 'Fontes de alteração do PL: investimento de capital pelos sócios e resultado do confronto entre receitas e despesas. Receita = entrada de elementos para o ativo (dinheiro ou direitos a receber) → aumenta o PL; despesa = consumo de bens ou serviços que ajuda a produzir receita, diminuindo o ativo ou aumentando o passivo → diminui o PL.',
    sourceReference: AULA4_PL,
  },
  {
    id: 'bp-035',
    topic: 'pl',
    subtopic: 'Fontes de alteração do PL',
    skill: 'pl-fontes-alteracao',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    type: 'numeric',
    context: 'CASO FICTÍCIO PARA ESTUDO — Clínica Bem Viver Ltda. (serviços de saúde)',
    stem:
      'O PL da Clínica Bem Viver era de R$ 800 mil em 01/01. No ano, os sócios aportaram R$ 200 mil em dinheiro e a clínica teve prejuízo líquido de R$ 50 mil. Não houve distribuição de lucros. Qual o PL em 31/12? Responda em R$ mil, sem casas decimais.',
    correct: 950,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'soma', args: [800, 200, -50] },
    solution: {
      formula: 'PL final = PL inicial + Aportes ± Resultado',
      substitution: 'PL final = 800 + 200 + (−50)',
      computation: '800 + 200 − 50 = 950',
      result: 'R$ 950 mil',
      unit: 'R$ mil',
      interpretation: 'O aporte aumentou a riqueza dos sócios em R$ 200 mil, mas o prejuízo consumiu R$ 50 mil dela.',
    },
    explanation:
      'O PL varia por aportes dos sócios e pelo resultado. O aporte soma R$ 200 mil; o prejuízo, sendo resultado negativo, reduz o PL em R$ 50 mil. Logo, PL final = 800 + 200 − 50 = 950.',
    reasoningSteps: [
      'Parta do PL inicial.',
      'Some aportes e subtraia retiradas/distribuições.',
      'Some lucro ou subtraia prejuízo do período.',
    ],
    commonMistake: 'Somar o prejuízo (tratando 50 como valor positivo) e chegar a 1.050, ou ignorar o aporte.',
    rule: 'PL final = PL inicial + aportes − retiradas + lucro (ou − prejuízo).',
    formula: 'PL final = PL inicial + Aportes ± Resultado',
    hint: 'Prejuízo tem sinal negativo no PL.',
    concept: 'Resultado (Receita > Despesa = lucro; Receita < Despesa = prejuízo) e aportes de capital são as duas fontes de variação do PL.',
    sourceReference: AULA4_PL,
  },
  {
    id: 'bp-036',
    topic: 'pl',
    subtopic: 'PL não é caixa',
    skill: 'pl-nao-e-caixa',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'short-answer',
    context: 'CASO FICTÍCIO PARA ESTUDO — Moveleira Araucária S.A. (indústria de móveis)',
    stem:
      'A Moveleira Araucária tem PL de R$ 2.000 mil, mas apenas R$ 50 mil em Caixa; o restante do Ativo está em estoques, máquinas e duplicatas a receber. Em reunião, um diretor afirma: "Temos R$ 2 milhões de patrimônio líquido, então podemos distribuir R$ 1 milhão aos sócios amanhã." Explique o erro de raciocínio do diretor.',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Explica que o PL não é dinheiro/caixa, e sim a riqueza residual (Ativo − Passivo).',
          points: 4,
          keywords: [
            ['nao', 'caixa'],
            ['nao', 'dinheiro'],
            ['residual'],
            ['ativo', 'menos', 'passivo'],
          ],
        },
        {
          id: 'c2',
          description: 'Indica que os recursos dos sócios estão aplicados em outros ativos (estoques, máquinas, recebíveis).',
          points: 3,
          keywords: [['aplicad'], ['investid'], ['estoque'], ['maquin']],
        },
        {
          id: 'c3',
          description: 'Conclui que a distribuição depende do caixa disponível (apenas R$ 50 mil) e de obrigações a pagar.',
          points: 3,
          keywords: [['50'], ['distribu', 'caixa'], ['pagar', 'caixa'], ['falta', 'caixa']],
        },
      ],
      seriousErrors: [
        {
          description: 'Afirma que o PL é dinheiro em caixa.',
          patterns: ['pl e o caixa', 'pl e dinheiro em caixa', 'pl esta no caixa', 'patrimonio liquido e o caixa'],
          penalty: 4,
        },
      ],
      modelAnswer:
        'O diretor confunde PL com dinheiro. O PL de R$ 2 milhões não é caixa: é a riqueza residual dos sócios, a diferença entre Ativo e Passivo, e indica apenas quanto do Ativo foi financiado pelos proprietários. Esses recursos estão aplicados em estoques, máquinas e duplicatas a receber. Para distribuir R$ 1 milhão seria preciso ter esse valor em caixa — e há só R$ 50 mil —, além de considerar as obrigações que vencem no curto prazo. Seria necessário vender ativos ou tomar dívida.',
    },
    explanation:
      'O PL está do lado das origens de recursos: diz quem financiou o Ativo, não em que forma o recurso está. Uma empresa pode ter PL alto e quase nenhum dinheiro, porque o capital dos sócios está imobilizado em máquinas, estoques e recebíveis. Decisões de pagamento dependem do Caixa (Ativo) e dos prazos do Passivo.',
    reasoningSteps: [
      'Localize o PL no BP: lado das origens.',
      'Localize o dinheiro: conta Caixa, no Ativo (R$ 50 mil).',
      'Compare o que se quer pagar com o caixa disponível e as obrigações próximas.',
      'Conclua que PL alto não garante liquidez.',
    ],
    commonMistake: 'Tratar o PL como um "saldo bancário dos sócios" disponível para saque.',
    rule: 'Para decidir pagamentos, olhe o Caixa e o prazo das obrigações; o PL mostra de quem é o patrimônio, não onde está o dinheiro.',
    hint: 'Onde está, de fato, o dinheiro da empresa no BP?',
    concept: 'PL não é dinheiro em caixa: é a parte do Ativo que pertence aos proprietários, aplicada em diversos bens e direitos.',
    sourceReference: AULA2_PL,
  },
  {
    id: 'bp-037',
    topic: 'pl',
    subtopic: 'PL não é caixa',
    skill: 'pl-nao-e-caixa',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: 'CASO FICTÍCIO PARA ESTUDO — Cerâmica Monte Alegre Ltda. (indústria de revestimentos)',
    stem: 'Com base no Balanço resumido da Cerâmica Monte Alegre, qual afirmação está correta?',
    table: {
      caption: 'Cerâmica Monte Alegre — Balanço Patrimonial em 31/12',
      note: MIL,
      headers: ['Ativo', 'Valor', 'Passivo + PL', 'Valor'],
      rows: [
        ['Caixa', '40', 'Passivo (fornecedores e empréstimos)', '450'],
        ['Estoques', '300', 'Capital Social', '600'],
        ['Imobilizado', '860', 'Reservas de Lucros', '150'],
        ['Total do Ativo', '1.200', 'Total do Passivo + PL', '1.200'],
      ],
      totalRows: [3],
    },
    options: [
      {
        id: 'A',
        text: 'A empresa pode distribuir hoje R$ 150 mil de Reservas de Lucros em dinheiro, pois esse valor está guardado no PL.',
        whyWrong: 'Reservas não são um "cofre": o lucro retido foi aplicado em ativos. Há só R$ 40 mil em Caixa.',
      },
      {
        id: 'B',
        text: 'O PL de R$ 750 mil indica a parte do Ativo financiada pelos sócios; esses recursos estão aplicados em caixa, estoques e imobilizado.',
      },
      {
        id: 'C',
        text: 'Há um erro no Balanço: com PL de R$ 750 mil, o Caixa deveria ser de pelo menos R$ 750 mil.',
        whyWrong: 'Não existe relação obrigatória entre PL e Caixa. O Balanço fecha (1.200 = 450 + 750) e está coerente.',
      },
      {
        id: 'D',
        text: 'Como o PL é maior que o Passivo, a empresa certamente tem caixa sobrando para pagar suas dívidas.',
        whyWrong: 'Comparar PL com Passivo não informa caixa disponível. A capacidade de pagamento depende do Caixa e dos prazos das obrigações.',
      },
    ],
    correct: 'B',
    balanceCheck: [{ label: 'Cerâmica Monte Alegre 31/12', ativo: 1200, passivo: 450, pl: 750 }],
    explanation:
      'O PL (600 + 150 = 750) mostra a origem de parte dos recursos — os sócios —, não a forma em que eles estão. Somados ao Passivo (450), financiam todo o Ativo de 1.200, que está distribuído em Caixa (40), Estoques (300) e Imobilizado (860). Reservas de Lucros são lucros retidos já reinvestidos; distribuí-las em dinheiro exigiria caixa que a empresa não tem.',
    reasoningSteps: [
      'Calcule o PL: Capital Social + Reservas = 750.',
      'Confira a equação: 450 + 750 = 1.200.',
      'Lembre que o Ativo mostra onde os recursos estão; Passivo e PL mostram de onde vieram.',
      'Avalie cada alternativa: alguma trata o PL como dinheiro?',
    ],
    commonMistake: 'Ler Reservas de Lucros como "dinheiro guardado" e supor que podem ser sacadas a qualquer momento.',
    rule: 'Origem (Passivo + PL) e aplicação (Ativo) são lados diferentes do mesmo valor: nunca procure dinheiro no PL.',
    formula: 'Ativo = Passivo + PL',
    hint: 'Onde estão os R$ 150 mil de lucros retidos agora?',
    concept: 'O PL é fonte de financiamento do Ativo; o dinheiro disponível é só o saldo de Caixa.',
    sourceReference: AULA2_PL,
  },
  {
    id: 'bp-038',
    topic: 'bp',
    subtopic: 'Estados patrimoniais',
    skill: 'bp-estados-patrimoniais',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'multiple-choice',
    stem:
      'Em 31/12, uma empresa apresenta Ativo de R$ 60 mil e Passivo (obrigações com terceiros) de R$ 100 mil. Pelos "estados patrimoniais" vistos em aula, como se descreve essa situação?',
    options: [
      {
        id: 'A',
        text: 'Situação normal: o PL é de R$ 40 mil, pois PL = Passivo − Ativo.',
        whyWrong: 'Inverteu a equação. PL = Ativo − Passivo = 60 − 100 = −40: o PL é negativo, não positivo.',
      },
      {
        id: 'B',
        text: 'O balanço está errado, pois o Passivo nunca pode ser maior que o Ativo.',
        whyWrong: 'Pode, sim. Quando prejuízos acumulados consomem o capital, o Passivo supera o Ativo e o PL fica negativo; a equação continua fechando com PL = −40.',
      },
      {
        id: 'C',
        text: 'Passivo a descoberto: o PL é negativo, PL = −40 (R$ mil), pois os prejuízos acumulados consumiram o capital — situação típica de empresas em recuperação judicial.',
      },
      {
        id: 'D',
        text: 'Situação de equilíbrio: terceiros financiam 100% do Ativo e o PL é zero.',
        whyWrong: 'PL = 0 ocorre quando Ativo = Passivo (a "fronteira entre a saúde e o desequilíbrio"). Aqui o Passivo é maior que o Ativo, então o PL é negativo.',
      },
      {
        id: 'E',
        text: 'Situação-limite teórica: só restam dívidas, pois o Ativo é zero.',
        whyWrong: 'O Ativo não é zero (R$ 60 mil). O estado "Ativo = 0, PL = −Passivo" é outro dos cinco estados, mais extremo que este.',
      },
    ],
    correct: 'C',
    calc: { fn: 'subtrai', args: [60, 100] },
    solution: {
      formula: 'PL = Ativo − Passivo',
      substitution: 'PL = 60 − 100',
      computation: '60 − 100 = −40',
      result: 'PL = −R$ 40 mil (passivo a descoberto)',
      unit: 'R$ mil',
      interpretation: 'Ativo 60 = Passivo 100 + PL (−40): a equação fecha, mas a riqueza dos sócios é negativa — as dívidas superam tudo o que a empresa tem.',
    },
    balanceCheck: [{ label: 'Passivo a descoberto', ativo: 60, passivo: 100, pl: -40 }],
    explanation:
      'Os slides apresentam cinco estados patrimoniais: (1) Ativo > Passivo, PL positivo; (2) Passivo = 0, Ativo = PL; (3) Ativo = Passivo, PL = 0, terceiros financiam 100% do ativo; (4) Passivo > Ativo, PL negativo — o "passivo a descoberto", em que prejuízos acumulados consumiram o capital, típico de empresas em recuperação judicial; (5) Ativo = 0, PL = −Passivo (situação-limite teórica). Com Ativo 60 e Passivo 100, PL = −40: estado 4.',
    reasoningSteps: [
      'Calcule o PL pela equação: PL = Ativo − Passivo.',
      'Leia o sinal: positivo (riqueza própria), zero (fronteira) ou negativo (passivo a descoberto).',
      'Confira que a equação continua fechando mesmo com PL negativo: 60 = 100 + (−40).',
      'Associe ao estado patrimonial correspondente e à sua leitura (prejuízos consumiram o capital).',
    ],
    commonMistake: 'Achar que PL negativo é impossível ou "erro de balanço", ou confundir Passivo > Ativo (PL negativo) com Ativo = Passivo (PL zero).',
    rule: 'PL = Ativo − Passivo: se der negativo, é passivo a descoberto — a equação fecha, mas os sócios já não têm riqueza própria na empresa.',
    formula: 'Ativo = Passivo + PL',
    hint: 'Qual é o sinal de Ativo − Passivo?',
    concept: 'Passivo a descoberto = Passivo maior que o Ativo, com PL negativo; prejuízos acumulados consumiram o capital investido pelos sócios.',
    sourceReference: 'Aula 2 — Os cinco estados patrimoniais; passivo a descoberto (slides)',
  },
];
