import type { Question } from '../../shared/types';

// Aula 3 — Débito e Crédito, Partidas Dobradas, Razão/Razonetes e Balancete.
// Regras da disciplina:
//   ATIVO: aumenta = DÉBITO; diminui = CRÉDITO.
//   PASSIVO e PL: aumentam = CRÉDITO; diminuem = DÉBITO.
//   Receita aumenta o PL (crédito); despesa diminui o PL (débito).

const REF_DC = 'Aula 3 — Débito e Crédito / Partidas Dobradas (resumo da P1)';
const REF_RAZ = 'Aula 3 — Razão e Razonetes (resumo da P1)';
const REF_BAL = 'Aula 3 — Balancete de Verificação (resumo da P1)';

const RULE_NATUREZA =
  'Antes de escolher débito ou crédito, identifique a natureza da conta (Ativo, Passivo ou PL) e se ela aumentou ou diminuiu — nunca pense em entrada ou saída de dinheiro.';

const CONCEPT_DC =
  'Débito e crédito são apenas os dois lados de um lançamento contábil, sem relação com cartão de débito/crédito. Contas de Ativo aumentam por débito; contas de Passivo e PL aumentam por crédito.';

const CTX_OFICINA = 'CASO FICTÍCIO PARA ESTUDO — Oficina Ponto Certo Ltda. (serviços de manutenção automotiva)';
const CTX_COMERCIAL = 'CASO FICTÍCIO PARA ESTUDO — Comercial Ipê Ltda. (comércio de materiais de construção)';
const CTX_ESTUDIO = 'CASO FICTÍCIO PARA ESTUDO — Estúdio Lumen Design Ltda. (serviços de design)';

export const questions: Question[] = [
  // =========================================================================
  // DÉBITO E CRÉDITO (15)
  // =========================================================================
  {
    id: 'dc-001',
    topic: 'debito-credito',
    subtopic: 'Aporte de capital',
    skill: 'dc-natureza-contas',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'Indique, para cada conta envolvida no fato abaixo, se ela deve ser debitada (D) ou creditada (C).',
    operation: 'Os sócios constituem a empresa e integralizam o Capital Social com R$ 80.000 em dinheiro, depositado no caixa da oficina.',
    accounts: [
      { id: 'caixa', label: 'Caixa (Ativo)' },
      { id: 'capital', label: 'Capital Social (PL)' },
    ],
    correct: { caixa: 'D', capital: 'C' },
    explanation:
      'O Caixa é um Ativo e aumentou em R$ 80.000, então é debitado. O Capital Social é conta do Patrimônio Líquido e também aumentou; como PL aumenta por crédito, ele é creditado. O lançamento fecha: R$ 80.000 a débito e R$ 80.000 a crédito.',
    reasoningSteps: [
      'Liste as contas afetadas: Caixa e Capital Social.',
      'Classifique cada uma: Caixa é Ativo; Capital Social é PL.',
      'Veja o movimento: as duas aumentaram.',
      'Aplique a regra: Ativo aumenta = D; PL aumenta = C.',
      'Confira as partidas dobradas: D 80.000 = C 80.000.',
    ],
    commonMistake:
      'Pensar "o dinheiro entrou, então é crédito no Caixa". Entrada de dinheiro no Caixa é aumento de Ativo, ou seja, DÉBITO.',
    rule: RULE_NATUREZA,
    hint: 'Capital Social não é dinheiro guardado: é a fonte de recursos que veio dos sócios. Em que grupo ele fica?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-002',
    topic: 'debito-credito',
    subtopic: 'Compra a prazo',
    skill: 'dc-natureza-contas',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'debit-credit',
    context: CTX_COMERCIAL,
    stem: 'Marque D (débito) ou C (crédito) em cada conta afetada pelo fato contábil.',
    operation: 'Compra de mercadorias para revenda no valor de R$ 25.000, a prazo, com vencimento em 60 dias.',
    accounts: [
      { id: 'estoques', label: 'Estoques de Mercadorias (Ativo)' },
      { id: 'fornecedores', label: 'Fornecedores (Passivo)' },
    ],
    correct: { estoques: 'D', fornecedores: 'C' },
    explanation:
      'A empresa passou a ter mais mercadorias: o Estoque (Ativo) aumentou e é debitado. Ao mesmo tempo, surgiu uma obrigação com o fornecedor: Fornecedores (Passivo) aumentou e é creditado. Nenhum dinheiro saiu ainda, por isso o Caixa não participa deste lançamento.',
    reasoningSteps: [
      'Pergunte: o que a empresa ganhou? Mercadorias (Estoques, Ativo).',
      'Pergunte: qual é a contrapartida? Uma dívida com o fornecedor (Passivo).',
      'Ativo aumentou = D; Passivo aumentou = C.',
      'Verifique se há dinheiro envolvido: "a prazo" significa que o Caixa não muda agora.',
    ],
    commonMistake: 'Incluir o Caixa no lançamento de uma compra a prazo, como se tivesse havido pagamento.',
    rule: RULE_NATUREZA,
    hint: 'Na compra a prazo, o que nasce no lugar da saída de dinheiro?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-003',
    topic: 'debito-credito',
    subtopic: 'Permuta entre ativos',
    skill: 'dc-permuta-ativo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'Classifique cada conta afetada como débito (D) ou crédito (C).',
    operation: 'Compra de um veículo utilitário para atendimento a clientes, por R$ 45.000, pago à vista em dinheiro.',
    accounts: [
      { id: 'veiculos', label: 'Veículos (Ativo Imobilizado)' },
      { id: 'caixa', label: 'Caixa (Ativo)' },
    ],
    correct: { veiculos: 'D', caixa: 'C' },
    explanation:
      'As duas contas são de Ativo, mas se movem em sentidos opostos. Veículos aumentou (débito) e Caixa diminuiu (crédito). É uma troca de um bem por outro dentro do Ativo: o total do Ativo não muda e o PL não é afetado.',
    reasoningSteps: [
      'Identifique as contas: Veículos e Caixa.',
      'As duas são Ativo; agora veja o sentido de cada uma.',
      'Veículos aumentou → débito. Caixa diminuiu → crédito.',
      'Conclua: o Ativo total ficou igual (permuta), nada mudou no Passivo nem no PL.',
    ],
    commonMistake:
      'Pensar "dinheiro saiu = débito no Caixa". Saída de dinheiro é redução de Ativo, portanto CRÉDITO no Caixa.',
    rule: RULE_NATUREZA,
    hint: 'Quando duas contas são do mesmo grupo, o que define D ou C é o sentido do movimento de cada uma.',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-004',
    topic: 'debito-credito',
    subtopic: 'Lançamento 1×n',
    skill: 'dc-partidas-dobradas-composto',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'O fato abaixo gera um lançamento com uma conta de um lado e duas do outro (1×n). Marque D ou C em cada conta.',
    operation:
      'Compra de um guincho por R$ 90.000: R$ 30.000 pagos à vista em dinheiro e R$ 60.000 financiados junto ao fabricante, em parcelas mensais.',
    accounts: [
      { id: 'veiculos', label: 'Veículos (Ativo Imobilizado) — R$ 90.000' },
      { id: 'caixa', label: 'Caixa (Ativo) — R$ 30.000' },
      { id: 'financiamentos', label: 'Financiamentos a Pagar (Passivo) — R$ 60.000' },
    ],
    correct: { veiculos: 'D', caixa: 'C', financiamentos: 'C' },
    explanation:
      'Veículos (Ativo) aumentou R$ 90.000: débito. Essa compra foi paga por duas fontes: parte saiu do Caixa (Ativo diminui, crédito de R$ 30.000) e parte virou dívida (Passivo aumenta, crédito de R$ 60.000). A soma dos créditos (30.000 + 60.000) é igual ao débito de 90.000 — partidas dobradas respeitadas.',
    reasoningSteps: [
      'Identifique o bem adquirido e seu valor total: Veículos, R$ 90.000 (D).',
      'Separe as formas de pagamento: à vista (Caixa) e a prazo (Financiamentos).',
      'Caixa diminuiu → C. Financiamentos aumentou → C.',
      'Confira: Σ débitos (90.000) = Σ créditos (30.000 + 60.000).',
    ],
    commonMistake: 'Debitar o Financiamento porque "a empresa vai pagar depois". Dívida nova é aumento de Passivo: crédito.',
    rule: 'Em lançamentos compostos, classifique cada conta isoladamente pela natureza e pelo sentido do movimento e depois confira se Σ débitos = Σ créditos.',
    hint: 'Some os valores de cada lado. Eles precisam bater.',
    concept:
      'Partidas dobradas: todo fato contábil tem débitos e créditos de mesmo valor total. Um lançamento pode ser 1×1, 1×n (uma conta contra várias) ou n×n.',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-005',
    topic: 'debito-credito',
    subtopic: 'Empréstimo obtido',
    skill: 'dc-natureza-contas',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_COMERCIAL,
    stem: 'Marque D ou C para cada conta.',
    operation: 'A empresa obtém um empréstimo bancário de R$ 50.000, creditado na sua conta corrente, para pagamento em 24 meses.',
    accounts: [
      { id: 'bancos', label: 'Bancos Conta Movimento (Ativo)' },
      { id: 'emprestimos', label: 'Empréstimos Bancários (Passivo)' },
    ],
    correct: { bancos: 'D', emprestimos: 'C' },
    explanation:
      'O saldo em banco (Ativo) aumentou, então é debitado. Em contrapartida, a empresa assumiu uma obrigação com o banco: Empréstimos (Passivo) aumentou e é creditado. Note que o extrato do banco diz "crédito em conta", mas isso é a visão do banco (para ele, o dinheiro do cliente é uma obrigação); na contabilidade da empresa, o Ativo Bancos é DEBITADO.',
    reasoningSteps: [
      'Contas afetadas: Bancos (Ativo) e Empréstimos (Passivo).',
      'Ambas aumentaram.',
      'Ativo aumenta = D; Passivo aumenta = C.',
      'Não use a linguagem do extrato bancário: a regra é a natureza da conta na sua empresa.',
    ],
    commonMistake: 'Copiar o "crédito em conta" do extrato e creditar Bancos. O extrato reflete a contabilidade do banco, não a da empresa.',
    rule: RULE_NATUREZA,
    hint: 'O dinheiro recebido é um bem da empresa (Ativo) ou uma obrigação?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-006',
    topic: 'debito-credito',
    subtopic: 'Pagamento de empréstimo',
    skill: 'dc-baixa-obrigacao',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_COMERCIAL,
    stem: 'Marque D ou C em cada conta (desconsidere juros).',
    operation: 'Pagamento de R$ 10.000 referente a uma parcela do empréstimo bancário, debitada da conta corrente da empresa.',
    accounts: [
      { id: 'emprestimos', label: 'Empréstimos Bancários (Passivo)' },
      { id: 'bancos', label: 'Bancos Conta Movimento (Ativo)' },
    ],
    correct: { emprestimos: 'D', bancos: 'C' },
    explanation:
      'A dívida com o banco diminuiu: Passivo diminui por débito. O saldo bancário (Ativo) também diminuiu: Ativo diminui por crédito. Ativo e Passivo caem no mesmo valor, e o PL não muda — pagar dívida não é despesa.',
    reasoningSteps: [
      'Identifique as contas: Empréstimos (Passivo) e Bancos (Ativo).',
      'As duas diminuíram.',
      'Passivo diminui = D; Ativo diminui = C.',
      'Pergunte se houve consumo de recurso que reduza o PL: o principal da dívida não é despesa.',
    ],
    commonMistake: 'Lançar o pagamento do principal como despesa. Só os juros seriam despesa; o principal apenas baixa a dívida.',
    rule: 'Pagar uma obrigação já registrada baixa o Passivo (débito) e o Ativo usado no pagamento (crédito); não cria despesa nova.',
    hint: 'A dívida aumentou ou diminuiu? Como o Passivo diminui?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-007',
    topic: 'debito-credito',
    subtopic: 'Pagamento de fornecedor',
    skill: 'dc-baixa-obrigacao',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_COMERCIAL,
    stem: 'A mercadoria comprada a prazo há 60 dias (já registrada em Estoques e Fornecedores) agora é paga. Marque D ou C.',
    operation: 'Pagamento, em dinheiro, de R$ 25.000 ao fornecedor de mercadorias.',
    accounts: [
      { id: 'fornecedores', label: 'Fornecedores (Passivo)' },
      { id: 'caixa', label: 'Caixa (Ativo)' },
    ],
    correct: { fornecedores: 'D', caixa: 'C' },
    explanation:
      'O pagamento quita uma obrigação que já existia: Fornecedores (Passivo) diminui, portanto é debitado; Caixa (Ativo) diminui, portanto é creditado. A mercadoria já tinha entrado no Estoque na data da compra; o pagamento não gera nova despesa nem novo estoque.',
    reasoningSteps: [
      'Lembre o que já foi registrado na compra: D Estoques / C Fornecedores.',
      'No pagamento, quais contas mudam? Fornecedores (zera a dívida) e Caixa (sai dinheiro).',
      'Passivo diminui = D; Ativo diminui = C.',
      'Confirme que nenhuma conta de despesa entra no lançamento.',
    ],
    commonMistake: 'Tratar o pagamento ao fornecedor como uma nova despesa (D Despesa / C Caixa), registrando o mesmo gasto duas vezes.',
    rule: 'Pagar uma obrigação já registrada baixa o Passivo (débito) e o Ativo usado no pagamento (crédito); não cria despesa nova.',
    hint: 'O que aconteceu com a dívida com o fornecedor depois do pagamento?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-008',
    topic: 'debito-credito',
    subtopic: 'Recebimento de cliente',
    skill: 'dc-permuta-ativo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'Um serviço prestado no mês anterior (já registrado como receita e como valor a receber) é recebido agora. Marque D ou C.',
    operation: 'Recebimento em dinheiro de R$ 6.000 de um cliente, referente a duplicata de serviço prestado no mês anterior.',
    accounts: [
      { id: 'caixa', label: 'Caixa (Ativo)' },
      { id: 'clientes', label: 'Clientes / Duplicatas a Receber (Ativo)' },
    ],
    correct: { caixa: 'D', clientes: 'C' },
    explanation:
      'O Caixa aumentou (Ativo, débito) e o direito de receber do cliente diminuiu (Ativo, crédito). É uma troca entre ativos: a receita já foi reconhecida quando o serviço foi prestado, então o recebimento não gera nova receita.',
    reasoningSteps: [
      'Identifique o que entrou: dinheiro (Caixa, Ativo).',
      'Identifique o que saiu: o direito de receber (Clientes, Ativo).',
      'Ativo aumenta = D (Caixa); Ativo diminui = C (Clientes).',
      'Verifique se a receita já foi registrada antes: sim, então não há conta de receita aqui.',
    ],
    commonMistake: 'Creditar uma Receita de Serviços no recebimento, contando a mesma receita duas vezes.',
    rule: RULE_NATUREZA,
    hint: 'O direito de receber ainda existe depois que o cliente pagou?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-009',
    topic: 'debito-credito',
    subtopic: 'Receita à vista',
    skill: 'dc-receita-despesa',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'Marque D ou C em cada conta.',
    operation: 'A oficina presta um serviço de revisão e recebe R$ 4.000 à vista, em dinheiro.',
    accounts: [
      { id: 'caixa', label: 'Caixa (Ativo)' },
      { id: 'receita', label: 'Receita de Serviços (Resultado — aumenta o PL)' },
    ],
    correct: { caixa: 'D', receita: 'C' },
    explanation:
      'O Caixa (Ativo) aumentou: débito. A receita representa um aumento do Patrimônio Líquido gerado pela operação; como o PL aumenta por crédito, a Receita de Serviços é creditada.',
    reasoningSteps: [
      'Identifique as contas: Caixa e Receita de Serviços.',
      'Caixa é Ativo e aumentou → D.',
      'Receita aumenta o PL → C.',
      'Confira: D 4.000 = C 4.000.',
    ],
    commonMistake: 'Achar que, como "o dinheiro entrou", o Caixa deve ser creditado.',
    rule: 'Receitas aumentam o PL e por isso são creditadas; despesas diminuem o PL e por isso são debitadas.',
    hint: 'A receita deixa os sócios mais ricos ou mais pobres? Como o PL aumenta?',
    concept: 'Contas de resultado são extensões do PL: receita aumenta o PL (natureza credora) e despesa diminui o PL (natureza devedora).',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-010',
    topic: 'debito-credito',
    subtopic: 'Pagamento de despesa',
    skill: 'dc-receita-despesa',
    dataSource: 'ficticio',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'debit-credit',
    context: CTX_ESTUDIO,
    stem: 'Marque D ou C em cada conta.',
    operation: 'Pagamento em dinheiro dos salários do mês dos designers, no valor de R$ 7.000.',
    accounts: [
      { id: 'despesa', label: 'Despesa de Salários (Resultado — diminui o PL)' },
      { id: 'caixa', label: 'Caixa (Ativo)' },
    ],
    correct: { despesa: 'D', caixa: 'C' },
    explanation:
      'O salário do mês é um consumo de recursos que reduz o PL: Despesa de Salários é debitada. O Caixa (Ativo) diminuiu e é creditado.',
    reasoningSteps: [
      'Identifique as contas: Despesa de Salários e Caixa.',
      'Despesa diminui o PL → D.',
      'Caixa é Ativo e diminuiu → C.',
      'Confira: D 7.000 = C 7.000.',
    ],
    commonMistake: 'Pensar "dinheiro saiu = débito no Caixa". A saída de dinheiro é crédito no Caixa; o débito vai para a despesa.',
    rule: 'Receitas aumentam o PL e por isso são creditadas; despesas diminuem o PL e por isso são debitadas.',
    hint: 'A despesa reduz o PL. Qual lado reduz o PL?',
    concept: 'Contas de resultado são extensões do PL: receita aumenta o PL (natureza credora) e despesa diminui o PL (natureza devedora).',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-011',
    topic: 'debito-credito',
    subtopic: 'Receita a prazo',
    skill: 'dc-receita-despesa',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'debit-credit',
    context: CTX_ESTUDIO,
    stem: 'Marque D ou C em cada conta.',
    operation: 'O estúdio entrega um projeto de identidade visual de R$ 12.000 a um cliente, que pagará em 30 dias.',
    accounts: [
      { id: 'clientes', label: 'Clientes / Duplicatas a Receber (Ativo)' },
      { id: 'receita', label: 'Receita de Serviços (Resultado — aumenta o PL)' },
    ],
    correct: { clientes: 'D', receita: 'C' },
    explanation:
      'O serviço foi prestado, então a receita existe agora, mesmo sem dinheiro: Receita de Serviços é creditada (aumenta o PL). Em troca, a empresa ganhou um direito de receber: Clientes (Ativo) aumenta e é debitado. O Caixa só será movimentado no recebimento.',
    reasoningSteps: [
      'Pergunte se o serviço foi prestado: sim, então há receita agora.',
      'Pergunte o que a empresa recebeu em troca: um direito (Clientes, Ativo).',
      'Ativo aumenta = D; receita aumenta o PL = C.',
      'O Caixa fica de fora: nada foi recebido ainda.',
    ],
    commonMistake: 'Esperar o recebimento para registrar a receita, ou debitar Caixa numa operação a prazo.',
    rule: 'Receitas aumentam o PL e por isso são creditadas; despesas diminuem o PL e por isso são debitadas.',
    hint: 'O que a empresa passou a ter quando entregou o serviço sem receber?',
    concept: 'Contas de resultado são extensões do PL: receita aumenta o PL (natureza credora) e despesa diminui o PL (natureza devedora).',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-012',
    topic: 'debito-credito',
    subtopic: 'Lançamento n×n',
    skill: 'dc-partidas-dobradas-composto',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'debit-credit',
    context: CTX_OFICINA,
    stem: 'Um único documento registra a compra abaixo, gerando um lançamento n×n (várias contas a débito e várias a crédito). Marque D ou C em cada conta.',
    operation:
      'Compra, do mesmo fornecedor, de um elevador automotivo (R$ 40.000) e de peças para estoque (R$ 10.000), total de R$ 50.000: R$ 20.000 pagos à vista em dinheiro e R$ 30.000 a prazo.',
    accounts: [
      { id: 'maquinas', label: 'Máquinas e Equipamentos (Ativo Imobilizado) — R$ 40.000' },
      { id: 'estoques', label: 'Estoque de Peças (Ativo) — R$ 10.000' },
      { id: 'caixa', label: 'Caixa (Ativo) — R$ 20.000' },
      { id: 'fornecedores', label: 'Fornecedores (Passivo) — R$ 30.000' },
    ],
    correct: { maquinas: 'D', estoques: 'D', caixa: 'C', fornecedores: 'C' },
    explanation:
      'Dois ativos aumentaram (Máquinas e Estoque de Peças): ambos a débito, totalizando R$ 50.000. Esse total foi coberto por um Ativo que diminuiu (Caixa, crédito de R$ 20.000) e por um Passivo que aumentou (Fornecedores, crédito de R$ 30.000). Σ débitos = 40.000 + 10.000 = 50.000 = 20.000 + 30.000 = Σ créditos.',
    reasoningSteps: [
      'Separe o que a empresa recebeu (itens adquiridos) de como pagou (caixa e prazo).',
      'Itens adquiridos são Ativos que aumentam → D.',
      'Caixa diminui → C; Fornecedores aumenta → C.',
      'Feche a conta: 50.000 a débito = 50.000 a crédito.',
    ],
    commonMistake: 'Creditar o Caixa por R$ 50.000 (ignorando a parte a prazo) ou lançar o elevador como despesa por ter sido comprado junto com as peças.',
    rule: 'Em lançamentos compostos, classifique cada conta isoladamente pela natureza e pelo sentido do movimento e depois confira se Σ débitos = Σ créditos.',
    hint: 'Quantas contas aumentaram de Ativo? E de onde vieram os recursos?',
    concept:
      'Partidas dobradas: todo fato contábil tem débitos e créditos de mesmo valor total. Um lançamento pode ser 1×1, 1×n (uma conta contra várias) ou n×n.',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-013',
    topic: 'debito-credito',
    subtopic: 'Pegadinha: entrada de dinheiro',
    skill: 'dc-natureza-contas',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Verdadeiro ou falso: "Quando entra dinheiro na empresa, a conta Caixa deve ser creditada, assim como acontece quando recebemos um crédito na conta do cartão."',
    correct: false,
    explanation:
      'Falso. O Caixa é Ativo, e Ativo aumenta por DÉBITO. Débito e crédito em contabilidade são os dois lados do lançamento, sem relação com cartão de débito/crédito ou com o extrato bancário. Quando entra dinheiro, debita-se o Caixa e credita-se a conta de origem (Capital, Receita, Empréstimo, Clientes...).',
    reasoningSteps: [
      'Classifique a conta: Caixa é Ativo.',
      'Defina o movimento: entrada de dinheiro = aumento.',
      'Aplique a regra: Ativo aumenta = débito.',
      'Descarte a analogia com cartão ou extrato: ela não vale na contabilidade da empresa.',
    ],
    commonMistake: 'Usar a linguagem do dia a dia ("caiu um crédito na conta") para decidir o lançamento.',
    rule: RULE_NATUREZA,
    hint: 'Qual é a natureza da conta Caixa?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },
  {
    id: 'dc-014',
    topic: 'debito-credito',
    subtopic: 'Partidas dobradas',
    skill: 'dc-partidas-dobradas-composto',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem:
      'Verdadeiro ou falso: "Em um lançamento com três contas — por exemplo, compra de veículo paga parte à vista e parte a prazo —, a soma dos débitos continua obrigatoriamente igual à soma dos créditos, mesmo que haja um débito e dois créditos."',
    correct: true,
    explanation:
      'Verdadeiro. Pelo método das partidas dobradas, não há débito sem crédito correspondente, e isso vale para o valor total, não para o número de contas. No exemplo, D Veículos 90.000 = C Caixa 30.000 + C Financiamentos 60.000.',
    reasoningSteps: [
      'Lembre o princípio: Σ débitos = Σ créditos em todo lançamento.',
      'Perceba que o princípio compara valores, não quantidade de contas.',
      'Teste com um exemplo numérico de 1×n para confirmar.',
    ],
    commonMistake: 'Achar que partidas dobradas exige o mesmo número de contas a débito e a crédito.',
    rule: 'Partidas dobradas comparam valores: a soma dos débitos sempre iguala a soma dos créditos, qualquer que seja o número de contas (1×1, 1×n ou n×n).',
    hint: 'O que precisa ser igual: a quantidade de contas ou os valores?',
    concept:
      'Partidas dobradas: todo fato contábil tem débitos e créditos de mesmo valor total. Um lançamento pode ser 1×1, 1×n (uma conta contra várias) ou n×n.',
    sourceReference: REF_DC,
  },
  {
    id: 'dc-015',
    topic: 'debito-credito',
    subtopic: 'Identificar erro de lançamento',
    skill: 'dc-baixa-obrigacao',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: CTX_COMERCIAL,
    stem:
      'Em março, a empresa comprou mercadorias a prazo por R$ 18.000 (registrou D Estoques / C Fornecedores). Em abril, ao pagar o fornecedor em dinheiro, o auxiliar lançou: D Despesas com Mercadorias 18.000 / C Caixa 18.000. Qual é o diagnóstico correto?',
    options: [
      {
        id: 'A',
        text: 'O lançamento está correto: todo pagamento em dinheiro gera uma despesa no mês em que ocorre.',
        whyWrong: 'Confunde saída de caixa com despesa. Pagamento de dívida já registrada não reduz o PL; apenas baixa Passivo e Ativo.',
      },
      {
        id: 'B',
        text: 'Errado: o débito deveria ir para Fornecedores. Do jeito que está, a despesa foi registrada indevidamente e a dívida de R$ 18.000 continua aparecendo no Passivo, embora já tenha sido paga.',
      },
      {
        id: 'C',
        text: 'Errado: o correto seria D Caixa / C Fornecedores, pois o dinheiro saiu da empresa.',
        whyWrong: 'Inverte a regra ("dinheiro saiu = débito"). Saída de dinheiro é diminuição de Ativo, logo crédito no Caixa; e Fornecedores diminui, logo débito.',
      },
      {
        id: 'D',
        text: 'Errado: o correto seria D Estoques / C Caixa, porque o pagamento se refere às mercadorias.',
        whyWrong: 'As mercadorias já entraram no Estoque em março. Debitar Estoques de novo duplicaria o estoque e manteria a dívida em aberto.',
      },
      {
        id: 'E',
        text: 'O lançamento está errado apenas porque débitos e créditos não somam o mesmo valor.',
        whyWrong: 'Os valores fecham (18.000 = 18.000). O erro é de escolha de conta (classificação), não de igualdade entre débitos e créditos.',
      },
    ],
    correct: 'B',
    explanation:
      'O pagamento de uma compra a prazo quita uma obrigação já registrada: o lançamento correto é D Fornecedores / C Caixa. Ao debitar uma despesa, o auxiliar reduziu o resultado sem que houvesse novo consumo de recurso e deixou Fornecedores com saldo de R$ 18.000 que não existe mais. Note que o lançamento errado fecha (débito = crédito) — por isso esse erro não aparece no balancete.',
    reasoningSteps: [
      'Reconstrua o que já foi registrado na compra: D Estoques / C Fornecedores.',
      'Pergunte o que mudou no pagamento: sai dinheiro e some a dívida.',
      'Monte o lançamento correto: D Fornecedores (Passivo diminui) / C Caixa (Ativo diminui).',
      'Compare com o lançamento feito e liste os efeitos do erro: despesa indevida e Passivo superavaliado.',
    ],
    commonMistake: 'Tratar o pagamento de fornecedor como nova despesa.',
    rule: 'Pagar uma obrigação já registrada baixa o Passivo (débito) e o Ativo usado no pagamento (crédito); não cria despesa nova.',
    hint: 'Depois do pagamento, quanto a empresa ainda deve ao fornecedor? O lançamento feito mostra isso?',
    concept: CONCEPT_DC,
    sourceReference: REF_DC,
  },

  // =========================================================================
  // RAZONETES (7)
  // =========================================================================
  {
    id: 'dc-016',
    topic: 'razonetes',
    subtopic: 'Saldo da conta Caixa',
    skill: 'razonete-saldo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    type: 'multi-part',
    context: CTX_OFICINA,
    stem: 'A tabela mostra os lançamentos do primeiro mês no razonete da conta Caixa (saldo inicial zero). Responda às partes.',
    table: {
      caption: 'Razonete — Caixa',
      note: 'Valores em R$',
      headers: ['Fato', 'Débito', 'Crédito'],
      rows: [
        ['1. Integralização de capital em dinheiro', '80.000', ''],
        ['2. Compra de veículo à vista', '', '45.000'],
        ['3. Serviço prestado e recebido à vista', '4.000', ''],
        ['4. Pagamento de salários', '', '7.000'],
        ['5. Recebimento de cliente (serviço do mês anterior)', '6.000', ''],
        ['Totais', '90.000', '52.000'],
      ],
      totalRows: [5],
    },
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'Qual é o saldo final da conta Caixa? Responda em R$, sem casas decimais.',
        correct: 38000,
        unit: 'currency',
        decimals: 0,
        points: 6,
        calc: { fn: 'subtrai', args: [90000, 52000] },
        solution: {
          formula: 'Saldo = Σ Débitos − Σ Créditos',
          substitution: '(80.000 + 4.000 + 6.000) − (45.000 + 7.000)',
          computation: '90.000 − 52.000 = 38.000',
          result: 'R$ 38.000',
          unit: 'R$',
          interpretation: 'Os débitos superam os créditos em R$ 38.000: é o dinheiro disponível no Caixa ao fim do mês.',
        },
      },
      {
        id: 'b',
        kind: 'choice',
        prompt: 'Esse saldo é devedor ou credor, e o que ele significa?',
        options: [
          { id: 'A', text: 'Credor: a empresa deve R$ 38.000 a terceiros.', whyWrong: 'Os débitos superam os créditos, então o saldo é devedor; e Caixa é Ativo, não dívida.' },
          { id: 'B', text: 'Devedor: a empresa tem R$ 38.000 disponíveis em caixa (Ativo).' },
          { id: 'C', text: 'Devedor: a empresa deve R$ 38.000 ao banco.', whyWrong: 'Confunde saldo devedor com dívida. Saldo devedor apenas indica que os débitos superam os créditos.' },
          { id: 'D', text: 'Credor: o Caixa aumentou porque entrou dinheiro.', whyWrong: 'Usa a lógica "dinheiro entrou = crédito". Aumento de Ativo é débito.' },
        ],
        correct: 'B',
        points: 4,
      },
    ],
    explanation:
      'No razonete, o saldo é a diferença entre o lado maior e o lado menor. Como os débitos (R$ 90.000) superam os créditos (R$ 52.000), o saldo é devedor de R$ 38.000. Saldo devedor é o saldo normal de uma conta de Ativo e, no caso do Caixa, representa dinheiro disponível — não uma dívida.',
    reasoningSteps: [
      'Some a coluna de débitos (aumentos do Caixa).',
      'Some a coluna de créditos (reduções do Caixa).',
      'Subtraia o menor do maior.',
      'O saldo fica do lado maior: débitos maiores → saldo devedor.',
      'Interprete pela natureza da conta: Ativo com saldo devedor = recurso disponível.',
    ],
    commonMistake: 'Ler "saldo devedor" como "a empresa está devendo".',
    rule: 'Saldo do razonete = lado maior − lado menor, e recebe o nome do lado maior (devedor ou credor); contas de Ativo normalmente têm saldo devedor.',
    formula: 'Saldo = Σ Débitos − Σ Créditos',
    hint: 'Some cada lado separadamente antes de subtrair.',
    concept: 'O razonete (conta em T) é a forma simplificada do Razão: à esquerda os débitos, à direita os créditos; o saldo é a diferença entre os lados.',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-017',
    topic: 'razonetes',
    subtopic: 'Saldo da conta Fornecedores',
    skill: 'razonete-saldo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    type: 'multi-part',
    context: CTX_COMERCIAL,
    stem: 'A tabela mostra o movimento do mês no razonete de Fornecedores (saldo inicial zero). Responda às partes.',
    table: {
      caption: 'Razonete — Fornecedores',
      note: 'Valores em R$',
      headers: ['Fato', 'Débito', 'Crédito'],
      rows: [
        ['1. Compra de mercadorias a prazo', '', '25.000'],
        ['2. Compra de mercadorias a prazo', '', '15.000'],
        ['3. Pagamento a fornecedor', '18.000', ''],
        ['Totais', '18.000', '40.000'],
      ],
      totalRows: [3],
    },
    parts: [
      {
        id: 'a',
        kind: 'numeric',
        prompt: 'Qual é o saldo final de Fornecedores? Responda em R$, sem casas decimais.',
        correct: 22000,
        unit: 'currency',
        decimals: 0,
        points: 6,
        calc: { fn: 'subtrai', args: [40000, 18000] },
        solution: {
          formula: 'Saldo = Σ Créditos − Σ Débitos (lado maior − lado menor)',
          substitution: '(25.000 + 15.000) − 18.000',
          computation: '40.000 − 18.000 = 22.000',
          result: 'R$ 22.000',
          unit: 'R$',
          interpretation: 'A empresa ainda deve R$ 22.000 aos fornecedores.',
        },
      },
      {
        id: 'b',
        kind: 'choice',
        prompt: 'Qual é a natureza desse saldo?',
        options: [
          { id: 'A', text: 'Devedor, porque a conta representa uma dívida.', whyWrong: 'O nome do saldo vem do lado maior do razonete, não da ideia de "dever". Aqui os créditos são maiores.' },
          { id: 'B', text: 'Devedor, porque houve pagamento no mês.', whyWrong: 'O pagamento (débito) foi menor que as compras (créditos); o saldo fica do lado credor.' },
          { id: 'C', text: 'Credor, que é o saldo normal de uma conta de Passivo: obrigação ainda a pagar.' },
          { id: 'D', text: 'Nulo, porque compras e pagamento se anulam.', whyWrong: 'Os valores não se anulam: 40.000 de compras contra 18.000 de pagamentos.' },
        ],
        correct: 'C',
        points: 4,
      },
    ],
    explanation:
      'Compras a prazo aumentam o Passivo (crédito) e pagamentos o reduzem (débito). Com R$ 40.000 a crédito e R$ 18.000 a débito, sobra saldo credor de R$ 22.000 — o saldo normal de uma conta de Passivo, que indica quanto ainda se deve.',
    reasoningSteps: [
      'Lembre a natureza: Fornecedores é Passivo (aumenta a crédito).',
      'Some os créditos (compras) e os débitos (pagamentos).',
      'Subtraia o menor do maior.',
      'Nomeie o saldo pelo lado maior: credor.',
    ],
    commonMistake: 'Chamar de "devedor" o saldo de uma dívida por associar a palavra a "dever".',
    rule: 'Saldo do razonete = lado maior − lado menor, e recebe o nome do lado maior (devedor ou credor); contas de Passivo e PL normalmente têm saldo credor.',
    formula: 'Saldo = lado maior − lado menor',
    hint: 'Qual lado do razonete ficou maior?',
    concept: 'O razonete (conta em T) é a forma simplificada do Razão: à esquerda os débitos, à direita os créditos; o saldo é a diferença entre os lados.',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-018',
    topic: 'razonetes',
    subtopic: 'Saldo de Empréstimos',
    skill: 'razonete-saldo',
    dataSource: 'ficticio',
    difficulty: 'medium',
    cognitiveLevel: 'calculation',
    type: 'numeric',
    context: CTX_COMERCIAL,
    stem:
      'Durante o ano, a empresa: (1) obteve um empréstimo bancário de R$ 100.000; (2) pagou R$ 40.000 de principal; (3) obteve um novo empréstimo de R$ 20.000. Partindo de saldo zero, qual é o saldo credor final da conta Empréstimos Bancários no razonete? Responda em R$, sem casas decimais (desconsidere juros).',
    correct: 80000,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'subtrai', args: [120000, 40000] },
    solution: {
      formula: 'Saldo credor = Σ Créditos − Σ Débitos',
      substitution: '(100.000 + 20.000) − 40.000',
      computation: '120.000 − 40.000 = 80.000',
      result: 'R$ 80.000 (saldo credor)',
      unit: 'R$',
      interpretation: 'A empresa ainda deve R$ 80.000 ao banco; o saldo credor é o normal de uma conta de Passivo.',
    },
    explanation:
      'Empréstimos é Passivo: cada empréstimo obtido aumenta a conta (crédito) e cada pagamento a reduz (débito). Créditos de R$ 120.000 menos débitos de R$ 40.000 deixam saldo credor de R$ 80.000.',
    reasoningSteps: [
      'Classifique a conta: Empréstimos Bancários é Passivo.',
      'Posicione cada fato: obtenções no crédito; pagamento no débito.',
      'Some cada lado: créditos 120.000; débitos 40.000.',
      'Saldo = 120.000 − 40.000, do lado credor.',
    ],
    commonMistake: 'Lançar o empréstimo obtido a débito ("entrou dinheiro") e chegar a um saldo com sinal ou lado invertido.',
    rule: 'Saldo do razonete = lado maior − lado menor, e recebe o nome do lado maior (devedor ou credor); contas de Passivo e PL normalmente têm saldo credor.',
    formula: 'Saldo = Σ Créditos − Σ Débitos (conta de Passivo)',
    hint: 'Em qual lado do razonete do Passivo entram os novos empréstimos?',
    concept: 'O razonete (conta em T) é a forma simplificada do Razão: à esquerda os débitos, à direita os créditos; o saldo é a diferença entre os lados.',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-019',
    topic: 'razonetes',
    subtopic: 'Saldo devedor ≠ dívida',
    skill: 'razonete-saldo',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Verdadeiro ou falso: "Se a conta Caixa apresenta saldo devedor de R$ 38.000, isso significa que a empresa está devendo R$ 38.000."',
    correct: false,
    explanation:
      'Falso. "Saldo devedor" significa apenas que, no razonete, os débitos superam os créditos. Para uma conta de Ativo como o Caixa, esse é o saldo normal e representa dinheiro disponível. Dívidas aparecem em contas de Passivo, que normalmente têm saldo credor.',
    reasoningSteps: [
      'Lembre o que define "devedor": o lado do razonete com maior soma.',
      'Classifique a conta: Caixa é Ativo.',
      'Ativo tem saldo normal devedor e representa um recurso, não uma obrigação.',
    ],
    commonMistake: 'Confundir o termo técnico "saldo devedor" com o sentido coloquial de "estar devendo".',
    rule: '"Devedor" e "credor" indicam apenas o lado maior do razonete; para saber se é recurso ou obrigação, olhe a natureza da conta.',
    hint: 'Em que grupo do Balanço fica o Caixa?',
    concept: 'Saldo devedor: Σ débitos > Σ créditos (normal em Ativo e despesas). Saldo credor: Σ créditos > Σ débitos (normal em Passivo, PL e receitas).',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-020',
    topic: 'razonetes',
    subtopic: 'Sequência de fatos',
    skill: 'razonete-sequencia-fatos',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: CTX_ESTUDIO,
    stem:
      'No primeiro mês, o estúdio registrou os fatos: (1) integralização de capital em dinheiro, R$ 80.000; (2) compra de computadores a prazo, R$ 25.000; (3) serviço prestado e recebido à vista, R$ 12.000; (4) pagamento de salários, R$ 7.000; (5) pagamento de R$ 10.000 ao fornecedor dos computadores; (6) serviço prestado a prazo (recebimento em 30 dias), R$ 9.000. Partindo de saldo zero, qual é o saldo da conta Caixa ao final do mês?',
    options: [
      {
        id: 'A',
        text: 'R$ 84.000 (saldo devedor)',
        whyWrong: 'Incluiu o serviço a prazo (fato 6) como entrada de caixa. Ele gera receita e um direito a receber, mas nenhum dinheiro entrou ainda.',
      },
      {
        id: 'B',
        text: 'R$ 50.000 (saldo devedor)',
        whyWrong: 'Tratou a compra a prazo (fato 2) como saída de dinheiro. Ela movimenta Equipamentos e Fornecedores, não o Caixa.',
      },
      { id: 'C', text: 'R$ 75.000 (saldo devedor)' },
      {
        id: 'D',
        text: 'R$ 85.000 (saldo devedor)',
        whyWrong: 'Ignorou o pagamento ao fornecedor (fato 5), que reduz o Caixa mesmo não sendo despesa.',
      },
      {
        id: 'E',
        text: 'R$ 59.000 (saldo devedor)',
        whyWrong: 'Cometeu dois erros ao mesmo tempo: somou o serviço a prazo e subtraiu a compra a prazo, como se ambos movimentassem dinheiro.',
      },
    ],
    correct: 'C',
    calc: { fn: 'subtrai', args: [92000, 7000, 10000] },
    solution: {
      formula: 'Saldo do Caixa = Σ Débitos − Σ Créditos',
      substitution: '(80.000 + 12.000) − (7.000 + 10.000)',
      computation: '92.000 − 17.000 = 75.000',
      result: 'R$ 75.000, saldo devedor',
      unit: 'R$',
      interpretation: 'Só os fatos 1, 3, 4 e 5 movimentam dinheiro; os fatos 2 e 6 são a prazo e não passam pelo Caixa.',
    },
    explanation:
      'Para montar o razonete do Caixa, selecione apenas os fatos que movimentam dinheiro. Débitos (entradas): capital 80.000 e serviço à vista 12.000. Créditos (saídas): salários 7.000 e pagamento ao fornecedor 10.000. A compra a prazo e o serviço a prazo afetam outras contas (Equipamentos/Fornecedores e Clientes/Receita). Saldo: 92.000 − 17.000 = 75.000, devedor.',
    reasoningSteps: [
      'Para cada fato, pergunte: o dinheiro entrou ou saiu agora?',
      'Descarte as operações a prazo (fatos 2 e 6) do razonete do Caixa.',
      'Coloque entradas no débito e saídas no crédito.',
      'Calcule lado maior − lado menor e nomeie o saldo.',
    ],
    commonMistake: 'Lançar no Caixa operações a prazo, ou esquecer que pagamento de fornecedor reduz o Caixa mesmo não sendo despesa.',
    rule: 'Em um razonete, lance apenas os fatos que realmente alteram aquela conta; operações a prazo movimentam direitos e obrigações, não o Caixa.',
    formula: 'Saldo = Σ Débitos − Σ Créditos',
    hint: 'Quais desses fatos envolveram dinheiro de verdade naquele mês?',
    concept: 'O Razão reúne, conta por conta, todos os lançamentos que a afetam; o razonete é sua forma simplificada em T.',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-021',
    topic: 'razonetes',
    subtopic: 'Plano de contas: sintéticas × analíticas',
    skill: 'razao-plano-contas',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    type: 'multiple-choice',
    stem:
      'No plano de contas de uma empresa, o grupo "Disponível" reúne as contas "Caixa" e "Banco Conta Movimento". Sobre esse arranjo e o Razão (General Ledger), qual afirmação está correta?',
    options: [
      {
        id: 'A',
        text: '"Disponível" é uma conta analítica e recebe os lançamentos do dia a dia; "Caixa" e "Banco" são apenas títulos de agrupamento.',
        whyWrong: 'Inverte os conceitos. A conta que agrupa é a sintética; as que recebem lançamentos são as analíticas.',
      },
      {
        id: 'B',
        text: 'O Razão é o registro em ordem cronológica de todos os fatos da empresa, sem separação por conta.',
        whyWrong: 'Esse é o papel do Diário. O Razão organiza os lançamentos por conta, permitindo apurar o saldo de cada uma.',
      },
      {
        id: 'C',
        text: 'Como "Disponível" é sintética, ela tem natureza credora, enquanto Caixa e Banco são devedoras.',
        whyWrong: 'Uma conta sintética tem a mesma natureza das contas que agrupa. Disponível é Ativo e tem saldo devedor.',
      },
      {
        id: 'D',
        text: '"Disponível" é uma conta sintética: seu saldo é a soma dos saldos de "Caixa" e "Banco Conta Movimento", que são analíticas e recebem os lançamentos.',
      },
      {
        id: 'E',
        text: 'O plano de contas é opcional; cada lançamento pode criar o nome de conta que o auxiliar preferir.',
        whyWrong: 'O plano de contas padroniza nomes, códigos e natureza das contas; sem ele, o Razão e o balancete perdem consistência.',
      },
    ],
    correct: 'D',
    explanation:
      'O plano de contas organiza as contas em níveis. Contas sintéticas (como "Disponível") agrupam e totalizam; contas analíticas (como "Caixa" e "Banco Conta Movimento") são as que recebem os lançamentos. O Razão mostra a movimentação e o saldo de cada conta; o saldo da sintética é a soma das analíticas.',
    reasoningSteps: [
      'Identifique qual conta agrupa e quais são agrupadas.',
      'Lembre: lançamentos vão para as contas analíticas (último nível).',
      'O saldo da sintética é a soma das analíticas e tem a mesma natureza.',
      'Diferencie Razão (por conta) de Diário (por ordem cronológica).',
    ],
    commonMistake: 'Inverter sintética e analítica, ou confundir o Razão com o Diário.',
    rule: 'Lançamentos são feitos nas contas analíticas; as sintéticas apenas somam as analíticas que agrupam, com a mesma natureza.',
    hint: 'Qual das contas é mais detalhada?',
    concept:
      'Plano de contas: lista estruturada e codificada das contas da empresa. Contas sintéticas agrupam; analíticas recebem lançamentos. O Razão (General Ledger) reúne os lançamentos por conta.',
    sourceReference: REF_RAZ,
  },
  {
    id: 'dc-022',
    topic: 'razonetes',
    subtopic: 'Valor faltante no razonete',
    skill: 'razonete-sequencia-fatos',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'numeric',
    context: CTX_COMERCIAL,
    stem:
      'O razonete de Fornecedores tinha saldo inicial credor de R$ 40.000. No mês, houve compras a prazo de R$ 35.000 e alguns pagamentos a fornecedores, cujo total não foi informado. O saldo final é credor de R$ 28.000. Qual foi o total pago aos fornecedores no mês? Responda em R$, sem casas decimais.',
    table: {
      caption: 'Razonete — Fornecedores',
      note: 'Valores em R$',
      headers: ['Movimento', 'Débito', 'Crédito'],
      rows: [
        ['Saldo inicial', '', '40.000'],
        ['Compras a prazo do mês', '', '35.000'],
        ['Pagamentos do mês', '?', ''],
        ['Saldo final (credor)', '', '28.000'],
      ],
      totalRows: [3],
    },
    correct: 47000,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'subtrai', args: [75000, 28000] },
    solution: {
      formula: 'Saldo final credor = Saldo inicial + Créditos − Débitos ⇒ Débitos = Saldo inicial + Créditos − Saldo final',
      substitution: 'Pagamentos = (40.000 + 35.000) − 28.000',
      computation: '75.000 − 28.000 = 47.000',
      result: 'R$ 47.000',
      unit: 'R$',
      interpretation: 'A empresa pagou R$ 47.000 no mês, mais do que comprou a prazo (R$ 35.000) — por isso a dívida com fornecedores caiu de R$ 40.000 para R$ 28.000.',
    },
    explanation:
      'Fornecedores é Passivo: saldo inicial e compras ficam no crédito; pagamentos, no débito. O total do lado credor é 40.000 + 35.000 = 75.000. Para sobrar saldo credor de 28.000, os débitos (pagamentos) precisam somar 75.000 − 28.000 = 47.000.',
    reasoningSteps: [
      'Posicione cada item no lado certo do razonete pela natureza da conta (Passivo).',
      'Escreva a equação do saldo: inicial + aumentos − reduções = final.',
      'Isole a incógnita (pagamentos).',
      'Confira: 40.000 + 35.000 − 47.000 = 28.000.',
    ],
    commonMistake: 'Calcular 35.000 − 28.000 = 7.000, esquecendo o saldo inicial, ou somar o saldo final em vez de subtraí-lo.',
    rule: 'Em qualquer razonete, saldo inicial + aumentos − reduções = saldo final; use essa equação para descobrir o valor que falta.',
    formula: 'Saldo final = Saldo inicial + Aumentos − Reduções',
    hint: 'Monte a equação do saldo final e isole os pagamentos.',
    concept: 'O razonete acumula saldo de um período para o outro: o saldo final de um mês é o inicial do mês seguinte.',
    sourceReference: REF_RAZ,
  },

  // =========================================================================
  // BALANCETE (6)
  // =========================================================================
  {
    id: 'dc-023',
    topic: 'balancete',
    subtopic: 'Ciclo contábil',
    skill: 'razao-plano-contas',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'ordering',
    stem: 'Ordene as etapas do ciclo contábil, da primeira à última.',
    items: [
      { id: 'fato', label: 'Fato contábil' },
      { id: 'lancamento', label: 'Lançamento (débito e crédito)' },
      { id: 'razao', label: 'Razão (registro por conta / razonetes)' },
      { id: 'saldo', label: 'Apuração do saldo de cada conta' },
      { id: 'balancete', label: 'Balancete de verificação' },
      { id: 'demonstracoes', label: 'Demonstrações contábeis (BP, DRE)' },
    ],
    explanation:
      'Tudo começa com um fato que altera o patrimônio. O fato é registrado em um lançamento de débito e crédito, que alimenta o Razão conta por conta. Com o Razão, apura-se o saldo de cada conta; os saldos são listados no balancete, que confere a igualdade devedor = credor; só então se montam as demonstrações.',
    reasoningSteps: [
      'Comece pelo evento econômico: o fato contábil.',
      'O fato vira lançamento; o lançamento alimenta o Razão.',
      'Do Razão saem os saldos; os saldos formam o balancete.',
      'O balancete é a base das demonstrações.',
    ],
    commonMistake: 'Colocar o balancete antes do Razão, como se fosse possível listar saldos antes de apurá-los.',
    rule: 'Fato contábil → Lançamento → Razão → Saldo → Balancete → Demonstrações: cada etapa usa o produto da anterior.',
    hint: 'Cada etapa precisa da informação produzida pela etapa anterior.',
    concept: 'O ciclo contábil transforma fatos em informação: registro (lançamento), organização (Razão), conferência (balancete) e comunicação (demonstrações).',
    sourceReference: REF_BAL,
  },
  {
    id: 'dc-024',
    topic: 'balancete',
    subtopic: 'Limites do balancete',
    skill: 'balancete-limites',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    type: 'true-false',
    stem: 'Verdadeiro ou falso: "Se a soma dos saldos devedores é igual à soma dos saldos credores no balancete, a contabilidade está livre de erros."',
    correct: false,
    explanation:
      'Falso. O balancete só comprova que, em cada lançamento, débitos e créditos tiveram o mesmo valor. Erros como lançar na conta errada (ex.: veículo em Estoques), inverter um lançamento inteiro ou omitir um fato não desfazem essa igualdade e passam despercebidos.',
    reasoningSteps: [
      'Pergunte o que o balancete testa: igualdade entre débitos e créditos.',
      'Imagine um erro que mantenha a igualdade (conta errada, mesmo valor).',
      'Conclua que o balancete detecta erros de valor, não de classificação.',
    ],
    commonMistake: 'Tratar o balancete fechado como prova de que todos os lançamentos estão corretos.',
    rule: 'Balancete fechado garante igualdade de débitos e créditos, não a escolha correta das contas.',
    hint: 'Um lançamento com a conta errada, mas com débito igual ao crédito, desequilibra o balancete?',
    concept: 'O balancete de verificação lista os saldos de todas as contas e confere Σ saldos devedores = Σ saldos credores.',
    sourceReference: REF_BAL,
  },
  {
    id: 'dc-025',
    topic: 'balancete',
    subtopic: 'Valor faltante no balancete',
    skill: 'balancete-igualdade',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'numeric',
    context: CTX_OFICINA,
    stem:
      'O balancete de verificação da oficina ao fim do primeiro mês está abaixo, mas o saldo do Capital Social foi apagado. Sabendo que o balancete está fechado, qual é o saldo do Capital Social? Responda em R$, sem casas decimais.',
    table: {
      caption: 'Balancete de verificação',
      note: 'Valores em R$',
      headers: ['Conta', 'Saldo devedor', 'Saldo credor'],
      rows: [
        ['Caixa', '26.000', ''],
        ['Clientes', '9.000', ''],
        ['Estoque de Peças', '15.000', ''],
        ['Veículos', '60.000', ''],
        ['Fornecedores', '', '20.000'],
        ['Empréstimos Bancários', '', '30.000'],
        ['Capital Social', '', '?'],
        ['Receita de Serviços', '', '21.000'],
        ['Despesa de Salários', '7.000', ''],
        ['Totais', '117.000', '?'],
      ],
      totalRows: [9],
    },
    correct: 46000,
    unit: 'currency',
    decimals: 0,
    calc: { fn: 'subtrai', args: [117000, 20000, 30000, 21000] },
    solution: {
      formula: 'Σ saldos devedores = Σ saldos credores ⇒ Capital = Σ devedores − demais credores',
      substitution: 'Capital = 117.000 − (20.000 + 30.000 + 21.000)',
      computation: '117.000 − 71.000 = 46.000',
      result: 'R$ 46.000 (saldo credor)',
      unit: 'R$',
      interpretation:
        'Com Capital de R$ 46.000, o balancete fecha em R$ 117.000 dos dois lados. Conferência no BP: Ativo 110.000 = Passivo 50.000 + PL 60.000 (46.000 de capital + 14.000 de resultado).',
    },
    balanceCheck: [{ label: 'BP após apurar o resultado (21.000 − 7.000 = 14.000 no PL)', ativo: 110000, passivo: 50000, pl: 60000 }],
    explanation:
      'O balancete fechado exige que o total credor seja igual ao total devedor (R$ 117.000). Os credores conhecidos somam 20.000 + 30.000 + 21.000 = 71.000, então o Capital Social é 117.000 − 71.000 = 46.000. Note que a Despesa de Salários fica entre os devedores (despesa reduz o PL) e a Receita entre os credores (receita aumenta o PL).',
    reasoningSteps: [
      'Confirme a natureza de cada saldo (Ativo e despesa: devedores; Passivo, PL e receita: credores).',
      'Some os saldos devedores: 117.000.',
      'Some os credores conhecidos: 71.000.',
      'Use a igualdade do balancete para achar o valor que falta.',
      'Faça a prova: Ativo = Passivo + PL depois de levar o resultado ao PL.',
    ],
    commonMistake: 'Ignorar a receita e a despesa (contas de resultado) e usar só Ativo − Passivo, obtendo 60.000, que é o PL total já com o lucro, e não o Capital Social.',
    rule: 'Se o balancete está fechado, o valor que falta é a diferença necessária para que Σ saldos devedores = Σ saldos credores.',
    formula: 'Σ saldos devedores = Σ saldos credores',
    hint: 'Comece somando a coluna que está completa.',
    concept: 'O balancete de verificação lista os saldos de todas as contas e confere Σ saldos devedores = Σ saldos credores.',
    sourceReference: REF_BAL,
  },
  {
    id: 'dc-026',
    topic: 'balancete',
    subtopic: 'Erro de classificação',
    skill: 'balancete-limites',
    dataSource: 'ficticio',
    difficulty: 'hard',
    cognitiveLevel: 'analysis',
    type: 'multiple-choice',
    context: CTX_COMERCIAL,
    stem:
      'A Comercial Ipê comprou um caminhão de entregas por R$ 120.000 à vista e o auxiliar lançou: D Estoques de Mercadorias 120.000 / C Caixa 120.000. O balancete do mês fechou (Σ devedores = Σ credores). Qual conclusão está correta?',
    options: [
      {
        id: 'A',
        text: 'Como o balancete fechou, o lançamento está correto.',
        whyWrong: 'Balancete fechado só garante igualdade entre débitos e créditos; não verifica se a conta escolhida é a certa.',
      },
      {
        id: 'B',
        text: 'O erro faz o balancete deixar de fechar em R$ 120.000, por isso será detectado automaticamente.',
        whyWrong: 'O lançamento errado tem débito e crédito de 120.000; a igualdade se mantém e o balancete fecha.',
      },
      {
        id: 'C',
        text: 'O correto seria D Despesa com Veículos / C Caixa, pois o caminhão será usado nas entregas.',
        whyWrong: 'Um veículo que será usado por anos é Ativo Imobilizado, não despesa do mês.',
      },
      {
        id: 'D',
        text: 'O erro só muda nomes de contas e não afeta nenhuma análise.',
        whyWrong: 'A classificação errada distorce o Ativo Circulante e o Imobilizado, afetando indicadores como a Liquidez Corrente e a leitura dos estoques.',
      },
      {
        id: 'E',
        text: 'O lançamento está errado: deveria ser D Veículos (Imobilizado) / C Caixa. O balancete fecha porque o erro é de classificação, mas o Ativo Circulante fica superavaliado e o Imobilizado subavaliado.',
      },
    ],
    correct: 'E',
    explanation:
      'O caminhão é um bem de uso, que não será revendido: pertence ao Imobilizado (Veículos), não aos Estoques. Como o lançamento errado mantém débito = crédito, o balancete fecha normalmente. O efeito do erro aparece na estrutura do BP: Estoques (Ativo Circulante) inflados e Imobilizado subavaliado, o que distorce, por exemplo, a Liquidez Corrente.',
    reasoningSteps: [
      'Classifique o bem pela finalidade: uso (Imobilizado) ou revenda (Estoques)?',
      'Monte o lançamento correto: D Veículos / C Caixa.',
      'Verifique se o erro altera a igualdade débito = crédito: não altera.',
      'Liste o impacto no BP: grupos do Ativo distorcidos.',
    ],
    commonMistake: 'Concluir que balancete fechado significa classificação correta.',
    rule: 'Balancete fechado garante igualdade de débitos e créditos, não a escolha correta das contas.',
    hint: 'O caminhão será revendido pela empresa?',
    concept: 'O balancete de verificação lista os saldos de todas as contas e confere Σ saldos devedores = Σ saldos credores.',
    sourceReference: REF_BAL,
  },
  {
    id: 'dc-027',
    topic: 'balancete',
    subtopic: 'Limites do balancete',
    skill: 'balancete-limites',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'interpretation',
    type: 'short-answer',
    stem: 'Por que um balancete que fecha (Σ saldos devedores = Σ saldos credores) pode conter erro? Explique e dê um exemplo.',
    rubric: {
      criteria: [
        {
          id: 'c1',
          description: 'Explica que o balancete só confere a igualdade entre débitos e créditos (partidas dobradas).',
          points: 4,
          keywords: [
            ['debit', 'credit', 'igua'],
            ['devedor', 'credor', 'igua'],
            ['partidas dobradas'],
            ['debito', 'credito', 'mesmo valor'],
          ],
        },
        {
          id: 'c2',
          description: 'Identifica que erros de classificação/conta errada (ou omissão, inversão) mantêm essa igualdade.',
          points: 3,
          keywords: [['conta errada'], ['classifica'], ['omiss'], ['invert'], ['conta incorreta']],
        },
        {
          id: 'c3',
          description: 'Dá um exemplo concreto (ex.: compra de veículo lançada em Estoques).',
          points: 3,
          keywords: [['veicul', 'estoque'], ['exemplo'], ['ex.'], ['por exemplo']],
        },
      ],
      seriousErrors: [
        { description: 'Afirma que balancete fechado garante ausência de erros.', patterns: ['garante que nao ha erro', 'entao esta tudo correto', 'esta livre de erros'], penalty: 3 },
        { description: 'Confunde débito/crédito com entrada/saída de dinheiro.', patterns: ['dinheiro entrou e credito', 'entrada de dinheiro e credito'], penalty: 2 },
      ],
      modelAnswer:
        'O balancete apenas verifica se a soma dos saldos devedores é igual à soma dos saldos credores, ou seja, se cada lançamento respeitou as partidas dobradas (débito = crédito). Erros que mantêm essa igualdade passam despercebidos: lançar em uma conta errada (erro de classificação), inverter o lançamento inteiro ou omitir um fato. Por exemplo, a compra de um veículo à vista lançada como D Estoques / C Caixa fecha o balancete, mas está errada: o veículo deveria ir para o Imobilizado, e o Ativo Circulante fica superavaliado.',
    },
    explanation:
      'O balancete é um teste de igualdade numérica, não de qualidade da classificação. Qualquer erro em que o débito e o crédito tenham o mesmo valor — conta errada, lançamento invertido, fato omitido ou lançado duas vezes — mantém o balancete fechado. Por isso a análise dos saldos (fazem sentido? a natureza está certa?) continua necessária.',
    reasoningSteps: [
      'Defina o que o balancete testa: Σ devedores = Σ credores.',
      'Pense em erros que não alteram essa igualdade.',
      'Escolha um exemplo simples e mostre o efeito no BP.',
    ],
    commonMistake: 'Responder que "se fechou, está certo".',
    rule: 'Balancete fechado garante igualdade de débitos e créditos, não a escolha correta das contas.',
    hint: 'Pense num lançamento com valor certo, mas na conta errada.',
    concept: 'O balancete de verificação lista os saldos de todas as contas e confere Σ saldos devedores = Σ saldos credores.',
    sourceReference: REF_BAL,
  },
  {
    id: 'dc-028',
    topic: 'balancete',
    subtopic: 'Por que o balancete fecha',
    skill: 'balancete-igualdade',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'interpretation',
    type: 'true-false',
    stem:
      'Verdadeiro ou falso: "Se todos os lançamentos do período respeitaram as partidas dobradas e os saldos foram apurados corretamente nos razonetes, a soma dos saldos devedores do balancete será igual à soma dos saldos credores — com contas como Caixa e Despesas na coluna devedora e Fornecedores, Capital Social e Receitas na coluna credora."',
    correct: true,
    explanation:
      'Verdadeiro. Como cada lançamento tem débitos iguais a créditos, o total debitado em todas as contas é igual ao total creditado; ao apurar os saldos, essa igualdade se transfere para o balancete. Ativos e despesas têm saldo normal devedor; Passivos, PL e receitas têm saldo normal credor.',
    reasoningSteps: [
      'Lembre que cada lançamento tem Σ D = Σ C.',
      'Somando todos os lançamentos, o total de débitos é igual ao de créditos.',
      'Os saldos são diferenças dentro de cada conta, então a igualdade se mantém no total.',
      'Posicione cada conta pela sua natureza (devedora ou credora).',
    ],
    commonMistake: 'Colocar Capital Social ou Fornecedores na coluna devedora por associar "dever" a "devedor".',
    rule: 'Se cada lançamento respeita Σ D = Σ C, o balancete fecha: Ativo e despesas com saldo devedor; Passivo, PL e receitas com saldo credor.',
    hint: 'A igualdade do balancete vem de onde?',
    concept: 'O balancete de verificação lista os saldos de todas as contas e confere Σ saldos devedores = Σ saldos credores.',
    sourceReference: REF_BAL,
  },
];
