import type { Question } from '../../shared/types';

// Questões de RECONHECIMENTO: identificar fórmulas, definições, a pergunta que cada
// indicador responde e o fator de DuPont que muda numa situação descrita.

const SRC = {
  av: 'Aula 4 — Como se analisa uma DRE / BP: A.V. = cada linha ÷ base (slides)',
  ah: 'Aula 4 — Como se analisa uma DRE / BP: A.H. = variação de cada linha entre os anos; convenção |Atual| ÷ |Anterior| − 1 da planilha (slides)',
  avah: 'Aula 4 — Como se analisa uma DRE / BP: A.V. (÷ base) e A.H. (variação) (slides)',
  margens: 'Aula 4 — Margens Bruta, Operacional e Líquida (Padaria São Jorge, Pedal Forte, Renner) (slides)',
  lc: 'Aula 5 — Liquidez Corrente = AC ÷ PC; regra de bolso e leitura da composição (slides)',
  indicadores: 'Aulas 4 e 5 — As perguntas que cada indicador responde (A.H., margens, ROE, LC, giro, alavancagem) (slides)',
  giro: 'Aula 5 — DuPont, fator 2: Giro do Ativo = Receita ÷ Ativo Total (slides)',
  alav: 'Aula 5 — DuPont, fator 3: Alavancagem = Ativo Total ÷ PL (slides)',
  dupont: 'Aula 5 — DuPont: ROE = Margem Líquida × Giro × Alavancagem (a barraca de praia) (slides)',
  dre: 'Aula 4 — Estrutura da DRE em degraus (slides)',
  custo: 'Aula 4 — Custo × Despesa: "o gasto gruda no produto?" (Camisetas Aurora) (slides)',
  comp: 'Aula 4 — Competência × Caixa: "o que manda é o fato gerador" (slides)',
  rf: 'Aula 4 — Resultado financeiro: efeito das dívidas e do caixa (slides)',
  ep: 'Equivalência Patrimonial (possivelmente Aula 6) — conteúdo não localizado nos slides das Aulas 1–5',
  pe: 'Margem de Contribuição e Ponto de Equilíbrio (possivelmente Aula 6) — conteúdo não localizado nos slides das Aulas 1–5',
};

export const questions: Question[] = [
  // ------------------------------------------------------------------ A.V.
  {
    id: 'rec-001',
    type: 'multiple-choice',
    topic: 'av',
    skill: 'av-ah-diferenca',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Qual ferramenta de análise responde à pergunta "Quanto essa conta representa dentro da estrutura?"',
    options: [
      { id: 'A', text: 'Análise Horizontal (A.H.)', whyWrong: 'A A.H. compara a conta com ela mesma em outro período e responde "quanto essa conta cresceu ou caiu?", não o peso dela na estrutura.' },
      { id: 'B', text: 'Análise Vertical (A.V.)' },
      { id: 'C', text: 'Margem Líquida', whyWrong: 'A Margem Líquida mede só quanto da Receita Líquida vira Lucro Líquido; não serve para medir o peso de qualquer conta na estrutura.' },
      { id: 'D', text: 'Liquidez Corrente', whyWrong: 'A Liquidez Corrente compara Ativo Circulante e Passivo Circulante para avaliar folga de curto prazo; não mede participação de uma conta no total.' },
      { id: 'E', text: 'Giro do Ativo', whyWrong: 'O Giro mostra quantos reais de venda cada R$ 1 de Ativo gera; é um indicador de eficiência, não de composição.' },
    ],
    correct: 'B',
    explanation: 'A Análise Vertical divide cada conta por uma base do mesmo período (Ativo Total, Passivo + PL ou Receita Líquida) e mostra quanto ela pesa na estrutura. A Análise Horizontal, ao contrário, compara a mesma conta entre dois períodos. Guardar a pergunta-chave de cada ferramenta evita confundir as duas na prova.',
    reasoningSteps: [
      'Repare na palavra-chave da pergunta: "dentro da estrutura" indica peso/participação.',
      'Peso em relação a um total do mesmo período é Análise Vertical.',
      'Se a pergunta falasse em "cresceu ou caiu", seria Análise Horizontal.',
    ],
    commonMistake: 'Trocar A.V. por A.H., pensando que qualquer análise "em %" é a mesma coisa.',
    rule: 'Peso dentro do total do mesmo período = A.V.; variação da mesma conta entre períodos = A.H.',
    formula: 'A.V. = Conta / Base (Ativo Total, Passivo + PL ou Receita Líquida) × 100',
    hint: 'A pergunta compara a conta com um total ou com ela mesma no passado?',
    concept: 'A Análise Vertical mede a participação de cada conta numa base do mesmo período, revelando a composição do Balanço ou da DRE.',
    sourceReference: SRC.avah,
  },
  {
    id: 'rec-002',
    type: 'true-false',
    topic: 'av',
    skill: 'av-base-correta',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Na Análise Vertical do Balanço Patrimonial, a conta Fornecedores pode ter como base o total de Passivo + PL, que tem o mesmo valor do Ativo Total."',
    correct: true,
    explanation: 'Pela equação fundamental, Ativo = Passivo + PL; logo, o total do lado direito do Balanço é numericamente igual ao Ativo Total. Por isso, na A.V. do Balanço, as contas do Passivo e do PL são divididas pelo total de Passivo + PL, e as do Ativo pelo Ativo Total, que é a mesma cifra. O que não pode é usar uma base de outro período ou da DRE.',
    reasoningSteps: [
      'Lembre a equação Ativo = Passivo + PL.',
      'Identifique a base da A.V. no Balanço: Ativo Total ou Passivo + PL (mesmo valor).',
      'Conclua que a afirmação descreve corretamente a base.',
    ],
    commonMistake: 'Achar que contas do Passivo precisam ser divididas pelo Passivo Total (sem o PL) ou pela Receita Líquida.',
    rule: 'Na A.V. do Balanço a base é o total do lado da conta (Ativo Total = Passivo + PL); na A.V. da DRE a base é a Receita Líquida.',
    formula: 'A.V. = Conta / Ativo Total (ou Passivo + PL) × 100',
    hint: 'Pense na equação fundamental do Balanço.',
    concept: 'A base da A.V. do Balanço é o total do Balanço, que é o mesmo dos dois lados: Ativo Total = Passivo + PL.',
    sourceReference: SRC.av,
  },
  // ------------------------------------------------------------------ A.H.
  {
    id: 'rec-003',
    type: 'multiple-choice',
    topic: 'ah',
    skill: 'ah-sinal',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Qual é a fórmula da Análise Horizontal (A.H.) de uma conta entre dois períodos, conforme a planilha da disciplina?',
    options: [
      { id: 'A', text: '(Atual − Anterior) / Atual × 100', whyWrong: 'Divide pela base errada: a variação deve ser medida em relação ao ponto de partida (período anterior), não ao valor de chegada.' },
      { id: 'B', text: 'Conta / Ativo Total × 100', whyWrong: 'Essa é a Análise Vertical: mede o peso da conta na estrutura, não a variação no tempo.' },
      { id: 'C', text: '(Anterior − Atual) / Anterior × 100', whyWrong: 'Inverte a subtração: uma conta que cresceu apareceria com sinal negativo.' },
      { id: 'D', text: '|Atual| / |Anterior| − 1 (× 100) — que, para valores positivos, é o mesmo que (Atual − Anterior) / Anterior × 100' },
      { id: 'E', text: 'Atual / Anterior × 100', whyWrong: 'Dá o índice do valor atual sobre o anterior (ex.: 125%), não a variação (+25%); faltou subtrair 1 (100%).' },
    ],
    correct: 'D',
    explanation: 'A Análise Horizontal mede quanto a conta cresceu ou caiu em relação ao período anterior, que é a base. A planilha da disciplina usa |Atual| ÷ |Anterior| − 1: para valores positivos é o mesmo que (Atual − Anterior) ÷ Anterior. Para linhas negativas da DRE (custos, despesas, resultado financeiro negativo) ela mede a variação do valor da linha: CPV de (43.615) para (42.864) dá −1,72% (o custo caiu); resultado financeiro de (2.318) para (4.002) dá +72,6% (a despesa financeira cresceu). Quando o sinal muda de um ano para o outro, a A.H. não é significativa ("n.m.").',
    reasoningSteps: [
      'Identifique a pergunta da A.H.: "quanto essa conta cresceu ou caiu?".',
      'Divida o módulo do valor atual pelo módulo do anterior e subtraia 1 — a base é sempre o ponto de partida.',
      'Em linhas negativas, leia o sinal como variação do valor da linha (custo que cai → A.H. negativa).',
      'Se o sinal da linha mudou entre os anos, escreva "n.m." em vez de calcular.',
    ],
    commonMistake: 'Dividir pelo valor atual, inverter a ordem da subtração ou calcular A.H. de uma linha que trocou de sinal.',
    rule: 'Na A.H., divida |atual| por |anterior| e subtraia 1; a base é sempre o anterior, nunca o atual, e sinal trocado = n.m.',
    formula: 'A.H. = |Atual| ÷ |Anterior| − 1 (× 100) — equivale a (Atual − Anterior) ÷ Anterior para valores positivos',
    hint: 'Em relação a qual valor você mede um crescimento?',
    concept: 'A Análise Horizontal mostra a evolução de uma mesma conta no tempo, usando o período anterior como base.',
    sourceReference: SRC.ah,
  },
  {
    id: 'rec-004',
    type: 'true-false',
    topic: 'ah',
    skill: 'av-ah-diferenca',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "A Análise Horizontal responde à pergunta: quanto essa conta representa dentro da estrutura do Balanço ou da DRE?"',
    correct: false,
    explanation: 'Essa é a pergunta da Análise Vertical, que divide a conta por uma base do mesmo período. A Análise Horizontal responde "quanto essa conta cresceu ou caiu?", comparando a mesma conta em dois períodos.',
    reasoningSteps: [
      'Associe "dentro da estrutura" a peso no total do mesmo período (A.V.).',
      'Associe "cresceu ou caiu" a comparação entre períodos (A.H.).',
      'Confronte a pergunta da afirmação com a ferramenta citada.',
    ],
    commonMistake: 'Trocar as perguntas-chave da A.V. e da A.H.',
    rule: 'A.V. = estrutura (peso no total); A.H. = evolução (variação no tempo).',
    formula: 'A.H. = |Atual| ÷ |Anterior| − 1 (× 100) — equivale a (Atual − Anterior) ÷ Anterior para valores positivos',
    hint: 'A palavra "horizontal" lembra que você percorre a linha de um ano para o outro.',
    concept: 'A A.H. compara a mesma conta entre períodos; a A.V. mede o peso da conta num total do mesmo período.',
    sourceReference: SRC.avah,
  },
  // ------------------------------------------------------------------ Margens
  {
    id: 'rec-005',
    type: 'multiple-choice',
    topic: 'margens',
    skill: 'margens-identificar',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Qual é a fórmula da Margem Operacional?',
    options: [
      { id: 'A', text: 'Lucro Operacional / Ativo Total', whyWrong: 'Margem sempre tem a Receita Líquida no denominador; dividir pelo Ativo mede retorno sobre os ativos, não margem.' },
      { id: 'B', text: 'Lucro Bruto / Receita Líquida', whyWrong: 'Essa é a Margem Bruta: considera só o custo das vendas, sem as despesas operacionais.' },
      { id: 'C', text: 'Lucro Líquido / Receita Líquida', whyWrong: 'Essa é a Margem Líquida: inclui também resultado financeiro e IR/CS.' },
      { id: 'D', text: 'Lucro Operacional / Patrimônio Líquido', whyWrong: 'O PL é a base do ROE (com o Lucro Líquido), não de uma margem; margem compara lucro com Receita Líquida.' },
      { id: 'E', text: 'Lucro Operacional / Receita Líquida' },
    ],
    correct: 'E',
    explanation: 'Toda margem responde "de cada R$ 100 de Receita Líquida, quanto sobra em determinado nível da DRE". A Margem Operacional usa o Lucro Operacional (Lucro Bruto − Despesas Operacionais) no numerador e a Receita Líquida no denominador.',
    reasoningSteps: [
      'Lembre que o denominador de toda margem é a Receita Líquida.',
      'Escolha o numerador pelo nome da margem: operacional → Lucro Operacional.',
      'Descarte fórmulas com Ativo ou PL no denominador.',
    ],
    commonMistake: 'Dividir o lucro pelo Ativo ou pelo PL, confundindo margem com rentabilidade.',
    rule: 'Margem = lucro do nível correspondente / Receita Líquida; Ativo e PL nunca são denominador de margem.',
    formula: 'MO = Lucro Operacional / Receita Líquida',
    hint: 'Qual é o denominador comum a todas as margens?',
    concept: 'As margens (bruta, operacional e líquida) mostram quanto da Receita Líquida sobra em cada degrau da DRE.',
    sourceReference: SRC.margens,
  },
  {
    id: 'rec-006',
    type: 'classification',
    topic: 'margens',
    skill: 'margens-identificar',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Associe cada descrição ou fórmula à margem correspondente.',
    items: [
      { id: 'i1', label: 'Quanto sobra da Receita Líquida depois do custo diretamente ligado ao produto vendido' },
      { id: 'i2', label: 'Quanto sobra depois do custo e das despesas operacionais, antes do resultado financeiro e dos tributos' },
      { id: 'i3', label: 'A cada R$ 100 de Receita Líquida, quantos reais viram lucro final para os sócios' },
      { id: 'i4', label: 'Lucro Bruto / Receita Líquida' },
      { id: 'i5', label: 'Lucro Operacional / Receita Líquida' },
      { id: 'i6', label: 'Lucro Líquido / Receita Líquida' },
    ],
    categories: [
      { id: 'mb', label: 'Margem Bruta' },
      { id: 'mo', label: 'Margem Operacional' },
      { id: 'ml', label: 'Margem Líquida' },
    ],
    correct: { i1: 'mb', i2: 'mo', i3: 'ml', i4: 'mb', i5: 'mo', i6: 'ml' },
    explanation: 'As três margens seguem a cascata da DRE. A Margem Bruta para no Lucro Bruto (só o custo foi descontado); a Operacional desconta também as despesas operacionais; a Líquida chega ao fim da DRE, depois do resultado financeiro e do IR/CS. Em todas, o denominador é a Receita Líquida.',
    reasoningSteps: [
      'Localize em que degrau da DRE a descrição para.',
      'Só custo descontado → Bruta; custo + despesas operacionais → Operacional; tudo, até IR/CS → Líquida.',
      'Para as fórmulas, olhe apenas o numerador: o denominador é sempre a Receita Líquida.',
    ],
    commonMistake: 'Colocar despesas administrativas e de vendas na Margem Bruta, ou achar que a Margem Operacional já inclui o resultado financeiro.',
    rule: 'Cada margem tem o nome do lucro que está no numerador; o denominador é sempre a Receita Líquida.',
    formula: 'MB = LB / RL; MO = LO / RL; ML = LL / RL',
    hint: 'Desça a DRE linha a linha e veja onde cada descrição para.',
    concept: 'As margens medem quanto da Receita Líquida sobra depois de cada grupo de gastos da DRE.',
    sourceReference: SRC.margens,
  },
  // ------------------------------------------------------------------ Liquidez
  {
    id: 'rec-007',
    type: 'multiple-choice',
    topic: 'liquidez',
    skill: 'lc-calculo',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Qual é a fórmula da Liquidez Corrente vista na disciplina?',
    options: [
      { id: 'A', text: 'Ativo Circulante / Passivo Circulante' },
      { id: 'B', text: 'Ativo Total / Passivo Total', whyWrong: 'Mistura prazos: inclui bens e dívidas de longo prazo, que não dizem nada sobre a folga dos próximos 12 meses.' },
      { id: 'C', text: 'Ativo Circulante / Passivo Total', whyWrong: 'Compara recursos de curto prazo com todas as dívidas, inclusive as de longo prazo; o denominador correto é só o Passivo Circulante.' },
      { id: 'D', text: 'Passivo Circulante / Ativo Circulante', whyWrong: 'Inverte a fração: a leitura "LC > 1 = folga" deixaria de valer.' },
      { id: 'E', text: 'Ativo Circulante / Patrimônio Líquido', whyWrong: 'O PL é capital dos sócios, não uma obrigação de curto prazo; a LC compara AC com o que vence em até 12 meses.' },
    ],
    correct: 'A',
    explanation: 'A Liquidez Corrente compara recursos que se realizam no curto prazo (Ativo Circulante) com obrigações exigíveis no curto prazo (Passivo Circulante). Por isso usamos AC/PC, e não Ativo Total/Passivo Total: os prazos precisam conversar.',
    reasoningSteps: [
      'Lembre que a LC mede folga de curto prazo.',
      'Escolha numerador e denominador do mesmo horizonte (até 12 meses): AC e PC.',
      'Confira o sentido da fração: o que tenho sobre o que devo.',
    ],
    commonMistake: 'Usar o Passivo Total no denominador ou inverter a fração.',
    rule: 'Liquidez Corrente compara só o circulante com o circulante: AC no numerador, PC no denominador.',
    formula: 'LC = Ativo Circulante / Passivo Circulante',
    hint: 'O índice olha apenas para os próximos 12 meses.',
    concept: 'A Liquidez Corrente indica quantos reais de Ativo Circulante existem para cada R$ 1 de Passivo Circulante.',
    sourceReference: SRC.lc,
  },
  {
    id: 'rec-008',
    type: 'true-false',
    topic: 'liquidez',
    skill: 'lc-regra-didatica',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Pela regra didática vista em aula, Liquidez Corrente igual a 1 indica situação de limite: o Ativo Circulante cobre exatamente o Passivo Circulante."',
    correct: true,
    explanation: 'A regra didática da disciplina é: LC > 1 indica folga, LC = 1 indica limite e LC < 1 indica atenção. Com LC = 1, cada R$ 1 de obrigação de curto prazo tem exatamente R$ 1 de Ativo Circulante. É um ponto de partida: a leitura final ainda depende da composição do AC e do PC e da natureza do negócio.',
    reasoningSteps: [
      'Lembre a régua: > 1 folga; = 1 limite; < 1 atenção.',
      'Traduza LC = 1: AC igual ao PC.',
      'Confira se a afirmação usa o rótulo correto.',
    ],
    commonMistake: 'Chamar LC = 1 de folga, ou tratar a régua como veredito definitivo sobre a empresa.',
    rule: 'LC > 1 folga, = 1 limite, < 1 atenção — e sempre complemente com a composição do circulante.',
    formula: 'LC = Ativo Circulante / Passivo Circulante',
    hint: 'Se AC = PC, sobra ou falta alguma coisa?',
    concept: 'A regra de bolso da LC classifica a folga de curto prazo, mas "nunca leia o número sozinho": caixa e recebíveis valem mais que estoque; um dividendo declarado incha o PC sem ser dívida nova; giro rápido convive bem com índice < 1.',
    sourceReference: SRC.lc,
  },
  // ------------------------------------------------------------------ ROE (indicador → pergunta)
  {
    id: 'rec-009',
    type: 'classification',
    topic: 'roe',
    skill: 'indicador-pergunta-chave',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Associe cada indicador à pergunta que ele responde.',
    items: [
      { id: 'i1', label: 'ROE' },
      { id: 'i2', label: 'Giro do Ativo' },
      { id: 'i3', label: 'Alavancagem' },
      { id: 'i4', label: 'Margem Líquida' },
      { id: 'i5', label: 'Liquidez Corrente' },
      { id: 'i6', label: 'Análise Horizontal (A.H.)' },
    ],
    categories: [
      { id: 'q1', label: 'Para cada R$ 100 de capital próprio, quanto de Lucro Líquido foi gerado?' },
      { id: 'q2', label: 'Quantos reais de venda cada R$ 1 de Ativo gera?' },
      { id: 'q3', label: 'Quanto de Ativo cada R$ 1 dos sócios sustenta?' },
      { id: 'q4', label: 'A cada R$ 100 de Receita Líquida, quantos reais viram Lucro Líquido?' },
      { id: 'q5', label: 'Os recursos de curto prazo cobrem as obrigações de curto prazo?' },
      { id: 'q6', label: 'Quanto essa conta cresceu ou caiu?' },
    ],
    correct: { i1: 'q1', i2: 'q2', i3: 'q3', i4: 'q4', i5: 'q5', i6: 'q6' },
    explanation: 'Cada indicador tem uma pergunta-chave que revela seu numerador e seu denominador. O ROE relaciona Lucro Líquido com PL (capital próprio); o Giro, Receita com Ativo; a Alavancagem, Ativo com PL; a Margem Líquida, Lucro Líquido com Receita Líquida; a Liquidez Corrente, AC com PC; e a A.H. compara a conta com ela mesma no período anterior.',
    reasoningSteps: [
      'Para cada pergunta, identifique o que está sendo comparado com o quê.',
      '"Capital próprio" ou "sócios" aponta para o PL no denominador (ROE ou Alavancagem).',
      'Diferencie: lucro sobre PL = ROE; Ativo sobre PL = Alavancagem.',
      '"Vendas por R$ 1 de Ativo" = Giro; "curto prazo" = Liquidez Corrente; "cresceu ou caiu" = A.H.',
    ],
    commonMistake: 'Confundir ROE com Alavancagem (ambos têm o PL no denominador) ou Giro com Margem (ambos envolvem a Receita).',
    rule: 'Traduza a pergunta-chave em "numerador / denominador" antes de escolher o indicador.',
    formula: 'ROE = LL / PL; Giro = Receita / Ativo; Alavancagem = Ativo / PL; ML = LL / RL; LC = AC / PC',
    hint: 'Olhe o "para cada R$ 1 (ou R$ 100) de…": isso é o denominador.',
    concept: 'O ROE mede o retorno do capital dos sócios; os demais indicadores explicam a estrutura, a eficiência e a folga que ajudam a entendê-lo.',
    sourceReference: SRC.indicadores,
  },
  // ------------------------------------------------------------------ Giro
  {
    id: 'rec-010',
    type: 'true-false',
    topic: 'giro',
    skill: 'giro-calculo',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "O Giro do Ativo é calculado como Receita Líquida / Patrimônio Líquido e mostra quantos reais de venda cada R$ 1 dos sócios gera."',
    correct: false,
    explanation: 'O Giro do Ativo usa o Ativo Total no denominador: Giro = Receita / Ativo Total, e mostra quantos reais de venda cada R$ 1 de Ativo gera. O PL aparece no denominador do ROE e da Alavancagem, não do Giro. A eficiência medida pelo Giro é a de todos os recursos aplicados, venham eles de sócios ou de terceiros.',
    reasoningSteps: [
      'Lembre o nome: Giro "do Ativo" — o Ativo é a base.',
      'Recupere a pergunta-chave: quantos reais de venda cada R$ 1 de Ativo gera.',
      'Identifique o erro de denominador na afirmação (PL no lugar do Ativo).',
    ],
    commonMistake: 'Usar o PL no denominador do Giro, misturando-o com ROE e Alavancagem.',
    rule: 'O nome do indicador costuma dizer a base: Giro do ATIVO = Receita / Ativo Total.',
    formula: 'Giro do Ativo = Receita Líquida / Ativo Total',
    hint: 'De quem é o "giro" no nome do indicador?',
    concept: 'O Giro do Ativo mede a eficiência com que a empresa transforma seus ativos em vendas.',
    sourceReference: SRC.giro,
  },
  // ------------------------------------------------------------------ Alavancagem
  {
    id: 'rec-011',
    type: 'multiple-choice',
    topic: 'alavancagem',
    skill: 'alavancagem-calculo',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Na disciplina, como se calcula a Alavancagem usada na decomposição DuPont?',
    options: [
      { id: 'A', text: 'Patrimônio Líquido / Ativo Total', whyWrong: 'É o inverso da Alavancagem: mostra a fração do Ativo financiada pelos sócios, e não quanto de Ativo cada R$ 1 dos sócios sustenta.' },
      { id: 'B', text: 'Passivo Total / Ativo Total', whyWrong: 'Mede a fração do Ativo financiada por terceiros; não é o fator de Alavancagem que entra no DuPont.' },
      { id: 'C', text: 'Ativo Total / Passivo Total', whyWrong: 'Usa o Passivo (terceiros) no denominador; a Alavancagem compara o Ativo com o capital dos sócios (PL).' },
      { id: 'D', text: 'Ativo Total / Patrimônio Líquido' },
      { id: 'E', text: 'Passivo Circulante / Patrimônio Líquido', whyWrong: 'Considera só as dívidas de curto prazo e as compara com o PL; não é a medida de Alavancagem do DuPont.' },
    ],
    correct: 'D',
    explanation: 'A Alavancagem responde "quanto de Ativo cada R$ 1 dos sócios sustenta" e é calculada como Ativo Total / PL. Quanto maior o índice, maior a parte do Ativo financiada por terceiros. É esse fator que, multiplicado por Margem Líquida e Giro, recompõe o ROE.',
    reasoningSteps: [
      'Lembre a pergunta-chave: Ativo sustentado por R$ 1 dos sócios.',
      'Numerador = Ativo Total; denominador = PL.',
      'Confira: ML × Giro × Alavancagem = (LL/RL) × (RL/Ativo) × (Ativo/PL) = LL/PL.',
    ],
    commonMistake: 'Colocar o Passivo no lugar do PL, ou inverter a fração.',
    rule: 'Alavancagem = Ativo Total / PL; só assim a DuPont fecha em LL / PL.',
    formula: 'Alavancagem = Ativo Total / Patrimônio Líquido',
    hint: 'Monte a DuPont e veja o que precisa cancelar para sobrar LL / PL.',
    concept: 'A Alavancagem mostra quanto do Ativo é sustentado por cada real dos sócios; o restante vem de capital de terceiros.',
    sourceReference: SRC.alav,
  },
  {
    id: 'rec-012',
    type: 'true-false',
    topic: 'alavancagem',
    skill: 'alavancagem-interpretacao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Uma Alavancagem (Ativo Total / PL) de 1,0x indica que todo o Ativo da empresa está financiado pelo Patrimônio Líquido, sem passivos com terceiros."',
    correct: true,
    explanation: 'Se Ativo / PL = 1, então Ativo = PL. Pela equação Ativo = Passivo + PL, o Passivo é zero. Qualquer Alavancagem acima de 1 indica que parte do Ativo é financiada por terceiros; por exemplo, 2,0x significa que metade do Ativo vem de terceiros.',
    reasoningSteps: [
      'Traduza 1,0x: Ativo = PL.',
      'Aplique Ativo = Passivo + PL e isole o Passivo.',
      'Conclua que o Passivo é nulo.',
    ],
    commonMistake: 'Achar que Alavancagem 1,0x significa "metade sócios, metade terceiros".',
    rule: 'Alavancagem = 1 → só capital próprio; quanto mais acima de 1, maior a participação de terceiros no Ativo.',
    formula: 'Alavancagem = Ativo Total / PL',
    hint: 'Use a equação fundamental do Balanço.',
    concept: 'Alavancagem igual a 1,0 = 100% capital próprio; sobe conforme fornecedores e dívida financiam parte do ativo. Amplia o ROE quando a operação rende mais do que custa o dinheiro de terceiros.',
    sourceReference: SRC.alav,
  },
  // ------------------------------------------------------------------ DuPont
  {
    id: 'rec-013',
    type: 'multiple-choice',
    topic: 'dupont',
    skill: 'dupont-fator-situacao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Uma loja renegocia com seus fornecedores e reduz o custo das mercadorias vendidas, mantendo preço, volume de vendas, Ativo Total e Patrimônio Líquido inalterados. Qual fator da decomposição DuPont muda?',
    options: [
      { id: 'A', text: 'Somente o Giro do Ativo', whyWrong: 'O Giro é Receita / Ativo; nem a receita nem o Ativo mudaram.' },
      { id: 'B', text: 'Somente a Alavancagem', whyWrong: 'A Alavancagem é Ativo / PL, e ambos foram mantidos; a renegociação não altera a estrutura de financiamento.' },
      { id: 'C', text: 'Somente a Margem Líquida' },
      { id: 'D', text: 'Giro do Ativo e Alavancagem', whyWrong: 'Nenhum dos dois tem o custo das mercadorias na fórmula; com receita, Ativo e PL constantes, ambos ficam iguais.' },
      { id: 'E', text: 'Nenhum: a receita não mudou, então o ROE fica igual', whyWrong: 'O custo menor aumenta o Lucro Líquido mesmo com receita igual; logo a Margem Líquida e o ROE sobem.' },
    ],
    correct: 'C',
    explanation: 'Custo menor com preço e volume iguais aumenta o Lucro Bruto e, mantido o resto, o Lucro Líquido. Como a Receita Líquida não mudou, a Margem Líquida (LL/RL) sobe. Giro (Receita/Ativo) e Alavancagem (Ativo/PL) não têm o custo em suas fórmulas e ficam iguais. O ROE sobe pela margem.',
    reasoningSteps: [
      'Identifique qual linha das demonstrações mudou: o custo (DRE).',
      'Veja quais fatores do DuPont contêm o lucro: só a Margem Líquida.',
      'Confira que Receita, Ativo e PL ficaram constantes: Giro e Alavancagem não mudam.',
    ],
    commonMistake: 'Achar que, se a receita não mudou, nada muda no ROE.',
    rule: 'Mudanças em custos e despesas mexem na Margem; mudanças no tamanho do Ativo mexem no Giro; mudanças no financiamento (dívida × PL) mexem na Alavancagem.',
    formula: 'ROE = ML × Giro × Alavancagem = (LL/RL) × (RL/Ativo) × (Ativo/PL)',
    hint: 'Em qual dos três fatores o custo das mercadorias aparece?',
    concept: 'A DuPont separa o ROE em eficiência de preço/custos (Margem), eficiência no uso dos ativos (Giro) e estrutura de capital (Alavancagem).',
    sourceReference: SRC.dupont,
  },
  {
    id: 'rec-014',
    type: 'multiple-choice',
    topic: 'dupont',
    skill: 'dupont-fator-situacao',
    dataSource: 'conceitual',
    difficulty: 'hard',
    cognitiveLevel: 'recognition',
    stem: 'Uma empresa toma um empréstimo de longo prazo e usa todo o dinheiro, no mesmo dia, para pagar dividendos extraordinários aos sócios. Desconsidere os juros do período e suponha vendas e Lucro Líquido inalterados. Como ficam os fatores da decomposição DuPont?',
    options: [
      { id: 'A', text: 'A Margem Líquida sobe, porque a empresa recebeu dinheiro do empréstimo', whyWrong: 'Empréstimo não é receita nem lucro: entra no Passivo. Como LL e RL não mudam, a margem fica igual.' },
      { id: 'B', text: 'O Giro do Ativo cai, porque o empréstimo aumentou o Ativo', whyWrong: 'O caixa entrou com o empréstimo e saiu no mesmo dia com os dividendos; o Ativo Total termina igual, e o Giro não muda.' },
      { id: 'C', text: 'Giro e Alavancagem sobem juntos', whyWrong: 'O Giro (Receita/Ativo) não muda, porque nem a receita nem o Ativo mudaram; só a relação Ativo/PL se altera.' },
      { id: 'D', text: 'Nenhum fator muda, pois o Lucro Líquido não mudou', whyWrong: 'O PL diminuiu com os dividendos: com o mesmo Ativo, a Alavancagem (Ativo/PL) sobe, e o ROE também.' },
      { id: 'E', text: 'Somente a Alavancagem aumenta; Margem Líquida e Giro permanecem iguais' },
    ],
    correct: 'E',
    explanation: 'O empréstimo aumenta Caixa e Passivo; o pagamento de dividendos reduz Caixa e PL. No saldo, o Ativo Total fica igual, o Passivo sobe e o PL cai. Com LL e Receita constantes, Margem Líquida e Giro não mudam; a Alavancagem (Ativo/PL) sobe porque o PL ficou menor. O ROE aumenta só pela estrutura de capital, não por eficiência operacional — e com mais risco.',
    reasoningSteps: [
      'Registre os dois fatos no Balanço: empréstimo (Caixa ↑, Passivo ↑) e dividendos (Caixa ↓, PL ↓).',
      'Some os efeitos: Ativo igual, Passivo maior, PL menor.',
      'Avalie fator a fator: ML (LL/RL), Giro (RL/Ativo), Alavancagem (Ativo/PL).',
      'Conclua que apenas a Alavancagem muda.',
    ],
    commonMistake: 'Tratar o empréstimo como aumento líquido do Ativo ou como ganho de margem, e não perceber a queda do PL.',
    rule: 'Antes de dizer qual fator mudou, faça o efeito líquido no Balanço e na DRE e confira o numerador e o denominador de cada fator.',
    formula: 'ROE = ML × Giro × Alavancagem; Alavancagem = Ativo Total / PL',
    hint: 'O que acontece com o Caixa ao final do dia? E com o PL?',
    concept: 'Operações de financiamento e distribuição aos sócios mexem na estrutura de capital (Alavancagem) sem melhorar a operação.',
    sourceReference: SRC.dupont,
  },
  // ------------------------------------------------------------------ DRE
  {
    id: 'rec-015',
    type: 'multiple-choice',
    topic: 'dre',
    skill: 'dre-estrutura',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Na estrutura da DRE vista em aula, qual item faz a passagem do Lucro Operacional para o Lucro antes do IR/CS (LAIR)?',
    options: [
      { id: 'A', text: 'Custo das Vendas', whyWrong: 'O Custo das Vendas é deduzido da Receita Líquida para chegar ao Lucro Bruto, bem acima do Lucro Operacional.' },
      { id: 'B', text: 'Resultado Financeiro (receitas financeiras − despesas financeiras)' },
      { id: 'C', text: 'Despesas Operacionais (administrativas e de vendas)', whyWrong: 'As Despesas Operacionais levam do Lucro Bruto ao Lucro Operacional; elas já foram descontadas quando se chega ao Lucro Operacional.' },
      { id: 'D', text: 'IR/CS', whyWrong: 'O IR/CS é deduzido do LAIR para chegar ao Lucro Líquido; não pode estar antes do LAIR.' },
      { id: 'E', text: 'Deduções da Receita Bruta', whyWrong: 'As deduções levam da Receita Bruta à Receita Líquida, no topo da DRE.' },
    ],
    correct: 'B',
    explanation: 'A DRE da disciplina segue a cascata: Receita Líquida − Custo = Lucro Bruto; − Despesas Operacionais = Lucro Operacional; ± Resultado Financeiro = LAIR; − IR/CS = Lucro Líquido. O Resultado Financeiro fica entre a operação e os tributos, o que permite perguntar se o lucro veio da operação ou foi ajudado/prejudicado pelo financeiro.',
    reasoningSteps: [
      'Escreva a cascata da DRE de cima para baixo.',
      'Localize o Lucro Operacional e a linha seguinte.',
      'Identifique o item que separa os dois subtotais.',
    ],
    commonMistake: 'Colocar o resultado financeiro antes do Lucro Operacional, misturando operação com financiamento.',
    rule: 'Operação primeiro (custo e despesas operacionais), depois financeiro, depois tributos.',
    formula: 'LAIR = Lucro Operacional ± Resultado Financeiro',
    hint: 'O que separa a operação dos tributos?',
    concept: 'A ordem da DRE separa o resultado da operação do efeito das decisões de financiamento e dos tributos.',
    sourceReference: SRC.dre,
  },
  // ------------------------------------------------------------------ Custo × Despesa
  {
    id: 'rec-016',
    type: 'true-false',
    topic: 'custo-despesa',
    skill: 'custo-despesa-classificar',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Numa fábrica de calçados, a comissão paga aos vendedores é custo, porque só existe quando o produto é vendido."',
    correct: false,
    explanation: 'A pergunta da aula é: "Esse gasto gruda diretamente no produto?". A comissão remunera o esforço de vender, não a fabricação do calçado; ela não integra o produto. Por isso é despesa operacional (de vendas), deduzida depois do Lucro Bruto. Custos são gastos como couro, solado e mão de obra da produção.',
    reasoningSteps: [
      'Aplique a pergunta: o gasto gruda diretamente no produto?',
      'Veja se o gasto ocorre na fabricação ou na venda/administração.',
      'Gasto de vender → despesa de vendas; gasto de fabricar → custo.',
    ],
    commonMistake: 'Achar que tudo o que varia com as vendas é custo.',
    rule: 'Se o gasto não gruda diretamente no produto (vender, administrar), é despesa, mesmo que acompanhe o volume de vendas.',
    hint: 'A comissão faz parte do sapato?',
    concept: 'Custo está ligado à produção do bem vendido; despesa sustenta a estrutura de vendas e administração.',
    sourceReference: SRC.custo,
  },
  // ------------------------------------------------------------------ Competência × Caixa
  {
    id: 'rec-017',
    type: 'multiple-choice',
    topic: 'competencia-caixa',
    skill: 'competencia-lucro-caixa',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Qual alternativa descreve corretamente o regime de competência, usado na DRE?',
    options: [
      { id: 'A', text: 'Receitas e despesas são reconhecidas no período em que ocorrem, independentemente de quando o dinheiro é recebido ou pago.' },
      { id: 'B', text: 'Receitas e despesas são reconhecidas quando o dinheiro entra ou sai do caixa.', whyWrong: 'Essa é a definição do regime de caixa, que é a lógica da DFC ("filme do caixa"), não da DRE.' },
      { id: 'C', text: 'As receitas são reconhecidas quando a venda ocorre, mas as despesas só quando são pagas.', whyWrong: 'Mistura os dois regimes; pela competência, despesas também vão para o período em que ocorrem (ex.: salário de setembro pago em outubro é despesa de setembro).' },
      { id: 'D', text: 'É o regime usado na DFC, enquanto a DRE segue o regime de caixa.', whyWrong: 'Inverte as demonstrações: DRE = competência; DFC = caixa.' },
      { id: 'E', text: 'Uma venda a prazo só vira receita quando o cliente paga a duplicata.', whyWrong: 'Pela competência, a venda a prazo é receita no momento da venda; o recebimento depois só baixa a conta a receber.' },
    ],
    correct: 'A',
    explanation: 'No regime de competência, o que define o período é a ocorrência do fato (venda realizada, serviço consumido), e não a movimentação do dinheiro. Por isso uma venda a prazo é receita no mês da venda e o salário de setembro é despesa de setembro, mesmo pago em outubro. É daí que vem a máxima "lucro não é caixa".',
    reasoningSteps: [
      'Lembre a dupla: DRE = competência (filme do resultado); DFC = caixa (filme do caixa).',
      'Pergunte: quando o fato ocorreu? Esse é o período da receita ou despesa.',
      'Descarte alternativas que dependem da data do recebimento ou do pagamento.',
    ],
    commonMistake: 'Associar receita a dinheiro recebido e despesa a dinheiro pago.',
    rule: 'Na DRE, pergunte "quando aconteceu?", e não "quando o dinheiro entrou ou saiu?".',
    hint: 'Pense na venda a prazo de 60 dias: em que mês ela aparece na DRE?',
    concept: 'O regime de competência reconhece receitas e despesas no período em que ocorrem; o regime de caixa, quando há entrada ou saída de dinheiro.',
    sourceReference: SRC.comp,
  },
  // ------------------------------------------------------------------ Resultado Financeiro
  {
    id: 'rec-018',
    type: 'true-false',
    topic: 'resultado-financeiro',
    skill: 'rf-composicao',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Rendimentos de aplicações financeiras e juros pagos sobre empréstimos bancários compõem o Resultado Financeiro, que na DRE aparece depois do Lucro Operacional e antes do LAIR."',
    correct: true,
    explanation: 'O Resultado Financeiro é a diferença entre receitas financeiras (rendimentos de aplicações, juros recebidos) e despesas financeiras (juros de empréstimos e financiamentos). Na DRE, ele é somado ou subtraído do Lucro Operacional para chegar ao LAIR. Essa separação permite ver se o lucro veio da operação ou foi ajudado/prejudicado pelo financeiro.',
    reasoningSteps: [
      'Classifique cada item: rendimento de aplicação = receita financeira; juros de empréstimo = despesa financeira.',
      'Lembre a posição do Resultado Financeiro: entre Lucro Operacional e LAIR.',
      'Confira se a afirmação respeita as duas coisas.',
    ],
    commonMistake: 'Tratar juros de empréstimos como despesa operacional, ou rendimentos de aplicação como receita de vendas.',
    rule: 'O que vem de aplicar ou captar dinheiro vai para o Resultado Financeiro, abaixo do Lucro Operacional.',
    formula: 'Resultado Financeiro = Receitas Financeiras − Despesas Financeiras',
    hint: 'Esses itens nascem da operação ou do financiamento/aplicação de recursos?',
    concept: 'O Resultado Financeiro reúne ganhos e custos ligados a aplicações e dívidas, separados do resultado da operação.',
    sourceReference: SRC.rf,
  },
  // ------------------------------------------------------------------ Equivalência Patrimonial
  {
    id: 'rec-019',
    type: 'true-false',
    topic: 'equivalencia',
    skill: 'ep-conceito',
    dataSource: 'conceitual',
    difficulty: 'medium',
    cognitiveLevel: 'recognition',
    stem: 'Julgue: "Se a empresa investida apurar prejuízo no ano, a investidora não registra nada na sua DRE, porque a equivalência patrimonial só reconhece a parte dos lucros da investida."',
    correct: false,
    explanation: 'A equivalência patrimonial reconhece a parte da investidora no resultado da investida: resultado da investida × % de participação. Se o resultado é lucro, a equivalência é positiva; se é prejuízo, é negativa e reduz o resultado da investidora (e o valor do investimento). Não há assimetria: lucro e prejuízo são reconhecidos proporcionalmente.',
    reasoningSteps: [
      'Lembre a fórmula: resultado da investida × % de participação.',
      'Note que "resultado" pode ser positivo ou negativo.',
      'Conclua que prejuízo gera equivalência negativa na DRE da investidora.',
    ],
    commonMistake: 'Achar que a equivalência só aparece quando há lucro ou dividendos.',
    rule: 'Equivalência patrimonial acompanha o resultado da investida, para cima ou para baixo, na proporção da participação.',
    formula: 'Equivalência Patrimonial = Resultado da investida × % de participação',
    hint: 'A fórmula usa "lucro" ou "resultado" da investida?',
    concept: 'Pela equivalência patrimonial, a investidora reconhece sua fatia do resultado (lucro ou prejuízo) das empresas em que tem participação relevante.',
    sourceReference: SRC.ep,
  },
  // ------------------------------------------------------------------ MC e PE
  {
    id: 'rec-020',
    type: 'multiple-choice',
    topic: 'mc-pe',
    skill: 'pe-calculo',
    dataSource: 'conceitual',
    difficulty: 'easy',
    cognitiveLevel: 'recognition',
    stem: 'Qual é a fórmula do Ponto de Equilíbrio (em unidades) vista em aula?',
    options: [
      { id: 'A', text: 'Gastos Fixos / Preço de venda unitário', whyWrong: 'Divide os fixos pelo preço inteiro, ignorando que parte de cada venda é consumida pelo custo variável; subestima o PE.' },
      { id: 'B', text: 'Gastos Fixos / Custo variável unitário', whyWrong: 'O custo variável não "paga" os fixos; o que sobra para cobri-los é a margem de contribuição (Preço − CV).' },
      { id: 'C', text: 'Gastos Fixos / (Preço − Custo variável unitário)' },
      { id: 'D', text: '(Preço − Custo variável unitário) / Gastos Fixos', whyWrong: 'Inverte a fração: o resultado não seria uma quantidade de unidades.' },
      { id: 'E', text: 'Gastos Fixos × Margem de Contribuição unitária', whyWrong: 'Multiplicar não faz sentido: queremos saber quantas margens unitárias são necessárias para cobrir os fixos, o que exige dividir.' },
    ],
    correct: 'C',
    explanation: 'Cada unidade vendida deixa uma Margem de Contribuição (Preço − Custo variável) para cobrir os gastos fixos. O Ponto de Equilíbrio é a quantidade em que a soma das margens iguala os fixos: PE = Fixos / MCu. No exemplo da água (P = 2, CV = 1, Fixos = 1.000), PE = 1.000 unidades.',
    reasoningSteps: [
      'Calcule o que sobra por unidade: MCu = Preço − CV.',
      'Pergunte quantas MCu são necessárias para cobrir os fixos.',
      'Divida os fixos pela MCu.',
    ],
    commonMistake: 'Dividir os fixos pelo preço de venda, esquecendo o custo variável.',
    rule: 'Ponto de Equilíbrio = Fixos / Margem de Contribuição unitária, nunca Fixos / Preço.',
    formula: 'PE = Gastos Fixos / (Preço − CV unitário)',
    hint: 'Quanto de cada venda sobra, de fato, para pagar os fixos?',
    concept: 'A Margem de Contribuição unitária é o que cada unidade deixa para cobrir os gastos fixos; o Ponto de Equilíbrio é o volume que zera o resultado.',
    sourceReference: SRC.pe,
  },
];
