// DADOS REAIS — Lojas Renner S.A., demonstrações consolidadas 2025 × 2024.
// FONTE: slides da Aula 4 ("Caso real — a DRE da Renner"; "Renner — ATIVO / PASSIVO + PL 2025 × 2024"),
// que citam Lojas Renner S.A., Release de Resultados 4T25 (ri.lojasrenner.com.br). Valores em R$ milhões.
// O slide registra o ROE 2025 da Renner em 13,9% (= 1.457,6 ÷ 10.456,1).

export const RENNER_SOURCE =
  'REAL — Lojas Renner S.A., DFs consolidadas 2025 × 2024 (slides da Aula 4; Release de Resultados 4T25). Valores em R$ milhões.';

export const RENNER = {
  dre: {
    2025: {
      vendaMercadorias: 13810.0,
      vendaServicos: 2019.5,
      receitaLiquida: 15829.5,
      custoVendas: -6061.6,
      lucroBruto: 9767.9,
      despesasVendas: -3359.4,
      despesasAdministrativas: -1560.8,
      depreciacoes: -1246.0,
      perdasCredito: -950.5,
      outrosOperacionais: -854.0,
      lucroOperacional: 1797.2,
      resultadoFinanceiro: -82.5,
      irCs: -257.1,
      lucroLiquido: 1457.6,
    },
    2024: {
      vendaMercadorias: 12629.9,
      vendaServicos: 1806.5,
      receitaLiquida: 14436.4,
      custoVendas: -5694.4,
      lucroBruto: 8741.9,
      despesasVendas: -3119.4,
      despesasAdministrativas: -1446.8,
      depreciacoes: -1197.8,
      perdasCredito: -957.3,
      outrosOperacionais: -761.3,
      lucroOperacional: 1259.3,
      resultadoFinanceiro: 61.7,
      irCs: -124.3,
      lucroLiquido: 1196.7,
    },
  },
  bp: {
    2025: {
      ativoTotal: 19625.9,
      ativoCirculante: 11633.6,
      caixa: 978.1,
      aplicacoesFinanceiras: 924.7,
      contasReceber: 7175.2,
      estoques: 1865.9,
      tributosRecuperar: 470.0,
      irCsRecuperar: 122.7,
      derivativos: 7.9,
      outrosAC: 89.1,
      ativoNaoCirculante: 7992.3,
      tributosRecuperarLP: 368.7,
      irCsDiferidos: 741.9,
      irCsRecuperarLP: 32.3,
      outrosANC: 177.5,
      investimentos: 55.1,
      imobilizado: 2929.2,
      direitoUso: 2076.6,
      intangivel: 1611.0,
      passivoCirculante: 6866.7,
      emprestimosDebentures: 0.0,
      financiamentosServFin: 21.1,
      arrendamentos: 740.2,
      fornecedores: 1774.4,
      riscoSacado: 41.2,
      administradorasCartoes: 2602.2,
      obrigacoesFiscais: 590.2,
      obrigacoesTrabalhistas: 543.9,
      obrigacoesEstatutarias: 212.0,
      provisaoRiscos: 92.1,
      derivativosPC: 13.8,
      outrasObrigacoes: 235.6,
      passivoNaoCirculante: 2303.1,
      financiamentosServFinLP: 358.8,
      arrendamentosLP: 1765.3,
      irCsDiferidosLP: 1.6,
      fornecedoresLP: 71.6,
      provisaoRiscosLP: 64.2,
      outrasObrigacoesLP: 41.6,
      patrimonioLiquido: 10456.1,
      capitalSocial: 9544.8,
      acoesTesouraria: -344.4,
      reservasCapital: 10.2,
      reservasLucros: 1148.8,
      ajusteAvaliacao: 96.7,
    },
    2024: {
      ativoTotal: 20364.5,
      ativoCirculante: 12316.7,
      caixa: 1926.1,
      aplicacoesFinanceiras: 845.2,
      contasReceber: 6902.9,
      estoques: 1929.9,
      tributosRecuperar: 414.2,
      irCsRecuperar: 164.1,
      derivativos: 27.8,
      outrosAC: 106.5,
      ativoNaoCirculante: 8047.8,
      tributosRecuperarLP: 305.7,
      irCsDiferidos: 790.2,
      irCsRecuperarLP: 31.3,
      outrosANC: 97.7,
      investimentos: 56.6,
      imobilizado: 2900.4,
      direitoUso: 2252.5,
      intangivel: 1613.4,
      passivoCirculante: 7647.6,
      emprestimosDebentures: 522.4,
      financiamentosServFin: 409.3,
      arrendamentos: 783.9,
      fornecedores: 1807.3,
      riscoSacado: 0.0,
      administradorasCartoes: 2610.2,
      obrigacoesFiscais: 545.3,
      obrigacoesTrabalhistas: 488.5,
      obrigacoesEstatutarias: 170.6,
      provisaoRiscos: 90.0,
      derivativosPC: 0.0,
      outrasObrigacoes: 220.1,
      passivoNaoCirculante: 1944.0,
      financiamentosServFinLP: 13.7,
      arrendamentosLP: 1847.6,
      irCsDiferidosLP: 5.7,
      fornecedoresLP: 1.8,
      provisaoRiscosLP: 56.2,
      outrasObrigacoesLP: 19.0,
      patrimonioLiquido: 10772.9,
      capitalSocial: 9540.9,
      acoesTesouraria: -154.4,
      reservasCapital: 166.4,
      reservasLucros: 1079.0,
      ajusteAvaliacao: 141.1,
    },
  },
} as const;

const fmt = (v: number) => v.toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 });
const av = (v: number, base: number) => `${((v / base) * 100).toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 })}%`;
const ah = (a: number, b: number) =>
  b === 0 ? '—' : Math.sign(a) !== Math.sign(b) && a !== 0 ? 'n.m.' : `${((Math.abs(a) / Math.abs(b) - 1) * 100).toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 })}%`;

function table<K extends string>(caption: string, a: Readonly<Record<K, number>>, b: Readonly<Record<K, number>>, baseKey: K, rows: [string, K][], totals: string[]) {
  return {
    caption,
    note: 'Valores em R$ milhões. A.V. = conta ÷ total; A.H. = |2025| ÷ |2024| − 1 (n.m. = não significativo, sinal mudou). ' + RENNER_SOURCE,
    headers: ['Conta', '2025', 'A.V.% 25', '2024', 'A.V.% 24', 'A.H.%'],
    rows: rows.map(([label, k]) => [label, fmt(a[k]), av(a[k], a[baseKey]), fmt(b[k]), av(b[k], b[baseKey]), ah(a[k], b[k])]),
    totalRows: rows.map(([label], i) => (totals.includes(label) ? i : -1)).filter((i) => i >= 0),
  };
}

export function rennerIncomeTable() {
  return table(
    'Lojas Renner — DRE 2025 × 2024',
    RENNER.dre[2025],
    RENNER.dre[2024],
    'receitaLiquida',
    [
      ['  Venda de mercadorias', 'vendaMercadorias'],
      ['  Venda de serviços (Realize)', 'vendaServicos'],
      ['Receita operacional líquida', 'receitaLiquida'],
      ['(−) Custo das vendas', 'custoVendas'],
      ['= Lucro Bruto', 'lucroBruto'],
      ['(−) Despesas com vendas', 'despesasVendas'],
      ['(−) Despesas gerais e administrativas', 'despesasAdministrativas'],
      ['(−) Depreciações e amortizações', 'depreciacoes'],
      ['(−) Perdas em crédito, líquidas', 'perdasCredito'],
      ['(−) Outros resultados operacionais', 'outrosOperacionais'],
      ['= Lucro Operacional', 'lucroOperacional'],
      ['(+/−) Resultado financeiro', 'resultadoFinanceiro'],
      ['(−) IR e contribuição social', 'irCs'],
      ['= Lucro Líquido do exercício', 'lucroLiquido'],
    ],
    ['Receita operacional líquida', '= Lucro Bruto', '= Lucro Operacional', '= Lucro Líquido do exercício'],
  );
}

export function rennerAssetTable() {
  return table(
    'Lojas Renner — ATIVO (consolidado) 31/12',
    RENNER.bp[2025],
    RENNER.bp[2024],
    'ativoTotal',
    [
      ['ATIVO TOTAL', 'ativoTotal'],
      ['ATIVO CIRCULANTE', 'ativoCirculante'],
      ['  Caixa e equivalentes de caixa', 'caixa'],
      ['  Aplicações financeiras', 'aplicacoesFinanceiras'],
      ['  Contas a receber', 'contasReceber'],
      ['  Estoques', 'estoques'],
      ['  Tributos a recuperar', 'tributosRecuperar'],
      ['  IR e CS a recuperar', 'irCsRecuperar'],
      ['  Instrumentos financeiros derivativos', 'derivativos'],
      ['  Outros ativos', 'outrosAC'],
      ['ATIVO NÃO CIRCULANTE', 'ativoNaoCirculante'],
      ['  Tributos a recuperar (LP)', 'tributosRecuperarLP'],
      ['  IR e CS diferidos', 'irCsDiferidos'],
      ['  IR e CS a recuperar (LP)', 'irCsRecuperarLP'],
      ['  Outros ativos (LP)', 'outrosANC'],
      ['  Investimentos', 'investimentos'],
      ['  Imobilizado', 'imobilizado'],
      ['  Direito de uso', 'direitoUso'],
      ['  Intangível', 'intangivel'],
    ],
    ['ATIVO TOTAL', 'ATIVO CIRCULANTE', 'ATIVO NÃO CIRCULANTE'],
  );
}

export function rennerLiabilityTable() {
  return table(
    'Lojas Renner — PASSIVO + PL (consolidado) 31/12',
    RENNER.bp[2025],
    RENNER.bp[2024],
    'ativoTotal',
    [
      ['PASSIVO TOTAL + PL', 'ativoTotal'],
      ['PASSIVO CIRCULANTE', 'passivoCirculante'],
      ['  Empréstimos, financiamentos e debêntures', 'emprestimosDebentures'],
      ['  Financiamentos — operações serv. financeiros', 'financiamentosServFin'],
      ['  Arrendamentos a pagar', 'arrendamentos'],
      ['  Fornecedores', 'fornecedores'],
      ['  Obrigações — risco sacado', 'riscoSacado'],
      ['  Obrigações com administradoras de cartões', 'administradorasCartoes'],
      ['  Obrigações fiscais', 'obrigacoesFiscais'],
      ['  Obrigações sociais e trabalhistas', 'obrigacoesTrabalhistas'],
      ['  Obrigações estatutárias (dividendos/JCP)', 'obrigacoesEstatutarias'],
      ['  Provisão para riscos', 'provisaoRiscos'],
      ['  Instrumentos financeiros derivativos', 'derivativosPC'],
      ['  Outras obrigações', 'outrasObrigacoes'],
      ['PASSIVO NÃO CIRCULANTE', 'passivoNaoCirculante'],
      ['  Financiamentos — operações serv. financeiros (LP)', 'financiamentosServFinLP'],
      ['  Arrendamentos a pagar (LP)', 'arrendamentosLP'],
      ['  IR e CS diferidos', 'irCsDiferidosLP'],
      ['  Fornecedores (LP)', 'fornecedoresLP'],
      ['  Provisão para riscos (LP)', 'provisaoRiscosLP'],
      ['  Outras obrigações (LP)', 'outrasObrigacoesLP'],
      ['PATRIMÔNIO LÍQUIDO', 'patrimonioLiquido'],
      ['  Capital social', 'capitalSocial'],
      ['  Ações em tesouraria', 'acoesTesouraria'],
      ['  Reservas de capital', 'reservasCapital'],
      ['  Reservas de lucros', 'reservasLucros'],
      ['  Ajuste de avaliação patrimonial', 'ajusteAvaliacao'],
    ],
    ['PASSIVO TOTAL + PL', 'PASSIVO CIRCULANTE', 'PASSIVO NÃO CIRCULANTE', 'PATRIMÔNIO LÍQUIDO'],
  );
}

export function rennerAnnex() {
  return [rennerAssetTable(), rennerLiabilityTable(), rennerIncomeTable()];
}
